In [2]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import FinanceDataReader as fdr

from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, GradientBoostingClassifier, HistGradientBoostingClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    log_loss,
    confusion_matrix
)
from sklearn.inspection import permutation_importance
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.preprocessing import StandardScaler

# =========================================================
# 기본 설정
# =========================================================

### 데이터 티커 및 기간 설정
ETF_CODE = "SMH"
START_DATE = "2020-01-01"
END_DATE = None

### Target 설정
N_DAYS = 5                                  # N일 후의 상승/하락 예측
THRESHOLD = 0.01                            # 상승/하락 판단 기준 (예: 0.05는 5% 상승/하락)
VALID_MONTHS = 1                            # 검증 데이터 기간 (개월 단위, 예: 1은 최근 1개월)


### 변수 선택시 
VIF_THRESHOLD = 10                          # 변수 선택시 VIF 기준 (예: 10 이상인 변수 제거)
LAG_SEARCH_YEARS = 1                        # 변수별 최적 lag 탐색시 사용할 최근 데이터 기간 (년 단위)
LAG_DAYS = [1, 3, 5, 10, 20, 40, 60, 120]   # 변수별 최적 lag 탐색시 사용할 일수 (예: 1, 3, 5, 10, 20, 40, 60, 120일)

### RF 설정 (변수 중요도 파악을 위한 과적합용 모델)
RANDOM_STATE = 42
N_RF_RUNS = 3
N_REPEATS = 10
TOP_N = 30 # 상위 N개 변수 선택
PRED_THRESHOLD = 0.5


# 외부 지표
EXTERNAL_TICKERS = {
    "QQQ": "QQQ",
    "SPY": "SPY",
    "SOXX": "SOXX",
    "NVDA": "NVDA",
    "TSM": "TSM",
    "VIX": "^VIX",
    "TNX": "^TNX",
    "USDKRW": "KRW=X",
    "DXY": "DX-Y.NYB",
    "GOLD": "GC=F",
    "OIL": "CL=F",
}

EXTERNAL_FEATURE_TYPES = {
    "QQQ": "price",
    "SPY": "price",
    "SOXX": "price",
    "NVDA": "price",
    "TSM": "price",
    "VIX": "risk",
    "TNX": "rate",
    "USDKRW": "price",
    "DXY": "price",
    "GOLD": "price",
    "OIL": "price",
}

model_configs = [
    {"model_name": "random_forest", "model_params": {"n_estimators": 500, "max_depth": None}},
    {"model_name": "extra_trees", "model_params": {"n_estimators": 500, "max_depth": None}},
    {"model_name": "gradient_boosting", "model_params": {"n_estimators": 300, "learning_rate": 0.03, "max_depth": 3}},
    {"model_name": "hist_gradient_boosting", "model_params": {"max_iter": 300, "learning_rate": 0.03}},
    {"model_name": "logistic", "model_params": {"C": 1.0}},
    {"model_name": "svc", "model_params": {"C": 1.0, "kernel": "rbf"}},
]


from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import make_pipeline

In [1]:
import requests

verify_ssl=False
session = requests.Session()
session.verify = verify_ssl
session.headers.update({
    "User-Agent": "Mozilla/5.0"
})

original_get = requests.get

def custom_get(*args, **kwargs):
    kwargs["verify"] = verify_ssl
    return session.get(*args, **kwargs)

# FinanceDataReader 내부 requests.get 일시 덮어쓰기
requests.get = custom_get

In [3]:
etf_list = fdr.StockListing("ETF/KR")
etf_list.head()

,Symbol,Category,Name,Price,RiseFall,Change,ChangeRate,NAV,EarningRate,Volume,Amount,MarCap
0,069500,1,KODEX 200,123350,2,290,0.24,123321.0,43.5661,13208639,1628702,267546
1,360750,4,TIGER 미국S&P500,28100,2,355,1.28,28010.0,14.0257,15775739,441821,184097
2,396500,2,TIGER 반도체TOP10,48000,5,-395,-0.82,48047.0,57.2504,10653376,512039,139968
3,102110,1,TIGER 200,123440,2,330,0.27,123372.0,43.7360,5164859,636988,107269
4,133690,4,TIGER 미국나스닥100,197990,2,2740,1.40,197210.0,24.3035,822145,162194,106083

In [4]:
## 함수

################################################################################################################################################
## 1. Base Feature Dataset 생성
################################################################################################################################################
def load_price_data(ticker, start_date="2020-01-01", end_date=None):
    """
    FinanceDataReader로 가격 데이터를 가져온다.
    Date 컬럼을 일반 컬럼으로 유지한다.
    """
    df = fdr.DataReader(ticker, start_date, end_date)
    df = df.reset_index().rename(columns={"index": "Date"})

    # 컬럼명 정리
    df["Date"] = pd.to_datetime(df["Date"])

    return df

def make_target_etf_features(etf_df, prefix):
    """
    예측 대상 ETF용 feature 생성.
    target은 여기서 만들지 않는다.
    """
    df = etf_df.copy()
    df = df.sort_values("Date").reset_index(drop=True)

    close = df["Adj Close"]
    volume = df["Volume"]

    result = pd.DataFrame()
    result["Date"] = df["Date"]

    # target 만들 때 필요하므로 Close는 반드시 보존
    result[f"{prefix}_adj_close"] = close

    # 수익률
    result[f"{prefix}_ret_1d"] = close.pct_change(1)
    result[f"{prefix}_ret_5d"] = close.pct_change(5)
    result[f"{prefix}_ret_20d"] = close.pct_change(20)

    # 이동평균 대비 위치
    ma_5 = close.rolling(5).mean()
    ma_20 = close.rolling(20).mean()
    ma_60 = close.rolling(60).mean()

    result[f"{prefix}_ma5_ratio"] = close / ma_5 - 1
    result[f"{prefix}_ma20_ratio"] = close / ma_20 - 1
    result[f"{prefix}_ma60_ratio"] = close / ma_60 - 1

    # 변동성
    result[f"{prefix}_vol_20d"] = result[f"{prefix}_ret_1d"].rolling(20).std()

    # 거래량 비율
    vol_ma20 = volume.rolling(20).mean()
    result[f"{prefix}_volume_ratio_20d"] = volume / vol_ma20 - 1

    return result

def make_external_features(raw_df, name, feature_type="price"):
    """
    외부 지표용 최소 파생변수 생성.
    feature_type:
        - price: 일반 가격형 지표
        - risk: VIX 같은 리스크 레벨 지표
        - rate: 금리 지표
    """
    df = raw_df.copy()
    df = df.sort_values("Date").reset_index(drop=True)

    close = df["Adj Close"]

    result = pd.DataFrame()
    result["Date"] = df["Date"]

    if feature_type == "price":
        result[f"{name}_ret_5d"] = close.pct_change(5)
        result[f"{name}_ret_20d"] = close.pct_change(20)

    elif feature_type == "risk":
        result[f"{name}_level"] = close
        result[f"{name}_chg_5d"] = close.diff(5)
        result[f"{name}_chg_20d"] = close.diff(20)

    elif feature_type == "rate":
        result[f"{name}_level"] = close
        result[f"{name}_diff_5d"] = close.diff(5)
        result[f"{name}_diff_20d"] = close.diff(20)

    else:
        raise ValueError("feature_type must be one of ['price', 'risk', 'rate']")

    return result

def make_base_feature_dataset(
    etf_code,
    external_tickers,
    external_feature_types,
    start_date="2020-01-01",
    end_date=None
):
    """
    target 없는 기본 feature dataset 생성.
    이 함수는 느린 작업이므로 한 번만 실행하는 것을 목표로 한다.
    """
    # 1. ETF 본체 로드
    etf_raw = load_price_data(etf_code, start_date, end_date)

    # 2. ETF 본체 feature 생성
    base_df = make_target_etf_features(etf_raw, prefix=etf_code)

    # 3. 외부 지표 붙이기
    for name, ticker in external_tickers.items():
        print(f"Loading external ticker: {name} / {ticker}")

        try:
            raw = load_price_data(ticker, start_date, end_date)

            feature_type = external_feature_types.get(name, "price")

            ext_feat = make_external_features(
                raw_df=raw,
                name=name,
                feature_type=feature_type
            )

            base_df = base_df.merge(ext_feat, on="Date", how="left")

        except Exception as e:
            print(f"[SKIP] {name} / {ticker} 로드 실패:", e)

    # 4. 날짜 정렬
    base_df = base_df.sort_values("Date").reset_index(drop=True)

    # 5. feature_cols 정리
    close_col = f"{etf_code}_adj_close"

    feature_cols = [
        col for col in base_df.columns
        if col not in ["Date", close_col]
    ]

    return base_df, feature_cols, close_col

def make_base_feature_dataset(
    etf_code,
    external_tickers,
    external_feature_types,
    start_date="2020-01-01",
    end_date=None
):
    """
    target 없는 기본 feature dataset 생성.
    이 함수는 느린 작업이므로 한 번만 실행하는 것을 목표로 한다.

    주말 데이터가 섞여 NA가 늘어나는 문제를 막기 위해
    ETF / 외부 ticker 모두 영업일(월~금)만 사용한다.
    """

    # =========================================================
    # 0. 영업일 필터 함수
    # =========================================================
    def keep_weekdays_only(df, date_col="Date"):
        df = df.copy()
        df[date_col] = pd.to_datetime(df[date_col])
        df = df[df[date_col].dt.weekday < 5]  # 월=0, 금=4
        df = df.sort_values(date_col).reset_index(drop=True)
        return df

    # =========================================================
    # 1. ETF 본체 로드
    # =========================================================
    etf_raw = load_price_data(etf_code, start_date, end_date)

    # 주말 제거
    etf_raw = keep_weekdays_only(etf_raw, date_col="Date")

    # =========================================================
    # 2. ETF 본체 feature 생성
    # =========================================================
    base_df = make_target_etf_features(etf_raw, prefix=etf_code)

    # feature 생성 후에도 혹시 모르니 다시 주말 제거
    base_df = keep_weekdays_only(base_df, date_col="Date")

    # =========================================================
    # 3. 외부 지표 붙이기
    # =========================================================
    for name, ticker in external_tickers.items():
        print(f"Loading external ticker: {name} / {ticker}")

        try:
            raw = load_price_data(ticker, start_date, end_date)

            # 외부 ticker도 주말 제거
            raw = keep_weekdays_only(raw, date_col="Date")

            feature_type = external_feature_types.get(name, "price")

            ext_feat = make_external_features(
                raw_df=raw,
                name=name,
                feature_type=feature_type
            )

            # 외부 feature 생성 후에도 다시 주말 제거
            ext_feat = keep_weekdays_only(ext_feat, date_col="Date")

            # ETF 거래일 기준으로 붙임
            base_df = base_df.merge(ext_feat, on="Date", how="left")

        except Exception as e:
            print(f"[SKIP] {name} / {ticker} 로드 실패:", e)

    # =========================================================
    # 4. 날짜 정렬 + 주말 최종 제거
    # =========================================================
    base_df = keep_weekdays_only(base_df, date_col="Date")
    
    # =========================================================
    # 4.1. 외부 지표 NA 보정
    # - ETF 본체는 건드리지 않고
    # - 외부 지표만 ffill
    # =========================================================
    etf_prefix = f"{etf_code}_"

    external_cols = [
        col for col in base_df.columns
        if col != "Date" and not col.startswith(etf_prefix)
    ]

    base_df[external_cols] = base_df[external_cols].ffill()

    # =========================================================
    # 5. feature_cols 정리
    # =========================================================
    close_col = f"{etf_code}_adj_close"

    feature_cols = [
        col for col in base_df.columns
        if col not in ["Date", close_col]
    ]

    return base_df, feature_cols, close_col

################################################################################################################################################
## 2. VIF 기반 불필요 칼럼 제거
################################################################################################################################################
def reduce_features_by_vif(
    df,
    feature_cols,
    vif_threshold=30.0,
    date_col="Date",
    verbose=True
):
    """
    VIF 기준으로 다중공선성이 높은 feature를 반복 제거한다.

    주의:
    - target 생성 전 단계에서 실행한다.
    - lag 생성 전 단계에서 실행한다.
    - Date, adj_close 등 보존 컬럼은 feature_cols에 넣지 않는 것을 전제로 한다.
    """

    # 1. 숫자형 feature만 사용
    numeric_feature_cols = [
        col for col in feature_cols
        if col in df.columns and pd.api.types.is_numeric_dtype(df[col])
    ]

    work_df = df[numeric_feature_cols].copy()

    # 2. inf 처리
    work_df = work_df.replace([np.inf, -np.inf], np.nan)

    # 3. VIF 계산용 결측 제거
    #    여기서는 VIF 계산에만 dropna를 쓰고,
    #    원본 df 자체를 줄이지는 않는다.
    vif_calc_df = work_df.dropna(axis=0).copy()

    print("VIF 계산 대상 row 수:", len(vif_calc_df))
    print("VIF 계산 대상 feature 수:", len(numeric_feature_cols))

    if len(vif_calc_df) == 0:
        raise ValueError("VIF 계산 가능한 데이터가 없습니다. 결측값을 확인하세요.")

    # 4. 상수 컬럼 제거
    nunique = vif_calc_df.nunique()
    constant_cols = nunique[nunique <= 1].index.tolist()

    if len(constant_cols) > 0:
        print("상수 컬럼 제거:", constant_cols)

    remaining_cols = [
        col for col in numeric_feature_cols
        if col not in constant_cols
    ]

    removed_records = []

    # 5. VIF 반복 제거
    while True:
        if len(remaining_cols) <= 1:
            break

        X = vif_calc_df[remaining_cols].copy()

        # 표준화
        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(X)

        vif_values = []

        for i, col in enumerate(remaining_cols):
            try:
                vif = variance_inflation_factor(X_scaled, i)
            except Exception:
                vif = np.inf

            vif_values.append({
                "feature": col,
                "vif": vif
            })

        vif_df = pd.DataFrame(vif_values).sort_values("vif", ascending=False)

        max_vif_row = vif_df.iloc[0]
        max_feature = max_vif_row["feature"]
        max_vif = max_vif_row["vif"]

        if verbose:
            print(f"현재 max VIF: {max_vif:.2f} / feature: {max_feature}")

        if max_vif <= vif_threshold:
            break

        # 가장 VIF 높은 컬럼 제거
        remaining_cols.remove(max_feature)

        removed_records.append({
            "removed_feature": max_feature,
            "vif": max_vif,
            "remaining_feature_count": len(remaining_cols)
        })

    removed_vif_df = pd.DataFrame(removed_records)

    # 6. 최종 VIF 테이블 계산
    final_vif_records = []

    if len(remaining_cols) > 1:
        X_final = vif_calc_df[remaining_cols].copy()

        scaler = StandardScaler()
        X_final_scaled = scaler.fit_transform(X_final)

        for i, col in enumerate(remaining_cols):
            try:
                vif = variance_inflation_factor(X_final_scaled, i)
            except Exception:
                vif = np.inf

            final_vif_records.append({
                "feature": col,
                "vif": vif
            })

        final_vif_df = pd.DataFrame(final_vif_records).sort_values("vif", ascending=False)

    else:
        final_vif_df = pd.DataFrame({
            "feature": remaining_cols,
            "vif": [np.nan] * len(remaining_cols)
        })

    print()
    print("========== VIF 제거 결과 ==========")
    print("초기 feature 수:", len(numeric_feature_cols))
    print("상수 제거 feature 수:", len(constant_cols))
    print("VIF 제거 feature 수:", len(removed_records))
    print("최종 feature 수:", len(remaining_cols))
    print("===================================")

    return remaining_cols, removed_vif_df, final_vif_df


################################################################################################################################################
## 3. Target 변수 생성
################################################################################################################################################
def add_target_column(
    df,
    close_col,
    n_days=5,
    threshold=0.05,
    target_col=None
):
    """
    현재 시점 기준 n_days 뒤 수익률이 threshold 이상이면 1, 아니면 0인 target 생성.

    예:
    n_days=5, threshold=0.05
    → 5거래일 뒤 수익률이 +5% 이상이면 target=1
    """

    result = df.copy()
    result = result.sort_values("Date").reset_index(drop=True)

    if target_col is None:
        target_col = f"target_{n_days}d_up_{int(threshold * 100)}pct"

    # 미래 가격
    future_close = result[close_col].shift(-n_days)

    # 미래 수익률
    result[f"future_ret_{n_days}d"] = future_close / result[close_col] - 1

    # target 생성
    result[target_col] = np.where(
        result[f"future_ret_{n_days}d"] >= threshold,
        1,
        0
    )

    # 마지막 n_days개는 미래 가격이 없으므로 제거
    result.loc[result[f"future_ret_{n_days}d"].isna(), target_col] = np.nan

    return result, target_col


################################################################################################################################################
## 4. Lag 생성 후 변수별 최적 lag 탐색
################################################################################################################################################

def find_best_lag_by_feature(
    df,
    feature_cols,
    target_col,
    lag_days=[1, 3, 5, 10, 20],
    date_col="Date",
    method="corr"
):
    """
    각 feature별로 target과 가장 관계가 강한 선행 lag를 찾는다.

    lag 의미:
    - lag=1  : feature의 1거래일 전 값으로 오늘 target 설명
    - lag=5  : feature의 5거래일 전 값으로 오늘 target 설명
    - lag=20 : feature의 20거래일 전 값으로 오늘 target 설명

    즉, feature가 먼저 움직이고 나중에 target이 움직이는 구조만 본다.
    """

    records = []

    for col in feature_cols:
        if col not in df.columns:
            continue

        for lag in lag_days:
            temp = df[[date_col, col, target_col]].copy()

            # 선행변수 구조
            temp[f"{col}_lag{lag}"] = temp[col].shift(lag)

            temp = temp[[f"{col}_lag{lag}", target_col]].replace(
                [np.inf, -np.inf],
                np.nan
            ).dropna()

            if len(temp) < 30:
                continue

            x = temp[f"{col}_lag{lag}"]
            y = temp[target_col]

            if x.nunique() <= 1:
                corr = np.nan
            else:
                corr = x.corr(y)

            records.append({
                "feature": col,
                "lag": lag,
                "corr": corr,
                "abs_corr": abs(corr) if pd.notna(corr) else np.nan,
                "n_rows": len(temp)
            })

    lag_result_df = pd.DataFrame(records)

    if lag_result_df.empty:
        raise ValueError("lag 탐색 결과가 비어 있습니다. feature_cols 또는 target_col을 확인하세요.")

    # feature별 abs_corr가 가장 큰 lag 선택
    best_lag_df = (
        lag_result_df
        .sort_values(["feature", "abs_corr"], ascending=[True, False])
        .groupby("feature", as_index=False)
        .head(1)
        .reset_index(drop=True)
    )

    best_lag_df = best_lag_df.sort_values("abs_corr", ascending=False).reset_index(drop=True)

    return lag_result_df, best_lag_df

def make_lagged_dataset_by_best_lag(
    df,
    best_lag_df,
    target_col,
    close_col,
    n_days=5,
    date_col="Date"
):
    """
    best_lag_df 기준으로 feature별 최적 lag를 적용한 최종 모델용 데이터셋 생성.
    """

    result = pd.DataFrame()
    result[date_col] = df[date_col]
    result[close_col] = df[close_col]

    # 확인용 미래수익률 보존
    future_ret_col = f"future_ret_{n_days}d"
    if future_ret_col in df.columns:
        result[future_ret_col] = df[future_ret_col]

    # target 보존
    result[target_col] = df[target_col]

    lagged_feature_cols = []

    for _, row in best_lag_df.iterrows():
        feature = row["feature"]
        lag = int(row["lag"])

        if feature not in df.columns:
            continue

        lagged_col = f"{feature}_lag{lag}"
        result[lagged_col] = df[feature].shift(lag)
        lagged_feature_cols.append(lagged_col)

    # 결측/무한값 제거
    result = result.replace([np.inf, -np.inf], np.nan)
    result = result.dropna().reset_index(drop=True)

    return result, lagged_feature_cols



################################################################################################################################################
## 5. RandomForest in-sample 학습 + permutation importance
################################################################################################################################################

def run_rf_permutation_importance_in_sample(
    lagged_df,
    feature_cols,
    target_col,
    date_col="Date",
    close_col=None,
    n_rf_runs=3,
    n_repeats=10,
    random_state=42
):
    """
    lagged_df 기준으로 RandomForestClassifier를 in-sample 학습한 뒤
    permutation importance를 반복 계산한다.

    핵심:
    - RF를 n_rf_runs번 학습
    - 각 RF마다 permutation을 n_repeats번 수행
    - feature별 importance raw 값을 전부 저장
    - 최종 importance_df는 총 n_rf_runs * n_repeats개의 raw importance 기준으로 계산

    예:
    n_rf_runs=3, n_repeats=10이면
    feature별 importance 값 30개를 기반으로 평균/표준편차/스코어 계산
    """

    df = lagged_df.copy()

    # =====================================================
    # 1. 모델 input / target 분리
    # =====================================================

    X = df[feature_cols].copy()
    y = df[target_col].copy()

    X = X.replace([np.inf, -np.inf], np.nan)

    model_df = pd.concat([X, y], axis=1).dropna().copy()

    X = model_df[feature_cols].copy()
    y = model_df[target_col].astype(int).copy()


    # =====================================================
    # 2. 여러 RF run + permutation raw importance 저장
    # =====================================================

    importance_records = []
    baseline_records = []

    for run in range(n_rf_runs):
        print()
        print(f"========== RF RUN {run + 1} / {n_rf_runs} ==========")

        rf = RandomForestClassifier(
            n_estimators=500,
            max_depth=None,
            min_samples_split=2,
            min_samples_leaf=1,
            max_features="sqrt",
            class_weight="balanced",
            random_state=random_state + run,
            n_jobs=-1
        )

        rf.fit(X, y)

        # =================================================
        # 3. in-sample 예측 성능 확인
        # =================================================

        pred = rf.predict(X)
        pred_proba = rf.predict_proba(X)[:, 1]

        acc = accuracy_score(y, pred)
        precision = precision_score(y, pred, zero_division=0)
        recall = recall_score(y, pred, zero_division=0)
        f1 = f1_score(y, pred, zero_division=0)
        loss = log_loss(y, pred_proba)

        cm = confusion_matrix(y, pred)

        print("accuracy :", round(acc, 4))
        print("precision:", round(precision, 4))
        print("recall   :", round(recall, 4))
        print("f1       :", round(f1, 4))
        print("log_loss :", round(loss, 4))

        baseline_records.append({
            "run": run + 1,
            "accuracy": acc,
            "precision": precision,
            "recall": recall,
            "f1": f1,
            "log_loss": loss,
            "pred_1_count": int((pred == 1).sum()),
            "actual_1_count": int((y == 1).sum())
        })

        # =================================================
        # 4. permutation importance
        # =================================================

        perm = permutation_importance(
            rf,
            X,
            y,
            scoring="neg_log_loss",
            n_repeats=n_repeats,
            random_state=random_state + run,
            n_jobs=-1
        )

        # 핵심:
        # perm.importances shape = (n_features, n_repeats)
        # 여기서 반복별 raw importance를 전부 저장한다.
        for i, col in enumerate(feature_cols):
            for repeat_idx, importance_value in enumerate(perm.importances[i]):
                importance_records.append({
                    "run": run + 1,
                    "repeat": repeat_idx + 1,
                    "feature": col,
                    "importance": importance_value
                })

    # =====================================================
    # 5. 결과 정리
    # =====================================================

    raw_importance_df = pd.DataFrame(importance_records)
    baseline_df = pd.DataFrame(baseline_records)

    importance_df = (
        raw_importance_df
        .groupby("feature", as_index=False)
        .agg(
            importance_mean=("importance", "mean"),
            importance_std=("importance", "std"),
            importance_var=("importance", "var"),
            importance_min=("importance", "min"),
            importance_max=("importance", "max"),
            run_count=("run", "nunique"),
            repeat_count=("repeat", "count")
        )
    )

    # 안정성 점수
    # 평균 중요도는 높고, 30회 전체 기준 표준편차는 낮을수록 높게
    importance_df["importance_score"] = (
        importance_df["importance_mean"]
        - importance_df["importance_std"].fillna(0)
    )

    importance_df = importance_df.sort_values(
        "importance_score",
        ascending=False
    ).reset_index(drop=True)

    return importance_df, raw_importance_df, baseline_df

def split_lagged_feature_name(feature_name):
    """
    feature_lag20 형태의 컬럼명을 원본 feature와 lag로 분리한다.
    """

    if "_lag" not in feature_name:
        return feature_name, np.nan

    base_name = feature_name.rsplit("_lag", 1)[0]
    lag = feature_name.rsplit("_lag", 1)[1]

    try:
        lag = int(lag)
    except:
        lag = np.nan

    return base_name, lag

In [5]:

# =========================================================
# 실행부 함수화
# - 1) top_feature_df 생성 함수
# - 2) valid 검증/예측 함수
# =========================================================

def build_top_feature_df(
    etf_code,
    n_days,
    threshold,
    lag_search_years,
    random_state=42,
    n_rf_runs=3,
    n_repeats=10,
    top_n=30,
    start_date=START_DATE,
    end_date=END_DATE,
    valid_months=VALID_MONTHS,
    external_tickers=EXTERNAL_TICKERS,
    external_feature_types=EXTERNAL_FEATURE_TYPES,
    vif_threshold=VIF_THRESHOLD,
    lag_days=LAG_DAYS,
    verbose=True
):
    """
    base_df 생성 → train/valid 분리 → VIF 제거 → target 생성
    → lag 탐색 → lagged_df 생성 → RF permutation importance
    → top_feature_df 추출까지 한 번에 수행한다.

    Returns
    -------
    result : dict
        검증 함수에서 다시 필요한 객체들을 모두 담아서 반환한다.
        주요 key:
        - top_feature_df
        - base_df
        - train_base_df
        - valid_base_df
        - close_col
        - target_col
        - lagged_df
        - lagged_feature_cols
        - best_lag_df
        - importance_df
        - importance_with_lag_df
    """

    # =========================================================
    # 1. target 없는 base dataset 생성
    # =========================================================
    if verbose:
        print()
        print("=" * 50)
        print("1. Base feature dataset created.")

    base_df, base_feature_cols, close_col = make_base_feature_dataset(
        etf_code=etf_code,
        external_tickers=external_tickers,
        external_feature_types=external_feature_types,
        start_date=start_date,
        end_date=end_date
    )

    max_date = base_df["Date"].max()
    valid_start_date = max_date - pd.DateOffset(months=valid_months)

    train_base_df = base_df[base_df["Date"] < valid_start_date].copy()
    valid_base_df = base_df[base_df["Date"] >= valid_start_date].copy()

    if verbose:
        print("train_base_df shape:", train_base_df.shape)
        print("valid_base_df shape:", valid_base_df.shape)
        print("close_col:", close_col)
        print("=" * 50)

    # =========================================================
    # 2. VIF 기반 불필요 칼럼 제거
    # =========================================================
    if verbose:
        print()
        print("=" * 50)
        print("2. VIF filtering completed.")

    vif_feature_cols, removed_vif_df, final_vif_df = reduce_features_by_vif(
        df=train_base_df,
        feature_cols=base_feature_cols,
        vif_threshold=vif_threshold,
        date_col="Date",
        verbose=verbose
    )

    keep_cols = ["Date", close_col] + vif_feature_cols
    vif_filtered_df = train_base_df[keep_cols].copy()

    if verbose:
        print("vif_filtered_df shape:", vif_filtered_df.shape)
        print("제거된 컬럼:")
        print(removed_vif_df)
        print("=" * 50)

    # =========================================================
    # 3. Target 변수 생성
    # =========================================================
    if verbose:
        print()
        print("=" * 50)
        print("3. Target column added.")

    target_df, target_col = add_target_column(
        df=vif_filtered_df,
        close_col=close_col,
        n_days=n_days,
        threshold=threshold
    )

    # target 없는 마지막 n_days 행 제거
    target_df = target_df.dropna(subset=[target_col]).copy()
    target_df[target_col] = target_df[target_col].astype(int)

    if verbose:
        print("target_col:", target_col)
        print("target_df shape after dropna:", target_df.shape)
        print("target 분포:")
        print(target_df[target_col].value_counts())
        print("target 비율:")
        print(target_df[target_col].value_counts(normalize=True))
        print("=" * 50)

    # =========================================================
    # 4. 최근 lag_search_years 기준으로 lag 탐색
    # =========================================================
    if verbose:
        print()
        print("=" * 50)
        print("4. 변수별 최적 LAG 탐색 완료.")

    max_date = target_df["Date"].max()
    lag_search_start_date = max_date - pd.DateOffset(years=lag_search_years)

    target_df_for_lag_search = target_df[
        target_df["Date"] >= lag_search_start_date
    ].copy()

    if verbose:
        print("lag 탐색 기준 기간:")
        print(target_df_for_lag_search["Date"].min(), "~", target_df_for_lag_search["Date"].max())
        print("lag 탐색용 데이터 shape:", target_df_for_lag_search.shape)

    exclude_cols_for_lag = [
        "Date",
        close_col,
        f"future_ret_{n_days}d",
        target_col
    ]

    lag_search_feature_cols = [
        col for col in target_df.columns
        if col not in exclude_cols_for_lag
    ]

    lag_result_df, best_lag_df = find_best_lag_by_feature(
        df=target_df_for_lag_search,
        feature_cols=lag_search_feature_cols,
        target_col=target_col,
        lag_days=lag_days,
        date_col="Date"
    )

    if verbose:
        print("전체 lag 탐색 결과 shape:", lag_result_df.shape)

    # =========================================================
    # 5. best lag 적용해서 lagged_df 생성
    # =========================================================
    lagged_df, lagged_feature_cols = make_lagged_dataset_by_best_lag(
        df=target_df,
        best_lag_df=best_lag_df,
        target_col=target_col,
        close_col=close_col,
        n_days=n_days,
        date_col="Date"
    )

    if verbose:
        print("lagged_df shape:", lagged_df.shape)
        print("lagged feature count:", len(lagged_feature_cols))
        print("=" * 50)

    # =========================================================
    # 6. permutation importance 실행
    # =========================================================
    if verbose:
        print()
        print("=" * 50)
        print("5. RandomForest in-sample 학습 + permutation importance 완료.")

    importance_df, raw_importance_df, baseline_df = run_rf_permutation_importance_in_sample(
        lagged_df=lagged_df,
        feature_cols=lagged_feature_cols,
        target_col=target_col,
        date_col="Date",
        close_col=close_col,
        n_rf_runs=n_rf_runs,
        n_repeats=n_repeats,
        random_state=random_state
    )

    # =========================================================
    # 7. 결과 feature명 / lag 분리
    # =========================================================
    importance_view_df = importance_df.copy()

    importance_view_df[["base_feature", "selected_lag"]] = importance_view_df["feature"].apply(
        lambda x: pd.Series(split_lagged_feature_name(x))
    )

    importance_view_df = importance_view_df[
        [
            "feature",
            "base_feature",
            "selected_lag",
            "importance_score",
            "importance_mean",
            "importance_std",
            "importance_var",
            "importance_min",
            "importance_max",
            "run_count",
            "repeat_count"
        ]
    ]

    # =========================================================
    # 8. best_lag_df와 importance 결과 합치기
    # =========================================================
    importance_with_lag_df = importance_view_df.merge(
        best_lag_df.rename(columns={
            "feature": "base_feature",
            "lag": "best_lag",
            "corr": "lag_corr",
            "abs_corr": "lag_abs_corr",
            "n_rows": "lag_n_rows"
        }),
        on="base_feature",
        how="left"
    )

    importance_with_lag_df = importance_with_lag_df[
        [
            "feature",
            "base_feature",
            "selected_lag",
            "importance_score",
            "importance_mean",
            "importance_std",
            "importance_var",
            "importance_min",
            "importance_max",
            "best_lag",
            "lag_corr",
            "lag_abs_corr",
            "lag_n_rows",
            "run_count",
            "repeat_count"
        ]
    ]

    importance_with_lag_df = importance_with_lag_df.sort_values(
        "importance_score",
        ascending=False
    ).reset_index(drop=True)

    # =========================================================
    # 9. TOP 변수 추출
    # =========================================================
    top_feature_df = importance_with_lag_df.head(top_n).copy()
    top_feature_cols = top_feature_df["feature"].tolist()

    if verbose:
        print("TOP feature count:", len(top_feature_cols))
        print(top_feature_cols)
        print("=" * 50)
        display(top_feature_df)

    result = {
        "etf_code": etf_code,
        "n_days": n_days,
        "threshold": threshold,
        "lag_search_years": lag_search_years,
        "random_state": random_state,
        "n_rf_runs": n_rf_runs,
        "n_repeats": n_repeats,
        "top_n": top_n,
        "start_date": start_date,
        "end_date": end_date,
        "valid_months": valid_months,
        "vif_threshold": vif_threshold,
        "lag_days": lag_days,

        "base_df": base_df,
        "base_feature_cols": base_feature_cols,
        "train_base_df": train_base_df,
        "valid_base_df": valid_base_df,
        "close_col": close_col,

        "vif_feature_cols": vif_feature_cols,
        "removed_vif_df": removed_vif_df,
        "final_vif_df": final_vif_df,
        "vif_filtered_df": vif_filtered_df,

        "target_df": target_df,
        "target_col": target_col,

        "lag_result_df": lag_result_df,
        "best_lag_df": best_lag_df,
        "lagged_df": lagged_df,
        "lagged_feature_cols": lagged_feature_cols,

        "importance_df": importance_df,
        "raw_importance_df": raw_importance_df,
        "baseline_df": baseline_df,
        "importance_with_lag_df": importance_with_lag_df,

        "top_feature_df": top_feature_df,
        "top_feature_cols": top_feature_cols
    }

    return result



# =========================================================
# 검증용 분류 모델 생성 함수
# - top_feature_df를 뽑는 모델은 RF로 유지
# - valid 검증 단계에서만 model_name으로 모델을 바꿔 테스트
# =========================================================

def make_classifier_model(model_name="random_forest", random_state=42, model_params=None):
    """
    검증/예측 단계에서 사용할 분류모델을 생성한다.

    Parameters
    ----------
    model_name : str
        사용할 모델 이름.
        지원 모델:
        - "random_forest"
        - "extra_trees"
        - "gradient_boosting"
        - "hist_gradient_boosting"
        - "logistic"
        - "svc"
        - "knn"
    random_state : int
        random_state를 지원하는 모델에 적용.
    model_params : dict or None
        모델별 파라미터 덮어쓰기용 dict.

    Returns
    -------
    model : sklearn estimator
        fit / predict_proba 가능한 분류모델.
    """

    if model_params is None:
        model_params = {}

    model_name = model_name.lower()

    if model_name == "random_forest":
        default_params = dict(
            n_estimators=500,
            max_depth=None,
            min_samples_split=2,
            min_samples_leaf=1,
            max_features="sqrt",
            class_weight="balanced",
            random_state=random_state,
            n_jobs=-1
        )
        default_params.update(model_params)
        model = RandomForestClassifier(**default_params)

    elif model_name == "extra_trees":
        default_params = dict(
            n_estimators=500,
            max_depth=None,
            min_samples_split=2,
            min_samples_leaf=1,
            max_features="sqrt",
            class_weight="balanced",
            random_state=random_state,
            n_jobs=-1
        )
        default_params.update(model_params)
        model = ExtraTreesClassifier(**default_params)

    elif model_name == "gradient_boosting":
        default_params = dict(
            n_estimators=300,
            learning_rate=0.03,
            max_depth=3,
            random_state=random_state
        )
        default_params.update(model_params)
        model = GradientBoostingClassifier(**default_params)

    elif model_name == "hist_gradient_boosting":
        default_params = dict(
            max_iter=300,
            learning_rate=0.03,
            max_leaf_nodes=31,
            random_state=random_state
        )
        default_params.update(model_params)
        model = HistGradientBoostingClassifier(**default_params)

    elif model_name == "logistic":
        default_params = dict(
            C=1.0,
            class_weight="balanced",
            max_iter=3000,
            random_state=random_state
        )
        default_params.update(model_params)
        model = make_pipeline(
            StandardScaler(),
            LogisticRegression(**default_params)
        )

    elif model_name == "svc":
        default_params = dict(
            C=1.0,
            kernel="rbf",
            gamma="scale",
            class_weight="balanced",
            probability=True,
            random_state=random_state
        )
        default_params.update(model_params)
        model = make_pipeline(
            StandardScaler(),
            SVC(**default_params)
        )

    elif model_name == "knn":
        default_params = dict(
            n_neighbors=15,
            weights="distance"
        )
        default_params.update(model_params)
        model = make_pipeline(
            StandardScaler(),
            KNeighborsClassifier(**default_params)
        )

    else:
        raise ValueError(
            "지원하지 않는 model_name입니다. "
            "사용 가능: random_forest, extra_trees, gradient_boosting, "
            "hist_gradient_boosting, logistic, svc, knn"
        )

    return model


def safe_binary_metrics(y_true, pred, pred_proba=None):
    """
    valid 구간에 한 클래스만 있는 경우에도 에러 없이 metric을 계산한다.
    """
    y_true = pd.Series(y_true).astype(int)
    pred = pd.Series(pred).astype(int)

    accuracy = accuracy_score(y_true, pred)
    precision = precision_score(y_true, pred, zero_division=0)
    recall = recall_score(y_true, pred, zero_division=0)
    f1 = f1_score(y_true, pred, zero_division=0)

    auc = np.nan
    valid_logloss = np.nan

    if pred_proba is not None:
        pred_proba = np.asarray(pred_proba)
        if y_true.nunique() == 2:
            auc = roc_auc_score(y_true, pred_proba)
            valid_logloss = log_loss(y_true, pred_proba, labels=[0, 1])

    cm = confusion_matrix(y_true, pred, labels=[0, 1])
    tn, fp, fn, tp = cm.ravel()

    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "auc": auc,
        "logloss": valid_logloss,
        "tn": tn,
        "fp": fp,
        "fn": fn,
        "tp": tp,
    }


def validate_top_feature_df(
    feature_result,
    model_name="random_forest",
    model_params=None,
    pred_threshold=0.5,
    random_state=42,
    n_days=None,
    threshold=None,
    verbose=True
):
    """
    build_top_feature_df() 결과를 받아서 valid_df 생성 후
    Train 전체 학습 → valid_df 예측 → precision 확인까지 수행한다.

    Parameters
    ----------
    feature_result : dict
        build_top_feature_df()에서 반환한 dict.
    model_name : str
        검증에 사용할 분류모델 이름.
    model_params : dict or None
        모델별 파라미터 덮어쓰기용 dict.
    pred_threshold : float
        예측 확률을 1로 바꿀 기준값.
    random_state : int
        RandomForest random_state.
    n_days : int or None
        None이면 feature_result의 n_days 사용.
    threshold : float or None
        None이면 feature_result의 threshold 사용.

    Returns
    -------
    result : dict
        - valid_df
        - valid_pred_df
        - eval_df
        - pred_1_df
        - metric_df
        - model
        - model_name
        - model_params
    """

    # =========================================================
    # 0. 필요한 객체 꺼내기
    # =========================================================
    top_feature_df = feature_result["top_feature_df"].copy()
    base_df = feature_result["base_df"].copy()
    valid_base_df = feature_result["valid_base_df"].copy()
    lagged_df = feature_result["lagged_df"].copy()
    close_col = feature_result["close_col"]
    target_col = feature_result["target_col"]

    if n_days is None:
        n_days = feature_result["n_days"]

    if threshold is None:
        threshold = feature_result["threshold"]

    # =========================================================
    # 1. valid_df 생성
    # =========================================================
    if verbose:
        print("=" * 60)
        print("6. valid_df 생성")
        print("=" * 60)

    if ("base_feature" not in top_feature_df.columns) or ("selected_lag" not in top_feature_df.columns):
        top_feature_df[["base_feature", "selected_lag"]] = top_feature_df["feature"].apply(
            lambda x: pd.Series(split_lagged_feature_name(x))
        )

    top_feature_df["selected_lag"] = top_feature_df["selected_lag"].astype(int)

    top_feature_cols = top_feature_df["feature"].tolist()
    top_base_features = top_feature_df["base_feature"].unique().tolist()

    if verbose:
        print("top feature 수:", len(top_feature_cols))

    need_cols = ["Date", close_col] + top_base_features
    missing_cols = [col for col in need_cols if col not in base_df.columns]

    if len(missing_cols) > 0:
        raise ValueError(f"base_df에 없는 컬럼이 있습니다: {missing_cols}")

    valid_df = base_df[need_cols].copy()
    valid_df = valid_df.sort_values("Date").reset_index(drop=True)

    # 전체 base_df 기준으로 lag 생성해야 최근 valid 구간의 lag가 계산됨
    for _, row in top_feature_df.iterrows():
        base_feature = row["base_feature"]
        selected_lag = int(row["selected_lag"])
        lagged_feature = row["feature"]

        valid_df[lagged_feature] = valid_df[base_feature].shift(selected_lag)

    if verbose:
        print("lag 생성 후 valid_df shape:", valid_df.shape)

    valid_df = valid_df[["Date", close_col] + top_feature_cols].copy()

    if verbose:
        print("원본 base_feature 제거 후 valid_df shape:", valid_df.shape)
        print("최종 컬럼 수:", len(valid_df.columns))

    valid_df, _ = add_target_column(
        df=valid_df,
        close_col=close_col,
        n_days=n_days,
        threshold=threshold,
        target_col=target_col
    )

    if verbose:
        print("target 생성 후 valid_df shape:", valid_df.shape)

    valid_df = valid_df.tail(len(valid_base_df)).copy()
    valid_df = valid_df.reset_index(drop=True)

    if verbose:
        print("최종 valid_df shape:", valid_df.shape)
        print("valid_base_df shape:", valid_base_df.shape)
        print("valid_df 기간:")
        print(valid_df["Date"].min(), "~", valid_df["Date"].max())

    # =========================================================
    # 2. Train 학습 후 valid_df 예측
    # =========================================================
    if verbose:
        print("=" * 60)
        print("7. Train 학습 후 valid_df 예측")
        print("=" * 60)

    missing_train_cols = [col for col in top_feature_cols if col not in lagged_df.columns]
    missing_valid_cols = [col for col in top_feature_cols if col not in valid_df.columns]

    if len(missing_train_cols) > 0:
        raise ValueError(f"lagged_df에 없는 top feature가 있습니다: {missing_train_cols}")

    if len(missing_valid_cols) > 0:
        raise ValueError(f"valid_df에 없는 top feature가 있습니다: {missing_valid_cols}")

    if verbose:
        print("사용 feature 수:", len(top_feature_cols))

    train_df = lagged_df[
        ["Date", close_col, target_col] + top_feature_cols
    ].copy()

    train_df = train_df.replace([np.inf, -np.inf], np.nan)
    train_df = train_df.dropna(subset=top_feature_cols + [target_col]).copy()

    X_train = train_df[top_feature_cols].copy()
    y_train = train_df[target_col].astype(int).copy()

    if verbose:
        print("train_df shape:", train_df.shape)
        print("X_train shape:", X_train.shape)
        print("train target 분포:")
        print(y_train.value_counts())
        print(y_train.value_counts(normalize=True))

    valid_pred_df = valid_df.copy()

    valid_pred_df["pred_proba"] = np.nan
    valid_pred_df["pred"] = np.nan

    valid_available_mask = (
        valid_pred_df[top_feature_cols]
        .replace([np.inf, -np.inf], np.nan)
        .notna()
        .all(axis=1)
    )

    X_valid = valid_pred_df.loc[valid_available_mask, top_feature_cols].copy()

    if verbose:
        print("valid_df shape:", valid_df.shape)
        print("예측 가능한 valid row 수:", len(X_valid))
        print("예측 불가능 row 수:", len(valid_df) - len(X_valid))

    model = make_classifier_model(
        model_name=model_name,
        random_state=random_state,
        model_params=model_params
    )

    model.fit(X_train, y_train)

    if verbose:
        print(f"모델 학습 완료: {model_name}")

    valid_pred_proba = model.predict_proba(X_valid)[:, 1]
    valid_pred = (valid_pred_proba >= pred_threshold).astype(int)

    valid_pred_df.loc[valid_available_mask, "pred_proba"] = valid_pred_proba
    valid_pred_df.loc[valid_available_mask, "pred"] = valid_pred

    valid_pred_df["pred"] = valid_pred_df["pred"].astype("Int64")

    if verbose:
        print("valid_df 예측 완료")

    # =========================================================
    # 3. 예측 결과 확인
    # =========================================================
    display_cols = ["Date", close_col, "pred_proba", "pred"]

    if target_col in valid_pred_df.columns:
        display_cols = ["Date", close_col, target_col, "pred_proba", "pred"]

    if verbose:
        display(valid_pred_df[display_cols])
        print("예측값 분포:")
        print(valid_pred_df["pred"].value_counts(dropna=False))

    # =========================================================
    # 4. pred = 1 기준 precision 확인
    # =========================================================
    if verbose:
        print("=" * 60)
        print("8. 예측 1 기준 정확도 확인")
        print("=" * 60)

    eval_df = valid_pred_df[
        valid_pred_df["pred"].notna() &
        valid_pred_df[target_col].notna()
    ].copy()

    eval_df["pred"] = eval_df["pred"].astype(int)
    eval_df[target_col] = eval_df[target_col].astype(int)

    pred_1_df = eval_df[eval_df["pred"] == 1].copy()

    pred_1_count = len(pred_1_df)
    pred_1_actual_1_count = (pred_1_df[target_col] == 1).sum()

    if pred_1_count > 0:
        pred_1_precision = pred_1_actual_1_count / pred_1_count
    else:
        pred_1_precision = np.nan

    if len(eval_df) > 0:
        metric_dict = safe_binary_metrics(
            y_true=eval_df[target_col],
            pred=eval_df["pred"],
            pred_proba=eval_df["pred_proba"]
        )
    else:
        metric_dict = {
            "accuracy": np.nan,
            "precision": np.nan,
            "recall": np.nan,
            "f1": np.nan,
            "auc": np.nan,
            "logloss": np.nan,
            "tn": np.nan,
            "fp": np.nan,
            "fn": np.nan,
            "tp": np.nan,
        }

    metric_df = pd.DataFrame([{
        "etf_code": feature_result.get("etf_code"),
        "n_days": n_days,
        "threshold": threshold,
        "lag_search_years": feature_result.get("lag_search_years"),
        "top_n": feature_result.get("top_n"),
        "feature_count": len(top_feature_cols),
        "model_name": model_name,
        "model_params": str(model_params),
        "eval_count": len(eval_df),
        "pred_1_count": pred_1_count,
        "pred_1_actual_1_count": pred_1_actual_1_count,
        "pred_1_precision": pred_1_precision,
        "pred_threshold": pred_threshold,
        **metric_dict
    }])

    if verbose:
        print("평가 가능 row 수:", len(eval_df))
        print("예측 1 개수:", pred_1_count)
        print("예측 1 중 실제 1 개수:", pred_1_actual_1_count)
        print("예측 1 기준 정확도 precision:", pred_1_precision)
        display(metric_df)

    result = {
        "valid_df": valid_df,
        "valid_pred_df": valid_pred_df,
        "eval_df": eval_df,
        "pred_1_df": pred_1_df,
        "metric_df": metric_df,
        "model": model,
        "model_name": model_name,
        "model_params": model_params,
        "top_feature_cols": top_feature_cols
    }

    return result



def validate_multiple_models(
    feature_result,
    model_configs=None,
    pred_threshold=0.5,
    random_state=42,
    verbose=True
):
    """
    동일한 top_feature_df / valid_df 조건에서 여러 분류모델을 한 번에 검증한다.

    Parameters
    ----------
    feature_result : dict
        build_top_feature_df() 결과.
    model_configs : list[dict] or None
        예:
        [
            {"model_name": "random_forest", "model_params": {"n_estimators": 300}},
            {"model_name": "extra_trees", "model_params": {"n_estimators": 300}},
            {"model_name": "logistic", "model_params": {"C": 0.5}},
        ]
        None이면 기본 모델 세트를 사용한다.
    pred_threshold : float
        예측확률을 1로 바꿀 기준값.

    Returns
    -------
    result : dict
        - summary_df : 모델별 metric 비교표
        - results : 모델별 상세 결과 dict
    """

    if model_configs is None:
        model_configs = [
            {"model_name": "random_forest", "model_params": None},
            {"model_name": "extra_trees", "model_params": None},
            {"model_name": "gradient_boosting", "model_params": None},
            {"model_name": "hist_gradient_boosting", "model_params": None},
            {"model_name": "logistic", "model_params": None},
            {"model_name": "svc", "model_params": None},
        ]

    results = {}
    metric_list = []

    for cfg in model_configs:
        model_name = cfg.get("model_name")
        model_params = cfg.get("model_params")

        if verbose:
            print("=" * 80)
            print(f"모델 검증 시작: {model_name}")
            print("model_params:", model_params)
            print("=" * 80)

        result = validate_top_feature_df(
            feature_result=feature_result,
            model_name=model_name,
            model_params=model_params,
            pred_threshold=pred_threshold,
            random_state=random_state,
            verbose=verbose
        )

        results[model_name] = result
        metric_list.append(result["metric_df"])

    summary_df = pd.concat(metric_list, ignore_index=True)

    sort_cols = ["pred_1_precision", "precision", "recall", "f1"]
    summary_df = summary_df.sort_values(
        sort_cols,
        ascending=[False, False, False, False]
    ).reset_index(drop=True)

    if verbose:
        print("=" * 80)
        print("모델별 검증 결과 요약")
        print("=" * 80)
        display(summary_df)

    return {
        "summary_df": summary_df,
        "results": results
    }

In [6]:

# =========================================================
# Rolling 검증 + Excel 관리용 함수
# - base_df는 한 번만 만들고, fold별 as_of_date 기준으로 잘라서 사용
# - 하나의 파라미터 조합 + 하나의 모델 = 하나의 Excel run
# - run 내부에 rolling 평균/표준편차와 fold별 상세 결과 저장
# =========================================================

import os
import json
import hashlib
from pathlib import Path
from datetime import datetime
import re


def get_nearest_trading_date_on_or_before(base_df, target_date, date_col="Date"):
    """target_date 이하에서 가장 가까운 실제 거래일을 반환한다."""
    dates = pd.to_datetime(base_df[date_col]).sort_values().dropna().unique()
    target_date = pd.to_datetime(target_date)
    valid_dates = dates[dates <= np.datetime64(target_date)]

    if len(valid_dates) == 0:
        raise ValueError(f"{target_date} 이전 거래일이 없습니다.")

    return pd.Timestamp(valid_dates[-1])


def make_rolling_as_of_dates(
    base_df,
    n_folds=10,
    step_months=1,
    end_date=None,
    date_col="Date"
):
    """
    최근 기준일부터 step_months씩 뒤로 밀면서 rolling 기준일 목록을 만든다.

    예:
    max_date=2026-05-20, n_folds=10, step_months=1
    → 2026-05-20, 2026-04-20, 2026-03-20 ... 근처의 실제 거래일
    """
    base_df = base_df.copy()
    base_df[date_col] = pd.to_datetime(base_df[date_col])

    if end_date is None:
        end_date = base_df[date_col].max()
    else:
        end_date = pd.to_datetime(end_date)

    as_of_dates = []

    for i in range(n_folds):
        raw_date = end_date - pd.DateOffset(months=i * step_months)
        as_of_date = get_nearest_trading_date_on_or_before(
            base_df=base_df,
            target_date=raw_date,
            date_col=date_col
        )
        as_of_dates.append(as_of_date)

    # 중복 제거. 휴장/월말 차이 때문에 드물게 중복될 수 있음.
    as_of_dates = list(dict.fromkeys(as_of_dates))
    return as_of_dates


def build_top_feature_df(
    etf_code,
    n_days,
    threshold,
    lag_search_years,
    random_state=42,
    n_rf_runs=3,
    n_repeats=10,
    top_n=30,
    start_date=START_DATE,
    end_date=END_DATE,
    valid_months=VALID_MONTHS,
    external_tickers=EXTERNAL_TICKERS,
    external_feature_types=EXTERNAL_FEATURE_TYPES,
    vif_threshold=VIF_THRESHOLD,
    lag_days=LAG_DAYS,
    base_df=None,
    base_feature_cols=None,
    close_col=None,
    as_of_date=None,
    verbose=True
):
    """
    base_df 생성/입력 → as_of_date 기준 자르기 → train/valid 분리 → VIF 제거 → target 생성
    → lag 탐색 → lagged_df 생성 → RF permutation importance → top_feature_df 추출.

    rolling 검증에서는 base_df/base_feature_cols/close_col을 미리 만들어 넣는 것을 권장한다.
    """

    # =========================================================
    # 1. target 없는 base dataset 준비
    # =========================================================
    if verbose:
        print()
        print("=" * 50)
        print("1. Base feature dataset prepared.")

    if base_df is None:
        base_df, base_feature_cols, close_col = make_base_feature_dataset(
            etf_code=etf_code,
            external_tickers=external_tickers,
            external_feature_types=external_feature_types,
            start_date=start_date,
            end_date=end_date
        )
    else:
        base_df = base_df.copy()
        if base_feature_cols is None:
            if close_col is None:
                close_col = f"{etf_code}_adj_close"
            base_feature_cols = [c for c in base_df.columns if c not in ["Date", close_col]]
        if close_col is None:
            close_col = f"{etf_code}_adj_close"

    base_df["Date"] = pd.to_datetime(base_df["Date"])
    base_df = base_df.sort_values("Date").reset_index(drop=True)

    if as_of_date is not None:
        as_of_date = get_nearest_trading_date_on_or_before(base_df, as_of_date, date_col="Date")
        base_df = base_df[base_df["Date"] <= as_of_date].copy().reset_index(drop=True)

    max_date = base_df["Date"].max()
    valid_start_date = max_date - pd.DateOffset(months=valid_months)

    train_base_df = base_df[base_df["Date"] < valid_start_date].copy()
    valid_base_df = base_df[base_df["Date"] >= valid_start_date].copy()

    if len(train_base_df) == 0 or len(valid_base_df) == 0:
        raise ValueError("train_base_df 또는 valid_base_df가 비어 있습니다. 기간 설정을 확인하세요.")

    if verbose:
        print("as_of_date:", max_date)
        print("valid_start_date:", valid_start_date)
        print("train_base_df shape:", train_base_df.shape)
        print("valid_base_df shape:", valid_base_df.shape)
        print("close_col:", close_col)
        print("=" * 50)

    # =========================================================
    # 2. VIF 기반 불필요 컬럼 제거: train 구간만 사용
    # =========================================================
    if verbose:
        print()
        print("=" * 50)
        print("2. VIF filtering")

    vif_feature_cols, removed_vif_df, final_vif_df = reduce_features_by_vif(
        df=train_base_df,
        feature_cols=base_feature_cols,
        vif_threshold=vif_threshold,
        date_col="Date",
        verbose=verbose
    )

    keep_cols = ["Date", close_col] + vif_feature_cols
    vif_filtered_df = train_base_df[keep_cols].copy()

    if verbose:
        print("vif_filtered_df shape:", vif_filtered_df.shape)
        print("=" * 50)

    # =========================================================
    # 3. Target 변수 생성: train 구간만 사용
    # =========================================================
    if verbose:
        print()
        print("=" * 50)
        print("3. Target column")

    target_df, target_col = add_target_column(
        df=vif_filtered_df,
        close_col=close_col,
        n_days=n_days,
        threshold=threshold
    )

    target_df = target_df.dropna(subset=[target_col]).copy()
    target_df[target_col] = target_df[target_col].astype(int)

    if target_df[target_col].nunique() < 2:
        raise ValueError(
            f"train target이 한 클래스만 존재합니다. target 분포: {target_df[target_col].value_counts().to_dict()}"
        )

    if verbose:
        print("target_col:", target_col)
        print("target_df shape after dropna:", target_df.shape)
        print("target 분포:")
        print(target_df[target_col].value_counts())
        print("=" * 50)

    # =========================================================
    # 4. 최근 lag_search_years 기준으로 lag 탐색: train 구간 내부만 사용
    # =========================================================
    if verbose:
        print()
        print("=" * 50)
        print("4. Best lag search")

    train_max_date = target_df["Date"].max()
    lag_search_start_date = train_max_date - pd.DateOffset(years=lag_search_years)

    target_df_for_lag_search = target_df[target_df["Date"] >= lag_search_start_date].copy()

    exclude_cols_for_lag = ["Date", close_col, f"future_ret_{n_days}d", target_col]
    lag_search_feature_cols = [col for col in target_df.columns if col not in exclude_cols_for_lag]

    lag_result_df, best_lag_df = find_best_lag_by_feature(
        df=target_df_for_lag_search,
        feature_cols=lag_search_feature_cols,
        target_col=target_col,
        lag_days=lag_days,
        date_col="Date"
    )

    # =========================================================
    # 5. best lag 적용해서 lagged_df 생성
    # =========================================================
    lagged_df, lagged_feature_cols = make_lagged_dataset_by_best_lag(
        df=target_df,
        best_lag_df=best_lag_df,
        target_col=target_col,
        close_col=close_col,
        n_days=n_days,
        date_col="Date"
    )

    if lagged_df[target_col].nunique() < 2:
        raise ValueError(
            f"lagged_df target이 한 클래스만 존재합니다. target 분포: {lagged_df[target_col].value_counts().to_dict()}"
        )

    if verbose:
        print("lagged_df shape:", lagged_df.shape)
        print("lagged feature count:", len(lagged_feature_cols))
        print("=" * 50)

    # =========================================================
    # 6. permutation importance 실행
    # =========================================================
    if verbose:
        print()
        print("=" * 50)
        print("5. RF permutation importance")

    importance_df, raw_importance_df, baseline_df = run_rf_permutation_importance_in_sample(
        lagged_df=lagged_df,
        feature_cols=lagged_feature_cols,
        target_col=target_col,
        date_col="Date",
        close_col=close_col,
        n_rf_runs=n_rf_runs,
        n_repeats=n_repeats,
        random_state=random_state
    )

    # =========================================================
    # 7. 결과 feature명 / lag 분리 + best_lag_df 병합
    # =========================================================
    importance_view_df = importance_df.copy()
    importance_view_df[["base_feature", "selected_lag"]] = importance_view_df["feature"].apply(
        lambda x: pd.Series(split_lagged_feature_name(x))
    )

    importance_view_df = importance_view_df[
        [
            "feature", "base_feature", "selected_lag",
            "importance_score", "importance_mean", "importance_std", "importance_var",
            "importance_min", "importance_max", "run_count", "repeat_count"
        ]
    ]

    importance_with_lag_df = importance_view_df.merge(
        best_lag_df.rename(columns={
            "feature": "base_feature",
            "lag": "best_lag",
            "corr": "lag_corr",
            "abs_corr": "lag_abs_corr",
            "n_rows": "lag_n_rows"
        }),
        on="base_feature",
        how="left"
    )

    importance_with_lag_df = importance_with_lag_df.sort_values(
        "importance_score",
        ascending=False
    ).reset_index(drop=True)

    top_feature_df = importance_with_lag_df.head(top_n).copy()
    top_feature_cols = top_feature_df["feature"].tolist()

    if verbose:
        print("TOP feature count:", len(top_feature_cols))
        print(top_feature_cols)
        print("=" * 50)
        display(top_feature_df)

    result = {
        "etf_code": etf_code,
        "n_days": n_days,
        "threshold": threshold,
        "lag_search_years": lag_search_years,
        "random_state": random_state,
        "n_rf_runs": n_rf_runs,
        "n_repeats": n_repeats,
        "top_n": top_n,
        "start_date": start_date,
        "end_date": end_date,
        "valid_months": valid_months,
        "vif_threshold": vif_threshold,
        "lag_days": lag_days,
        "as_of_date": max_date,
        "valid_start_date": valid_start_date,

        "base_df": base_df,
        "base_feature_cols": base_feature_cols,
        "train_base_df": train_base_df,
        "valid_base_df": valid_base_df,
        "close_col": close_col,

        "vif_feature_cols": vif_feature_cols,
        "removed_vif_df": removed_vif_df,
        "final_vif_df": final_vif_df,
        "vif_filtered_df": vif_filtered_df,

        "target_df": target_df,
        "target_col": target_col,

        "lag_result_df": lag_result_df,
        "best_lag_df": best_lag_df,
        "lagged_df": lagged_df,
        "lagged_feature_cols": lagged_feature_cols,

        "importance_df": importance_df,
        "raw_importance_df": raw_importance_df,
        "baseline_df": baseline_df,
        "importance_with_lag_df": importance_with_lag_df,

        "top_feature_df": top_feature_df,
        "top_feature_cols": top_feature_cols
    }

    return result


def summarize_selected_features(fold_feature_results):
    """rolling fold별 top_feature_df를 모아서 반복 선택된 feature를 집계한다."""
    records = []

    for fold_result in fold_feature_results:
        fold = fold_result["fold"]
        as_of_date = fold_result["as_of_date"]
        top_df = fold_result["feature_result"]["top_feature_df"].copy()
        top_df["fold"] = fold
        top_df["as_of_date"] = as_of_date
        records.append(top_df)

    if len(records) == 0:
        return pd.DataFrame(), pd.DataFrame()

    all_selected_df = pd.concat(records, ignore_index=True)

    selected_summary_df = (
        all_selected_df
        .groupby("feature", as_index=False)
        .agg(
            selected_count=("fold", "nunique"),
            avg_importance_score=("importance_score", "mean"),
            avg_importance_mean=("importance_mean", "mean"),
            avg_importance_std=("importance_std", "mean"),
            avg_selected_lag=("selected_lag", "mean"),
            first_base_feature=("base_feature", "first")
        )
        .sort_values(["selected_count", "avg_importance_score"], ascending=[False, False])
        .reset_index(drop=True)
    )

    return all_selected_df, selected_summary_df


def summarize_rolling_metrics(fold_metric_df):
    """fold별 metric을 평균/표준편차 metric dict로 변환한다."""
    metric_cols = [
        "accuracy", "precision", "recall", "f1", "auc", "logloss",
        "pred_1_precision", "eval_count", "pred_1_count",
        "pred_1_actual_1_count", "tp", "fp", "tn", "fn"
    ]

    summary = {}
    for col in metric_cols:
        if col not in fold_metric_df.columns:
            continue

        s = pd.to_numeric(fold_metric_df[col], errors="coerce")
        summary[f"rolling_{col}_mean"] = s.mean(skipna=True)
        summary[f"rolling_{col}_std"] = s.std(skipna=True)
        summary[f"rolling_{col}_min"] = s.min(skipna=True)
        summary[f"rolling_{col}_max"] = s.max(skipna=True)

    # pred_1_precision은 pred=1이 하나도 없으면 NaN이 되므로, 보수적으로 0 처리한 평균도 같이 저장
    if "pred_1_precision" in fold_metric_df.columns:
        s0 = pd.to_numeric(fold_metric_df["pred_1_precision"], errors="coerce").fillna(0)
        summary["rolling_pred_1_precision_zero_fill_mean"] = s0.mean()

    return summary




# =========================================================
# Excel 저장 유틸
# =========================================================
EXCEL_EXPERIMENT_DIR = Path("experiments_excel")


def make_safe_filename(value):
    """파일/폴더명에 쓰기 어려운 문자를 정리한다."""
    value = str(value)
    value = re.sub(r"[^0-9A-Za-z가-힣_.\-]+", "_", value)
    value = value.strip("_")
    return value[:120] if len(value) > 120 else value


def make_run_id(etf_code, model_name, n_days, threshold, top_n, run_name=None):
    """실험별 고유 run_id 생성."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    if run_name is None:
        run_name = f"{etf_code}_{model_name}_{n_days}d_thr{threshold}_top{top_n}"

    return make_safe_filename(f"{timestamp}_{run_name}")


# ---------------------------------------------------------
# 중복 실험 스킵용 유틸
# ---------------------------------------------------------
EXPERIMENT_KEY_COLS = [
    "etf_code",
    "n_days",
    "threshold",
    "valid_months",
    "vif_threshold",
    "lag_search_years",
    "lag_days",
    "random_state",
    "n_rf_runs",
    "n_repeats",
    "top_n",
    "pred_threshold",
    "model_name",
    "model_params",
    "n_folds",
    "step_months",
    "start_date",
    "end_date",
]


SUMMARY_COLUMNS = [
    "experiment_key",
    "created_dt",
    "run_id",
    "etf_code",
    "rolling_precision_mean",
    "n_days",
    "threshold",
    "valid_months",
    "vif_threshold",
    "lag_search_years",
    "lag_days",
    "top_n",
    "pred_threshold",
    "model_name",
    "model_params",
    "n_folds",
    "step_months",
    "rolling_accuracy_mean",
    "rolling_accuracy_std",
    "rolling_accuracy_min",
    "rolling_accuracy_max",
    "rolling_precision_std",
    "rolling_precision_min",
    "rolling_precision_max",
    "rolling_recall_mean",
    "rolling_recall_std",
    "rolling_recall_min",
    "rolling_recall_max",
    "rolling_f1_mean",
    "rolling_f1_std",
    "rolling_f1_min",
    "rolling_f1_max",
    "rolling_auc_mean",
    "rolling_auc_std",
    "rolling_auc_min",
    "rolling_auc_max",
    "rolling_logloss_mean",
    "rolling_logloss_std",
    "rolling_logloss_min",
    "rolling_logloss_max",
    "n_folds_success",
    "error_count",
]


def normalize_experiment_value(value):
    """실험 조건 비교를 위해 값 표현을 안정적으로 통일한다."""
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, (pd.Timestamp, np.datetime64)):
        return str(pd.to_datetime(value).date())
    if isinstance(value, float):
        return round(value, 12)
    if isinstance(value, dict):
        return {str(k): normalize_experiment_value(v) for k, v in sorted(value.items(), key=lambda x: str(x[0]))}
    if isinstance(value, (list, tuple, set)):
        return [normalize_experiment_value(v) for v in list(value)]
    if pd.isna(value) if not isinstance(value, (list, tuple, dict, set)) else False:
        return None
    return value


def make_experiment_key(config):
    """동일 실험 여부를 판단하는 key를 만든다. run_id처럼 시간은 포함하지 않는다."""
    key_dict = {
        col: normalize_experiment_value(config.get(col))
        for col in EXPERIMENT_KEY_COLS
    }
    key_json = json.dumps(key_dict, ensure_ascii=False, sort_keys=True, default=str)
    return hashlib.md5(key_json.encode("utf-8")).hexdigest()


def load_master_summary(experiment_dir=EXCEL_EXPERIMENT_DIR):
    """전체 summary Excel을 읽는다. 없으면 빈 DataFrame 반환."""
    master_summary_path = Path(experiment_dir) / "experiment_summary.xlsx"
    if not master_summary_path.exists():
        return pd.DataFrame()

    try:
        return pd.read_excel(master_summary_path, sheet_name="summary")
    except Exception:
        return pd.DataFrame()


def find_existing_experiment(config, experiment_dir=EXCEL_EXPERIMENT_DIR):
    """
    같은 실험 조건이 이미 저장되어 있는지 찾는다.
    - 새 버전 summary에는 experiment_key가 있으므로 experiment_key로 비교
    - 예전 summary에 experiment_key가 없으면 주요 config 컬럼 값으로 비교
    """
    master_summary_df = load_master_summary(experiment_dir)
    if master_summary_df.empty:
        return None

    target_key = make_experiment_key(config)

    for key_col in ["experiment_key", "run_key"]:
        if key_col in master_summary_df.columns:
            matched = master_summary_df[master_summary_df[key_col].astype(str) == str(target_key)]
            if len(matched) > 0:
                return matched.iloc[0].to_dict()

    compare_cols = [c for c in EXPERIMENT_KEY_COLS if c in master_summary_df.columns]
    if len(compare_cols) == 0:
        return None

    target_norm = {c: normalize_experiment_value(config.get(c)) for c in compare_cols}

    for _, row in master_summary_df.iterrows():
        is_same = True
        for col in compare_cols:
            old_value = row.get(col)
            # Excel에서 list/dict는 문자열로 저장되므로 문자열 비교까지 허용
            old_norm = normalize_experiment_value(old_value)
            new_norm = target_norm[col]
            if str(old_norm) != str(new_norm):
                is_same = False
                break
        if is_same:
            return row.to_dict()

    return None


def to_excel_safe_value(value):
    """dict/list/Timestamp 등을 Excel에 넣기 쉬운 값으로 변환한다."""
    if isinstance(value, (dict, list, tuple, set)):
        return json.dumps(value, ensure_ascii=False, default=str)
    if isinstance(value, (pd.Timestamp, np.datetime64)):
        return str(pd.to_datetime(value))
    if isinstance(value, Path):
        return str(value)
    return value


def make_config_df(config):
    """config dict를 key/value 형태의 DataFrame으로 변환한다."""
    return pd.DataFrame([
        {"key": k, "value": to_excel_safe_value(v)}
        for k, v in config.items()
    ])


def make_one_row_df(row_dict):
    """summary dict를 한 줄 DataFrame으로 변환한다."""
    return pd.DataFrame([{k: to_excel_safe_value(v) for k, v in row_dict.items()}])


def prepare_df_for_excel(df):
    """Excel 저장 전 object 컬럼 내 dict/list 등을 문자열로 변환한다."""
    if df is None:
        return pd.DataFrame()

    out = df.copy()

    for col in out.columns:
        if out[col].dtype == "object":
            out[col] = out[col].apply(to_excel_safe_value)

    return out


def write_excel_book(path, sheet_dict):
    """여러 DataFrame을 하나의 Excel 파일로 저장한다."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    with pd.ExcelWriter(path, engine="openpyxl") as writer:
        for sheet_name, df in sheet_dict.items():
            safe_sheet_name = str(sheet_name)[:31]
            safe_df = prepare_df_for_excel(df)
            safe_df.to_excel(writer, sheet_name=safe_sheet_name, index=False)

            # 컬럼 너비 자동 보정
            ws = writer.sheets[safe_sheet_name]
            for col_cells in ws.columns:
                col_letter = col_cells[0].column_letter
                max_len = 0
                for cell in col_cells[:200]:
                    if cell.value is not None:
                        max_len = max(max_len, len(str(cell.value)))
                ws.column_dimensions[col_letter].width = min(max(max_len + 2, 10), 45)

    return path


def concat_fold_validation_df(fold_validation_results, key):
    """fold_validation_results 안의 valid_pred_df/eval_df 등을 fold 정보와 함께 합친다."""
    records = []

    for item in fold_validation_results:
        fold = item["fold"]
        as_of_date = item["as_of_date"]
        valid_result = item["valid_result"]

        if key not in valid_result:
            continue

        df = valid_result[key]
        if df is None or len(df) == 0:
            continue

        tmp = df.copy()
        tmp.insert(0, "fold", fold)
        tmp.insert(1, "as_of_date", as_of_date)
        records.append(tmp)

    if len(records) == 0:
        return pd.DataFrame()

    return pd.concat(records, ignore_index=True)


def concat_fold_feature_df(fold_feature_results, key):
    """fold_feature_results 안의 top_feature_df/best_lag_df 등을 fold 정보와 함께 합친다."""
    records = []

    for item in fold_feature_results:
        fold = item["fold"]
        as_of_date = item["as_of_date"]
        feature_result = item["feature_result"]

        if key not in feature_result:
            continue

        df = feature_result[key]
        if df is None or len(df) == 0:
            continue

        tmp = df.copy()
        tmp.insert(0, "fold", fold)
        tmp.insert(1, "as_of_date", as_of_date)
        records.append(tmp)

    if len(records) == 0:
        return pd.DataFrame()

    return pd.concat(records, ignore_index=True)


def order_summary_df(summary_df, summary_columns=SUMMARY_COLUMNS):
    """summary 시트 컬럼 순서를 고정한다. 지정하지 않은 추가 컬럼은 뒤쪽에 붙인다."""
    if summary_df is None or len(summary_df.columns) == 0:
        return pd.DataFrame(columns=summary_columns)

    summary_df = summary_df.copy()

    # 예전 컬럼명 호환
    if "experiment_key" in summary_df.columns and "experiment_key" not in summary_df.columns:
        summary_df = summary_df.rename(columns={"experiment_key": "experiment_key"})
    if "created_dt" in summary_df.columns and "created_dt" not in summary_df.columns:
        summary_df = summary_df.rename(columns={"created_dt": "created_dt"})
    if "n_folds" in summary_df.columns and "n_folds" not in summary_df.columns:
        summary_df = summary_df.rename(columns={"n_folds": "n_folds"})

    for col in summary_columns:
        if col not in summary_df.columns:
            summary_df[col] = np.nan

    extra_cols = [c for c in summary_df.columns if c not in summary_columns]
    return summary_df[summary_columns + extra_cols]


def save_rolling_result_to_excel(result, config, experiment_dir=EXCEL_EXPERIMENT_DIR, run_name=None):
    """
    rolling 검증 결과를 experiment_summary.xlsx 하나에 누적 저장한다.

    저장 구조:
    experiments_excel/
      experiment_summary.xlsx    # summary 시트 하나만 사용
    """
    experiment_dir = Path(experiment_dir)
    experiment_dir.mkdir(parents=True, exist_ok=True)

    run_id = make_run_id(
        etf_code=config.get("etf_code"),
        model_name=config.get("model_name"),
        n_days=config.get("n_days"),
        threshold=config.get("threshold"),
        top_n=config.get("top_n"),
        run_name=run_name,
    )

    rolling_summary = result.get("rolling_summary", {})
    fold_metric_df = result.get("fold_metric_df", pd.DataFrame())
    errors = result.get("errors", [])

    experiment_key = make_experiment_key(config)

    summary_row = {
        "experiment_key": experiment_key,
        "created_dt": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "run_id": run_id,
        **config,
        **rolling_summary,
        "n_folds_success": len(fold_metric_df),
        "error_count": len(errors),
    }

    summary_df = order_summary_df(make_one_row_df(summary_row))

    # 전체 summary 누적 파일 갱신. 개별 run_result.xlsx는 만들지 않는다.
    # master_summary_path = experiment_dir / "experiment_summary.xlsx"
    master_summary_path = experiment_dir / "experiment_summary2.xlsx"

    if master_summary_path.exists():
        try:
            old_summary_df = pd.read_excel(master_summary_path, sheet_name="summary")
            old_summary_df = order_summary_df(old_summary_df)
            master_summary_df = pd.concat([old_summary_df, summary_df], ignore_index=True)
        except Exception:
            master_summary_df = summary_df.copy()
    else:
        master_summary_df = summary_df.copy()

    # 혹시 같은 experiment_key가 중복으로 들어왔으면 최신 1개만 남긴다.
    if "experiment_key" in master_summary_df.columns:
        master_summary_df = master_summary_df.drop_duplicates(subset=["experiment_key"], keep="last")

    master_summary_df = order_summary_df(master_summary_df)

    sort_candidates = [
        "rolling_precision_mean",
        "rolling_recall_mean",
        "rolling_f1_mean",
        "rolling_auc_mean",
    ]
    sort_cols = [c for c in sort_candidates if c in master_summary_df.columns]

    if len(sort_cols) > 0:
        master_summary_df = master_summary_df.sort_values(sort_cols, ascending=False).reset_index(drop=True)

    write_excel_book(
        master_summary_path,
        {
            "summary": master_summary_df,
        }
    )

    return {
        "run_id": run_id,
        "experiment_key": experiment_key,
        "master_summary_path": str(master_summary_path),
    }

def run_rolling_validation(
    etf_code=ETF_CODE,
    n_days=N_DAYS,
    threshold=THRESHOLD,
    valid_months=VALID_MONTHS,
    vif_threshold=VIF_THRESHOLD,
    lag_search_years=LAG_SEARCH_YEARS,
    lag_days=LAG_DAYS,
    random_state=RANDOM_STATE,
    n_rf_runs=N_RF_RUNS,
    n_repeats=N_REPEATS,
    top_n=TOP_N,
    pred_threshold=PRED_THRESHOLD,
    model_name="random_forest",
    model_params=None,
    n_folds=10,
    step_months=1,
    start_date=START_DATE,
    end_date=END_DATE,
    external_tickers=EXTERNAL_TICKERS,
    external_feature_types=EXTERNAL_FEATURE_TYPES,
    base_df=None,
    base_feature_cols=None,
    close_col=None,
    save_to_excel=True,
    experiment_dir=EXCEL_EXPERIMENT_DIR,
    skip_existing=True,
    run_name=None,
    verbose=True,
    fold_verbose=False
):
    """
    rolling 검증 실행.

    구조:
    - base_df를 한 번만 생성
    - fold 1: 최신 as_of_date 기준 최근 valid_months 검증
    - fold 2: as_of_date를 step_months만큼 과거로 이동
    - ... n_folds 반복
    - fold별 성능 평균/표준편차와 상세 결과를 Excel로 저장
    """

    if model_params is None:
        model_params = {}

    config = {
        "etf_code": etf_code,
        "n_days": n_days,
        "threshold": threshold,
        "valid_months": valid_months,
        "vif_threshold": vif_threshold,
        "lag_search_years": lag_search_years,
        "lag_days": lag_days,
        "random_state": random_state,
        "n_rf_runs": n_rf_runs,
        "n_repeats": n_repeats,
        "top_n": top_n,
        "pred_threshold": pred_threshold,
        "model_name": model_name,
        "model_params": model_params,
        "n_folds": n_folds,
        "step_months": step_months,
        "start_date": start_date,
        "end_date": end_date,
    }

    # 이미 같은 조건으로 저장된 실험이 있으면 재실행하지 않는다.
    if save_to_excel and skip_existing:
        existing_run = find_existing_experiment(config, experiment_dir=experiment_dir)
        if existing_run is not None:
            if verbose:
                print("\n기존에 같은 조건의 실험 결과가 있어 재실행을 건너뜁니다.")
                print("기존 run_id:", existing_run.get("run_id"))
                if "master_summary_path" in existing_run:
                    print("summary 파일:", existing_run.get("master_summary_path"))
            return {
                "skipped_existing": True,
                "existing_run": existing_run,
                "rolling_summary": {k: v for k, v in existing_run.items() if str(k).startswith("rolling_")},
                "fold_metric_df": pd.DataFrame(),
                "errors": [],
                "excel_save_info": {
                    "run_id": existing_run.get("run_id"),
                    "experiment_key": existing_run.get("experiment_key"),
                    "master_summary_path": str(Path(experiment_dir) / "experiment_summary.xlsx"),
                },
            }

    # =========================================================
    # 0. base_df 한 번만 생성
    # =========================================================
    if base_df is None:
        if verbose:
            print("=" * 80)
            print("Base dataset 생성 시작")
            print("=" * 80)

        base_df, base_feature_cols, close_col = make_base_feature_dataset(
            etf_code=etf_code,
            external_tickers=external_tickers,
            external_feature_types=external_feature_types,
            start_date=start_date,
            end_date=end_date
        )
    else:
        base_df = base_df.copy()
        if close_col is None:
            close_col = f"{etf_code}_adj_close"
        if base_feature_cols is None:
            base_feature_cols = [c for c in base_df.columns if c not in ["Date", close_col]]

    base_df["Date"] = pd.to_datetime(base_df["Date"])
    base_df = base_df.sort_values("Date").reset_index(drop=True)

    as_of_dates = make_rolling_as_of_dates(
        base_df=base_df,
        n_folds=n_folds,
        step_months=step_months,
        end_date=end_date if end_date is not None else None,
        date_col="Date"
    )

    if verbose:
        print("=" * 80)
        print("Rolling 기준일")
        print("=" * 80)
        for i, d in enumerate(as_of_dates, start=1):
            print(f"fold {i:02d}: {d.date()}")

    fold_metric_list = []
    fold_feature_results = []
    fold_validation_results = []
    errors = []

    # =========================================================
    # 1. rolling fold 반복
    # =========================================================
    for fold, as_of_date in enumerate(as_of_dates, start=1):
        if verbose:
            print("\n" + "#" * 100)
            print(f"ROLLING FOLD {fold}/{len(as_of_dates)} | as_of_date={as_of_date.date()}")
            print("#" * 100)

        try:
            feature_result = build_top_feature_df(
                etf_code=etf_code,
                n_days=n_days,
                threshold=threshold,
                lag_search_years=lag_search_years,
                random_state=random_state,
                n_rf_runs=n_rf_runs,
                n_repeats=n_repeats,
                top_n=top_n,
                start_date=start_date,
                end_date=end_date,
                valid_months=valid_months,
                external_tickers=external_tickers,
                external_feature_types=external_feature_types,
                vif_threshold=vif_threshold,
                lag_days=lag_days,
                base_df=base_df,
                base_feature_cols=base_feature_cols,
                close_col=close_col,
                as_of_date=as_of_date,
                verbose=fold_verbose
            )

            valid_result = validate_top_feature_df(
                feature_result=feature_result,
                model_name=model_name,
                model_params=model_params,
                pred_threshold=pred_threshold,
                random_state=random_state,
                verbose=fold_verbose
            )

            metric_row = valid_result["metric_df"].iloc[0].to_dict()
            metric_row.update({
                "fold": fold,
                "as_of_date": as_of_date,
                "valid_start_date": feature_result.get("valid_start_date"),
                "valid_end_date": feature_result.get("as_of_date"),
                "error": None
            })

            fold_metric_list.append(pd.DataFrame([metric_row]))
            fold_feature_results.append({
                "fold": fold,
                "as_of_date": as_of_date,
                "feature_result": feature_result
            })
            fold_validation_results.append({
                "fold": fold,
                "as_of_date": as_of_date,
                "valid_result": valid_result
            })

            if verbose:
                print(
                    f"fold {fold:02d} 완료 | "
                    f"precision={metric_row.get('precision')} | "
                    f"pred_1_precision={metric_row.get('pred_1_precision')} | "
                    f"pred_1_count={metric_row.get('pred_1_count')} | "
                    f"eval_count={metric_row.get('eval_count')}"
                )

        except Exception as e:
            err = {
                "fold": fold,
                "as_of_date": as_of_date,
                "error": str(e)
            }
            errors.append(err)
            if verbose:
                print(f"[FOLD SKIP] fold {fold} 실패: {e}")

    if len(fold_metric_list) == 0:
        raise ValueError(f"성공한 rolling fold가 없습니다. errors={errors}")

    fold_metric_df = pd.concat(fold_metric_list, ignore_index=True)
    rolling_summary = summarize_rolling_metrics(fold_metric_df)

    all_selected_features_df, selected_features_summary_df = summarize_selected_features(fold_feature_results)

    # 보기 좋게 정렬
    sort_cols = ["rolling_precision_mean", "rolling_pred_1_precision_zero_fill_mean", "rolling_recall_mean", "rolling_f1_mean"]
    for c in sort_cols:
        if c not in rolling_summary:
            rolling_summary[c] = np.nan

    if verbose:
        print("\n" + "=" * 80)
        print("Rolling 검증 요약")
        print("=" * 80)
        print("성공 fold 수:", len(fold_metric_df))
        print("실패 fold 수:", len(errors))
        print("rolling_precision_mean:", rolling_summary.get("rolling_precision_mean"))
        print("rolling_pred_1_precision_zero_fill_mean:", rolling_summary.get("rolling_pred_1_precision_zero_fill_mean"))
        print("rolling_pred_1_count_mean:", rolling_summary.get("rolling_pred_1_count_mean"))
        display(fold_metric_df)
        display(selected_features_summary_df.head(30))

    result = {
        "fold_metric_df": fold_metric_df,
        "rolling_summary": rolling_summary,
        "all_selected_features_df": all_selected_features_df,
        "selected_features_summary_df": selected_features_summary_df,
        "fold_feature_results": fold_feature_results,
        "fold_validation_results": fold_validation_results,
        "errors": errors,
        "base_df": base_df,
        "base_feature_cols": base_feature_cols,
        "close_col": close_col,
    }

    config = {
        "etf_code": etf_code,
        "n_days": n_days,
        "threshold": threshold,
        "valid_months": valid_months,
        "vif_threshold": vif_threshold,
        "lag_search_years": lag_search_years,
        "lag_days": lag_days,
        "random_state": random_state,
        "n_rf_runs": n_rf_runs,
        "n_repeats": n_repeats,
        "top_n": top_n,
        "pred_threshold": pred_threshold,
        "model_name": model_name,
        "model_params": model_params,
        "n_folds": n_folds,
        "step_months": step_months,
        "start_date": start_date,
        "end_date": end_date,
    }

    if save_to_excel:
        excel_save_info = save_rolling_result_to_excel(
            result=result,
            config=config,
            experiment_dir=experiment_dir,
            run_name=run_name,
        )
        result["excel_save_info"] = excel_save_info

        if verbose:
            print("\nExcel 저장 완료")
            print("전체 summary 파일:", excel_save_info["master_summary_path"])

    return result


def run_experiment_grid_rolling(
    experiment_grid,
    base_df=None,
    base_feature_cols=None,
    close_col=None,
    save_to_excel=True,
    experiment_dir=EXCEL_EXPERIMENT_DIR,
    skip_existing=True,
    verbose=True,
    fold_verbose=False
):
    """
    여러 파라미터 조합을 rolling 검증으로 반복 실행한다.

    experiment_grid 예:
    [
        {
            "etf_code": "SMH",
            "n_days": 5,
            "threshold": 0.01,
            "model_name": "random_forest",
            "model_params": {"n_estimators": 500, "max_depth": None},
            "top_n": 30,
            "n_folds": 10,
        },
        ...
    ]
    """

    experiment_dir = Path(experiment_dir)
    results = []
    summary_rows = []

    # base_df를 넣지 않았으면 첫 번째 grid 기준으로 한 번만 생성
    if base_df is None:
        first = experiment_grid[0]
        etf_code = first.get("etf_code", ETF_CODE)
        start_date = first.get("start_date", START_DATE)
        end_date = first.get("end_date", END_DATE)
        external_tickers = first.get("external_tickers", EXTERNAL_TICKERS)
        external_feature_types = first.get("external_feature_types", EXTERNAL_FEATURE_TYPES)

        if verbose:
            print("=" * 80)
            print("Grid 공통 base_df 생성")
            print("=" * 80)

        base_df, base_feature_cols, close_col = make_base_feature_dataset(
            etf_code=etf_code,
            external_tickers=external_tickers,
            external_feature_types=external_feature_types,
            start_date=start_date,
            end_date=end_date
        )

    for i, cfg in enumerate(experiment_grid, start=1):
        if verbose:
            print("\n" + "=" * 100)
            print(f"EXPERIMENT {i}/{len(experiment_grid)}")
            print(cfg)
            print("=" * 100)

        result = run_rolling_validation(
            etf_code=cfg.get("etf_code", ETF_CODE),
            n_days=cfg.get("n_days", N_DAYS),
            threshold=cfg.get("threshold", THRESHOLD),
            valid_months=cfg.get("valid_months", VALID_MONTHS),
            vif_threshold=cfg.get("vif_threshold", VIF_THRESHOLD),
            lag_search_years=cfg.get("lag_search_years", LAG_SEARCH_YEARS),
            lag_days=cfg.get("lag_days", LAG_DAYS),
            random_state=cfg.get("random_state", RANDOM_STATE),
            n_rf_runs=cfg.get("n_rf_runs", N_RF_RUNS),
            n_repeats=cfg.get("n_repeats", N_REPEATS),
            top_n=cfg.get("top_n", TOP_N),
            pred_threshold=cfg.get("pred_threshold", PRED_THRESHOLD),
            model_name=cfg.get("model_name", "random_forest"),
            model_params=cfg.get("model_params", {}),
            n_folds=cfg.get("n_folds", 10),
            step_months=cfg.get("step_months", 1),
            start_date=cfg.get("start_date", START_DATE),
            end_date=cfg.get("end_date", END_DATE),
            external_tickers=cfg.get("external_tickers", EXTERNAL_TICKERS),
            external_feature_types=cfg.get("external_feature_types", EXTERNAL_FEATURE_TYPES),
            base_df=base_df,
            base_feature_cols=base_feature_cols,
            close_col=close_col,
            save_to_excel=save_to_excel,
            experiment_dir=experiment_dir,
            skip_existing=skip_existing,
            run_name=cfg.get("run_name"),
            verbose=verbose,
            fold_verbose=fold_verbose
        )

        results.append(result)

        row = cfg.copy()
        row.update(result["rolling_summary"])
        row["n_folds_success"] = len(result["fold_metric_df"])
        row["error_count"] = len(result["errors"])
        if "excel_save_info" in result:
            row.update(result["excel_save_info"])
        summary_rows.append(row)

    grid_summary_df = pd.DataFrame(summary_rows)

    if len(grid_summary_df) > 0:
        sort_candidates = [
            "rolling_precision_mean",
            "rolling_pred_1_precision_zero_fill_mean",
            "rolling_recall_mean",
            "rolling_f1_mean"
        ]
        sort_cols = [c for c in sort_candidates if c in grid_summary_df.columns]
        if len(sort_cols) > 0:
            grid_summary_df = grid_summary_df.sort_values(sort_cols, ascending=False).reset_index(drop=True)

    # 별도 grid_summary_*.xlsx는 만들지 않는다.
    # 각 실험 결과는 run_rolling_validation 내부에서 experiment_summary.xlsx 하나에 누적 저장된다.
    grid_excel_path = None
    if save_to_excel and verbose:
        print("\nGrid 결과는 experiment_summary.xlsx의 summary 시트에 누적 저장되었습니다.")

    if verbose:
        print("\n" + "=" * 80)
        print("GRID SUMMARY")
        print("=" * 80)
        display(grid_summary_df)

    return {
        "grid_summary_df": grid_summary_df,
        "results": results,
        "base_df": base_df,
        "base_feature_cols": base_feature_cols,
        "close_col": close_col,
        "grid_excel_path": str(grid_excel_path) if grid_excel_path is not None else None,
    }

In [21]:

# # =========================================================
# # Rolling 검증 실행 예시: 단일 모델/단일 조합
# # - 결과는 experiments_excel 폴더의 Excel 파일로 저장됨
# # =========================================================

# rolling_result = run_rolling_validation(
#     etf_code=ETF_CODE,
#     n_days=N_DAYS,
#     threshold=THRESHOLD,
#     valid_months=VALID_MONTHS,
#     vif_threshold=VIF_THRESHOLD,
#     lag_search_years=LAG_SEARCH_YEARS,
#     lag_days=LAG_DAYS,
#     random_state=RANDOM_STATE,
#     n_rf_runs=N_RF_RUNS,
#     n_repeats=N_REPEATS,
#     top_n=TOP_N,
#     pred_threshold=PRED_THRESHOLD,
#     model_name="random_forest",
#     model_params={
#         "n_estimators": 500,
#         "max_depth": None,
#         "class_weight": "balanced"
#     },
#     n_folds=10,
#     step_months=1,
#     save_to_excel=True,
#     experiment_dir=EXCEL_EXPERIMENT_DIR,
#     verbose=True,
#     fold_verbose=False
# )

# fold_metric_df = rolling_result["fold_metric_df"]
# selected_features_summary_df = rolling_result["selected_features_summary_df"]
# rolling_summary = rolling_result["rolling_summary"]

# print(rolling_summary)

In [22]:

# # =========================================================
# # 여러 조합 Rolling 검증 예시
# # - 하나의 cfg가 Excel run 하나가 됨
# # - 처음에는 조합을 너무 많이 넣지 말고 2~4개 정도로 테스트 추천
# # =========================================================

# experiment_grid = [
#     {
#         "etf_code": "SMH",
#         "n_days": 5,
#         "threshold": 0.01,
#         "valid_months": 1,
#         "vif_threshold": 10,
#         "lag_search_years": 1,
#         "lag_days": [1, 3, 5, 10, 20, 40, 60, 120],
#         "top_n": 30,
#         "pred_threshold": 0.5,
#         "model_name": "random_forest",
#         "model_params": {"n_estimators": 500, "max_depth": None, "class_weight": "balanced"},
#         "n_folds": 10,
#         "step_months": 1,
#     },
#     {
#         "etf_code": "SMH",
#         "n_days": 5,
#         "threshold": 0.01,
#         "valid_months": 1,
#         "vif_threshold": 10,
#         "lag_search_years": 1,
#         "lag_days": [1, 3, 5, 10, 20, 40, 60, 120],
#         "top_n": 30,
#         "pred_threshold": 0.5,
#         "model_name": "extra_trees",
#         "model_params": {"n_estimators": 500, "max_depth": None, "class_weight": "balanced"},
#         "n_folds": 10,
#         "step_months": 1,
#     },
# ]

# grid_result = run_experiment_grid_rolling(
#     experiment_grid=experiment_grid,
#     save_to_excel=True,
#     experiment_dir=EXCEL_EXPERIMENT_DIR,
#     verbose=True,
#     fold_verbose=False
# )

# grid_summary_df = grid_result["grid_summary_df"]
# grid_summary_df

In [7]:

# =========================================================
# Optuna 자동 탐색
# - 사람이 직접 조합을 다 만들지 않고 Optuna가 조합을 선택
# - 결과 저장은 기존과 동일하게 experiments_excel/experiment_summary.xlsx 하나에 누적
# - 같은 조건은 experiment_key 기준으로 자동 스킵
# =========================================================

try:
    import optuna
except ModuleNotFoundError as e:
    raise ModuleNotFoundError(
        "optuna가 설치되어 있지 않습니다. 터미널에서 아래 명령 실행 후 커널을 재시작하세요.\n"
        "pip install optuna"
    ) from e


def suggest_model_params_for_optuna(trial, model_name):
    """Optuna trial에서 모델별 하이퍼파라미터를 제안한다."""
    model_name = str(model_name).lower()

    if model_name == "random_forest":
        return {
            "n_estimators": trial.suggest_categorical("rf_n_estimators", [300, 500, 800]),
            "max_depth": trial.suggest_categorical("rf_max_depth", [None, 3, 5, 7, 10]),
            "min_samples_leaf": trial.suggest_categorical("rf_min_samples_leaf", [1, 2, 5, 10]),
            "max_features": trial.suggest_categorical("rf_max_features", ["sqrt", "log2", 0.5]),
            "class_weight": "balanced",
        }

    if model_name == "extra_trees":
        return {
            "n_estimators": trial.suggest_categorical("et_n_estimators", [300, 500, 800]),
            "max_depth": trial.suggest_categorical("et_max_depth", [None, 3, 5, 7, 10]),
            "min_samples_leaf": trial.suggest_categorical("et_min_samples_leaf", [1, 2, 5, 10]),
            "max_features": trial.suggest_categorical("et_max_features", ["sqrt", "log2", 0.5]),
            "class_weight": "balanced",
        }

    if model_name == "gradient_boosting":
        return {
            "n_estimators": trial.suggest_categorical("gb_n_estimators", [100, 300, 500]),
            "learning_rate": trial.suggest_categorical("gb_learning_rate", [0.01, 0.03, 0.05, 0.1]),
            "max_depth": trial.suggest_categorical("gb_max_depth", [2, 3, 4, 5]),
        }

    if model_name == "hist_gradient_boosting":
        return {
            "max_iter": trial.suggest_categorical("hgb_max_iter", [100, 300, 500]),
            "learning_rate": trial.suggest_categorical("hgb_learning_rate", [0.01, 0.03, 0.05, 0.1]),
            "max_leaf_nodes": trial.suggest_categorical("hgb_max_leaf_nodes", [15, 31, 63]),
        }

    if model_name == "logistic":
        return {
            "C": trial.suggest_categorical("logistic_C", [0.01, 0.1, 1.0, 10.0]),
            "class_weight": "balanced",
            "max_iter": 3000,
        }

    return {}


def build_optuna_config(trial, fixed_cfg=None):
    """
    fixed_cfg는 고정값, trial은 탐색값을 만든다.
    fixed_cfg에 값이 있으면 그 값을 우선 사용하고, 없으면 Optuna가 탐색한다.
    """
    if fixed_cfg is None:
        fixed_cfg = {}

    cfg = dict(fixed_cfg)

    cfg.setdefault("etf_code", ETF_CODE)
    cfg.setdefault("valid_months", VALID_MONTHS)
    cfg.setdefault("vif_threshold", VIF_THRESHOLD)
    cfg.setdefault("lag_search_years", LAG_SEARCH_YEARS)
    cfg.setdefault("lag_days", LAG_DAYS)
    cfg.setdefault("random_state", RANDOM_STATE)
    cfg.setdefault("n_rf_runs", N_RF_RUNS)
    cfg.setdefault("n_repeats", N_REPEATS)
    cfg.setdefault("n_folds", 6)
    cfg.setdefault("step_months", 1)
    cfg.setdefault("start_date", START_DATE)
    cfg.setdefault("end_date", END_DATE)

    if "n_days" not in cfg:
        cfg["n_days"] = trial.suggest_categorical("n_days", [3, 5, 10])

    if "threshold" not in cfg:
        cfg["threshold"] = trial.suggest_categorical("threshold", [0.005, 0.01, 0.02, 0.03])

    if "top_n" not in cfg:
        cfg["top_n"] = trial.suggest_categorical("top_n", [10, 20, 30, 50])

    if "pred_threshold" not in cfg:
        cfg["pred_threshold"] = trial.suggest_float("pred_threshold", 0.25, 0.80, step=0.05)

    if "model_name" not in cfg:
        cfg["model_name"] = trial.suggest_categorical(
            "model_name",
            ["random_forest", "gradient_boosting", "hist_gradient_boosting", "logistic"]
        )

    if "model_params" not in cfg:
        cfg["model_params"] = suggest_model_params_for_optuna(trial, cfg["model_name"])

    # summary에서 Optuna 실험 여부를 구분하기 위한 보조 컬럼. experiment_key에는 포함되지 않는다.
    cfg["search_method"] = "optuna"
    cfg["optuna_trial_number"] = trial.number

    return cfg


def get_metric_from_result(result, metric_name, default=np.nan):
    """일반 실행 결과와 skip_existing 결과에서 metric을 안전하게 꺼낸다."""
    if result is None:
        return default

    if result.get("skipped_existing", False):
        existing_run = result.get("existing_run", {})
        return existing_run.get(metric_name, default)

    rolling_summary = result.get("rolling_summary", {})
    return rolling_summary.get(metric_name, default)


def get_n_folds_success_from_result(result):
    """일반 실행 결과와 skip_existing 결과에서 성공 fold 수를 안전하게 꺼낸다."""
    if result is None:
        return 0

    if result.get("skipped_existing", False):
        existing_run = result.get("existing_run", {})
        value = existing_run.get("n_folds_success", 0)
        try:
            return int(value)
        except Exception:
            return 0

    fold_metric_df = result.get("fold_metric_df", pd.DataFrame())
    return len(fold_metric_df)


def compute_optuna_score(
    result,
    n_folds,
    objective_metric="rolling_precision_mean",
    min_success_ratio=0.8,
    min_pred_1_count_mean=1.0,
):
    """
    Optuna가 최대화할 점수를 만든다.

    기본은 rolling_precision_mean을 최대화하되,
    - 성공 fold가 너무 적으면 감점
    - 예측 1이 거의 안 나오면 감점
    """
    base_score = get_metric_from_result(result, objective_metric, default=np.nan)
    pred_1_count_mean = get_metric_from_result(result, "rolling_pred_1_count_mean", default=np.nan)
    n_success = get_n_folds_success_from_result(result)

    if pd.isna(base_score):
        return 0.0

    success_ratio = n_success / max(int(n_folds), 1)
    score = float(base_score)

    # fold 성공률 패널티
    if success_ratio < min_success_ratio:
        score *= success_ratio / max(min_success_ratio, 1e-9)

    # 예측 1 개수가 너무 적으면 패널티
    if not pd.isna(pred_1_count_mean) and pred_1_count_mean < min_pred_1_count_mean:
        score *= max(float(pred_1_count_mean), 0.0) / max(float(min_pred_1_count_mean), 1e-9)

    return float(score)


def run_optuna_experiments(
    n_trials=30,
    fixed_cfg=None,
    objective_metric="rolling_precision_mean",
    min_success_ratio=0.8,
    min_pred_1_count_mean=1.0,
    save_to_excel=True,
    experiment_dir=EXCEL_EXPERIMENT_DIR,
    skip_existing=True,
    verbose=True,
    fold_verbose=False,
):
    """
    Optuna로 실험 조건을 자동 탐색한다.

    Returns
    -------
    dict
        - study: Optuna study
        - trials_df: trial별 결과 요약
        - base_df/base_feature_cols/close_col: 재사용된 base dataset
    """
    if fixed_cfg is None:
        fixed_cfg = {}

    # Optuna 전체 trial에서 base_df는 한 번만 생성해서 재사용한다.
    etf_code = fixed_cfg.get("etf_code", ETF_CODE)
    start_date = fixed_cfg.get("start_date", START_DATE)
    end_date = fixed_cfg.get("end_date", END_DATE)
    external_tickers = fixed_cfg.get("external_tickers", EXTERNAL_TICKERS)
    external_feature_types = fixed_cfg.get("external_feature_types", EXTERNAL_FEATURE_TYPES)

    if verbose:
        print("=" * 80)
        print("Optuna 공통 base_df 생성")
        print("=" * 80)

    base_df, base_feature_cols, close_col = make_base_feature_dataset(
        etf_code=etf_code,
        external_tickers=external_tickers,
        external_feature_types=external_feature_types,
        start_date=start_date,
        end_date=end_date,
    )

    trial_rows = []

    def objective(trial):
        cfg = build_optuna_config(trial, fixed_cfg=fixed_cfg)

        if verbose:
            print("\n" + "=" * 100)
            print(f"OPTUNA TRIAL {trial.number + 1}/{n_trials}")
            print(cfg)
            print("=" * 100)

        try:
            result = run_rolling_validation(
                etf_code=cfg.get("etf_code", ETF_CODE),
                n_days=cfg.get("n_days", N_DAYS),
                threshold=cfg.get("threshold", THRESHOLD),
                valid_months=cfg.get("valid_months", VALID_MONTHS),
                vif_threshold=cfg.get("vif_threshold", VIF_THRESHOLD),
                lag_search_years=cfg.get("lag_search_years", LAG_SEARCH_YEARS),
                lag_days=cfg.get("lag_days", LAG_DAYS),
                random_state=cfg.get("random_state", RANDOM_STATE),
                n_rf_runs=cfg.get("n_rf_runs", N_RF_RUNS),
                n_repeats=cfg.get("n_repeats", N_REPEATS),
                top_n=cfg.get("top_n", TOP_N),
                pred_threshold=cfg.get("pred_threshold", PRED_THRESHOLD),
                model_name=cfg.get("model_name", "random_forest"),
                model_params=cfg.get("model_params", {}),
                n_folds=cfg.get("n_folds", 6),
                step_months=cfg.get("step_months", 1),
                start_date=cfg.get("start_date", START_DATE),
                end_date=cfg.get("end_date", END_DATE),
                external_tickers=external_tickers,
                external_feature_types=external_feature_types,
                base_df=base_df,
                base_feature_cols=base_feature_cols,
                close_col=close_col,
                save_to_excel=save_to_excel,
                experiment_dir=experiment_dir,
                skip_existing=skip_existing,
                run_name=f"optuna_trial_{trial.number:04d}",
                verbose=verbose,
                fold_verbose=fold_verbose,
            )

            score = compute_optuna_score(
                result=result,
                n_folds=cfg.get("n_folds", 6),
                objective_metric=objective_metric,
                min_success_ratio=min_success_ratio,
                min_pred_1_count_mean=min_pred_1_count_mean,
            )

            row = {
                "trial_number": trial.number,
                "score": score,
                **cfg,
                "n_folds_success": get_n_folds_success_from_result(result),
                objective_metric: get_metric_from_result(result, objective_metric),
                "rolling_pred_1_count_mean": get_metric_from_result(result, "rolling_pred_1_count_mean"),
                "skipped_existing": result.get("skipped_existing", False),
            }
            trial_rows.append(row)

            trial.set_user_attr("score", score)
            trial.set_user_attr("n_folds_success", row["n_folds_success"])
            trial.set_user_attr(objective_metric, row[objective_metric])
            trial.set_user_attr("rolling_pred_1_count_mean", row["rolling_pred_1_count_mean"])
            trial.set_user_attr("cfg", cfg)

            return score

        except Exception as e:
            if verbose:
                print(f"[OPTUNA TRIAL FAIL] trial={trial.number}, error={e}")

            trial_rows.append({
                "trial_number": trial.number,
                "score": 0.0,
                **cfg,
                "error": str(e),
            })
            return 0.0

    study = optuna.create_study(direction="maximize")
    study.optimize(objective, n_trials=n_trials)

    trials_df = pd.DataFrame(trial_rows)
    if len(trials_df) > 0 and "score" in trials_df.columns:
        trials_df = trials_df.sort_values("score", ascending=False).reset_index(drop=True)

    if verbose:
        print("\n" + "=" * 80)
        print("OPTUNA BEST TRIAL")
        print("=" * 80)
        print("best_value:", study.best_value)
        print("best_params:", study.best_params)
        display(trials_df.head(20))

    return {
        "study": study,
        "trials_df": trials_df,
        "base_df": base_df,
        "base_feature_cols": base_feature_cols,
        "close_col": close_col,
    }

In [8]:
fixed_cfg = {
    "etf_code": "SMH",  
    # 예측 대상 ETF 코드
    # 예: SMH, QQQ, SPY, SOXX 등

    "valid_months": 3,  
    # fold 1개당 검증 구간 길이
    # 1이면 한 번 검증할 때 1개월 데이터를 valid로 사용

    "vif_threshold": 10,  
    # VIF 기반 다중공선성 제거 기준
    # 값이 낮을수록 비슷한 변수들을 더 강하게 제거
    # 보통 5~10 사용, 10은 무난한 기준

    "lag_search_years": 1,  
    # 변수별 최적 lag를 찾을 때 사용할 과거 기간
    # 1이면 각 fold 기준 최근 1년 데이터로 최적 lag 탐색

    "lag_days": [1, 3, 5, 10, 20, 40, 60, 120],  
    # 테스트할 lag 후보
    # 예: lag 5는 해당 변수가 5거래일 전에 움직인 값으로 타겟과 비교

    "random_state": 42,  
    # 랜덤 고정값
    # 같은 조건에서 결과가 최대한 동일하게 나오도록 고정

    "n_rf_runs": 3,  
    # feature importance 계산 시 RandomForest를 몇 번 반복할지
    # 여러 번 돌려 평균내면 변수 중요도가 조금 더 안정적임

    "n_repeats": 10,  
    # permutation importance 반복 횟수
    # 값이 클수록 중요도는 안정적이지만 실행 시간이 길어짐

    "n_folds": 10,  
    # rolling validation을 몇 번 수행할지
    # 10이면 최근 10개 fold를 검증

    "step_months": 1,  
    # fold를 몇 개월씩 이동할지
    # 1이면 valid 구간을 한 달씩 밀면서 검증
}
optuna_result = run_optuna_experiments(
    n_trials=30,
    fixed_cfg=fixed_cfg,
    objective_metric="rolling_precision_mean",
    min_success_ratio=0.8,
    min_pred_1_count_mean=1.0,
    save_to_excel=True,
    experiment_dir=EXCEL_EXPERIMENT_DIR,
    skip_existing=True,
    verbose=True,
    fold_verbose=False,
)

optuna_trials_df = optuna_result["trials_df"]

================================================================================
Optuna 공통 base_df 생성
================================================================================
Loading external ticker: QQQ / QQQ
Loading external ticker: SPY / SPY
Loading external ticker: SOXX / SOXX
Loading external ticker: NVDA / NVDA
Loading external ticker: TSM / TSM
Loading external ticker: VIX / ^VIX
Loading external ticker: TNX / ^TNX
Loading external ticker: USDKRW / KRW=X
Loading external ticker: DXY / DX-Y.NYB
Loading external ticker: GOLD / GC=F
Loading external ticker: OIL / CL=F

[I 2026-05-23 19:08:03,008] A new study created in memory with name: no-name-d8c09092-3692-45d3-ae4c-c5b7586fe239

====================================================================================================
OPTUNA TRIAL 1/30
{'etf_code': 'SMH', 'valid_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'n_folds': 10, 'step_months': 1, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 10, 'threshold': 0.02, 'top_n': 50, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 100, 'learning_rate': 0.05, 'max_depth': 2}, 'search_method': 'optuna', 'optuna_trial_number': 0}
====================================================================================================
================================================================================
Rolling 기준일
================================================================================
fold 01: 2026-05-22
fold 02: 2026-04-22
fold 03: 2026-03-20
fold 04: 2026-02-20
fold 05: 2026-01-22
fold 06: 2025-12-22
fold 07: 2025-11-21
fold 08: 2025-10-22
fold 09: 2025-09-22
fold 10: 2025-08-22

####################################################################################################
ROLLING FOLD 1/10 | as_of_date=2026-05-22
####################################################################################################
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.145

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1444

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.145
fold 01 완료 | precision=0.0 | pred_1_precision=nan | pred_1_count=0 | eval_count=54

####################################################################################################
ROLLING FOLD 2/10 | as_of_date=2026-04-22
####################################################################################################
VIF 계산 대상 row 수: 1463
VIF 계산 대상 feature 수: 32

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1438

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1458

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.144
fold 02 완료 | precision=0.25 | pred_1_precision=0.25 | pred_1_count=4 | eval_count=53

####################################################################################################
ROLLING FOLD 3/10 | as_of_date=2026-03-20
####################################################################################################
VIF 계산 대상 row 수: 1443
VIF 계산 대상 feature 수: 32

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1444

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1434

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1444
fold 03 완료 | precision=0.0 | pred_1_precision=nan | pred_1_count=0 | eval_count=51

####################################################################################################
ROLLING FOLD 4/10 | as_of_date=2026-02-20
####################################################################################################
VIF 계산 대상 row 수: 1422
VIF 계산 대상 feature 수: 32

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1466

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.146

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1472
fold 04 완료 | precision=0.0 | pred_1_precision=0.0 | pred_1_count=3 | eval_count=52

####################################################################################################
ROLLING FOLD 5/10 | as_of_date=2026-01-22
####################################################################################################
VIF 계산 대상 row 수: 1401
VIF 계산 대상 feature 수: 32

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.147

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1466

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.147
fold 05 완료 | precision=0.5 | pred_1_precision=0.5 | pred_1_count=6 | eval_count=53

####################################################################################################
ROLLING FOLD 6/10 | as_of_date=2025-12-22
####################################################################################################
VIF 계산 대상 row 수: 1379
VIF 계산 대상 feature 수: 32

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1505

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1506

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.151
fold 06 완료 | precision=0.45454545454545453 | pred_1_precision=0.45454545454545453 | pred_1_count=11 | eval_count=55

####################################################################################################
ROLLING FOLD 7/10 | as_of_date=2025-11-21
####################################################################################################
VIF 계산 대상 row 수: 1358
VIF 계산 대상 feature 수: 32

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1494

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1482

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1483
fold 07 완료 | precision=0.14285714285714285 | pred_1_precision=0.14285714285714285 | pred_1_count=7 | eval_count=56

####################################################################################################
ROLLING FOLD 8/10 | as_of_date=2025-10-22
####################################################################################################
VIF 계산 대상 row 수: 1336
VIF 계산 대상 feature 수: 32

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1487

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1494

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1498
fold 08 완료 | precision=0.5 | pred_1_precision=0.5 | pred_1_count=4 | eval_count=56

####################################################################################################
ROLLING FOLD 9/10 | as_of_date=2025-09-22
####################################################################################################
VIF 계산 대상 row 수: 1316
VIF 계산 대상 feature 수: 32

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 6
최종 feature 수: 26
===================================

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1484

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.148

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1479
fold 09 완료 | precision=0.0 | pred_1_precision=0.0 | pred_1_count=2 | eval_count=54

####################################################################################################
ROLLING FOLD 10/10 | as_of_date=2025-08-22
####################################################################################################
VIF 계산 대상 row 수: 1296
VIF 계산 대상 feature 수: 32

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 6
최종 feature 수: 26
===================================

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1523

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1512

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1515
fold 10 완료 | precision=0.0 | pred_1_precision=0.0 | pred_1_count=2 | eval_count=54

================================================================================
Rolling 검증 요약
================================================================================
성공 fold 수: 10
실패 fold 수: 0
rolling_precision_mean: 0.18474025974025973
rolling_pred_1_precision_zero_fill_mean: 0.18474025974025973
rolling_pred_1_count_mean: 3.9

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,logloss,tn,fp,fn,tp,fold,as_of_date,valid_start_date,valid_end_date,error
0,SMH,10,0.02,1,50,27,gradient_boosting,"{'n_estimators': 100, 'learning_rate': 0.05, '...",54,0,...,0.741547,20,0,34,0,1,2026-05-22,2026-02-22,2026-05-22,None
1,SMH,10,0.02,1,50,27,gradient_boosting,"{'n_estimators': 100, 'learning_rate': 0.05, '...",53,4,...,0.684085,31,3,18,1,2,2026-04-22,2026-01-22,2026-04-22,None
2,SMH,10,0.02,1,50,27,gradient_boosting,"{'n_estimators': 100, 'learning_rate': 0.05, '...",51,0,...,0.704068,29,0,22,0,3,2026-03-20,2025-12-20,2026-03-20,None
3,SMH,10,0.02,1,50,27,gradient_boosting,"{'n_estimators': 100, 'learning_rate': 0.05, '...",52,3,...,0.712177,19,3,30,0,4,2026-02-20,2025-11-20,2026-02-20,None
4,SMH,10,0.02,1,50,27,gradient_boosting,"{'n_estimators': 100, 'learning_rate': 0.05, '...",53,6,...,0.724722,22,3,25,3,5,2026-01-22,2025-10-22,2026-01-22,None
5,SMH,10,0.02,1,50,27,gradient_boosting,"{'n_estimators': 100, 'learning_rate': 0.05, '...",55,11,...,0.740325,22,6,22,5,6,2025-12-22,2025-09-22,2025-12-22,None
6,SMH,10,0.02,1,50,27,gradient_boosting,"{'n_estimators': 100, 'learning_rate': 0.05, '...",56,7,...,0.822918,16,6,33,1,7,2025-11-21,2025-08-21,2025-11-21,None
7,SMH,10,0.02,1,50,27,gradient_boosting,"{'n_estimators': 100, 'learning_rate': 0.05, '...",56,4,...,0.723811,24,2,28,2,8,2025-10-22,2025-07-22,2025-10-22,None
8,SMH,10,0.02,1,50,26,gradient_boosting,"{'n_estimators': 100, 'learning_rate': 0.05, '...",54,2,...,0.777236,27,2,25,0,9,2025-09-22,2025-06-22,2025-09-22,None
9,SMH,10,0.02,1,50,26,gradient_boosting,"{'n_estimators': 100, 'learning_rate': 0.05, '...",54,2,...,0.798978,15,2,37,0,10,2025-08-22,2025-05-22,2025-08-22,None

,feature,selected_count,avg_importance_score,avg_importance_mean,avg_importance_std,avg_selected_lag,first_base_feature
0,TSM_ret_20d_lag40,10,0.051973,0.053624,0.001651,40.0,TSM_ret_20d
1,TNX_level_lag120,8,0.086924,0.089328,0.002404,120.0,TNX_level
2,OIL_ret_20d_lag40,8,0.070253,0.072742,0.002489,40.0,OIL_ret_20d
3,USDKRW_ret_20d_lag120,8,0.058933,0.060822,0.001888,120.0,USDKRW_ret_20d
4,VIX_level_lag40,8,0.056319,0.058300,0.001981,40.0,VIX_level
5,DXY_ret_20d_lag120,7,0.056765,0.058590,0.001825,120.0,DXY_ret_20d
6,VIX_chg_20d_lag120,7,0.046516,0.047975,0.001459,120.0,VIX_chg_20d
7,USDKRW_ret_5d_lag120,7,0.038063,0.039531,0.001468,120.0,USDKRW_ret_5d
8,NVDA_ret_5d_lag60,7,0.034626,0.036212,0.001586,60.0,NVDA_ret_5d
9,SPY_ret_5d_lag60,7,0.029618,0.030801,0.001183,60.0,SPY_ret_5d
10,TNX_diff_5d_lag60,7,0.028935,0.030050,0.001115,60.0,TNX_diff_5d
11,SOXX_ret_5d_lag60,7,0.028086,0.029251,0.001165,60.0,SOXX_ret_5d
12,SMH_ma5_ratio_lag60,7,0.023068,0.024002,0.000934,60.0,SMH_ma5_ratio
13,SMH_ma60_ratio_lag40,6,0.063459,0.065483,0.002024,40.0,SMH_ma60_ratio
14,VIX_chg_5d_lag60,6,0.048658,0.050768,0.002110,60.0,VIX_chg_5d
15,SPY_ret_20d_lag120,6,0.042395,0.043990,0.001595,120.0,SPY_ret_20d
16,GOLD_ret_20d_lag120,6,0.041909,0.043608,0.001699,120.0,GOLD_ret_20d
17,SMH_ret_1d_lag60,6,0.019339,0.020084,0.000745,60.0,SMH_ret_1d
18,DXY_ret_5d_lag40,5,0.092623,0.096297,0.003673,40.0,DXY_ret_5d
19,NVDA_ret_20d_lag60,5,0.085576,0.089034,0.003458,60.0,NVDA_ret_20d
20,SMH_vol_20d_lag40,5,0.076007,0.078174,0.002167,40.0,SMH_vol_20d
21,TNX_diff_20d_lag120,5,0.057129,0.059586,0.002457,120.0,TNX_diff_20d
22,SMH_ma20_ratio_lag40,5,0.055288,0.057775,0.002487,40.0,SMH_ma20_ratio
23,TSM_ret_5d_lag40,5,0.045927,0.047900,0.001973,40.0,TSM_ret_5d
24,SMH_ma20_ratio_lag60,5,0.041232,0.042728,0.001497,60.0,SMH_ma20_ratio
25,SMH_volume_ratio_20d_lag5,5,0.038740,0.040277,0.001537,5.0,SMH_volume_ratio_20d
26,OIL_ret_5d_lag10,5,0.027414,0.028499,0.001085,10.0,OIL_ret_5d
27,SMH_vol_20d_lag120,4,0.088208,0.091193,0.002986,120.0,SMH_vol_20d
28,OIL_ret_5d_lag3,4,0.050035,0.052162,0.002127,3.0,OIL_ret_5d
29,SMH_volume_ratio_20d_lag1,4,0.042545,0.044351,0.001806,1.0,SMH_volume_ratio_20d

[I 2026-05-23 19:10:51,991] Trial 0 finished with value: 0.18474025974025973 and parameters: {'n_days': 10, 'threshold': 0.02, 'top_n': 50, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'gb_n_estimators': 100, 'gb_learning_rate': 0.05, 'gb_max_depth': 2}. Best is trial 0 with value: 0.18474025974025973.

Excel 저장 완료
전체 summary 파일: experiments_excel/experiment_summary2.xlsx

====================================================================================================
OPTUNA TRIAL 2/30
{'etf_code': 'SMH', 'valid_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'n_folds': 10, 'step_months': 1, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 5, 'threshold': 0.005, 'top_n': 50, 'pred_threshold': 0.35, 'model_name': 'logistic', 'model_params': {'C': 1.0, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna', 'optuna_trial_number': 1}
====================================================================================================
================================================================================
Rolling 기준일
================================================================================
fold 01: 2026-05-22
fold 02: 2026-04-22
fold 03: 2026-03-20
fold 04: 2026-02-20
fold 05: 2026-01-22
fold 06: 2025-12-22
fold 07: 2025-11-21
fold 08: 2025-10-22
fold 09: 2025-09-22
fold 10: 2025-08-22

####################################################################################################
ROLLING FOLD 1/10 | as_of_date=2026-05-22
####################################################################################################
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1663

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.165

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1668
fold 01 완료 | precision=0.5862068965517241 | pred_1_precision=0.5862068965517241 | pred_1_count=58 | eval_count=59

####################################################################################################
ROLLING FOLD 2/10 | as_of_date=2026-04-22
####################################################################################################
VIF 계산 대상 row 수: 1463
VIF 계산 대상 feature 수: 32

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1679

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1667

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1671
fold 02 완료 | precision=0.54 | pred_1_precision=0.54 | pred_1_count=50 | eval_count=58

####################################################################################################
ROLLING FOLD 3/10 | as_of_date=2026-03-20
####################################################################################################
VIF 계산 대상 row 수: 1443
VIF 계산 대상 feature 수: 32

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1688

[W 2026-05-23 19:11:40,005] Trial 1 failed with parameters: {'n_days': 5, 'threshold': 0.005, 'top_n': 50, 'pred_threshold': 0.35, 'model_name': 'logistic', 'logistic_C': 1.0} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/Users/jongheelee/Desktop/JH/01. Working/1. ETF_Prediction/etf_predict/.venv/lib/python3.11/site-packages/optuna/study/_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/var/folders/8q/_1f4z4tj6zqgt3d_xgf1mz280000gn/T/ipykernel_77754/2807428258.py", line 236, in objective
    result = run_rolling_validation(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/folders/8q/_1f4z4tj6zqgt3d_xgf1mz280000gn/T/ipykernel_77754/1527653700.py", line 955, in run_rolling_validation
    feature_result = build_top_feature_df(
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/var/folders/8q/_1f4z4tj6zqgt3d_xgf1mz280000gn/T/ipykernel_77754/1527653700.py", line 251, in build_top_feature_df
    importance_df, raw_importance_df, baseline_df = run_rf_permutation_importance_in_sample(
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/folders/8q/_1f4z4tj6zqgt3d_xgf1mz280000gn/T/ipykernel_77754/703042482.py", line 657, in run_rf_permutation_importance_in_sample
    perm = permutation_importance(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jongheelee/Desktop/JH/01. Working/1. ETF_Prediction/etf_predict/.venv/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jongheelee/Desktop/JH/01. Working/1. ETF_Prediction/etf_predict/.venv/lib/python3.11/site-packages/sklearn/inspection/_permutation_importance.py", line 288, in permutation_importance
    scores = Parallel(n_jobs=n_jobs)(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jongheelee/Desktop/JH/01. Working/1. ETF_Prediction/etf_predict/.venv/lib/python3.11/site-packages/sklearn/utils/parallel.py", line 91, in __call__
    return super().__call__(iterable_with_config_and_warning_filters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jongheelee/Desktop/JH/01. Working/1. ETF_Prediction/etf_predict/.venv/lib/python3.11/site-packages/joblib/parallel.py", line 2072, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/Users/jongheelee/Desktop/JH/01. Working/1. ETF_Prediction/etf_predict/.venv/lib/python3.11/site-packages/joblib/parallel.py", line 1682, in _get_outputs
    yield from self._retrieve()
  File "/Users/jongheelee/Desktop/JH/01. Working/1. ETF_Prediction/etf_predict/.venv/lib/python3.11/site-packages/joblib/parallel.py", line 1800, in _retrieve
    time.sleep(0.01)
KeyboardInterrupt
[W 2026-05-23 19:11:40,009] Trial 1 failed with value None.

KeyboardInterrupt:

## Holdout 방식 Optuna 추가

마지막 `test_months`개월을 test로 분리하고, 그 이전 train 데이터로 변수 선택/학습 후 test를 예측합니다. 선택된 변수 리스트도 summary에 저장됩니다.

In [9]:

# =========================================================
# Holdout 방식 Optuna 실험
# - fold/rolling 검증 제거
# - 마지막 test_months 개월을 test로 분리
# - test 시작 전까지의 train 데이터로 feature selection 1회
# - 같은 selected feature로 train 학습 후 test 예측
# - 선택된 변수 리스트까지 experiment_summary_holdout.xlsx에 저장
# =========================================================

HOLDOUT_SUMMARY_FILE_NAME = "experiment_summary_holdout.xlsx"

HOLDOUT_EXPERIMENT_KEY_COLS = [
    "etf_code",
    "n_days",
    "threshold",
    "test_months",
    "vif_threshold",
    "lag_search_years",
    "lag_days",
    "random_state",
    "n_rf_runs",
    "n_repeats",
    "top_n",
    "pred_threshold",
    "model_name",
    "model_params",
    "start_date",
    "end_date",
]

HOLDOUT_SUMMARY_COLUMNS = [
    "experiment_key",
    "created_dt",
    "run_id",
    "etf_code",
    "test_precision",
    "n_days",
    "threshold",
    "test_months",
    "vif_threshold",
    "lag_search_years",
    "lag_days",
    "top_n",
    "selected_feature_count",
    "selected_feature_list",
    "selected_feature_top10",
    "pred_threshold",
    "model_name",
    "model_params",
    "test_accuracy",
    "test_recall",
    "test_f1",
    "test_auc",
    "test_logloss",
    "test_eval_count",
    "test_pred_1_count",
    "test_actual_1_count",
    "test_pred_1_actual_1_count",
    "test_pred_1_precision",
    "test_tn",
    "test_fp",
    "test_fn",
    "test_tp",
    "error_count",
]


def make_holdout_experiment_key(config):
    """holdout 방식 동일 실험 여부 판단 key."""
    key_dict = {
        col: normalize_experiment_value(config.get(col))
        for col in HOLDOUT_EXPERIMENT_KEY_COLS
    }
    key_json = json.dumps(key_dict, ensure_ascii=False, sort_keys=True, default=str)
    return hashlib.md5(key_json.encode("utf-8")).hexdigest()


def load_holdout_summary(experiment_dir=EXCEL_EXPERIMENT_DIR):
    """holdout summary Excel을 읽는다. 없으면 빈 DataFrame 반환."""
    path = Path(experiment_dir) / HOLDOUT_SUMMARY_FILE_NAME
    if not path.exists():
        return pd.DataFrame()
    try:
        return pd.read_excel(path, sheet_name="summary")
    except Exception:
        return pd.DataFrame()


def find_existing_holdout_experiment(config, experiment_dir=EXCEL_EXPERIMENT_DIR):
    """같은 holdout 실험 조건이 이미 저장되어 있는지 찾는다."""
    summary_df = load_holdout_summary(experiment_dir)
    if summary_df.empty:
        return None

    target_key = make_holdout_experiment_key(config)
    if "experiment_key" in summary_df.columns:
        matched = summary_df[summary_df["experiment_key"].astype(str) == str(target_key)]
        if len(matched) > 0:
            return matched.iloc[0].to_dict()
    return None


def order_holdout_summary_df(summary_df, summary_columns=HOLDOUT_SUMMARY_COLUMNS):
    """holdout summary 컬럼 순서를 고정한다."""
    if summary_df is None or len(summary_df.columns) == 0:
        return pd.DataFrame(columns=summary_columns)

    summary_df = summary_df.copy()
    for col in summary_columns:
        if col not in summary_df.columns:
            summary_df[col] = np.nan

    extra_cols = [c for c in summary_df.columns if c not in summary_columns]
    return summary_df[summary_columns + extra_cols]


def make_selected_feature_summary_values(top_feature_df, max_chars=30000):
    """top_feature_df에서 Excel summary용 선택 변수 요약값을 만든다."""
    if top_feature_df is None or len(top_feature_df) == 0:
        return {
            "selected_feature_count": 0,
            "selected_feature_list": "",
            "selected_feature_top10": "",
        }

    df = top_feature_df.copy()
    if "feature" not in df.columns:
        return {
            "selected_feature_count": 0,
            "selected_feature_list": "",
            "selected_feature_top10": "",
        }

    feature_list = df["feature"].astype(str).tolist()
    selected_feature_list = " | ".join(feature_list)

    top10_items = []
    for _, row in df.head(10).iterrows():
        feature = str(row.get("feature", ""))
        score = row.get("importance_score", np.nan)
        if pd.notna(score):
            top10_items.append(f"{feature}({float(score):.6f})")
        else:
            top10_items.append(feature)

    selected_feature_top10 = " | ".join(top10_items)

    # Excel 셀 문자 수 제한 방어
    if len(selected_feature_list) > max_chars:
        selected_feature_list = selected_feature_list[:max_chars] + " ...[truncated]"

    return {
        "selected_feature_count": len(feature_list),
        "selected_feature_list": selected_feature_list,
        "selected_feature_top10": selected_feature_top10,
    }


def build_top_feature_df_from_base(
    base_df,
    base_feature_cols,
    close_col,
    etf_code,
    n_days,
    threshold,
    test_months=3,
    lag_search_years=1,
    random_state=42,
    n_rf_runs=3,
    n_repeats=10,
    top_n=30,
    start_date=START_DATE,
    end_date=END_DATE,
    vif_threshold=VIF_THRESHOLD,
    lag_days=LAG_DAYS,
    verbose=True,
):
    """
    holdout 방식 feature selection.

    핵심 구조:
    - base_df의 마지막 test_months 개월은 test로 분리
    - test 시작일 전까지의 train 데이터만 사용해 VIF / target / lag / importance / top_n 선택
    - 선택된 변수와 lag는 이후 test 검증에서 고정 사용
    """
    base_df = base_df.copy().sort_values("Date").reset_index(drop=True)

    max_date = base_df["Date"].max()
    test_start_date = max_date - pd.DateOffset(months=test_months)

    train_base_df = base_df[base_df["Date"] < test_start_date].copy()
    valid_base_df = base_df[base_df["Date"] >= test_start_date].copy()

    if verbose:
        print("=" * 60)
        print("Holdout feature selection")
        print("train 기간:", train_base_df["Date"].min(), "~", train_base_df["Date"].max())
        print("test  기간:", valid_base_df["Date"].min(), "~", valid_base_df["Date"].max())
        print("train_base_df shape:", train_base_df.shape)
        print("test_base_df shape:", valid_base_df.shape)
        print("close_col:", close_col)

    # 1. VIF는 train 데이터에서만 수행
    vif_feature_cols, removed_vif_df, final_vif_df = reduce_features_by_vif(
        df=train_base_df,
        feature_cols=base_feature_cols,
        vif_threshold=vif_threshold,
        date_col="Date",
        verbose=verbose,
    )

    keep_cols = ["Date", close_col] + vif_feature_cols
    vif_filtered_df = train_base_df[keep_cols].copy()

    # 2. target도 train 데이터에서만 생성
    target_df, target_col = add_target_column(
        df=vif_filtered_df,
        close_col=close_col,
        n_days=n_days,
        threshold=threshold,
    )
    target_df = target_df.dropna(subset=[target_col]).copy()
    target_df[target_col] = target_df[target_col].astype(int)

    if target_df[target_col].nunique() < 2:
        raise ValueError(f"train target class가 1개뿐입니다. target 분포: {target_df[target_col].value_counts().to_dict()}")

    if verbose:
        print("target_col:", target_col)
        print("target_df shape:", target_df.shape)
        print("target 분포:")
        print(target_df[target_col].value_counts())

    # 3. lag 탐색도 train 데이터의 최근 lag_search_years 구간에서만 수행
    max_train_target_date = target_df["Date"].max()
    lag_search_start_date = max_train_target_date - pd.DateOffset(years=lag_search_years)
    target_df_for_lag_search = target_df[target_df["Date"] >= lag_search_start_date].copy()

    exclude_cols_for_lag = [
        "Date",
        close_col,
        f"future_ret_{n_days}d",
        target_col,
    ]
    lag_search_feature_cols = [
        col for col in target_df.columns
        if col not in exclude_cols_for_lag
    ]

    lag_result_df, best_lag_df = find_best_lag_by_feature(
        df=target_df_for_lag_search,
        feature_cols=lag_search_feature_cols,
        target_col=target_col,
        lag_days=lag_days,
        date_col="Date",
    )

    # 4. train 데이터에 best lag 적용
    lagged_df, lagged_feature_cols = make_lagged_dataset_by_best_lag(
        df=target_df,
        best_lag_df=best_lag_df,
        target_col=target_col,
        close_col=close_col,
        n_days=n_days,
        date_col="Date",
    )

    if lagged_df[target_col].nunique() < 2:
        raise ValueError(f"lagged train target class가 1개뿐입니다. target 분포: {lagged_df[target_col].value_counts().to_dict()}")

    if verbose:
        print("lagged_df shape:", lagged_df.shape)
        print("lagged feature count:", len(lagged_feature_cols))

    # 5. train 데이터에서 RF permutation importance로 top feature 선택
    importance_df, raw_importance_df, baseline_df = run_rf_permutation_importance_in_sample(
        lagged_df=lagged_df,
        feature_cols=lagged_feature_cols,
        target_col=target_col,
        date_col="Date",
        close_col=close_col,
        n_rf_runs=n_rf_runs,
        n_repeats=n_repeats,
        random_state=random_state,
    )

    importance_view_df = importance_df.copy()
    importance_view_df[["base_feature", "selected_lag"]] = importance_view_df["feature"].apply(
        lambda x: pd.Series(split_lagged_feature_name(x))
    )

    importance_with_lag_df = importance_view_df.merge(
        best_lag_df.rename(columns={
            "feature": "base_feature",
            "lag": "best_lag",
            "corr": "lag_corr",
            "abs_corr": "lag_abs_corr",
            "n_rows": "lag_n_rows",
        }),
        on="base_feature",
        how="left",
    )

    importance_with_lag_df = importance_with_lag_df.sort_values(
        "importance_score",
        ascending=False,
    ).reset_index(drop=True)

    top_feature_df = importance_with_lag_df.head(top_n).copy()
    top_feature_cols = top_feature_df["feature"].tolist()

    if verbose:
        print("TOP feature count:", len(top_feature_cols))
        print(top_feature_cols)
        display(top_feature_df)

    return {
        "etf_code": etf_code,
        "n_days": n_days,
        "threshold": threshold,
        "test_months": test_months,
        "lag_search_years": lag_search_years,
        "random_state": random_state,
        "n_rf_runs": n_rf_runs,
        "n_repeats": n_repeats,
        "top_n": top_n,
        "start_date": start_date,
        "end_date": end_date,
        "vif_threshold": vif_threshold,
        "lag_days": lag_days,
        "base_df": base_df,
        "base_feature_cols": base_feature_cols,
        "train_base_df": train_base_df,
        "valid_base_df": valid_base_df,  # validate_top_feature_df 호환을 위해 이름 유지. 실제 의미는 test_base_df.
        "test_base_df": valid_base_df,
        "test_start_date": test_start_date,
        "close_col": close_col,
        "vif_feature_cols": vif_feature_cols,
        "removed_vif_df": removed_vif_df,
        "final_vif_df": final_vif_df,
        "vif_filtered_df": vif_filtered_df,
        "target_df": target_df,
        "target_col": target_col,
        "lag_result_df": lag_result_df,
        "best_lag_df": best_lag_df,
        "lagged_df": lagged_df,
        "lagged_feature_cols": lagged_feature_cols,
        "importance_df": importance_df,
        "raw_importance_df": raw_importance_df,
        "baseline_df": baseline_df,
        "importance_with_lag_df": importance_with_lag_df,
        "top_feature_df": top_feature_df,
        "top_feature_cols": top_feature_cols,
    }


def summarize_holdout_metrics(metric_df):
    """validate_top_feature_df의 metric_df를 test_* 컬럼으로 변환한다."""
    if metric_df is None or len(metric_df) == 0:
        return {
            "test_accuracy": np.nan,
            "test_precision": np.nan,
            "test_recall": np.nan,
            "test_f1": np.nan,
            "test_auc": np.nan,
            "test_logloss": np.nan,
            "test_eval_count": 0,
            "test_pred_1_count": 0,
            "test_actual_1_count": np.nan,
            "test_pred_1_actual_1_count": np.nan,
            "test_pred_1_precision": np.nan,
            "test_tn": np.nan,
            "test_fp": np.nan,
            "test_fn": np.nan,
            "test_tp": np.nan,
        }

    row = metric_df.iloc[0].to_dict()
    return {
        "test_accuracy": row.get("accuracy", np.nan),
        "test_precision": row.get("precision", np.nan),
        "test_recall": row.get("recall", np.nan),
        "test_f1": row.get("f1", np.nan),
        "test_auc": row.get("auc", np.nan),
        "test_logloss": row.get("logloss", np.nan),
        "test_eval_count": row.get("eval_count", 0),
        "test_pred_1_count": row.get("pred_1_count", 0),
        "test_actual_1_count": row.get("actual_1_count", np.nan),
        "test_pred_1_actual_1_count": row.get("pred_1_actual_1_count", np.nan),
        "test_pred_1_precision": row.get("pred_1_precision", np.nan),
        "test_tn": row.get("tn", np.nan),
        "test_fp": row.get("fp", np.nan),
        "test_fn": row.get("fn", np.nan),
        "test_tp": row.get("tp", np.nan),
    }


def save_holdout_result_to_excel(result, config, experiment_dir=EXCEL_EXPERIMENT_DIR, run_name=None):
    """holdout 검증 결과를 experiment_summary_holdout.xlsx 하나에 누적 저장한다."""
    experiment_dir = Path(experiment_dir)
    experiment_dir.mkdir(parents=True, exist_ok=True)

    run_id = make_run_id(
        etf_code=config.get("etf_code"),
        model_name=config.get("model_name"),
        n_days=config.get("n_days"),
        threshold=config.get("threshold"),
        top_n=config.get("top_n"),
        run_name=run_name,
    )

    experiment_key = make_holdout_experiment_key(config)
    errors = result.get("errors", [])

    metric_df = result.get("metric_df", pd.DataFrame())
    test_summary = summarize_holdout_metrics(metric_df)

    feature_result = result.get("feature_result", {})
    selected_summary = make_selected_feature_summary_values(
        feature_result.get("top_feature_df", pd.DataFrame())
    )

    summary_row = {
        "experiment_key": experiment_key,
        "created_dt": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "run_id": run_id,
        **config,
        **selected_summary,
        **test_summary,
        "error_count": len(errors),
    }

    summary_df = order_holdout_summary_df(make_one_row_df(summary_row))
    master_summary_path = experiment_dir / HOLDOUT_SUMMARY_FILE_NAME

    if master_summary_path.exists():
        try:
            old_summary_df = pd.read_excel(master_summary_path, sheet_name="summary")
            old_summary_df = order_holdout_summary_df(old_summary_df)
            master_summary_df = pd.concat([old_summary_df, summary_df], ignore_index=True)
        except Exception:
            master_summary_df = summary_df.copy()
    else:
        master_summary_df = summary_df.copy()

    if "experiment_key" in master_summary_df.columns:
        master_summary_df = master_summary_df.drop_duplicates(subset=["experiment_key"], keep="last")

    master_summary_df = order_holdout_summary_df(master_summary_df)

    sort_cols = [c for c in ["test_precision", "test_f1", "test_recall", "test_auc"] if c in master_summary_df.columns]
    if len(sort_cols) > 0:
        master_summary_df = master_summary_df.sort_values(sort_cols, ascending=False).reset_index(drop=True)

    write_excel_book(master_summary_path, {"summary": master_summary_df})

    return {
        "run_id": run_id,
        "experiment_key": experiment_key,
        "master_summary_path": str(master_summary_path),
    }


def run_holdout_validation(
    etf_code=ETF_CODE,
    n_days=N_DAYS,
    threshold=THRESHOLD,
    test_months=3,
    vif_threshold=VIF_THRESHOLD,
    lag_search_years=LAG_SEARCH_YEARS,
    lag_days=LAG_DAYS,
    random_state=RANDOM_STATE,
    n_rf_runs=N_RF_RUNS,
    n_repeats=N_REPEATS,
    top_n=TOP_N,
    pred_threshold=PRED_THRESHOLD,
    model_name="random_forest",
    model_params=None,
    start_date=START_DATE,
    end_date=END_DATE,
    external_tickers=EXTERNAL_TICKERS,
    external_feature_types=EXTERNAL_FEATURE_TYPES,
    base_df=None,
    base_feature_cols=None,
    close_col=None,
    save_to_excel=True,
    experiment_dir=EXCEL_EXPERIMENT_DIR,
    skip_existing=True,
    run_name=None,
    verbose=True,
):
    """
    holdout 검증 실행.

    구조:
    1. 전체 데이터의 마지막 test_months 개월을 test로 분리
    2. test 시작 전까지의 train 데이터로 feature selection 1회
    3. 같은 selected feature로 train 학습
    4. 마지막 test_months 개월 예측 검증
    """
    if model_params is None:
        model_params = {}

    config = {
        "etf_code": etf_code,
        "n_days": n_days,
        "threshold": threshold,
        "test_months": test_months,
        "vif_threshold": vif_threshold,
        "lag_search_years": lag_search_years,
        "lag_days": lag_days,
        "random_state": random_state,
        "n_rf_runs": n_rf_runs,
        "n_repeats": n_repeats,
        "top_n": top_n,
        "pred_threshold": pred_threshold,
        "model_name": model_name,
        "model_params": model_params,
        "start_date": start_date,
        "end_date": end_date,
    }

    if save_to_excel and skip_existing:
        existing_run = find_existing_holdout_experiment(config, experiment_dir=experiment_dir)
        if existing_run is not None:
            if verbose:
                print("\n기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.")
                print("기존 run_id:", existing_run.get("run_id"))
                print("기존 test_precision:", existing_run.get("test_precision"))
            return {
                "skipped_existing": True,
                "existing_run": existing_run,
                "metric_df": pd.DataFrame(),
                "errors": [],
                "excel_save_info": {
                    "run_id": existing_run.get("run_id"),
                    "experiment_key": existing_run.get("experiment_key"),
                    "master_summary_path": str(Path(experiment_dir) / HOLDOUT_SUMMARY_FILE_NAME),
                },
            }

    if base_df is None or base_feature_cols is None or close_col is None:
        if verbose:
            print("=" * 80)
            print("base_df 생성")
            print("=" * 80)
        base_df, base_feature_cols, close_col = make_base_feature_dataset(
            etf_code=etf_code,
            external_tickers=external_tickers,
            external_feature_types=external_feature_types,
            start_date=start_date,
            end_date=end_date,
        )

    errors = []

    try:
        feature_result = build_top_feature_df_from_base(
            base_df=base_df,
            base_feature_cols=base_feature_cols,
            close_col=close_col,
            etf_code=etf_code,
            n_days=n_days,
            threshold=threshold,
            test_months=test_months,
            lag_search_years=lag_search_years,
            random_state=random_state,
            n_rf_runs=n_rf_runs,
            n_repeats=n_repeats,
            top_n=top_n,
            start_date=start_date,
            end_date=end_date,
            vif_threshold=vif_threshold,
            lag_days=lag_days,
            verbose=verbose,
        )

        valid_result = validate_top_feature_df(
            feature_result=feature_result,
            model_name=model_name,
            model_params=model_params,
            pred_threshold=pred_threshold,
            random_state=random_state,
            n_days=n_days,
            threshold=threshold,
            verbose=verbose,
        )

        result = {
            "config": config,
            "feature_result": feature_result,
            "valid_result": valid_result,
            "metric_df": valid_result.get("metric_df", pd.DataFrame()),
            "valid_pred_df": valid_result.get("valid_pred_df", pd.DataFrame()),
            "eval_df": valid_result.get("eval_df", pd.DataFrame()),
            "errors": errors,
        }

    except Exception as e:
        errors.append({"error": str(e)})
        if verbose:
            print("[HOLDOUT FAIL]", e)
        result = {
            "config": config,
            "feature_result": {},
            "valid_result": {},
            "metric_df": pd.DataFrame(),
            "valid_pred_df": pd.DataFrame(),
            "eval_df": pd.DataFrame(),
            "errors": errors,
        }

    if save_to_excel:
        excel_save_info = save_holdout_result_to_excel(
            result=result,
            config=config,
            experiment_dir=experiment_dir,
            run_name=run_name,
        )
        result["excel_save_info"] = excel_save_info
        if verbose:
            print("\nExcel 저장 완료")
            print("holdout summary 파일:", excel_save_info["master_summary_path"])

    return result


def build_optuna_holdout_config(trial, fixed_cfg=None):
    """holdout 방식 Optuna config 생성."""
    if fixed_cfg is None:
        fixed_cfg = {}

    cfg = dict(fixed_cfg)

    cfg.setdefault("etf_code", ETF_CODE)
    cfg.setdefault("test_months", 3)
    cfg.setdefault("vif_threshold", VIF_THRESHOLD)
    cfg.setdefault("lag_search_years", LAG_SEARCH_YEARS)
    cfg.setdefault("lag_days", LAG_DAYS)
    cfg.setdefault("random_state", RANDOM_STATE)
    cfg.setdefault("n_rf_runs", N_RF_RUNS)
    cfg.setdefault("n_repeats", N_REPEATS)
    cfg.setdefault("start_date", START_DATE)
    cfg.setdefault("end_date", END_DATE)

    if "n_days" not in cfg:
        cfg["n_days"] = trial.suggest_categorical("n_days", [3, 5, 10, 20])

    if "threshold" not in cfg:
        cfg["threshold"] = trial.suggest_categorical("threshold", [0.005, 0.01, 0.015, 0.02, 0.03])

    if "top_n" not in cfg:
        cfg["top_n"] = trial.suggest_categorical("top_n", [10, 20, 30, 50])

    if "pred_threshold" not in cfg:
        cfg["pred_threshold"] = trial.suggest_float("pred_threshold", 0.25, 0.80, step=0.05)

    if "model_name" not in cfg:
        cfg["model_name"] = trial.suggest_categorical(
            "model_name",
            ["random_forest", "gradient_boosting", "hist_gradient_boosting", "logistic"],
        )

    if "model_params" not in cfg:
        cfg["model_params"] = suggest_model_params_for_optuna(trial, cfg["model_name"])

    cfg["search_method"] = "optuna_holdout"
    cfg["optuna_trial_number"] = trial.number

    return cfg


def get_holdout_metric_from_result(result, metric_name, default=np.nan):
    """holdout result 또는 skipped_existing에서 metric을 안전하게 가져온다."""
    if result is None:
        return default

    if result.get("skipped_existing", False):
        return result.get("existing_run", {}).get(metric_name, default)

    metric_df = result.get("metric_df", pd.DataFrame())
    test_summary = summarize_holdout_metrics(metric_df)
    return test_summary.get(metric_name, default)


def compute_optuna_holdout_score(
    result,
    objective_metric="test_precision",
    min_eval_count=10,
    min_pred_1_count=3,
):
    """
    holdout Optuna 점수.
    기본은 test_precision 최대화.
    단, 평가 row나 예측 1 개수가 너무 적으면 감점한다.
    """
    base_score = get_holdout_metric_from_result(result, objective_metric, default=np.nan)
    eval_count = get_holdout_metric_from_result(result, "test_eval_count", default=0)
    pred_1_count = get_holdout_metric_from_result(result, "test_pred_1_count", default=0)

    if pd.isna(base_score):
        return 0.0

    score = float(base_score)
    score *= min(1.0, float(eval_count) / max(float(min_eval_count), 1e-9))
    score *= min(1.0, float(pred_1_count) / max(float(min_pred_1_count), 1e-9))
    return float(score)


def run_optuna_holdout_experiments(
    n_trials=30,
    fixed_cfg=None,
    objective_metric="test_precision",
    min_eval_count=10,
    min_pred_1_count=3,
    save_to_excel=True,
    experiment_dir=EXCEL_EXPERIMENT_DIR,
    skip_existing=True,
    verbose=True,
):
    """
    Optuna로 holdout 실험 조건을 자동 탐색한다.

    결과는 experiment_summary_holdout.xlsx의 summary 시트에 누적된다.
    """
    if fixed_cfg is None:
        fixed_cfg = {}

    etf_code = fixed_cfg.get("etf_code", ETF_CODE)
    start_date = fixed_cfg.get("start_date", START_DATE)
    end_date = fixed_cfg.get("end_date", END_DATE)
    external_tickers = fixed_cfg.get("external_tickers", EXTERNAL_TICKERS)
    external_feature_types = fixed_cfg.get("external_feature_types", EXTERNAL_FEATURE_TYPES)

    if verbose:
        print("=" * 80)
        print("Optuna holdout 공통 base_df 생성")
        print("=" * 80)

    base_df, base_feature_cols, close_col = make_base_feature_dataset(
        etf_code=etf_code,
        external_tickers=external_tickers,
        external_feature_types=external_feature_types,
        start_date=start_date,
        end_date=end_date,
    )

    trial_rows = []

    def objective(trial):
        cfg = build_optuna_holdout_config(trial, fixed_cfg=fixed_cfg)

        if verbose:
            print("\n" + "=" * 100)
            print(f"OPTUNA HOLDOUT TRIAL {trial.number + 1}/{n_trials}")
            print(cfg)
            print("=" * 100)

        try:
            result = run_holdout_validation(
                etf_code=cfg.get("etf_code", ETF_CODE),
                n_days=cfg.get("n_days", N_DAYS),
                threshold=cfg.get("threshold", THRESHOLD),
                test_months=cfg.get("test_months", 3),
                vif_threshold=cfg.get("vif_threshold", VIF_THRESHOLD),
                lag_search_years=cfg.get("lag_search_years", LAG_SEARCH_YEARS),
                lag_days=cfg.get("lag_days", LAG_DAYS),
                random_state=cfg.get("random_state", RANDOM_STATE),
                n_rf_runs=cfg.get("n_rf_runs", N_RF_RUNS),
                n_repeats=cfg.get("n_repeats", N_REPEATS),
                top_n=cfg.get("top_n", TOP_N),
                pred_threshold=cfg.get("pred_threshold", PRED_THRESHOLD),
                model_name=cfg.get("model_name", "random_forest"),
                model_params=cfg.get("model_params", {}),
                start_date=cfg.get("start_date", START_DATE),
                end_date=cfg.get("end_date", END_DATE),
                external_tickers=external_tickers,
                external_feature_types=external_feature_types,
                base_df=base_df,
                base_feature_cols=base_feature_cols,
                close_col=close_col,
                save_to_excel=save_to_excel,
                experiment_dir=experiment_dir,
                skip_existing=skip_existing,
                run_name=f"optuna_holdout_trial_{trial.number:04d}",
                verbose=verbose,
            )

            score = compute_optuna_holdout_score(
                result=result,
                objective_metric=objective_metric,
                min_eval_count=min_eval_count,
                min_pred_1_count=min_pred_1_count,
            )

            row = {
                "trial_number": trial.number,
                "score": score,
                **cfg,
                objective_metric: get_holdout_metric_from_result(result, objective_metric),
                "test_eval_count": get_holdout_metric_from_result(result, "test_eval_count"),
                "test_pred_1_count": get_holdout_metric_from_result(result, "test_pred_1_count"),
                "skipped_existing": result.get("skipped_existing", False),
            }
            trial_rows.append(row)

            trial.set_user_attr("score", score)
            trial.set_user_attr(objective_metric, row[objective_metric])
            trial.set_user_attr("test_eval_count", row["test_eval_count"])
            trial.set_user_attr("test_pred_1_count", row["test_pred_1_count"])
            trial.set_user_attr("cfg", cfg)

            return score

        except Exception as e:
            if verbose:
                print(f"[OPTUNA HOLDOUT TRIAL FAIL] trial={trial.number}, error={e}")
            trial_rows.append({
                "trial_number": trial.number,
                "score": 0.0,
                **cfg,
                "error": str(e),
            })
            return 0.0

    study = optuna.create_study(direction="maximize")
    study.optimize(objective, n_trials=n_trials)

    trials_df = pd.DataFrame(trial_rows)
    if len(trials_df) > 0 and "score" in trials_df.columns:
        trials_df = trials_df.sort_values("score", ascending=False).reset_index(drop=True)

    if verbose:
        print("\n" + "=" * 80)
        print("OPTUNA HOLDOUT BEST TRIAL")
        print("=" * 80)
        print("best_value:", study.best_value)
        print("best_params:", study.best_params)
        display(trials_df.head(20))

    return {
        "study": study,
        "trials_df": trials_df,
        "base_df": base_df,
        "base_feature_cols": base_feature_cols,
        "close_col": close_col,
    }

In [12]:

# =========================================================
# Holdout Optuna 실행 예시
# - 전체 데이터 마지막 3개월을 test로 사용
# - test 시작 전까지 train으로 변수 선택/학습
# - 결과: experiments_excel/experiment_summary_holdout.xlsx
# =========================================================

fixed_cfg = {
    "etf_code": "SMH",
    "test_months": 3,
    "vif_threshold": 10,
    "lag_search_years": 1,
    "lag_days": [1, 3, 5, 10, 20, 40, 60, 120],
    "random_state": 42,
    "n_rf_runs": 3,
    "n_repeats": 10,
}

holdout_optuna_result = run_optuna_holdout_experiments(
    n_trials=200,
    fixed_cfg=fixed_cfg,
    objective_metric="test_precision",
    min_eval_count=10,
    min_pred_1_count=3,
    save_to_excel=True,
    experiment_dir=EXCEL_EXPERIMENT_DIR,
    skip_existing=True,
    verbose=True,
)

================================================================================
Optuna holdout 공통 base_df 생성
================================================================================
Loading external ticker: QQQ / QQQ
Loading external ticker: SPY / SPY
Loading external ticker: SOXX / SOXX
Loading external ticker: NVDA / NVDA
Loading external ticker: TSM / TSM
Loading external ticker: VIX / ^VIX
Loading external ticker: TNX / ^TNX
Loading external ticker: USDKRW / KRW=X
Loading external ticker: DXY / DX-Y.NYB
Loading external ticker: GOLD / GC=F
Loading external ticker: OIL / CL=F

[I 2026-05-23 20:44:44,022] A new study created in memory with name: no-name-0b8948ef-d0eb-44e3-9abd-fb6c1c1d49d5

====================================================================================================
OPTUNA HOLDOUT TRIAL 1/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 5, 'threshold': 0.01, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'random_forest', 'model_params': {'n_estimators': 500, 'max_depth': 10, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'class_weight': 'balanced'}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 0}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_5d_up_1pct
target_df shape: (1538, 31)
target 분포:
target_5d_up_1pct
0    783
1    755
Name: count, dtype: int64
lagged_df shape: (1398, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1688

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1684

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1685
TOP feature count: 20
['DXY_ret_20d_lag120', 'USDKRW_ret_20d_lag1', 'GOLD_ret_5d_lag120', 'TNX_level_lag120', 'OIL_ret_20d_lag60', 'VIX_level_lag40', 'TNX_diff_5d_lag20', 'SMH_vol_20d_lag60', 'TSM_ret_20d_lag120', 'GOLD_ret_20d_lag1', 'SMH_ma60_ratio_lag40', 'SPY_ret_20d_lag120', 'NVDA_ret_20d_lag120', 'NVDA_ret_5d_lag60', 'TNX_diff_20d_lag5', 'SPY_ret_5d_lag40', 'SMH_ma20_ratio_lag120', 'USDKRW_ret_5d_lag3', 'OIL_ret_5d_lag120', 'VIX_chg_20d_lag20']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,DXY_ret_20d_lag120,0.123290,0.002489,6.197355e-06,0.119057,0.128485,3,30,0.120801,DXY_ret_20d,120,120,-0.222084,0.222084,132
1,USDKRW_ret_20d_lag1,0.077059,0.001727,2.982988e-06,0.074559,0.080329,3,30,0.075332,USDKRW_ret_20d,1,1,-0.239377,0.239377,251
2,GOLD_ret_5d_lag120,0.074402,0.002680,7.181190e-06,0.068122,0.079361,3,30,0.071722,GOLD_ret_5d,120,120,-0.178798,0.178798,132
3,TNX_level_lag120,0.072721,0.001518,2.305315e-06,0.069368,0.075558,3,30,0.071203,TNX_level,120,120,-0.186774,0.186774,132
4,OIL_ret_20d_lag60,0.061638,0.001838,3.379399e-06,0.057992,0.065463,3,30,0.059800,OIL_ret_20d,60,60,0.219382,0.219382,192
5,VIX_level_lag40,0.059311,0.001439,2.071372e-06,0.057185,0.062564,3,30,0.057872,VIX_level,40,40,0.163867,0.163867,212
6,TNX_diff_5d_lag20,0.059156,0.002600,6.759679e-06,0.054395,0.063171,3,30,0.056556,TNX_diff_5d,20,20,0.180109,0.180109,232
7,SMH_vol_20d_lag60,0.058574,0.002574,6.627958e-06,0.054366,0.062443,3,30,0.055999,SMH_vol_20d,60,60,-0.124807,0.124807,192
8,TSM_ret_20d_lag120,0.051865,0.001436,2.062305e-06,0.048627,0.053826,3,30,0.050429,TSM_ret_20d,120,120,-0.153156,0.153156,132
9,GOLD_ret_20d_lag1,0.051330,0.001163,1.352521e-06,0.049480,0.054350,3,30,0.050167,GOLD_ret_20d,1,1,0.135460,0.135460,251
10,SMH_ma60_ratio_lag40,0.051951,0.001808,3.269816e-06,0.047841,0.054963,3,30,0.050143,SMH_ma60_ratio,40,40,-0.126200,0.126200,212
11,SPY_ret_20d_lag120,0.050949,0.000864,7.459016e-07,0.049516,0.052441,3,30,0.050086,SPY_ret_20d,120,120,-0.193781,0.193781,132
12,NVDA_ret_20d_lag120,0.051557,0.002003,4.012540e-06,0.048422,0.055273,3,30,0.049554,NVDA_ret_20d,120,120,-0.156460,0.156460,132
13,NVDA_ret_5d_lag60,0.047515,0.002605,6.786357e-06,0.044222,0.052144,3,30,0.044909,NVDA_ret_5d,60,60,-0.160344,0.160344,192
14,TNX_diff_20d_lag5,0.045462,0.001319,1.740925e-06,0.043227,0.047514,3,30,0.044142,TNX_diff_20d,5,5,0.204467,0.204467,247
15,SPY_ret_5d_lag40,0.043878,0.000924,8.538559e-07,0.041587,0.046061,3,30,0.042954,SPY_ret_5d,40,40,-0.256629,0.256629,212
16,SMH_ma20_ratio_lag120,0.042750,0.000881,7.762968e-07,0.041166,0.044024,3,30,0.041869,SMH_ma20_ratio,120,120,-0.147304,0.147304,132
17,USDKRW_ret_5d_lag3,0.041226,0.000756,5.708342e-07,0.039340,0.042809,3,30,0.040471,USDKRW_ret_5d,3,3,-0.131065,0.131065,249
18,OIL_ret_5d_lag120,0.039740,0.000690,4.757277e-07,0.038231,0.041596,3,30,0.039051,OIL_ret_5d,120,120,-0.096786,0.096786,132
19,VIX_chg_20d_lag20,0.039091,0.000637,4.058666e-07,0.037322,0.040579,3,30,0.038454,VIX_chg_20d,20,20,-0.126048,0.126048,232

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1398, 23)
X_train shape: (1398, 20)
train target 분포:
target_5d_up_1pct
0    720
1    678
Name: count, dtype: int64
target_5d_up_1pct
0    0.515021
1    0.484979
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: random_forest
valid_df 예측 완료

         Date  SMH_adj_close  target_5d_up_1pct  pred_proba  pred
0  2026-02-23     412.880005                0.0    0.441771     0
1  2026-02-24     419.160004                0.0    0.329255     0
2  2026-02-25     426.160004                0.0    0.357353     0
3  2026-02-26     412.010010                0.0    0.287121     0
4  2026-02-27     406.369995                0.0    0.342205     0
..        ...            ...                ...         ...   ...
59 2026-05-18     546.159973                NaN    0.390718     0
60 2026-05-19     543.960022                NaN    0.433690     0
61 2026-05-20     564.659973                NaN    0.395862     0
62 2026-05-21     567.880005                NaN    0.421236     0
63 2026-05-22     576.320007                NaN    0.415067     0

[64 rows x 5 columns]

예측값 분포:
pred
0    64
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 59
예측 1 개수: 0
예측 1 중 실제 1 개수: 0
예측 1 기준 정확도 precision: nan

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,5,0.01,1,20,20,random_forest,"{'n_estimators': 500, 'max_depth': 10, 'min_sa...",59,0,...,0.440678,0.0,0.0,0.0,0.483683,0.727568,26,0,33,0

[I 2026-05-23 20:44:59,223] Trial 0 finished with value: 0.0 and parameters: {'n_days': 5, 'threshold': 0.01, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'random_forest', 'rf_n_estimators': 500, 'rf_max_depth': 10, 'rf_min_samples_leaf': 10, 'rf_max_features': 'sqrt'}. Best is trial 0 with value: 0.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 2/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.01, 'top_n': 30, 'pred_threshold': 0.3, 'model_name': 'logistic', 'model_params': {'C': 0.1, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 1}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_1pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_1pct
1    917
0    606
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1301

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1302

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1305
TOP feature count: 27
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'NVDA_ret_5d_lag120', 'DXY_ret_5d_lag120', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SMH_ma60_ratio_lag1', 'OIL_ret_20d_lag120', 'VIX_chg_5d_lag120', 'SPY_ret_20d_lag1', 'TNX_diff_5d_lag5', 'GOLD_ret_20d_lag120', 'SMH_ma20_ratio_lag120', 'TSM_ret_5d_lag120', 'GOLD_ret_5d_lag40', 'OIL_ret_5d_lag10', 'USDKRW_ret_5d_lag10', 'SPY_ret_5d_lag120', 'SOXX_ret_5d_lag120', 'SMH_volume_ratio_20d_lag120', 'SMH_ma5_ratio_lag120', 'SMH_ret_1d_lag120']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.113199,0.003130,9.798652e-06,0.105366,0.117758,3,30,0.110069,SMH_vol_20d,120,120,-0.305565,0.305565,132
1,TNX_level_lag20,0.111395,0.001966,3.863856e-06,0.107542,0.114334,3,30,0.109430,TNX_level,20,20,-0.282349,0.282349,232
2,NVDA_ret_20d_lag1,0.080573,0.003084,9.508619e-06,0.075624,0.086273,3,30,0.077490,NVDA_ret_20d,1,1,0.282168,0.282168,251
3,VIX_chg_20d_lag120,0.077843,0.001462,2.138529e-06,0.074670,0.080400,3,30,0.076381,VIX_chg_20d,120,120,0.371232,0.371232,132
4,DXY_ret_20d_lag60,0.073491,0.002177,4.737914e-06,0.068070,0.077471,3,30,0.071314,DXY_ret_20d,60,60,-0.256904,0.256904,192
5,TNX_diff_20d_lag1,0.066654,0.002093,4.380060e-06,0.062034,0.070705,3,30,0.064561,TNX_diff_20d,1,1,0.416622,0.416622,251
6,NVDA_ret_5d_lag120,0.056072,0.001459,2.128896e-06,0.052971,0.058355,3,30,0.054613,NVDA_ret_5d,120,120,-0.233880,0.233880,132
7,DXY_ret_5d_lag120,0.053295,0.001976,3.904778e-06,0.049647,0.058129,3,30,0.051319,DXY_ret_5d,120,120,-0.267096,0.267096,132
8,VIX_level_lag20,0.051839,0.001035,1.070311e-06,0.049900,0.053607,3,30,0.050805,VIX_level,20,20,0.239784,0.239784,232
9,USDKRW_ret_20d_lag40,0.051299,0.001162,1.350872e-06,0.049044,0.053384,3,30,0.050136,USDKRW_ret_20d,40,40,0.281470,0.281470,212
10,TSM_ret_20d_lag1,0.050516,0.002066,4.268228e-06,0.047785,0.054069,3,30,0.048450,TSM_ret_20d,1,1,0.339692,0.339692,251
11,SMH_ma60_ratio_lag1,0.047034,0.001847,3.412431e-06,0.043919,0.049834,3,30,0.045187,SMH_ma60_ratio,1,1,0.226498,0.226498,251
12,OIL_ret_20d_lag120,0.044614,0.001553,2.410659e-06,0.041020,0.048293,3,30,0.043061,OIL_ret_20d,120,120,0.291387,0.291387,132
13,VIX_chg_5d_lag120,0.042947,0.001208,1.459362e-06,0.040616,0.045759,3,30,0.041739,VIX_chg_5d,120,120,0.143824,0.143824,132
14,SPY_ret_20d_lag1,0.043100,0.001912,3.657161e-06,0.039473,0.046173,3,30,0.041188,SPY_ret_20d,1,1,0.273031,0.273031,251
15,TNX_diff_5d_lag5,0.041964,0.001642,2.694547e-06,0.039434,0.045450,3,30,0.040323,TNX_diff_5d,5,5,0.182059,0.182059,247
16,GOLD_ret_20d_lag120,0.037065,0.001167,1.361693e-06,0.034635,0.040013,3,30,0.035898,GOLD_ret_20d,120,120,-0.306548,0.306548,132
17,SMH_ma20_ratio_lag120,0.034339,0.000618,3.813267e-07,0.033254,0.035764,3,30,0.033721,SMH_ma20_ratio,120,120,-0.303183,0.303183,132
18,TSM_ret_5d_lag120,0.034178,0.001041,1.084444e-06,0.032365,0.036477,3,30,0.033136,TSM_ret_5d,120,120,-0.251775,0.251775,132
19,GOLD_ret_5d_lag40,0.031021,0.001323,1.750672e-06,0.028289,0.032956,3,30,0.029698,GOLD_ret_5d,40,40,-0.185968,0.185968,212
20,OIL_ret_5d_lag10,0.029586,0.001875,3.517040e-06,0.027166,0.032706,3,30,0.027711,OIL_ret_5d,10,10,0.146724,0.146724,242
21,USDKRW_ret_5d_lag10,0.027594,0.000588,3.460618e-07,0.026296,0.028759,3,30,0.027005,USDKRW_ret_5d,10,10,-0.121963,0.121963,242
22,SPY_ret_5d_lag120,0.028773,0.001908,3.640026e-06,0.025646,0.031853,3,30,0.026865,SPY_ret_5d,120,120,-0.246520,0.246520,132
23,SOXX_ret_5d_lag120,0.025931,0.000598,3.576511e-07,0.024603,0.027262,3,30,0.025333,SOXX_ret_5d,120,120,-0.291324,0.291324,132
24,SMH_volume_ratio_20d_lag120,0.020064,0.000543,2.953606e-07,0.018983,0.021253,3,30,0.019521,SMH_volume_ratio_20d,120,120,0.253841,0.253841,132
25,SMH_ma5_ratio_lag120,0.018507,0.000645,4.156173e-07,0.017517,0.019844,3,30,0.017862,SMH_ma5_ratio,120,120,-0.227259,0.227259,132
26,SMH_ret_1d_lag120,0.016140,0.000249,6.191607e-08,0.015550,0.016531,3,30,0.015892,SMH_ret_1d,120,120,-0.110756,0.110756,132

============================================================
6. valid_df 생성
============================================================
top feature 수: 27
lag 생성 후 valid_df shape: (1607, 56)
원본 base_feature 제거 후 valid_df shape: (1607, 29)
최종 컬럼 수: 29
target 생성 후 valid_df shape: (1607, 31)
최종 valid_df shape: (64, 31)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 27
train_df shape: (1383, 30)
X_train shape: (1383, 27)
train target 분포:
target_20d_up_1pct
1    815
0    568
Name: count, dtype: int64
target_20d_up_1pct
1    0.589299
0    0.410701
Name: proportion, dtype: float64
valid_df shape: (64, 31)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_1pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.441386     1
1  2026-02-24     419.160004                 0.0    0.449462     1
2  2026-02-25     426.160004                 0.0    0.521919     1
3  2026-02-26     412.010010                 0.0    0.530099     1
4  2026-02-27     406.369995                 0.0    0.719955     1
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.487530     1
60 2026-05-19     543.960022                 NaN    0.530313     1
61 2026-05-20     564.659973                 NaN    0.666356     1
62 2026-05-21     567.880005                 NaN    0.736791     1
63 2026-05-22     576.320007                 NaN    0.694920     1

[64 rows x 5 columns]

예측값 분포:
pred
1    64
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 44
예측 1 중 실제 1 개수: 35
예측 1 기준 정확도 precision: 0.7954545454545454

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.01,1,30,27,logistic,"{'C': 0.1, 'class_weight': 'balanced', 'max_it...",44,44,...,0.795455,0.795455,1.0,0.886076,0.231746,0.770995,0,9,0,35

[I 2026-05-23 20:45:12,376] Trial 1 finished with value: 0.7954545454545454 and parameters: {'n_days': 20, 'threshold': 0.01, 'top_n': 30, 'pred_threshold': 0.3, 'model_name': 'logistic', 'logistic_C': 0.1}. Best is trial 1 with value: 0.7954545454545454.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 3/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 3, 'threshold': 0.005, 'top_n': 30, 'pred_threshold': 0.45, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 100, 'learning_rate': 0.1, 'max_depth': 5}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 2}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_3d_up_0pct
target_df shape: (1540, 31)
target 분포:
target_3d_up_0pct
1    785
0    755
Name: count, dtype: int64
lagged_df shape: (1361, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1802

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1801

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1802
TOP feature count: 27
['DXY_ret_20d_lag120', 'TNX_diff_5d_lag20', 'SMH_ma5_ratio_lag10', 'TNX_level_lag120', 'NVDA_ret_20d_lag120', 'SMH_vol_20d_lag40', 'USDKRW_ret_20d_lag1', 'SPY_ret_20d_lag120', 'GOLD_ret_20d_lag1', 'NVDA_ret_5d_lag1', 'TSM_ret_5d_lag5', 'VIX_chg_20d_lag120', 'SMH_ma60_ratio_lag120', 'DXY_ret_5d_lag10', 'SMH_volume_ratio_20d_lag60', 'VIX_level_lag40', 'VIX_chg_5d_lag40', 'TSM_ret_20d_lag120', 'OIL_ret_20d_lag10', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag120', 'SOXX_ret_5d_lag40', 'OIL_ret_5d_lag40', 'SPY_ret_5d_lag40', 'USDKRW_ret_5d_lag60', 'GOLD_ret_5d_lag40', 'SMH_ret_1d_lag10']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,DXY_ret_20d_lag120,0.095051,0.002523,6.365593e-06,0.089643,0.098954,3,30,0.092528,DXY_ret_20d,120,120,-0.173415,0.173415,131
1,TNX_diff_5d_lag20,0.077516,0.003086,9.520754e-06,0.071449,0.081991,3,30,0.074431,TNX_diff_5d,20,20,0.185352,0.185352,231
2,SMH_ma5_ratio_lag10,0.072413,0.002780,7.727570e-06,0.067169,0.077714,3,30,0.069633,SMH_ma5_ratio,10,10,-0.129532,0.129532,241
3,TNX_level_lag120,0.062731,0.002337,5.459984e-06,0.058887,0.067321,3,30,0.060395,TNX_level,120,120,-0.159365,0.159365,131
4,NVDA_ret_20d_lag120,0.061209,0.002360,5.571273e-06,0.056570,0.064739,3,30,0.058848,NVDA_ret_20d,120,120,-0.167576,0.167576,131
5,SMH_vol_20d_lag40,0.061249,0.002893,8.366799e-06,0.057907,0.066194,3,30,0.058357,SMH_vol_20d,40,40,0.077548,0.077548,211
6,USDKRW_ret_20d_lag1,0.058843,0.002171,4.714448e-06,0.054917,0.062474,3,30,0.056672,USDKRW_ret_20d,1,1,-0.155957,0.155957,250
7,SPY_ret_20d_lag120,0.059022,0.002674,7.149388e-06,0.054000,0.062454,3,30,0.056348,SPY_ret_20d,120,120,-0.201833,0.201833,131
8,GOLD_ret_20d_lag1,0.055258,0.002037,4.150077e-06,0.052435,0.058914,3,30,0.053221,GOLD_ret_20d,1,1,0.106859,0.106859,250
9,NVDA_ret_5d_lag1,0.053249,0.000955,9.115023e-07,0.050535,0.055074,3,30,0.052294,NVDA_ret_5d,1,1,-0.141075,0.141075,250
10,TSM_ret_5d_lag5,0.053881,0.001836,3.369065e-06,0.050081,0.057347,3,30,0.052045,TSM_ret_5d,5,5,0.292130,0.292130,246
11,VIX_chg_20d_lag120,0.049308,0.001172,1.372957e-06,0.047214,0.052258,3,30,0.048136,VIX_chg_20d,120,120,0.156735,0.156735,131
12,SMH_ma60_ratio_lag120,0.048400,0.000947,8.967629e-07,0.047069,0.050483,3,30,0.047453,SMH_ma60_ratio,120,120,-0.079687,0.079687,131
13,DXY_ret_5d_lag10,0.045327,0.000923,8.519899e-07,0.043719,0.047217,3,30,0.044404,DXY_ret_5d,10,10,-0.125095,0.125095,241
14,SMH_volume_ratio_20d_lag60,0.043484,0.000993,9.853630e-07,0.041321,0.046249,3,30,0.042492,SMH_volume_ratio_20d,60,60,0.244273,0.244273,191
15,VIX_level_lag40,0.042859,0.000772,5.966071e-07,0.040937,0.044428,3,30,0.042086,VIX_level,40,40,0.121059,0.121059,211
16,VIX_chg_5d_lag40,0.043320,0.001263,1.595443e-06,0.040784,0.045440,3,30,0.042056,VIX_chg_5d,40,40,0.142520,0.142520,211
17,TSM_ret_20d_lag120,0.043276,0.001308,1.711773e-06,0.041513,0.046066,3,30,0.041968,TSM_ret_20d,120,120,-0.176868,0.176868,131
18,OIL_ret_20d_lag10,0.042898,0.002029,4.115852e-06,0.038814,0.046355,3,30,0.040869,OIL_ret_20d,10,10,0.140951,0.140951,241
19,TNX_diff_20d_lag5,0.042138,0.001669,2.784700e-06,0.039179,0.044949,3,30,0.040469,TNX_diff_20d,5,5,0.183670,0.183670,246
20,SMH_ma20_ratio_lag120,0.041413,0.001349,1.819773e-06,0.038568,0.044904,3,30,0.040064,SMH_ma20_ratio,120,120,-0.165502,0.165502,131
21,SOXX_ret_5d_lag40,0.040428,0.000928,8.607765e-07,0.038254,0.042169,3,30,0.039501,SOXX_ret_5d,40,40,-0.148812,0.148812,211
22,OIL_ret_5d_lag40,0.039956,0.001354,1.834178e-06,0.037266,0.041523,3,30,0.038601,OIL_ret_5d,40,40,-0.170497,0.170497,211
23,SPY_ret_5d_lag40,0.038536,0.001406,1.975763e-06,0.036707,0.041898,3,30,0.037130,SPY_ret_5d,40,40,-0.188059,0.188059,211
24,USDKRW_ret_5d_lag60,0.037953,0.000883,7.791327e-07,0.035494,0.039662,3,30,0.037070,USDKRW_ret_5d,60,60,0.118828,0.118828,191
25,GOLD_ret_5d_lag40,0.036113,0.001118,1.250674e-06,0.033439,0.038168,3,30,0.034995,GOLD_ret_5d,40,40,-0.145775,0.145775,211
26,SMH_ret_1d_lag10,0.036470,0.002121,4.500694e-06,0.032953,0.039605,3,30,0.034349,SMH_ret_1d,10,10,-0.076671,0.076671,241

============================================================
6. valid_df 생성
============================================================
top feature 수: 27
lag 생성 후 valid_df shape: (1607, 56)
원본 base_feature 제거 후 valid_df shape: (1607, 29)
최종 컬럼 수: 29
target 생성 후 valid_df shape: (1607, 31)
최종 valid_df shape: (64, 31)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 27
train_df shape: (1361, 30)
X_train shape: (1361, 27)
train target 분포:
target_3d_up_0pct
1    687
0    674
Name: count, dtype: int64
target_3d_up_0pct
1    0.504776
0    0.495224
Name: proportion, dtype: float64
valid_df shape: (64, 31)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_3d_up_0pct  pred_proba  pred
0  2026-02-23     412.880005                0.0    0.499656     1
1  2026-02-24     419.160004                0.0    0.486297     1
2  2026-02-25     426.160004                0.0    0.233567     0
3  2026-02-26     412.010010                0.0    0.445665     0
4  2026-02-27     406.369995                0.0    0.387123     0
..        ...            ...                ...         ...   ...
59 2026-05-18     546.159973                1.0    0.358728     0
60 2026-05-19     543.960022                1.0    0.433651     0
61 2026-05-20     564.659973                NaN    0.690910     1
62 2026-05-21     567.880005                NaN    0.563532     1
63 2026-05-22     576.320007                NaN    0.698659     1

[64 rows x 5 columns]

예측값 분포:
pred
1    32
0    32
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 61
예측 1 개수: 29
예측 1 중 실제 1 개수: 23
예측 1 기준 정확도 precision: 0.7931034482758621

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,3,0.005,1,30,27,gradient_boosting,"{'n_estimators': 100, 'learning_rate': 0.1, 'm...",61,29,...,0.672131,0.793103,0.621622,0.69697,0.689189,0.686329,18,6,14,23

[I 2026-05-23 20:45:27,182] Trial 2 finished with value: 0.7931034482758621 and parameters: {'n_days': 3, 'threshold': 0.005, 'top_n': 30, 'pred_threshold': 0.45, 'model_name': 'gradient_boosting', 'gb_n_estimators': 100, 'gb_learning_rate': 0.1, 'gb_max_depth': 5}. Best is trial 1 with value: 0.7954545454545454.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 4/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 10, 'threshold': 0.01, 'top_n': 10, 'pred_threshold': 0.25, 'model_name': 'logistic', 'model_params': {'C': 1.0, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 3}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_10d_up_1pct
target_df shape: (1533, 31)
target 분포:
target_10d_up_1pct
1    837
0    696
Name: count, dtype: int64
lagged_df shape: (1393, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1422

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1419

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.142
TOP feature count: 10
['TNX_level_lag120', 'USDKRW_ret_20d_lag3', 'DXY_ret_20d_lag120', 'SMH_vol_20d_lag40', 'SMH_ma60_ratio_lag40', 'OIL_ret_20d_lag40', 'TSM_ret_20d_lag1', 'GOLD_ret_20d_lag40', 'TNX_diff_20d_lag5', 'VIX_level_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.103907,0.005387,0.000029,0.094888,0.112756,3,30,0.098520,TNX_level,120,120,-0.277689,0.277689,132
1,USDKRW_ret_20d_lag3,0.096126,0.003008,0.000009,0.089867,0.100682,3,30,0.093118,USDKRW_ret_20d,3,3,-0.343097,0.343097,249
2,DXY_ret_20d_lag120,0.078045,0.003997,0.000016,0.070637,0.084179,3,30,0.074048,DXY_ret_20d,120,120,-0.284585,0.284585,132
3,SMH_vol_20d_lag40,0.076580,0.003149,0.000010,0.071988,0.083066,3,30,0.073431,SMH_vol_20d,40,40,0.227843,0.227843,212
4,SMH_ma60_ratio_lag40,0.074700,0.001793,0.000003,0.071572,0.079336,3,30,0.072907,SMH_ma60_ratio,40,40,-0.197085,0.197085,212
5,OIL_ret_20d_lag40,0.067693,0.002280,0.000005,0.063479,0.071986,3,30,0.065413,OIL_ret_20d,40,40,-0.236786,0.236786,212
6,TSM_ret_20d_lag1,0.064156,0.002883,0.000008,0.059290,0.069357,3,30,0.061273,TSM_ret_20d,1,1,0.262393,0.262393,251
7,GOLD_ret_20d_lag40,0.062099,0.002347,0.000006,0.058111,0.066442,3,30,0.059752,GOLD_ret_20d,40,40,-0.119939,0.119939,212
8,TNX_diff_20d_lag5,0.056086,0.001336,0.000002,0.053196,0.058570,3,30,0.054750,TNX_diff_20d,5,5,0.351351,0.351351,247
9,VIX_level_lag40,0.050925,0.001653,0.000003,0.047678,0.054358,3,30,0.049272,VIX_level,40,40,0.157321,0.157321,212

============================================================
6. valid_df 생성
============================================================
top feature 수: 10
lag 생성 후 valid_df shape: (1607, 22)
원본 base_feature 제거 후 valid_df shape: (1607, 12)
최종 컬럼 수: 12
target 생성 후 valid_df shape: (1607, 14)
최종 valid_df shape: (64, 14)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 10
train_df shape: (1393, 13)
X_train shape: (1393, 10)
train target 분포:
target_10d_up_1pct
1    749
0    644
Name: count, dtype: int64
target_10d_up_1pct
1    0.537688
0    0.462312
Name: proportion, dtype: float64
valid_df shape: (64, 14)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_10d_up_1pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.594874     1
1  2026-02-24     419.160004                 0.0    0.557204     1
2  2026-02-25     426.160004                 0.0    0.538276     1
3  2026-02-26     412.010010                 0.0    0.455982     1
4  2026-02-27     406.369995                 0.0    0.481813     1
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.394724     1
60 2026-05-19     543.960022                 NaN    0.369502     1
61 2026-05-20     564.659973                 NaN    0.389445     1
62 2026-05-21     567.880005                 NaN    0.422943     1
63 2026-05-22     576.320007                 NaN    0.358227     1

[64 rows x 5 columns]

예측값 분포:
pred
1    64
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 54
예측 1 개수: 54
예측 1 중 실제 1 개수: 37
예측 1 기준 정확도 precision: 0.6851851851851852

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,10,0.01,1,10,10,logistic,"{'C': 1.0, 'class_weight': 'balanced', 'max_it...",54,54,...,0.685185,0.685185,1.0,0.813187,0.534181,0.633821,0,17,0,37

[I 2026-05-23 20:45:40,869] Trial 3 finished with value: 0.6851851851851852 and parameters: {'n_days': 10, 'threshold': 0.01, 'top_n': 10, 'pred_threshold': 0.25, 'model_name': 'logistic', 'logistic_C': 1.0}. Best is trial 1 with value: 0.7954545454545454.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 5/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 3, 'threshold': 0.005, 'top_n': 30, 'pred_threshold': 0.55, 'model_name': 'random_forest', 'model_params': {'n_estimators': 500, 'max_depth': 3, 'min_samples_leaf': 10, 'max_features': 'log2', 'class_weight': 'balanced'}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 4}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_3d_up_0pct
target_df shape: (1540, 31)
target 분포:
target_3d_up_0pct
1    785
0    755
Name: count, dtype: int64
lagged_df shape: (1361, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1802

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1801

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1802
TOP feature count: 27
['DXY_ret_20d_lag120', 'TNX_diff_5d_lag20', 'SMH_ma5_ratio_lag10', 'TNX_level_lag120', 'NVDA_ret_20d_lag120', 'SMH_vol_20d_lag40', 'USDKRW_ret_20d_lag1', 'SPY_ret_20d_lag120', 'GOLD_ret_20d_lag1', 'NVDA_ret_5d_lag1', 'TSM_ret_5d_lag5', 'VIX_chg_20d_lag120', 'SMH_ma60_ratio_lag120', 'DXY_ret_5d_lag10', 'SMH_volume_ratio_20d_lag60', 'VIX_level_lag40', 'VIX_chg_5d_lag40', 'TSM_ret_20d_lag120', 'OIL_ret_20d_lag10', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag120', 'SOXX_ret_5d_lag40', 'OIL_ret_5d_lag40', 'SPY_ret_5d_lag40', 'USDKRW_ret_5d_lag60', 'GOLD_ret_5d_lag40', 'SMH_ret_1d_lag10']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,DXY_ret_20d_lag120,0.095051,0.002523,6.365593e-06,0.089643,0.098954,3,30,0.092528,DXY_ret_20d,120,120,-0.173415,0.173415,131
1,TNX_diff_5d_lag20,0.077516,0.003086,9.520754e-06,0.071449,0.081991,3,30,0.074431,TNX_diff_5d,20,20,0.185352,0.185352,231
2,SMH_ma5_ratio_lag10,0.072413,0.002780,7.727570e-06,0.067169,0.077714,3,30,0.069633,SMH_ma5_ratio,10,10,-0.129532,0.129532,241
3,TNX_level_lag120,0.062731,0.002337,5.459984e-06,0.058887,0.067321,3,30,0.060395,TNX_level,120,120,-0.159365,0.159365,131
4,NVDA_ret_20d_lag120,0.061209,0.002360,5.571273e-06,0.056570,0.064739,3,30,0.058848,NVDA_ret_20d,120,120,-0.167576,0.167576,131
5,SMH_vol_20d_lag40,0.061249,0.002893,8.366799e-06,0.057907,0.066194,3,30,0.058357,SMH_vol_20d,40,40,0.077548,0.077548,211
6,USDKRW_ret_20d_lag1,0.058843,0.002171,4.714448e-06,0.054917,0.062474,3,30,0.056672,USDKRW_ret_20d,1,1,-0.155957,0.155957,250
7,SPY_ret_20d_lag120,0.059022,0.002674,7.149388e-06,0.054000,0.062454,3,30,0.056348,SPY_ret_20d,120,120,-0.201833,0.201833,131
8,GOLD_ret_20d_lag1,0.055258,0.002037,4.150077e-06,0.052435,0.058914,3,30,0.053221,GOLD_ret_20d,1,1,0.106859,0.106859,250
9,NVDA_ret_5d_lag1,0.053249,0.000955,9.115023e-07,0.050535,0.055074,3,30,0.052294,NVDA_ret_5d,1,1,-0.141075,0.141075,250
10,TSM_ret_5d_lag5,0.053881,0.001836,3.369065e-06,0.050081,0.057347,3,30,0.052045,TSM_ret_5d,5,5,0.292130,0.292130,246
11,VIX_chg_20d_lag120,0.049308,0.001172,1.372957e-06,0.047214,0.052258,3,30,0.048136,VIX_chg_20d,120,120,0.156735,0.156735,131
12,SMH_ma60_ratio_lag120,0.048400,0.000947,8.967629e-07,0.047069,0.050483,3,30,0.047453,SMH_ma60_ratio,120,120,-0.079687,0.079687,131
13,DXY_ret_5d_lag10,0.045327,0.000923,8.519899e-07,0.043719,0.047217,3,30,0.044404,DXY_ret_5d,10,10,-0.125095,0.125095,241
14,SMH_volume_ratio_20d_lag60,0.043484,0.000993,9.853630e-07,0.041321,0.046249,3,30,0.042492,SMH_volume_ratio_20d,60,60,0.244273,0.244273,191
15,VIX_level_lag40,0.042859,0.000772,5.966071e-07,0.040937,0.044428,3,30,0.042086,VIX_level,40,40,0.121059,0.121059,211
16,VIX_chg_5d_lag40,0.043320,0.001263,1.595443e-06,0.040784,0.045440,3,30,0.042056,VIX_chg_5d,40,40,0.142520,0.142520,211
17,TSM_ret_20d_lag120,0.043276,0.001308,1.711773e-06,0.041513,0.046066,3,30,0.041968,TSM_ret_20d,120,120,-0.176868,0.176868,131
18,OIL_ret_20d_lag10,0.042898,0.002029,4.115852e-06,0.038814,0.046355,3,30,0.040869,OIL_ret_20d,10,10,0.140951,0.140951,241
19,TNX_diff_20d_lag5,0.042138,0.001669,2.784700e-06,0.039179,0.044949,3,30,0.040469,TNX_diff_20d,5,5,0.183670,0.183670,246
20,SMH_ma20_ratio_lag120,0.041413,0.001349,1.819773e-06,0.038568,0.044904,3,30,0.040064,SMH_ma20_ratio,120,120,-0.165502,0.165502,131
21,SOXX_ret_5d_lag40,0.040428,0.000928,8.607765e-07,0.038254,0.042169,3,30,0.039501,SOXX_ret_5d,40,40,-0.148812,0.148812,211
22,OIL_ret_5d_lag40,0.039956,0.001354,1.834178e-06,0.037266,0.041523,3,30,0.038601,OIL_ret_5d,40,40,-0.170497,0.170497,211
23,SPY_ret_5d_lag40,0.038536,0.001406,1.975763e-06,0.036707,0.041898,3,30,0.037130,SPY_ret_5d,40,40,-0.188059,0.188059,211
24,USDKRW_ret_5d_lag60,0.037953,0.000883,7.791327e-07,0.035494,0.039662,3,30,0.037070,USDKRW_ret_5d,60,60,0.118828,0.118828,191
25,GOLD_ret_5d_lag40,0.036113,0.001118,1.250674e-06,0.033439,0.038168,3,30,0.034995,GOLD_ret_5d,40,40,-0.145775,0.145775,211
26,SMH_ret_1d_lag10,0.036470,0.002121,4.500694e-06,0.032953,0.039605,3,30,0.034349,SMH_ret_1d,10,10,-0.076671,0.076671,241

============================================================
6. valid_df 생성
============================================================
top feature 수: 27
lag 생성 후 valid_df shape: (1607, 56)
원본 base_feature 제거 후 valid_df shape: (1607, 29)
최종 컬럼 수: 29
target 생성 후 valid_df shape: (1607, 31)
최종 valid_df shape: (64, 31)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 27
train_df shape: (1361, 30)
X_train shape: (1361, 27)
train target 분포:
target_3d_up_0pct
1    687
0    674
Name: count, dtype: int64
target_3d_up_0pct
1    0.504776
0    0.495224
Name: proportion, dtype: float64
valid_df shape: (64, 31)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: random_forest
valid_df 예측 완료

         Date  SMH_adj_close  target_3d_up_0pct  pred_proba  pred
0  2026-02-23     412.880005                0.0    0.502007     0
1  2026-02-24     419.160004                0.0    0.500469     0
2  2026-02-25     426.160004                0.0    0.461116     0
3  2026-02-26     412.010010                0.0    0.470012     0
4  2026-02-27     406.369995                0.0    0.490817     0
..        ...            ...                ...         ...   ...
59 2026-05-18     546.159973                1.0    0.492833     0
60 2026-05-19     543.960022                1.0    0.497496     0
61 2026-05-20     564.659973                NaN    0.513590     0
62 2026-05-21     567.880005                NaN    0.511173     0
63 2026-05-22     576.320007                NaN    0.505419     0

[64 rows x 5 columns]

예측값 분포:
pred
0    63
1     1
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 61
예측 1 개수: 1
예측 1 중 실제 1 개수: 1
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,3,0.005,1,30,27,random_forest,"{'n_estimators': 500, 'max_depth': 3, 'min_sam...",61,1,...,0.409836,1.0,0.027027,0.052632,0.63964,0.689102,24,0,36,1

[I 2026-05-23 20:45:55,346] Trial 4 finished with value: 0.3333333333333333 and parameters: {'n_days': 3, 'threshold': 0.005, 'top_n': 30, 'pred_threshold': 0.55, 'model_name': 'random_forest', 'rf_n_estimators': 500, 'rf_max_depth': 3, 'rf_min_samples_leaf': 10, 'rf_max_features': 'log2'}. Best is trial 1 with value: 0.7954545454545454.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 6/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 10, 'threshold': 0.02, 'top_n': 10, 'pred_threshold': 0.4, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 500, 'learning_rate': 0.01, 'max_leaf_nodes': 31}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 5}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_10d_up_2pct
target_df shape: (1533, 31)
target 분포:
target_10d_up_2pct
0    796
1    737
Name: count, dtype: int64
lagged_df shape: (1393, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1451

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1444

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.145
TOP feature count: 10
['USDKRW_ret_20d_lag3', 'TNX_level_lag120', 'NVDA_ret_20d_lag60', 'DXY_ret_20d_lag120', 'OIL_ret_20d_lag40', 'SMH_vol_20d_lag40', 'SMH_ma60_ratio_lag40', 'VIX_chg_5d_lag60', 'VIX_level_lag40', 'TSM_ret_20d_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,USDKRW_ret_20d_lag3,0.109887,0.002912,0.000008,0.104706,0.114723,3,30,0.106975,USDKRW_ret_20d,3,3,-0.361488,0.361488,249
1,TNX_level_lag120,0.100155,0.003176,0.000010,0.095000,0.107899,3,30,0.096979,TNX_level,120,120,-0.215120,0.215120,132
2,NVDA_ret_20d_lag60,0.090154,0.002180,0.000005,0.086989,0.095382,3,30,0.087975,NVDA_ret_20d,60,60,-0.177262,0.177262,192
3,DXY_ret_20d_lag120,0.080840,0.002467,0.000006,0.077294,0.086061,3,30,0.078372,DXY_ret_20d,120,120,-0.296418,0.296418,132
4,OIL_ret_20d_lag40,0.078288,0.003562,0.000013,0.073828,0.086503,3,30,0.074726,OIL_ret_20d,40,40,-0.298890,0.298890,212
5,SMH_vol_20d_lag40,0.072109,0.001926,0.000004,0.067649,0.075586,3,30,0.070182,SMH_vol_20d,40,40,0.280782,0.280782,212
6,SMH_ma60_ratio_lag40,0.061142,0.001488,0.000002,0.057642,0.064227,3,30,0.059654,SMH_ma60_ratio,40,40,-0.243144,0.243144,212
7,VIX_chg_5d_lag60,0.054753,0.001912,0.000004,0.051218,0.059758,3,30,0.052840,VIX_chg_5d,60,60,0.163074,0.163074,192
8,VIX_level_lag40,0.054488,0.002225,0.000005,0.050400,0.058960,3,30,0.052262,VIX_level,40,40,0.186078,0.186078,212
9,TSM_ret_20d_lag40,0.051417,0.001871,0.000003,0.047055,0.054811,3,30,0.049546,TSM_ret_20d,40,40,-0.254788,0.254788,212

============================================================
6. valid_df 생성
============================================================
top feature 수: 10
lag 생성 후 valid_df shape: (1607, 22)
원본 base_feature 제거 후 valid_df shape: (1607, 12)
최종 컬럼 수: 12
target 생성 후 valid_df shape: (1607, 14)
최종 valid_df shape: (64, 14)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 10
train_df shape: (1393, 13)
X_train shape: (1393, 10)
train target 분포:
target_10d_up_2pct
0    734
1    659
Name: count, dtype: int64
target_10d_up_2pct
0    0.52692
1    0.47308
Name: proportion, dtype: float64
valid_df shape: (64, 14)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_10d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.843195     1
1  2026-02-24     419.160004                 0.0    0.711310     1
2  2026-02-25     426.160004                 0.0    0.355083     0
3  2026-02-26     412.010010                 0.0    0.258820     0
4  2026-02-27     406.369995                 0.0    0.256663     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.280887     0
60 2026-05-19     543.960022                 NaN    0.369729     0
61 2026-05-20     564.659973                 NaN    0.361733     0
62 2026-05-21     567.880005                 NaN    0.409575     1
63 2026-05-22     576.320007                 NaN    0.314289     0

[64 rows x 5 columns]

예측값 분포:
pred
1    32
0    32
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 54
예측 1 개수: 27
예측 1 중 실제 1 개수: 15
예측 1 기준 정확도 precision: 0.5555555555555556

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,10,0.02,1,10,10,hist_gradient_boosting,"{'max_iter': 500, 'learning_rate': 0.01, 'max_...",54,27,...,0.425926,0.555556,0.441176,0.491803,0.438235,0.892699,8,12,19,15

[I 2026-05-23 20:46:10,611] Trial 5 finished with value: 0.5555555555555556 and parameters: {'n_days': 10, 'threshold': 0.02, 'top_n': 10, 'pred_threshold': 0.4, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 500, 'hgb_learning_rate': 0.01, 'hgb_max_leaf_nodes': 31}. Best is trial 1 with value: 0.7954545454545454.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 7/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 10, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.01, 'max_depth': 5}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 6}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_10d_up_3pct
target_df shape: (1533, 31)
target 분포:
target_10d_up_3pct
0    907
1    626
Name: count, dtype: int64
lagged_df shape: (1393, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1431

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1425

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1433
TOP feature count: 20
['USDKRW_ret_20d_lag1', 'OIL_ret_20d_lag40', 'TNX_level_lag120', 'DXY_ret_20d_lag120', 'SMH_vol_20d_lag40', 'VIX_level_lag1', 'TNX_diff_20d_lag5', 'TSM_ret_20d_lag40', 'SMH_ma20_ratio_lag40', 'SMH_ma60_ratio_lag40', 'SMH_volume_ratio_20d_lag1', 'NVDA_ret_20d_lag40', 'SPY_ret_20d_lag40', 'VIX_chg_5d_lag60', 'VIX_chg_20d_lag40', 'GOLD_ret_20d_lag1', 'USDKRW_ret_5d_lag3', 'DXY_ret_5d_lag5', 'SOXX_ret_5d_lag40', 'TSM_ret_5d_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,USDKRW_ret_20d_lag1,0.126034,0.002997,8.980695e-06,0.119453,0.133261,3,30,0.123037,USDKRW_ret_20d,1,1,-0.408214,0.408214,251
1,OIL_ret_20d_lag40,0.096463,0.002678,7.170844e-06,0.091112,0.102565,3,30,0.093785,OIL_ret_20d,40,40,-0.318626,0.318626,212
2,TNX_level_lag120,0.080627,0.002211,4.888913e-06,0.074639,0.086368,3,30,0.078416,TNX_level,120,120,-0.195924,0.195924,132
3,DXY_ret_20d_lag120,0.073622,0.001373,1.884736e-06,0.070474,0.075453,3,30,0.072249,DXY_ret_20d,120,120,-0.293154,0.293154,132
4,SMH_vol_20d_lag40,0.063920,0.001438,2.066961e-06,0.061510,0.067246,3,30,0.062482,SMH_vol_20d,40,40,0.281937,0.281937,212
5,VIX_level_lag1,0.059403,0.001746,3.047977e-06,0.056041,0.063472,3,30,0.057657,VIX_level,1,1,0.240225,0.240225,251
6,TNX_diff_20d_lag5,0.059302,0.002218,4.918486e-06,0.054268,0.064710,3,30,0.057085,TNX_diff_20d,5,5,0.307873,0.307873,247
7,TSM_ret_20d_lag40,0.055242,0.001483,2.198098e-06,0.052429,0.058885,3,30,0.053759,TSM_ret_20d,40,40,-0.349006,0.349006,212
8,SMH_ma20_ratio_lag40,0.054793,0.001213,1.471149e-06,0.052111,0.057220,3,30,0.053580,SMH_ma20_ratio,40,40,-0.288530,0.288530,212
9,SMH_ma60_ratio_lag40,0.053386,0.001023,1.046921e-06,0.051840,0.055668,3,30,0.052363,SMH_ma60_ratio,40,40,-0.297396,0.297396,212
10,SMH_volume_ratio_20d_lag1,0.051650,0.002090,4.367474e-06,0.048032,0.055660,3,30,0.049560,SMH_volume_ratio_20d,1,1,0.186136,0.186136,251
11,NVDA_ret_20d_lag40,0.047124,0.001591,2.531745e-06,0.043689,0.049773,3,30,0.045533,NVDA_ret_20d,40,40,-0.192054,0.192054,212
12,SPY_ret_20d_lag40,0.049969,0.004929,2.429532e-05,0.042242,0.057221,3,30,0.045040,SPY_ret_20d,40,40,-0.270977,0.270977,212
13,VIX_chg_5d_lag60,0.043663,0.001981,3.925745e-06,0.039731,0.047597,3,30,0.041682,VIX_chg_5d,60,60,0.176557,0.176557,192
14,VIX_chg_20d_lag40,0.042420,0.001552,2.410066e-06,0.039666,0.045644,3,30,0.040867,VIX_chg_20d,40,40,0.240142,0.240142,212
15,GOLD_ret_20d_lag1,0.039796,0.000720,5.186415e-07,0.038508,0.041410,3,30,0.039076,GOLD_ret_20d,1,1,0.150955,0.150955,251
16,USDKRW_ret_5d_lag3,0.037802,0.001225,1.500943e-06,0.035512,0.039620,3,30,0.036577,USDKRW_ret_5d,3,3,-0.270483,0.270483,249
17,DXY_ret_5d_lag5,0.036078,0.000914,8.350636e-07,0.034211,0.037683,3,30,0.035164,DXY_ret_5d,5,5,-0.186237,0.186237,247
18,SOXX_ret_5d_lag40,0.034375,0.001310,1.716438e-06,0.032454,0.036978,3,30,0.033064,SOXX_ret_5d,40,40,-0.243564,0.243564,212
19,TSM_ret_5d_lag40,0.034537,0.001604,2.573093e-06,0.031413,0.037121,3,30,0.032933,TSM_ret_5d,40,40,-0.332453,0.332453,212

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1393, 23)
X_train shape: (1393, 20)
train target 분포:
target_10d_up_3pct
0    834
1    559
Name: count, dtype: int64
target_10d_up_3pct
0    0.598708
1    0.401292
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_10d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.312037     0
1  2026-02-24     419.160004                 0.0    0.287289     0
2  2026-02-25     426.160004                 0.0    0.318978     0
3  2026-02-26     412.010010                 0.0    0.236500     0
4  2026-02-27     406.369995                 0.0    0.433765     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.202915     0
60 2026-05-19     543.960022                 NaN    0.280569     0
61 2026-05-20     564.659973                 NaN    0.414758     0
62 2026-05-21     567.880005                 NaN    0.315915     0
63 2026-05-22     576.320007                 NaN    0.223260     0

[64 rows x 5 columns]

예측값 분포:
pred
0    61
1     3
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 54
예측 1 개수: 3
예측 1 중 실제 1 개수: 3
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,10,0.03,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.01, '...",54,3,...,0.481481,1.0,0.096774,0.176471,0.45582,0.821008,23,0,28,3

[I 2026-05-23 20:46:26,297] Trial 6 finished with value: 1.0 and parameters: {'n_days': 10, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.01, 'gb_max_depth': 5}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 8/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'logistic', 'model_params': {'C': 1.0, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 7}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.476654     0
1  2026-02-24     419.160004                 0.0    0.471490     0
2  2026-02-25     426.160004                 0.0    0.503152     0
3  2026-02-26     412.010010                 0.0    0.561370     0
4  2026-02-27     406.369995                 0.0    0.573927     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.452401     0
60 2026-05-19     543.960022                 NaN    0.504150     0
61 2026-05-20     564.659973                 NaN    0.565276     0
62 2026-05-21     567.880005                 NaN    0.585366     0
63 2026-05-22     576.320007                 NaN    0.566451     0

[64 rows x 5 columns]

예측값 분포:
pred
0    53
1    11
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 4
예측 1 중 실제 1 개수: 4
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,logistic,"{'C': 1.0, 'class_weight': 'balanced', 'max_it...",44,4,...,0.318182,1.0,0.117647,0.210526,0.3,0.770975,10,0,30,4

[I 2026-05-23 20:46:40,031] Trial 7 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'logistic', 'logistic_C': 1.0}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 9/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 5, 'threshold': 0.015, 'top_n': 50, 'pred_threshold': 0.35, 'model_name': 'random_forest', 'model_params': {'n_estimators': 500, 'max_depth': None, 'min_samples_leaf': 10, 'max_features': 0.5, 'class_weight': 'balanced'}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 8}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_5d_up_1pct
target_df shape: (1538, 31)
target 분포:
target_5d_up_1pct
0    853
1    685
Name: count, dtype: int64
lagged_df shape: (1398, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1642

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1654

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.165
TOP feature count: 27
['DXY_ret_20d_lag120', 'TNX_level_lag120', 'GOLD_ret_5d_lag120', 'USDKRW_ret_5d_lag40', 'USDKRW_ret_20d_lag1', 'VIX_level_lag40', 'GOLD_ret_20d_lag3', 'TSM_ret_20d_lag40', 'VIX_chg_20d_lag40', 'TNX_diff_5d_lag1', 'OIL_ret_20d_lag40', 'SMH_vol_20d_lag60', 'NVDA_ret_20d_lag60', 'NVDA_ret_5d_lag60', 'SMH_ma60_ratio_lag40', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag40', 'SPY_ret_20d_lag40', 'DXY_ret_5d_lag120', 'SPY_ret_5d_lag40', 'TSM_ret_5d_lag40', 'VIX_chg_5d_lag40', 'SOXX_ret_5d_lag40', 'OIL_ret_5d_lag40', 'SMH_ma5_ratio_lag40', 'SMH_volume_ratio_20d_lag10', 'SMH_ret_1d_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,DXY_ret_20d_lag120,0.104071,0.003598,1.294837e-05,0.098762,0.111431,3,30,0.100473,DXY_ret_20d,120,120,-0.183805,0.183805,132
1,TNX_level_lag120,0.079102,0.003349,1.121792e-05,0.073379,0.085953,3,30,0.075752,TNX_level,120,120,-0.183228,0.183228,132
2,GOLD_ret_5d_lag120,0.072470,0.002329,5.425619e-06,0.067662,0.076652,3,30,0.070141,GOLD_ret_5d,120,120,-0.213118,0.213118,132
3,USDKRW_ret_5d_lag40,0.063233,0.003598,1.294563e-05,0.058276,0.071108,3,30,0.059635,USDKRW_ret_5d,40,40,0.134320,0.134320,212
4,USDKRW_ret_20d_lag1,0.061270,0.002583,6.672587e-06,0.057380,0.067002,3,30,0.058687,USDKRW_ret_20d,1,1,-0.233704,0.233704,251
5,VIX_level_lag40,0.058514,0.001156,1.336009e-06,0.055890,0.061066,3,30,0.057358,VIX_level,40,40,0.180440,0.180440,212
6,GOLD_ret_20d_lag3,0.058364,0.002017,4.066719e-06,0.054216,0.061834,3,30,0.056348,GOLD_ret_20d,3,3,0.161376,0.161376,249
7,TSM_ret_20d_lag40,0.055110,0.001226,1.503739e-06,0.052496,0.057890,3,30,0.053884,TSM_ret_20d,40,40,-0.194079,0.194079,212
8,VIX_chg_20d_lag40,0.053873,0.000912,8.314653e-07,0.052220,0.056159,3,30,0.052961,VIX_chg_20d,40,40,0.161598,0.161598,212
9,TNX_diff_5d_lag1,0.054584,0.003111,9.675457e-06,0.049361,0.058411,3,30,0.051474,TNX_diff_5d,1,1,-0.183673,0.183673,251
10,OIL_ret_20d_lag40,0.051672,0.001291,1.665516e-06,0.048819,0.054398,3,30,0.050382,OIL_ret_20d,40,40,-0.191868,0.191868,212
11,SMH_vol_20d_lag60,0.051890,0.001533,2.348935e-06,0.049826,0.055686,3,30,0.050357,SMH_vol_20d,60,60,-0.172619,0.172619,192
12,NVDA_ret_20d_lag60,0.052186,0.002632,6.925425e-06,0.047887,0.057749,3,30,0.049554,NVDA_ret_20d,60,60,-0.123282,0.123282,192
13,NVDA_ret_5d_lag60,0.049602,0.002165,4.687399e-06,0.045953,0.053440,3,30,0.047437,NVDA_ret_5d,60,60,-0.206827,0.206827,192
14,SMH_ma60_ratio_lag40,0.050652,0.003261,1.063195e-05,0.045693,0.055555,3,30,0.047391,SMH_ma60_ratio,40,40,-0.163308,0.163308,212
15,TNX_diff_20d_lag5,0.048536,0.002515,6.326977e-06,0.045591,0.053011,3,30,0.046021,TNX_diff_20d,5,5,0.228074,0.228074,247
16,SMH_ma20_ratio_lag40,0.046795,0.000986,9.714768e-07,0.045205,0.048919,3,30,0.045809,SMH_ma20_ratio,40,40,-0.197290,0.197290,212
17,SPY_ret_20d_lag40,0.042290,0.001380,1.905652e-06,0.040303,0.045232,3,30,0.040910,SPY_ret_20d,40,40,-0.188896,0.188896,212
18,DXY_ret_5d_lag120,0.040919,0.000784,6.143003e-07,0.039557,0.042721,3,30,0.040136,DXY_ret_5d,120,120,0.156545,0.156545,132
19,SPY_ret_5d_lag40,0.041440,0.001637,2.680725e-06,0.038598,0.044893,3,30,0.039803,SPY_ret_5d,40,40,-0.286210,0.286210,212
20,TSM_ret_5d_lag40,0.039797,0.001508,2.275340e-06,0.037079,0.042213,3,30,0.038289,TSM_ret_5d,40,40,-0.254717,0.254717,212
21,VIX_chg_5d_lag40,0.038319,0.001692,2.862110e-06,0.035976,0.041786,3,30,0.036627,VIX_chg_5d,40,40,0.230314,0.230314,212
22,SOXX_ret_5d_lag40,0.036282,0.001188,1.410842e-06,0.034132,0.038742,3,30,0.035095,SOXX_ret_5d,40,40,-0.221961,0.221961,212
23,OIL_ret_5d_lag40,0.033347,0.000629,3.959301e-07,0.031919,0.034383,3,30,0.032717,OIL_ret_5d,40,40,-0.129317,0.129317,212
24,SMH_ma5_ratio_lag40,0.033046,0.000572,3.275566e-07,0.032001,0.034472,3,30,0.032474,SMH_ma5_ratio,40,40,-0.166325,0.166325,212
25,SMH_volume_ratio_20d_lag10,0.032792,0.001691,2.860054e-06,0.029670,0.036310,3,30,0.031101,SMH_volume_ratio_20d,10,10,0.183892,0.183892,242
26,SMH_ret_1d_lag40,0.027669,0.000796,6.340962e-07,0.025676,0.028958,3,30,0.026873,SMH_ret_1d,40,40,-0.090943,0.090943,212

============================================================
6. valid_df 생성
============================================================
top feature 수: 27
lag 생성 후 valid_df shape: (1607, 56)
원본 base_feature 제거 후 valid_df shape: (1607, 29)
최종 컬럼 수: 29
target 생성 후 valid_df shape: (1607, 31)
최종 valid_df shape: (64, 31)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 27
train_df shape: (1398, 30)
X_train shape: (1398, 27)
train target 분포:
target_5d_up_1pct
0    783
1    615
Name: count, dtype: int64
target_5d_up_1pct
0    0.560086
1    0.439914
Name: proportion, dtype: float64
valid_df shape: (64, 31)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: random_forest
valid_df 예측 완료

         Date  SMH_adj_close  target_5d_up_1pct  pred_proba  pred
0  2026-02-23     412.880005                0.0    0.378321     1
1  2026-02-24     419.160004                0.0    0.258427     0
2  2026-02-25     426.160004                0.0    0.314754     0
3  2026-02-26     412.010010                0.0    0.271019     0
4  2026-02-27     406.369995                0.0    0.342685     0
..        ...            ...                ...         ...   ...
59 2026-05-18     546.159973                NaN    0.545203     1
60 2026-05-19     543.960022                NaN    0.415557     1
61 2026-05-20     564.659973                NaN    0.473180     1
62 2026-05-21     567.880005                NaN    0.429551     1
63 2026-05-22     576.320007                NaN    0.495820     1

[64 rows x 5 columns]

예측값 분포:
pred
1    53
0    11
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 59
예측 1 개수: 48
예측 1 중 실제 1 개수: 27
예측 1 기준 정확도 precision: 0.5625

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,5,0.015,1,50,27,random_forest,"{'n_estimators': 500, 'max_depth': None, 'min_...",59,48,...,0.559322,0.5625,0.84375,0.675,0.534722,0.728997,6,21,5,27

[I 2026-05-23 20:46:54,968] Trial 8 finished with value: 0.5625 and parameters: {'n_days': 5, 'threshold': 0.015, 'top_n': 50, 'pred_threshold': 0.35, 'model_name': 'random_forest', 'rf_n_estimators': 500, 'rf_max_depth': None, 'rf_min_samples_leaf': 10, 'rf_max_features': 0.5}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 10/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 3, 'threshold': 0.01, 'top_n': 30, 'pred_threshold': 0.45, 'model_name': 'logistic', 'model_params': {'C': 0.01, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 9}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_3d_up_1pct
target_df shape: (1540, 31)
target 분포:
target_3d_up_1pct
0    858
1    682
Name: count, dtype: int64
lagged_df shape: (1361, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1775

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.178

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1777
TOP feature count: 27
['DXY_ret_20d_lag120', 'SOXX_ret_5d_lag10', 'TNX_diff_5d_lag20', 'NVDA_ret_5d_lag1', 'USDKRW_ret_20d_lag1', 'SMH_vol_20d_lag60', 'SMH_ma5_ratio_lag10', 'NVDA_ret_20d_lag120', 'VIX_chg_20d_lag120', 'SPY_ret_20d_lag120', 'TSM_ret_5d_lag5', 'OIL_ret_20d_lag60', 'GOLD_ret_20d_lag1', 'OIL_ret_5d_lag20', 'SMH_ma60_ratio_lag120', 'TNX_level_lag1', 'TNX_diff_20d_lag5', 'TSM_ret_20d_lag120', 'VIX_chg_5d_lag40', 'VIX_level_lag40', 'SPY_ret_5d_lag40', 'SMH_ma20_ratio_lag120', 'DXY_ret_5d_lag10', 'USDKRW_ret_5d_lag60', 'GOLD_ret_5d_lag40', 'SMH_ret_1d_lag10', 'SMH_volume_ratio_20d_lag60']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,DXY_ret_20d_lag120,0.099679,0.002438,5.943633e-06,0.094715,0.104590,3,30,0.097242,DXY_ret_20d,120,120,-0.202539,0.202539,131
1,SOXX_ret_5d_lag10,0.077610,0.005324,2.834364e-05,0.069281,0.086203,3,30,0.072286,SOXX_ret_5d,10,10,-0.138531,0.138531,241
2,TNX_diff_5d_lag20,0.057548,0.002587,6.691529e-06,0.052693,0.061019,3,30,0.054961,TNX_diff_5d,20,20,0.185910,0.185910,231
3,NVDA_ret_5d_lag1,0.056908,0.002596,6.739910e-06,0.052460,0.061254,3,30,0.054312,NVDA_ret_5d,1,1,-0.153357,0.153357,250
4,USDKRW_ret_20d_lag1,0.057024,0.002773,7.687779e-06,0.052551,0.060200,3,30,0.054251,USDKRW_ret_20d,1,1,-0.156555,0.156555,250
5,SMH_vol_20d_lag60,0.055205,0.001767,3.122677e-06,0.051758,0.057493,3,30,0.053438,SMH_vol_20d,60,60,-0.119649,0.119649,191
6,SMH_ma5_ratio_lag10,0.054981,0.001559,2.429523e-06,0.052625,0.059181,3,30,0.053423,SMH_ma5_ratio,10,10,-0.198808,0.198808,241
7,NVDA_ret_20d_lag120,0.054383,0.001651,2.726769e-06,0.051834,0.057944,3,30,0.052732,NVDA_ret_20d,120,120,-0.151425,0.151425,131
8,VIX_chg_20d_lag120,0.049870,0.000823,6.780593e-07,0.047655,0.051175,3,30,0.049046,VIX_chg_20d,120,120,0.129767,0.129767,131
9,SPY_ret_20d_lag120,0.050411,0.001498,2.245267e-06,0.047224,0.053040,3,30,0.048913,SPY_ret_20d,120,120,-0.188158,0.188158,131
10,TSM_ret_5d_lag5,0.049761,0.001009,1.017911e-06,0.047816,0.051717,3,30,0.048752,TSM_ret_5d,5,5,0.232924,0.232924,246
11,OIL_ret_20d_lag60,0.051218,0.003152,9.934761e-06,0.046043,0.057292,3,30,0.048066,OIL_ret_20d,60,60,0.207999,0.207999,191
12,GOLD_ret_20d_lag1,0.049863,0.002615,6.840338e-06,0.046775,0.054317,3,30,0.047248,GOLD_ret_20d,1,1,0.109612,0.109612,250
13,OIL_ret_5d_lag20,0.048873,0.002054,4.220476e-06,0.045117,0.052153,3,30,0.046819,OIL_ret_5d,20,20,-0.145432,0.145432,231
14,SMH_ma60_ratio_lag120,0.047406,0.001284,1.648376e-06,0.044350,0.049324,3,30,0.046122,SMH_ma60_ratio,120,120,-0.088680,0.088680,131
15,TNX_level_lag1,0.046193,0.001356,1.837639e-06,0.043787,0.048247,3,30,0.044837,TNX_level,1,1,-0.173322,0.173322,250
16,TNX_diff_20d_lag5,0.046170,0.001424,2.026992e-06,0.043856,0.048976,3,30,0.044746,TNX_diff_20d,5,5,0.153462,0.153462,246
17,TSM_ret_20d_lag120,0.045639,0.000973,9.472751e-07,0.043245,0.047114,3,30,0.044666,TSM_ret_20d,120,120,-0.149607,0.149607,131
18,VIX_chg_5d_lag40,0.045701,0.001570,2.464805e-06,0.043163,0.048905,3,30,0.044131,VIX_chg_5d,40,40,0.164356,0.164356,211
19,VIX_level_lag40,0.044222,0.001178,1.387722e-06,0.041839,0.046441,3,30,0.043044,VIX_level,40,40,0.108848,0.108848,211
20,SPY_ret_5d_lag40,0.042658,0.001605,2.575774e-06,0.040204,0.046719,3,30,0.041053,SPY_ret_5d,40,40,-0.196471,0.196471,211
21,SMH_ma20_ratio_lag120,0.041076,0.000729,5.318602e-07,0.039626,0.042816,3,30,0.040346,SMH_ma20_ratio,120,120,-0.161674,0.161674,131
22,DXY_ret_5d_lag10,0.041448,0.001183,1.398532e-06,0.039747,0.043669,3,30,0.040265,DXY_ret_5d,10,10,-0.106461,0.106461,241
23,USDKRW_ret_5d_lag60,0.040413,0.001389,1.928093e-06,0.037287,0.042835,3,30,0.039024,USDKRW_ret_5d,60,60,0.171187,0.171187,191
24,GOLD_ret_5d_lag40,0.036305,0.001062,1.126799e-06,0.034741,0.038311,3,30,0.035243,GOLD_ret_5d,40,40,-0.142592,0.142592,211
25,SMH_ret_1d_lag10,0.036388,0.001929,3.719899e-06,0.033193,0.040295,3,30,0.034459,SMH_ret_1d,10,10,-0.153831,0.153831,241
26,SMH_volume_ratio_20d_lag60,0.034284,0.000922,8.495581e-07,0.032439,0.036607,3,30,0.033362,SMH_volume_ratio_20d,60,60,0.218922,0.218922,191

============================================================
6. valid_df 생성
============================================================
top feature 수: 27
lag 생성 후 valid_df shape: (1607, 56)
원본 base_feature 제거 후 valid_df shape: (1607, 29)
최종 컬럼 수: 29
target 생성 후 valid_df shape: (1607, 31)
최종 valid_df shape: (64, 31)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 27
train_df shape: (1361, 30)
X_train shape: (1361, 27)
train target 분포:
target_3d_up_1pct
0    758
1    603
Name: count, dtype: int64
target_3d_up_1pct
0    0.556943
1    0.443057
Name: proportion, dtype: float64
valid_df shape: (64, 31)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_3d_up_1pct  pred_proba  pred
0  2026-02-23     412.880005                0.0    0.529899     1
1  2026-02-24     419.160004                0.0    0.483789     1
2  2026-02-25     426.160004                0.0    0.428504     0
3  2026-02-26     412.010010                0.0    0.399659     0
4  2026-02-27     406.369995                0.0    0.433945     0
..        ...            ...                ...         ...   ...
59 2026-05-18     546.159973                1.0    0.529476     1
60 2026-05-19     543.960022                1.0    0.478940     1
61 2026-05-20     564.659973                NaN    0.463456     1
62 2026-05-21     567.880005                NaN    0.483171     1
63 2026-05-22     576.320007                NaN    0.468048     1

[64 rows x 5 columns]

예측값 분포:
pred
1    45
0    19
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 61
예측 1 개수: 42
예측 1 중 실제 1 개수: 22
예측 1 기준 정확도 precision: 0.5238095238095238

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,3,0.01,1,30,27,logistic,"{'C': 0.01, 'class_weight': 'balanced', 'max_i...",61,42,...,0.459016,0.52381,0.628571,0.571429,0.431868,0.730809,6,20,13,22

[I 2026-05-23 20:47:09,487] Trial 9 finished with value: 0.5238095238095238 and parameters: {'n_days': 3, 'threshold': 0.01, 'top_n': 30, 'pred_threshold': 0.45, 'model_name': 'logistic', 'logistic_C': 0.01}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 11/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 10, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.8, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.01, 'max_depth': 5}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 10}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_10d_up_3pct
target_df shape: (1533, 31)
target 분포:
target_10d_up_3pct
0    907
1    626
Name: count, dtype: int64
lagged_df shape: (1393, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1431

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1425

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1433
TOP feature count: 20
['USDKRW_ret_20d_lag1', 'OIL_ret_20d_lag40', 'TNX_level_lag120', 'DXY_ret_20d_lag120', 'SMH_vol_20d_lag40', 'VIX_level_lag1', 'TNX_diff_20d_lag5', 'TSM_ret_20d_lag40', 'SMH_ma20_ratio_lag40', 'SMH_ma60_ratio_lag40', 'SMH_volume_ratio_20d_lag1', 'NVDA_ret_20d_lag40', 'SPY_ret_20d_lag40', 'VIX_chg_5d_lag60', 'VIX_chg_20d_lag40', 'GOLD_ret_20d_lag1', 'USDKRW_ret_5d_lag3', 'DXY_ret_5d_lag5', 'SOXX_ret_5d_lag40', 'TSM_ret_5d_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,USDKRW_ret_20d_lag1,0.126034,0.002997,8.980695e-06,0.119453,0.133261,3,30,0.123037,USDKRW_ret_20d,1,1,-0.408214,0.408214,251
1,OIL_ret_20d_lag40,0.096463,0.002678,7.170844e-06,0.091112,0.102565,3,30,0.093785,OIL_ret_20d,40,40,-0.318626,0.318626,212
2,TNX_level_lag120,0.080627,0.002211,4.888913e-06,0.074639,0.086368,3,30,0.078416,TNX_level,120,120,-0.195924,0.195924,132
3,DXY_ret_20d_lag120,0.073622,0.001373,1.884736e-06,0.070474,0.075453,3,30,0.072249,DXY_ret_20d,120,120,-0.293154,0.293154,132
4,SMH_vol_20d_lag40,0.063920,0.001438,2.066961e-06,0.061510,0.067246,3,30,0.062482,SMH_vol_20d,40,40,0.281937,0.281937,212
5,VIX_level_lag1,0.059403,0.001746,3.047977e-06,0.056041,0.063472,3,30,0.057657,VIX_level,1,1,0.240225,0.240225,251
6,TNX_diff_20d_lag5,0.059302,0.002218,4.918486e-06,0.054268,0.064710,3,30,0.057085,TNX_diff_20d,5,5,0.307873,0.307873,247
7,TSM_ret_20d_lag40,0.055242,0.001483,2.198098e-06,0.052429,0.058885,3,30,0.053759,TSM_ret_20d,40,40,-0.349006,0.349006,212
8,SMH_ma20_ratio_lag40,0.054793,0.001213,1.471149e-06,0.052111,0.057220,3,30,0.053580,SMH_ma20_ratio,40,40,-0.288530,0.288530,212
9,SMH_ma60_ratio_lag40,0.053386,0.001023,1.046921e-06,0.051840,0.055668,3,30,0.052363,SMH_ma60_ratio,40,40,-0.297396,0.297396,212
10,SMH_volume_ratio_20d_lag1,0.051650,0.002090,4.367474e-06,0.048032,0.055660,3,30,0.049560,SMH_volume_ratio_20d,1,1,0.186136,0.186136,251
11,NVDA_ret_20d_lag40,0.047124,0.001591,2.531745e-06,0.043689,0.049773,3,30,0.045533,NVDA_ret_20d,40,40,-0.192054,0.192054,212
12,SPY_ret_20d_lag40,0.049969,0.004929,2.429532e-05,0.042242,0.057221,3,30,0.045040,SPY_ret_20d,40,40,-0.270977,0.270977,212
13,VIX_chg_5d_lag60,0.043663,0.001981,3.925745e-06,0.039731,0.047597,3,30,0.041682,VIX_chg_5d,60,60,0.176557,0.176557,192
14,VIX_chg_20d_lag40,0.042420,0.001552,2.410066e-06,0.039666,0.045644,3,30,0.040867,VIX_chg_20d,40,40,0.240142,0.240142,212
15,GOLD_ret_20d_lag1,0.039796,0.000720,5.186415e-07,0.038508,0.041410,3,30,0.039076,GOLD_ret_20d,1,1,0.150955,0.150955,251
16,USDKRW_ret_5d_lag3,0.037802,0.001225,1.500943e-06,0.035512,0.039620,3,30,0.036577,USDKRW_ret_5d,3,3,-0.270483,0.270483,249
17,DXY_ret_5d_lag5,0.036078,0.000914,8.350636e-07,0.034211,0.037683,3,30,0.035164,DXY_ret_5d,5,5,-0.186237,0.186237,247
18,SOXX_ret_5d_lag40,0.034375,0.001310,1.716438e-06,0.032454,0.036978,3,30,0.033064,SOXX_ret_5d,40,40,-0.243564,0.243564,212
19,TSM_ret_5d_lag40,0.034537,0.001604,2.573093e-06,0.031413,0.037121,3,30,0.032933,TSM_ret_5d,40,40,-0.332453,0.332453,212

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1393, 23)
X_train shape: (1393, 20)
train target 분포:
target_10d_up_3pct
0    834
1    559
Name: count, dtype: int64
target_10d_up_3pct
0    0.598708
1    0.401292
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_10d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.312037     0
1  2026-02-24     419.160004                 0.0    0.287289     0
2  2026-02-25     426.160004                 0.0    0.318978     0
3  2026-02-26     412.010010                 0.0    0.236500     0
4  2026-02-27     406.369995                 0.0    0.433765     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.202915     0
60 2026-05-19     543.960022                 NaN    0.280569     0
61 2026-05-20     564.659973                 NaN    0.414758     0
62 2026-05-21     567.880005                 NaN    0.315915     0
63 2026-05-22     576.320007                 NaN    0.223260     0

[64 rows x 5 columns]

예측값 분포:
pred
0    64
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 54
예측 1 개수: 0
예측 1 중 실제 1 개수: 0
예측 1 기준 정확도 precision: nan

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,10,0.03,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.01, '...",54,0,...,0.425926,0.0,0.0,0.0,0.45582,0.821008,23,0,31,0

[I 2026-05-23 20:47:25,661] Trial 10 finished with value: 0.0 and parameters: {'n_days': 10, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.8, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.01, 'gb_max_depth': 5}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 12/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 11}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.555357     0
1  2026-02-24     419.160004                 0.0    0.646397     0
2  2026-02-25     426.160004                 0.0    0.597912     0
3  2026-02-26     412.010010                 0.0    0.457527     0
4  2026-02-27     406.369995                 0.0    0.545480     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.619136     0
60 2026-05-19     543.960022                 NaN    0.842201     1
61 2026-05-20     564.659973                 NaN    0.492613     0
62 2026-05-21     567.880005                 NaN    0.405804     0
63 2026-05-22     576.320007                 NaN    0.501921     0

[64 rows x 5 columns]

예측값 분포:
pred
0    44
1    20
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 6
예측 1 중 실제 1 개수: 6
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.03, '...",44,6,...,0.363636,1.0,0.176471,0.3,0.370588,0.77784,10,0,28,6

[I 2026-05-23 20:47:41,155] Trial 11 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 13/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 12}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 20
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.298517     0
1  2026-02-24     419.160004                 0.0    0.339273     0
2  2026-02-25     426.160004                 0.0    0.612624     0
3  2026-02-26     412.010010                 0.0    0.400821     0
4  2026-02-27     406.369995                 0.0    0.632620     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.808243     1
60 2026-05-19     543.960022                 NaN    0.869996     1
61 2026-05-20     564.659973                 NaN    0.490125     0
62 2026-05-21     567.880005                 NaN    0.353365     0
63 2026-05-22     576.320007                 NaN    0.432212     0

[64 rows x 5 columns]

예측값 분포:
pred
0    41
1    23
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 8
예측 1 중 실제 1 개수: 8
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,20,20,hist_gradient_boosting,"{'max_iter': 300, 'learning_rate': 0.03, 'max_...",44,8,...,0.409091,1.0,0.235294,0.380952,0.55,0.894799,10,0,26,8

[I 2026-05-23 20:47:56,652] Trial 12 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 14/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 10, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.55, 'model_name': 'logistic', 'model_params': {'C': 1.0, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 13}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_10d_up_3pct
target_df shape: (1533, 31)
target 분포:
target_10d_up_3pct
0    907
1    626
Name: count, dtype: int64
lagged_df shape: (1393, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1431

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1425

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1433
TOP feature count: 20
['USDKRW_ret_20d_lag1', 'OIL_ret_20d_lag40', 'TNX_level_lag120', 'DXY_ret_20d_lag120', 'SMH_vol_20d_lag40', 'VIX_level_lag1', 'TNX_diff_20d_lag5', 'TSM_ret_20d_lag40', 'SMH_ma20_ratio_lag40', 'SMH_ma60_ratio_lag40', 'SMH_volume_ratio_20d_lag1', 'NVDA_ret_20d_lag40', 'SPY_ret_20d_lag40', 'VIX_chg_5d_lag60', 'VIX_chg_20d_lag40', 'GOLD_ret_20d_lag1', 'USDKRW_ret_5d_lag3', 'DXY_ret_5d_lag5', 'SOXX_ret_5d_lag40', 'TSM_ret_5d_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,USDKRW_ret_20d_lag1,0.126034,0.002997,8.980695e-06,0.119453,0.133261,3,30,0.123037,USDKRW_ret_20d,1,1,-0.408214,0.408214,251
1,OIL_ret_20d_lag40,0.096463,0.002678,7.170844e-06,0.091112,0.102565,3,30,0.093785,OIL_ret_20d,40,40,-0.318626,0.318626,212
2,TNX_level_lag120,0.080627,0.002211,4.888913e-06,0.074639,0.086368,3,30,0.078416,TNX_level,120,120,-0.195924,0.195924,132
3,DXY_ret_20d_lag120,0.073622,0.001373,1.884736e-06,0.070474,0.075453,3,30,0.072249,DXY_ret_20d,120,120,-0.293154,0.293154,132
4,SMH_vol_20d_lag40,0.063920,0.001438,2.066961e-06,0.061510,0.067246,3,30,0.062482,SMH_vol_20d,40,40,0.281937,0.281937,212
5,VIX_level_lag1,0.059403,0.001746,3.047977e-06,0.056041,0.063472,3,30,0.057657,VIX_level,1,1,0.240225,0.240225,251
6,TNX_diff_20d_lag5,0.059302,0.002218,4.918486e-06,0.054268,0.064710,3,30,0.057085,TNX_diff_20d,5,5,0.307873,0.307873,247
7,TSM_ret_20d_lag40,0.055242,0.001483,2.198098e-06,0.052429,0.058885,3,30,0.053759,TSM_ret_20d,40,40,-0.349006,0.349006,212
8,SMH_ma20_ratio_lag40,0.054793,0.001213,1.471149e-06,0.052111,0.057220,3,30,0.053580,SMH_ma20_ratio,40,40,-0.288530,0.288530,212
9,SMH_ma60_ratio_lag40,0.053386,0.001023,1.046921e-06,0.051840,0.055668,3,30,0.052363,SMH_ma60_ratio,40,40,-0.297396,0.297396,212
10,SMH_volume_ratio_20d_lag1,0.051650,0.002090,4.367474e-06,0.048032,0.055660,3,30,0.049560,SMH_volume_ratio_20d,1,1,0.186136,0.186136,251
11,NVDA_ret_20d_lag40,0.047124,0.001591,2.531745e-06,0.043689,0.049773,3,30,0.045533,NVDA_ret_20d,40,40,-0.192054,0.192054,212
12,SPY_ret_20d_lag40,0.049969,0.004929,2.429532e-05,0.042242,0.057221,3,30,0.045040,SPY_ret_20d,40,40,-0.270977,0.270977,212
13,VIX_chg_5d_lag60,0.043663,0.001981,3.925745e-06,0.039731,0.047597,3,30,0.041682,VIX_chg_5d,60,60,0.176557,0.176557,192
14,VIX_chg_20d_lag40,0.042420,0.001552,2.410066e-06,0.039666,0.045644,3,30,0.040867,VIX_chg_20d,40,40,0.240142,0.240142,212
15,GOLD_ret_20d_lag1,0.039796,0.000720,5.186415e-07,0.038508,0.041410,3,30,0.039076,GOLD_ret_20d,1,1,0.150955,0.150955,251
16,USDKRW_ret_5d_lag3,0.037802,0.001225,1.500943e-06,0.035512,0.039620,3,30,0.036577,USDKRW_ret_5d,3,3,-0.270483,0.270483,249
17,DXY_ret_5d_lag5,0.036078,0.000914,8.350636e-07,0.034211,0.037683,3,30,0.035164,DXY_ret_5d,5,5,-0.186237,0.186237,247
18,SOXX_ret_5d_lag40,0.034375,0.001310,1.716438e-06,0.032454,0.036978,3,30,0.033064,SOXX_ret_5d,40,40,-0.243564,0.243564,212
19,TSM_ret_5d_lag40,0.034537,0.001604,2.573093e-06,0.031413,0.037121,3,30,0.032933,TSM_ret_5d,40,40,-0.332453,0.332453,212

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1393, 23)
X_train shape: (1393, 20)
train target 분포:
target_10d_up_3pct
0    834
1    559
Name: count, dtype: int64
target_10d_up_3pct
0    0.598708
1    0.401292
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_10d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.532595     0
1  2026-02-24     419.160004                 0.0    0.518504     0
2  2026-02-25     426.160004                 0.0    0.564896     1
3  2026-02-26     412.010010                 0.0    0.487281     0
4  2026-02-27     406.369995                 0.0    0.652156     1
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.557982     1
60 2026-05-19     543.960022                 NaN    0.584448     1
61 2026-05-20     564.659973                 NaN    0.580750     1
62 2026-05-21     567.880005                 NaN    0.616328     1
63 2026-05-22     576.320007                 NaN    0.507909     0

[64 rows x 5 columns]

예측값 분포:
pred
1    50
0    14
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 54
예측 1 개수: 43
예측 1 중 실제 1 개수: 25
예측 1 기준 정확도 precision: 0.5813953488372093

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,10,0.03,1,20,20,logistic,"{'C': 1.0, 'class_weight': 'balanced', 'max_it...",54,43,...,0.555556,0.581395,0.806452,0.675676,0.532959,0.702805,5,18,6,25

[I 2026-05-23 20:48:11,026] Trial 13 finished with value: 0.5813953488372093 and parameters: {'n_days': 10, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.55, 'model_name': 'logistic', 'logistic_C': 1.0}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 15/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 50, 'pred_threshold': 0.75, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 500, 'learning_rate': 0.01, 'max_depth': 2}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 14}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 27
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1', 'NVDA_ret_5d_lag60', 'SPY_ret_5d_lag120', 'SOXX_ret_5d_lag120', 'USDKRW_ret_5d_lag40', 'SMH_ma5_ratio_lag60', 'SMH_volume_ratio_20d_lag120', 'SMH_ret_1d_lag60']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251
20,NVDA_ret_5d_lag60,0.026639,0.001112,1.237156e-06,0.024575,0.028571,3,30,0.025526,NVDA_ret_5d,60,60,-0.251682,0.251682,192
21,SPY_ret_5d_lag120,0.025915,0.000723,5.228773e-07,0.024417,0.027251,3,30,0.025192,SPY_ret_5d,120,120,-0.252525,0.252525,132
22,SOXX_ret_5d_lag120,0.025491,0.000480,2.300800e-07,0.024445,0.026427,3,30,0.025011,SOXX_ret_5d,120,120,-0.254602,0.254602,132
23,USDKRW_ret_5d_lag40,0.025065,0.000769,5.909936e-07,0.023745,0.026481,3,30,0.024296,USDKRW_ret_5d,40,40,0.146047,0.146047,212
24,SMH_ma5_ratio_lag60,0.021075,0.000702,4.932835e-07,0.019899,0.022518,3,30,0.020372,SMH_ma5_ratio,60,60,-0.238638,0.238638,192
25,SMH_volume_ratio_20d_lag120,0.020579,0.001005,1.009657e-06,0.018787,0.022134,3,30,0.019574,SMH_volume_ratio_20d,120,120,0.263883,0.263883,132
26,SMH_ret_1d_lag60,0.014771,0.000621,3.856972e-07,0.013554,0.015965,3,30,0.014150,SMH_ret_1d,60,60,-0.167087,0.167087,192

============================================================
6. valid_df 생성
============================================================
top feature 수: 27
lag 생성 후 valid_df shape: (1607, 56)
원본 base_feature 제거 후 valid_df shape: (1607, 29)
최종 컬럼 수: 29
target 생성 후 valid_df shape: (1607, 31)
최종 valid_df shape: (64, 31)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 27
train_df shape: (1383, 30)
X_train shape: (1383, 27)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 31)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.601443     0
1  2026-02-24     419.160004                 0.0    0.606306     0
2  2026-02-25     426.160004                 0.0    0.596364     0
3  2026-02-26     412.010010                 0.0    0.595444     0
4  2026-02-27     406.369995                 0.0    0.583789     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.412694     0
60 2026-05-19     543.960022                 NaN    0.426002     0
61 2026-05-20     564.659973                 NaN    0.272825     0
62 2026-05-21     567.880005                 NaN    0.375889     0
63 2026-05-22     576.320007                 NaN    0.387884     0

[64 rows x 5 columns]

예측값 분포:
pred
0    64
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 0
예측 1 중 실제 1 개수: 0
예측 1 기준 정확도 precision: nan

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,50,27,gradient_boosting,"{'n_estimators': 500, 'learning_rate': 0.01, '...",44,0,...,0.227273,0.0,0.0,0.0,0.276471,0.6749,10,0,34,0

[I 2026-05-23 20:48:27,074] Trial 14 finished with value: 0.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 50, 'pred_threshold': 0.75, 'model_name': 'gradient_boosting', 'gb_n_estimators': 500, 'gb_learning_rate': 0.01, 'gb_max_depth': 2}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 16/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 10, 'threshold': 0.015, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'logistic', 'model_params': {'C': 10.0, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 15}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_10d_up_1pct
target_df shape: (1533, 31)
target 분포:
target_10d_up_1pct
1    789
0    744
Name: count, dtype: int64
lagged_df shape: (1393, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1435

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.143

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1436
TOP feature count: 20
['USDKRW_ret_20d_lag3', 'TNX_level_lag120', 'DXY_ret_20d_lag120', 'OIL_ret_20d_lag40', 'SMH_vol_20d_lag40', 'SMH_ma60_ratio_lag40', 'SMH_ma20_ratio_lag40', 'TNX_diff_20d_lag5', 'TSM_ret_20d_lag40', 'NVDA_ret_20d_lag120', 'VIX_chg_20d_lag120', 'VIX_level_lag40', 'SPY_ret_20d_lag120', 'GOLD_ret_20d_lag120', 'VIX_chg_5d_lag60', 'USDKRW_ret_5d_lag120', 'TSM_ret_5d_lag40', 'SMH_volume_ratio_20d_lag5', 'NVDA_ret_5d_lag60', 'SOXX_ret_5d_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,USDKRW_ret_20d_lag3,0.120179,0.003203,1.025687e-05,0.114064,0.127153,3,30,0.116976,USDKRW_ret_20d,3,3,-0.357632,0.357632,249
1,TNX_level_lag120,0.098635,0.002875,8.264090e-06,0.089594,0.103376,3,30,0.095760,TNX_level,120,120,-0.209417,0.209417,132
2,DXY_ret_20d_lag120,0.089309,0.002229,4.967756e-06,0.083745,0.092958,3,30,0.087080,DXY_ret_20d,120,120,-0.244463,0.244463,132
3,OIL_ret_20d_lag40,0.069472,0.001444,2.086402e-06,0.066390,0.072341,3,30,0.068028,OIL_ret_20d,40,40,-0.261638,0.261638,212
4,SMH_vol_20d_lag40,0.068675,0.001826,3.334384e-06,0.065220,0.072490,3,30,0.066849,SMH_vol_20d,40,40,0.258244,0.258244,212
5,SMH_ma60_ratio_lag40,0.066721,0.001533,2.351514e-06,0.063232,0.069945,3,30,0.065187,SMH_ma60_ratio,40,40,-0.236194,0.236194,212
6,SMH_ma20_ratio_lag40,0.057550,0.001558,2.426530e-06,0.053863,0.060871,3,30,0.055992,SMH_ma20_ratio,40,40,-0.241800,0.241800,212
7,TNX_diff_20d_lag5,0.055415,0.001547,2.392637e-06,0.052586,0.058614,3,30,0.053869,TNX_diff_20d,5,5,0.323838,0.323838,247
8,TSM_ret_20d_lag40,0.054409,0.001754,3.076881e-06,0.050440,0.058271,3,30,0.052655,TSM_ret_20d,40,40,-0.276363,0.276363,212
9,NVDA_ret_20d_lag120,0.054923,0.002644,6.989798e-06,0.049354,0.059768,3,30,0.052279,NVDA_ret_20d,120,120,-0.174684,0.174684,132
10,VIX_chg_20d_lag120,0.052718,0.001795,3.222371e-06,0.050121,0.057159,3,30,0.050923,VIX_chg_20d,120,120,0.179828,0.179828,132
11,VIX_level_lag40,0.050085,0.001329,1.765036e-06,0.047345,0.052508,3,30,0.048756,VIX_level,40,40,0.190705,0.190705,212
12,SPY_ret_20d_lag120,0.048621,0.000906,8.215688e-07,0.046890,0.050990,3,30,0.047715,SPY_ret_20d,120,120,-0.230254,0.230254,132
13,GOLD_ret_20d_lag120,0.045884,0.002215,4.904031e-06,0.041327,0.048565,3,30,0.043669,GOLD_ret_20d,120,120,-0.137286,0.137286,132
14,VIX_chg_5d_lag60,0.044085,0.001796,3.227083e-06,0.041035,0.047028,3,30,0.042289,VIX_chg_5d,60,60,0.141418,0.141418,192
15,USDKRW_ret_5d_lag120,0.044194,0.002562,6.566231e-06,0.040713,0.049551,3,30,0.041632,USDKRW_ret_5d,120,120,0.211443,0.211443,132
16,TSM_ret_5d_lag40,0.039475,0.001123,1.262164e-06,0.037073,0.042047,3,30,0.038352,TSM_ret_5d,40,40,-0.314300,0.314300,212
17,SMH_volume_ratio_20d_lag5,0.036161,0.001115,1.243013e-06,0.033575,0.038225,3,30,0.035046,SMH_volume_ratio_20d,5,5,0.179281,0.179281,247
18,NVDA_ret_5d_lag60,0.036037,0.001161,1.349002e-06,0.034426,0.039001,3,30,0.034876,NVDA_ret_5d,60,60,-0.223746,0.223746,192
19,SOXX_ret_5d_lag40,0.034374,0.001140,1.299101e-06,0.032316,0.037244,3,30,0.033234,SOXX_ret_5d,40,40,-0.229707,0.229707,212

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1393, 23)
X_train shape: (1393, 20)
train target 분포:
target_10d_up_1pct
1    706
0    687
Name: count, dtype: int64
target_10d_up_1pct
1    0.50682
0    0.49318
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_10d_up_1pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.573779     0
1  2026-02-24     419.160004                 0.0    0.581092     0
2  2026-02-25     426.160004                 0.0    0.532162     0
3  2026-02-26     412.010010                 0.0    0.452510     0
4  2026-02-27     406.369995                 0.0    0.420171     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.578029     0
60 2026-05-19     543.960022                 NaN    0.642138     1
61 2026-05-20     564.659973                 NaN    0.551652     0
62 2026-05-21     567.880005                 NaN    0.593671     0
63 2026-05-22     576.320007                 NaN    0.572247     0

[64 rows x 5 columns]

예측값 분포:
pred
0    56
1     8
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 54
예측 1 개수: 4
예측 1 중 실제 1 개수: 3
예측 1 기준 정확도 precision: 0.75

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,10,0.015,1,20,20,logistic,"{'C': 10.0, 'class_weight': 'balanced', 'max_i...",54,4,...,0.388889,0.75,0.085714,0.153846,0.437594,0.749319,18,1,32,3

[I 2026-05-23 20:48:41,782] Trial 15 finished with value: 0.75 and parameters: {'n_days': 10, 'threshold': 0.015, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'logistic', 'logistic_C': 10.0}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 17/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.5, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 4}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 16}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 20
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.405828     0
1  2026-02-24     419.160004                 0.0    0.582132     1
2  2026-02-25     426.160004                 0.0    0.374571     0
3  2026-02-26     412.010010                 0.0    0.394180     0
4  2026-02-27     406.369995                 0.0    0.632008     1
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.580402     1
60 2026-05-19     543.960022                 NaN    0.537228     1
61 2026-05-20     564.659973                 NaN    0.342186     0
62 2026-05-21     567.880005                 NaN    0.528416     1
63 2026-05-22     576.320007                 NaN    0.576779     1

[64 rows x 5 columns]

예측값 분포:
pred
1    35
0    29
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 17
예측 1 중 실제 1 개수: 13
예측 1 기준 정확도 precision: 0.7647058823529411

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.05, '...",44,17,...,0.431818,0.764706,0.382353,0.509804,0.585294,0.768868,6,4,21,13

[I 2026-05-23 20:48:58,057] Trial 16 finished with value: 0.7647058823529411 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.5, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.05, 'gb_max_depth': 4}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 18/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 5, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 100, 'learning_rate': 0.05, 'max_leaf_nodes': 15}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 17}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_5d_up_2pct
target_df shape: (1538, 31)
target 분포:
target_5d_up_2pct
0    919
1    619
Name: count, dtype: int64
lagged_df shape: (1398, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1646

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1648

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1651
TOP feature count: 20
['DXY_ret_20d_lag120', 'SMH_vol_20d_lag60', 'TNX_diff_5d_lag1', 'TNX_level_lag1', 'GOLD_ret_5d_lag120', 'VIX_level_lag40', 'VIX_chg_20d_lag120', 'DXY_ret_5d_lag120', 'TNX_diff_20d_lag5', 'SPY_ret_20d_lag120', 'OIL_ret_20d_lag60', 'GOLD_ret_20d_lag1', 'USDKRW_ret_5d_lag40', 'TSM_ret_20d_lag40', 'VIX_chg_5d_lag40', 'USDKRW_ret_20d_lag40', 'TSM_ret_5d_lag40', 'SPY_ret_5d_lag40', 'SMH_ma20_ratio_lag40', 'SMH_ma60_ratio_lag20']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,DXY_ret_20d_lag120,0.097643,0.003116,9.710753e-06,0.091485,0.102341,3,30,0.094526,DXY_ret_20d,120,120,-0.177627,0.177627,132
1,SMH_vol_20d_lag60,0.073933,0.001638,2.684309e-06,0.071582,0.077448,3,30,0.072294,SMH_vol_20d,60,60,-0.200945,0.200945,192
2,TNX_diff_5d_lag1,0.072014,0.003887,1.510828e-05,0.064915,0.076751,3,30,0.068127,TNX_diff_5d,1,1,-0.194687,0.194687,251
3,TNX_level_lag1,0.070761,0.003199,1.023364e-05,0.063743,0.075185,3,30,0.067562,TNX_level,1,1,-0.214996,0.214996,251
4,GOLD_ret_5d_lag120,0.061778,0.001114,1.241156e-06,0.059052,0.064708,3,30,0.060664,GOLD_ret_5d,120,120,-0.197469,0.197469,132
5,VIX_level_lag40,0.057051,0.001657,2.746894e-06,0.053453,0.059921,3,30,0.055394,VIX_level,40,40,0.129031,0.129031,212
6,VIX_chg_20d_lag120,0.051215,0.001738,3.018957e-06,0.048241,0.053650,3,30,0.049477,VIX_chg_20d,120,120,0.178242,0.178242,132
7,DXY_ret_5d_lag120,0.050292,0.001078,1.163088e-06,0.048544,0.052323,3,30,0.049214,DXY_ret_5d,120,120,0.144858,0.144858,132
8,TNX_diff_20d_lag5,0.049925,0.001771,3.135040e-06,0.046680,0.052575,3,30,0.048155,TNX_diff_20d,5,5,0.233782,0.233782,247
9,SPY_ret_20d_lag120,0.049587,0.001888,3.563241e-06,0.047120,0.053090,3,30,0.047699,SPY_ret_20d,120,120,-0.184210,0.184210,132
10,OIL_ret_20d_lag60,0.049609,0.002562,6.566202e-06,0.046023,0.054144,3,30,0.047046,OIL_ret_20d,60,60,0.183668,0.183668,192
11,GOLD_ret_20d_lag1,0.049299,0.002614,6.835072e-06,0.045773,0.053670,3,30,0.046685,GOLD_ret_20d,1,1,0.156010,0.156010,251
12,USDKRW_ret_5d_lag40,0.047465,0.000926,8.578479e-07,0.045333,0.048986,3,30,0.046538,USDKRW_ret_5d,40,40,0.194949,0.194949,212
13,TSM_ret_20d_lag40,0.046758,0.001039,1.080266e-06,0.044701,0.048959,3,30,0.045719,TSM_ret_20d,40,40,-0.156042,0.156042,212
14,VIX_chg_5d_lag40,0.046637,0.001318,1.737261e-06,0.043782,0.049049,3,30,0.045319,VIX_chg_5d,40,40,0.213755,0.213755,212
15,USDKRW_ret_20d_lag40,0.044589,0.000760,5.781988e-07,0.043431,0.046596,3,30,0.043829,USDKRW_ret_20d,40,40,0.230330,0.230330,212
16,TSM_ret_5d_lag40,0.044796,0.001053,1.108525e-06,0.042784,0.046687,3,30,0.043743,TSM_ret_5d,40,40,-0.250401,0.250401,212
17,SPY_ret_5d_lag40,0.045185,0.001809,3.272031e-06,0.041485,0.048565,3,30,0.043376,SPY_ret_5d,40,40,-0.271129,0.271129,212
18,SMH_ma20_ratio_lag40,0.042832,0.000860,7.400631e-07,0.041198,0.044580,3,30,0.041972,SMH_ma20_ratio,40,40,-0.200945,0.200945,212
19,SMH_ma60_ratio_lag20,0.039862,0.000882,7.786455e-07,0.037686,0.041883,3,30,0.038980,SMH_ma60_ratio,20,20,-0.095011,0.095011,232

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1398, 23)
X_train shape: (1398, 20)
train target 분포:
target_5d_up_2pct
0    841
1    557
Name: count, dtype: int64
target_5d_up_2pct
0    0.601574
1    0.398426
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_5d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                0.0    0.413380     0
1  2026-02-24     419.160004                0.0    0.213597     0
2  2026-02-25     426.160004                0.0    0.263394     0
3  2026-02-26     412.010010                0.0    0.156976     0
4  2026-02-27     406.369995                0.0    0.211401     0
..        ...            ...                ...         ...   ...
59 2026-05-18     546.159973                NaN    0.537268     0
60 2026-05-19     543.960022                NaN    0.491440     0
61 2026-05-20     564.659973                NaN    0.345272     0
62 2026-05-21     567.880005                NaN    0.293521     0
63 2026-05-22     576.320007                NaN    0.238726     0

[64 rows x 5 columns]

예측값 분포:
pred
0    64
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 59
예측 1 개수: 0
예측 1 중 실제 1 개수: 0
예측 1 기준 정확도 precision: nan

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,5,0.02,1,20,20,hist_gradient_boosting,"{'max_iter': 100, 'learning_rate': 0.05, 'max_...",59,0,...,0.508475,0.0,0.0,0.0,0.462069,0.768,30,0,29,0

[I 2026-05-23 20:49:13,252] Trial 17 finished with value: 0.0 and parameters: {'n_days': 5, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 100, 'hgb_learning_rate': 0.05, 'hgb_max_leaf_nodes': 15}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 19/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 50, 'pred_threshold': 0.6000000000000001, 'model_name': 'logistic', 'model_params': {'C': 1.0, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 18}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 27
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1', 'TNX_diff_5d_lag5', 'SPY_ret_5d_lag120', 'NVDA_ret_5d_lag60', 'SOXX_ret_5d_lag120', 'SMH_volume_ratio_20d_lag40', 'SMH_ma5_ratio_lag60', 'SMH_ret_1d_lag60']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251
20,TNX_diff_5d_lag5,0.028148,0.001107,1.226237e-06,0.026030,0.029843,3,30,0.027041,TNX_diff_5d,5,5,0.205918,0.205918,247
21,SPY_ret_5d_lag120,0.027266,0.000982,9.634165e-07,0.025657,0.029503,3,30,0.026284,SPY_ret_5d,120,120,-0.226060,0.226060,132
22,NVDA_ret_5d_lag60,0.026746,0.001502,2.255625e-06,0.024752,0.029620,3,30,0.025244,NVDA_ret_5d,60,60,-0.230714,0.230714,192
23,SOXX_ret_5d_lag120,0.025377,0.000772,5.958999e-07,0.023624,0.026787,3,30,0.024605,SOXX_ret_5d,120,120,-0.180724,0.180724,132
24,SMH_volume_ratio_20d_lag40,0.023451,0.000495,2.454801e-07,0.022375,0.024293,3,30,0.022956,SMH_volume_ratio_20d,40,40,-0.175235,0.175235,212
25,SMH_ma5_ratio_lag60,0.020131,0.000685,4.688208e-07,0.018742,0.021058,3,30,0.019447,SMH_ma5_ratio,60,60,-0.179975,0.179975,192
26,SMH_ret_1d_lag60,0.015072,0.000675,4.562163e-07,0.013999,0.016328,3,30,0.014397,SMH_ret_1d,60,60,-0.127110,0.127110,192

============================================================
6. valid_df 생성
============================================================
top feature 수: 27
lag 생성 후 valid_df shape: (1607, 56)
원본 base_feature 제거 후 valid_df shape: (1607, 29)
최종 컬럼 수: 29
target 생성 후 valid_df shape: (1607, 31)
최종 valid_df shape: (64, 31)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 27
train_df shape: (1383, 30)
X_train shape: (1383, 27)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 31)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.380619     0
1  2026-02-24     419.160004                 0.0    0.432329     0
2  2026-02-25     426.160004                 0.0    0.468745     0
3  2026-02-26     412.010010                 0.0    0.459336     0
4  2026-02-27     406.369995                 0.0    0.627009     1
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.492659     0
60 2026-05-19     543.960022                 NaN    0.607206     1
61 2026-05-20     564.659973                 NaN    0.666179     1
62 2026-05-21     567.880005                 NaN    0.724017     1
63 2026-05-22     576.320007                 NaN    0.605746     1

[64 rows x 5 columns]

예측값 분포:
pred
0    35
1    29
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 20
예측 1 중 실제 1 개수: 18
예측 1 기준 정확도 precision: 0.9

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,50,27,logistic,"{'C': 1.0, 'class_weight': 'balanced', 'max_it...",44,20,...,0.590909,0.9,0.529412,0.666667,0.747059,0.58148,8,2,16,18

[I 2026-05-23 20:49:28,436] Trial 18 finished with value: 0.9 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 50, 'pred_threshold': 0.6000000000000001, 'model_name': 'logistic', 'logistic_C': 1.0}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 20/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 10, 'threshold': 0.02, 'top_n': 10, 'pred_threshold': 0.75, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 100, 'learning_rate': 0.01, 'max_depth': 5}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 19}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_10d_up_2pct
target_df shape: (1533, 31)
target 분포:
target_10d_up_2pct
0    796
1    737
Name: count, dtype: int64
lagged_df shape: (1393, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1451

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1444

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.145
TOP feature count: 10
['USDKRW_ret_20d_lag3', 'TNX_level_lag120', 'NVDA_ret_20d_lag60', 'DXY_ret_20d_lag120', 'OIL_ret_20d_lag40', 'SMH_vol_20d_lag40', 'SMH_ma60_ratio_lag40', 'VIX_chg_5d_lag60', 'VIX_level_lag40', 'TSM_ret_20d_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,USDKRW_ret_20d_lag3,0.109887,0.002912,0.000008,0.104706,0.114723,3,30,0.106975,USDKRW_ret_20d,3,3,-0.361488,0.361488,249
1,TNX_level_lag120,0.100155,0.003176,0.000010,0.095000,0.107899,3,30,0.096979,TNX_level,120,120,-0.215120,0.215120,132
2,NVDA_ret_20d_lag60,0.090154,0.002180,0.000005,0.086989,0.095382,3,30,0.087975,NVDA_ret_20d,60,60,-0.177262,0.177262,192
3,DXY_ret_20d_lag120,0.080840,0.002467,0.000006,0.077294,0.086061,3,30,0.078372,DXY_ret_20d,120,120,-0.296418,0.296418,132
4,OIL_ret_20d_lag40,0.078288,0.003562,0.000013,0.073828,0.086503,3,30,0.074726,OIL_ret_20d,40,40,-0.298890,0.298890,212
5,SMH_vol_20d_lag40,0.072109,0.001926,0.000004,0.067649,0.075586,3,30,0.070182,SMH_vol_20d,40,40,0.280782,0.280782,212
6,SMH_ma60_ratio_lag40,0.061142,0.001488,0.000002,0.057642,0.064227,3,30,0.059654,SMH_ma60_ratio,40,40,-0.243144,0.243144,212
7,VIX_chg_5d_lag60,0.054753,0.001912,0.000004,0.051218,0.059758,3,30,0.052840,VIX_chg_5d,60,60,0.163074,0.163074,192
8,VIX_level_lag40,0.054488,0.002225,0.000005,0.050400,0.058960,3,30,0.052262,VIX_level,40,40,0.186078,0.186078,212
9,TSM_ret_20d_lag40,0.051417,0.001871,0.000003,0.047055,0.054811,3,30,0.049546,TSM_ret_20d,40,40,-0.254788,0.254788,212

============================================================
6. valid_df 생성
============================================================
top feature 수: 10
lag 생성 후 valid_df shape: (1607, 22)
원본 base_feature 제거 후 valid_df shape: (1607, 12)
최종 컬럼 수: 12
target 생성 후 valid_df shape: (1607, 14)
최종 valid_df shape: (64, 14)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 10
train_df shape: (1393, 13)
X_train shape: (1393, 10)
train target 분포:
target_10d_up_2pct
0    734
1    659
Name: count, dtype: int64
target_10d_up_2pct
0    0.52692
1    0.47308
Name: proportion, dtype: float64
valid_df shape: (64, 14)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_10d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.705298     0
1  2026-02-24     419.160004                 0.0    0.747121     0
2  2026-02-25     426.160004                 0.0    0.665141     0
3  2026-02-26     412.010010                 0.0    0.580814     0
4  2026-02-27     406.369995                 0.0    0.617962     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.374073     0
60 2026-05-19     543.960022                 NaN    0.407964     0
61 2026-05-20     564.659973                 NaN    0.419872     0
62 2026-05-21     567.880005                 NaN    0.401915     0
63 2026-05-22     576.320007                 NaN    0.370652     0

[64 rows x 5 columns]

예측값 분포:
pred
0    64
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 54
예측 1 개수: 0
예측 1 중 실제 1 개수: 0
예측 1 기준 정확도 precision: nan

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,10,0.02,1,10,10,gradient_boosting,"{'n_estimators': 100, 'learning_rate': 0.01, '...",54,0,...,0.37037,0.0,0.0,0.0,0.427941,0.764801,20,0,34,0

[I 2026-05-23 20:49:44,220] Trial 19 finished with value: 0.0 and parameters: {'n_days': 10, 'threshold': 0.02, 'top_n': 10, 'pred_threshold': 0.75, 'model_name': 'gradient_boosting', 'gb_n_estimators': 100, 'gb_learning_rate': 0.01, 'gb_max_depth': 5}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 21/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.015, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'logistic', 'model_params': {'C': 0.1, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 20}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_1pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_1pct
1    875
0    648
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1282

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1291

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1292
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'VIX_chg_20d_lag120', 'NVDA_ret_20d_lag1', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'SMH_ma20_ratio_lag1', 'USDKRW_ret_20d_lag40', 'DXY_ret_5d_lag120', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'VIX_level_lag20', 'VIX_chg_5d_lag120', 'OIL_ret_20d_lag120', 'SMH_ma60_ratio_lag1', 'TNX_diff_5d_lag5', 'GOLD_ret_20d_lag120', 'OIL_ret_5d_lag10', 'GOLD_ret_5d_lag60', 'SPY_ret_5d_lag120']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118484,0.002821,7.957216e-06,0.109722,0.124056,3,30,0.115663,SMH_vol_20d,120,120,-0.303085,0.303085,132
1,TNX_level_lag20,0.098508,0.003546,1.257577e-05,0.091406,0.103231,3,30,0.094962,TNX_level,20,20,-0.312171,0.312171,232
2,VIX_chg_20d_lag120,0.084307,0.004767,2.272657e-05,0.074815,0.090386,3,30,0.079540,VIX_chg_20d,120,120,0.361218,0.361218,132
3,NVDA_ret_20d_lag1,0.077011,0.002656,7.056867e-06,0.073438,0.082286,3,30,0.074355,NVDA_ret_20d,1,1,0.255267,0.255267,251
4,DXY_ret_20d_lag60,0.073972,0.003501,1.226018e-05,0.065067,0.079207,3,30,0.070471,DXY_ret_20d,60,60,-0.224007,0.224007,192
5,TNX_diff_20d_lag1,0.067782,0.002068,4.275689e-06,0.063536,0.070710,3,30,0.065714,TNX_diff_20d,1,1,0.409580,0.409580,251
6,SMH_ma20_ratio_lag1,0.064028,0.003588,1.287606e-05,0.057455,0.069127,3,30,0.060440,SMH_ma20_ratio,1,1,0.278312,0.278312,251
7,USDKRW_ret_20d_lag40,0.054209,0.001347,1.813178e-06,0.051963,0.056946,3,30,0.052862,USDKRW_ret_20d,40,40,0.344971,0.344971,212
8,DXY_ret_5d_lag120,0.053646,0.002349,5.516362e-06,0.049564,0.057537,3,30,0.051297,DXY_ret_5d,120,120,-0.258618,0.258618,132
9,SPY_ret_20d_lag120,0.053166,0.002152,4.629870e-06,0.049174,0.057806,3,30,0.051015,SPY_ret_20d,120,120,-0.257846,0.257846,132
10,TSM_ret_20d_lag1,0.051027,0.002671,7.136912e-06,0.045914,0.054292,3,30,0.048356,TSM_ret_20d,1,1,0.323766,0.323766,251
11,VIX_level_lag20,0.051332,0.003401,1.156368e-05,0.046068,0.056499,3,30,0.047931,VIX_level,20,20,0.256886,0.256886,232
12,VIX_chg_5d_lag120,0.050033,0.002465,6.074460e-06,0.045693,0.053445,3,30,0.047568,VIX_chg_5d,120,120,0.140989,0.140989,132
13,OIL_ret_20d_lag120,0.046951,0.001639,2.685367e-06,0.043890,0.051856,3,30,0.045313,OIL_ret_20d,120,120,0.317093,0.317093,132
14,SMH_ma60_ratio_lag1,0.045240,0.000929,8.634352e-07,0.043842,0.047279,3,30,0.044311,SMH_ma60_ratio,1,1,0.195063,0.195063,251
15,TNX_diff_5d_lag5,0.044214,0.002358,5.561184e-06,0.039888,0.047489,3,30,0.041856,TNX_diff_5d,5,5,0.211260,0.211260,247
16,GOLD_ret_20d_lag120,0.038123,0.001246,1.553398e-06,0.035914,0.041085,3,30,0.036877,GOLD_ret_20d,120,120,-0.347004,0.347004,132
17,OIL_ret_5d_lag10,0.030618,0.000852,7.251870e-07,0.029380,0.032145,3,30,0.029766,OIL_ret_5d,10,10,0.189850,0.189850,242
18,GOLD_ret_5d_lag60,0.029241,0.000940,8.827980e-07,0.027493,0.030948,3,30,0.028301,GOLD_ret_5d,60,60,0.194501,0.194501,192
19,SPY_ret_5d_lag120,0.028214,0.000910,8.287835e-07,0.026523,0.029787,3,30,0.027304,SPY_ret_5d,120,120,-0.236798,0.236798,132

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_1pct
1    773
0    610
Name: count, dtype: int64
target_20d_up_1pct
1    0.55893
0    0.44107
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_1pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.494719     0
1  2026-02-24     419.160004                 0.0    0.471355     0
2  2026-02-25     426.160004                 0.0    0.517602     0
3  2026-02-26     412.010010                 0.0    0.557605     0
4  2026-02-27     406.369995                 0.0    0.603228     1
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.498466     0
60 2026-05-19     543.960022                 NaN    0.539728     0
61 2026-05-20     564.659973                 NaN    0.607452     1
62 2026-05-21     567.880005                 NaN    0.646141     1
63 2026-05-22     576.320007                 NaN    0.582683     0

[64 rows x 5 columns]

예측값 분포:
pred
0    47
1    17
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 8
예측 1 중 실제 1 개수: 6
예측 1 기준 정확도 precision: 0.75

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.015,1,20,20,logistic,"{'C': 0.1, 'class_weight': 'balanced', 'max_it...",44,8,...,0.318182,0.75,0.176471,0.285714,0.314706,0.767682,8,2,28,6

[I 2026-05-23 20:50:01,060] Trial 20 finished with value: 0.75 and parameters: {'n_days': 20, 'threshold': 0.015, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'logistic', 'logistic_C': 0.1}. Best is trial 6 with value: 1.0.
[I 2026-05-23 20:50:01,077] Trial 21 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.
[I 2026-05-23 20:50:01,094] Trial 22 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 22/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 21}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204741_optuna_holdout_trial_0011
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 23/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 22}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204741_optuna_holdout_trial_0011
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 24/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.5, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 23}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.555357     1
1  2026-02-24     419.160004                 0.0    0.646397     1
2  2026-02-25     426.160004                 0.0    0.597912     1
3  2026-02-26     412.010010                 0.0    0.457527     0
4  2026-02-27     406.369995                 0.0    0.545480     1
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.619136     1
60 2026-05-19     543.960022                 NaN    0.842201     1
61 2026-05-20     564.659973                 NaN    0.492613     0
62 2026-05-21     567.880005                 NaN    0.405804     0
63 2026-05-22     576.320007                 NaN    0.501921     1

[64 rows x 5 columns]

예측값 분포:
pred
1    38
0    26
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 20
예측 1 중 실제 1 개수: 13
예측 1 기준 정확도 precision: 0.65

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.03, '...",44,20,...,0.363636,0.65,0.382353,0.481481,0.370588,0.77784,3,7,21,13

[I 2026-05-23 20:50:18,888] Trial 23 finished with value: 0.65 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.5, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 25/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 500, 'learning_rate': 0.1, 'max_depth': 4}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 24}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.271947     0
1  2026-02-24     419.160004                 0.0    0.813810     1
2  2026-02-25     426.160004                 0.0    0.669559     0
3  2026-02-26     412.010010                 0.0    0.212050     0
4  2026-02-27     406.369995                 0.0    0.253497     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.669316     0
60 2026-05-19     543.960022                 NaN    0.897947     1
61 2026-05-20     564.659973                 NaN    0.849257     1
62 2026-05-21     567.880005                 NaN    0.817739     1
63 2026-05-22     576.320007                 NaN    0.758162     1

[64 rows x 5 columns]

예측값 분포:
pred
1    33
0    31
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 16
예측 1 중 실제 1 개수: 14
예측 1 기준 정확도 precision: 0.875

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,gradient_boosting,"{'n_estimators': 500, 'learning_rate': 0.1, 'm...",44,16,...,0.5,0.875,0.411765,0.56,0.558824,0.788287,8,2,20,14

[I 2026-05-23 20:50:38,224] Trial 24 finished with value: 0.875 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'gb_n_estimators': 500, 'gb_learning_rate': 0.1, 'gb_max_depth': 4}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 26/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 10, 'threshold': 0.005, 'top_n': 20, 'pred_threshold': 0.8, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 2}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 25}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_10d_up_0pct
target_df shape: (1533, 31)
target 분포:
target_10d_up_0pct
1    882
0    651
Name: count, dtype: int64
lagged_df shape: (1354, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1396

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1396

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1394
TOP feature count: 20
['TNX_level_lag120', 'USDKRW_ret_20d_lag3', 'DXY_ret_20d_lag120', 'SMH_vol_20d_lag40', 'OIL_ret_20d_lag120', 'TNX_diff_20d_lag5', 'GOLD_ret_20d_lag40', 'NVDA_ret_20d_lag120', 'TSM_ret_5d_lag40', 'SPY_ret_20d_lag120', 'VIX_level_lag40', 'VIX_chg_5d_lag60', 'VIX_chg_20d_lag120', 'SMH_ma60_ratio_lag120', 'SMH_volume_ratio_20d_lag5', 'SMH_ma20_ratio_lag120', 'TSM_ret_20d_lag120', 'USDKRW_ret_5d_lag120', 'TNX_diff_5d_lag60', 'DXY_ret_5d_lag120']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.114099,0.005156,2.658068e-05,0.102361,0.121295,3,30,0.108944,TNX_level,120,120,-0.247079,0.247079,132
1,USDKRW_ret_20d_lag3,0.105354,0.006455,4.166613e-05,0.094970,0.115848,3,30,0.098899,USDKRW_ret_20d,3,3,-0.314678,0.314678,249
2,DXY_ret_20d_lag120,0.097480,0.002902,8.420871e-06,0.091990,0.102329,3,30,0.094578,DXY_ret_20d,120,120,-0.300370,0.300370,132
3,SMH_vol_20d_lag40,0.079376,0.002295,5.266172e-06,0.075700,0.083706,3,30,0.077081,SMH_vol_20d,40,40,0.216317,0.216317,212
4,OIL_ret_20d_lag120,0.066135,0.001842,3.394378e-06,0.063081,0.069975,3,30,0.064293,OIL_ret_20d,120,120,-0.229237,0.229237,132
5,TNX_diff_20d_lag5,0.061168,0.001872,3.503907e-06,0.057590,0.065294,3,30,0.059296,TNX_diff_20d,5,5,0.361960,0.361960,247
6,GOLD_ret_20d_lag40,0.057597,0.001910,3.647110e-06,0.053794,0.061701,3,30,0.055687,GOLD_ret_20d,40,40,-0.148102,0.148102,212
7,NVDA_ret_20d_lag120,0.054337,0.001519,2.307904e-06,0.050717,0.058087,3,30,0.052818,NVDA_ret_20d,120,120,-0.253585,0.253585,132
8,TSM_ret_5d_lag40,0.053448,0.001459,2.129743e-06,0.051298,0.056400,3,30,0.051989,TSM_ret_5d,40,40,-0.242780,0.242780,212
9,SPY_ret_20d_lag120,0.051863,0.001866,3.480598e-06,0.047460,0.055409,3,30,0.049998,SPY_ret_20d,120,120,-0.318511,0.318511,132
10,VIX_level_lag40,0.050667,0.001172,1.372871e-06,0.047863,0.052770,3,30,0.049496,VIX_level,40,40,0.151591,0.151591,212
11,VIX_chg_5d_lag60,0.047297,0.003269,1.068507e-05,0.042487,0.052602,3,30,0.044028,VIX_chg_5d,60,60,0.127624,0.127624,192
12,VIX_chg_20d_lag120,0.044215,0.001232,1.516596e-06,0.041359,0.046152,3,30,0.042983,VIX_chg_20d,120,120,0.313103,0.313103,132
13,SMH_ma60_ratio_lag120,0.043850,0.001086,1.179128e-06,0.041431,0.046171,3,30,0.042764,SMH_ma60_ratio,120,120,-0.197638,0.197638,132
14,SMH_volume_ratio_20d_lag5,0.042285,0.001657,2.746598e-06,0.039245,0.045566,3,30,0.040627,SMH_volume_ratio_20d,5,5,0.195126,0.195126,247
15,SMH_ma20_ratio_lag120,0.040721,0.001256,1.578181e-06,0.039018,0.043972,3,30,0.039465,SMH_ma20_ratio,120,120,-0.312656,0.312656,132
16,TSM_ret_20d_lag120,0.039925,0.001511,2.282005e-06,0.037629,0.043307,3,30,0.038415,TSM_ret_20d,120,120,-0.264108,0.264108,132
17,USDKRW_ret_5d_lag120,0.037754,0.001205,1.451256e-06,0.034878,0.039443,3,30,0.036549,USDKRW_ret_5d,120,120,0.236574,0.236574,132
18,TNX_diff_5d_lag60,0.034374,0.000919,8.439244e-07,0.032628,0.036210,3,30,0.033455,TNX_diff_5d,60,60,-0.203933,0.203933,192
19,DXY_ret_5d_lag120,0.032644,0.001161,1.349066e-06,0.030826,0.035434,3,30,0.031482,DXY_ret_5d,120,120,-0.110706,0.110706,132

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1354, 23)
X_train shape: (1354, 20)
train target 분포:
target_10d_up_0pct
1    766
0    588
Name: count, dtype: int64
target_10d_up_0pct
1    0.565731
0    0.434269
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_10d_up_0pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.844602     1
1  2026-02-24     419.160004                 0.0    0.831725     1
2  2026-02-25     426.160004                 0.0    0.582214     0
3  2026-02-26     412.010010                 0.0    0.375419     0
4  2026-02-27     406.369995                 0.0    0.344464     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.310610     0
60 2026-05-19     543.960022                 NaN    0.397828     0
61 2026-05-20     564.659973                 NaN    0.425513     0
62 2026-05-21     567.880005                 NaN    0.406821     0
63 2026-05-22     576.320007                 NaN    0.509176     0

[64 rows x 5 columns]

예측값 분포:
pred
0    62
1     2
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 54
예측 1 개수: 2
예측 1 중 실제 1 개수: 0
예측 1 기준 정확도 precision: 0.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,10,0.005,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.05, '...",54,2,...,0.277778,0.0,0.0,0.0,0.282989,0.790652,15,2,37,0

[I 2026-05-23 20:50:55,576] Trial 25 finished with value: 0.0 and parameters: {'n_days': 10, 'threshold': 0.005, 'top_n': 20, 'pred_threshold': 0.8, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.05, 'gb_max_depth': 2}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 27/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 5, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'random_forest', 'model_params': {'n_estimators': 300, 'max_depth': 7, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'class_weight': 'balanced'}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 26}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_5d_up_3pct
target_df shape: (1538, 31)
target 분포:
target_5d_up_3pct
0    1051
1     487
Name: count, dtype: int64
lagged_df shape: (1398, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1462

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1467

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1461
TOP feature count: 20
['SMH_ma60_ratio_lag1', 'SMH_vol_20d_lag60', 'TNX_level_lag1', 'GOLD_ret_5d_lag120', 'VIX_level_lag1', 'VIX_chg_20d_lag40', 'OIL_ret_20d_lag60', 'TNX_diff_5d_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag40', 'DXY_ret_20d_lag5', 'USDKRW_ret_20d_lag40', 'USDKRW_ret_5d_lag1', 'GOLD_ret_20d_lag1', 'DXY_ret_5d_lag120', 'TNX_diff_20d_lag5', 'SMH_volume_ratio_20d_lag20', 'SMH_ma20_ratio_lag40', 'OIL_ret_5d_lag60', 'NVDA_ret_20d_lag120']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_ma60_ratio_lag1,0.078441,0.001863,3.470473e-06,0.074815,0.082776,3,30,0.076578,SMH_ma60_ratio,1,1,-0.172629,0.172629,251
1,SMH_vol_20d_lag60,0.069105,0.001919,3.684021e-06,0.065530,0.073300,3,30,0.067185,SMH_vol_20d,60,60,-0.189027,0.189027,192
2,TNX_level_lag1,0.069129,0.002486,6.181890e-06,0.063543,0.073483,3,30,0.066643,TNX_level,1,1,-0.191147,0.191147,251
3,GOLD_ret_5d_lag120,0.060355,0.002163,4.676538e-06,0.055174,0.064143,3,30,0.058193,GOLD_ret_5d,120,120,-0.218877,0.218877,132
4,VIX_level_lag1,0.059673,0.002784,7.752705e-06,0.055123,0.064462,3,30,0.056889,VIX_level,1,1,0.153605,0.153605,251
5,VIX_chg_20d_lag40,0.056407,0.001996,3.983510e-06,0.052414,0.060620,3,30,0.054411,VIX_chg_20d,40,40,0.225283,0.225283,212
6,OIL_ret_20d_lag60,0.053212,0.002001,4.002755e-06,0.049749,0.057240,3,30,0.051212,OIL_ret_20d,60,60,0.237427,0.237427,192
7,TNX_diff_5d_lag20,0.053372,0.002314,5.355884e-06,0.048577,0.056207,3,30,0.051058,TNX_diff_5d,20,20,0.185217,0.185217,232
8,SPY_ret_20d_lag120,0.048811,0.001230,1.513431e-06,0.045170,0.051545,3,30,0.047581,SPY_ret_20d,120,120,-0.195151,0.195151,132
9,TSM_ret_20d_lag40,0.049182,0.002547,6.484842e-06,0.045876,0.055137,3,30,0.046635,TSM_ret_20d,40,40,-0.186887,0.186887,212
10,DXY_ret_20d_lag5,0.044759,0.001859,3.455597e-06,0.040812,0.048252,3,30,0.042900,DXY_ret_20d,5,5,-0.123856,0.123856,247
11,USDKRW_ret_20d_lag40,0.044490,0.001832,3.357242e-06,0.041625,0.048470,3,30,0.042657,USDKRW_ret_20d,40,40,0.204293,0.204293,212
12,USDKRW_ret_5d_lag1,0.042260,0.001278,1.633171e-06,0.039336,0.045023,3,30,0.040982,USDKRW_ret_5d,1,1,-0.135928,0.135928,251
13,GOLD_ret_20d_lag1,0.039152,0.002092,4.374883e-06,0.035630,0.042243,3,30,0.037061,GOLD_ret_20d,1,1,0.185988,0.185988,251
14,DXY_ret_5d_lag120,0.037692,0.000937,8.787204e-07,0.035442,0.040194,3,30,0.036755,DXY_ret_5d,120,120,0.201244,0.201244,132
15,TNX_diff_20d_lag5,0.038099,0.001366,1.866021e-06,0.035694,0.040829,3,30,0.036733,TNX_diff_20d,5,5,0.197432,0.197432,247
16,SMH_volume_ratio_20d_lag20,0.037433,0.000858,7.356760e-07,0.035823,0.038871,3,30,0.036576,SMH_volume_ratio_20d,20,20,-0.106779,0.106779,232
17,SMH_ma20_ratio_lag40,0.036965,0.000649,4.216770e-07,0.035800,0.038710,3,30,0.036315,SMH_ma20_ratio,40,40,-0.224204,0.224204,212
18,OIL_ret_5d_lag60,0.035339,0.000720,5.182253e-07,0.033657,0.036754,3,30,0.034619,OIL_ret_5d,60,60,0.222858,0.222858,192
19,NVDA_ret_20d_lag120,0.035294,0.000913,8.331741e-07,0.033754,0.037211,3,30,0.034381,NVDA_ret_20d,120,120,-0.135504,0.135504,132

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1398, 23)
X_train shape: (1398, 20)
train target 분포:
target_5d_up_3pct
0    958
1    440
Name: count, dtype: int64
target_5d_up_3pct
0    0.685265
1    0.314735
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: random_forest
valid_df 예측 완료

         Date  SMH_adj_close  target_5d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                0.0    0.428459     0
1  2026-02-24     419.160004                0.0    0.398473     0
2  2026-02-25     426.160004                0.0    0.399491     0
3  2026-02-26     412.010010                0.0    0.393848     0
4  2026-02-27     406.369995                0.0    0.390817     0
..        ...            ...                ...         ...   ...
59 2026-05-18     546.159973                NaN    0.361894     0
60 2026-05-19     543.960022                NaN    0.329822     0
61 2026-05-20     564.659973                NaN    0.333148     0
62 2026-05-21     567.880005                NaN    0.340627     0
63 2026-05-22     576.320007                NaN    0.306359     0

[64 rows x 5 columns]

예측값 분포:
pred
0    64
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 59
예측 1 개수: 0
예측 1 중 실제 1 개수: 0
예측 1 기준 정확도 precision: nan

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,5,0.03,1,20,20,random_forest,"{'n_estimators': 300, 'max_depth': 7, 'min_sam...",59,0,...,0.525424,0.0,0.0,0.0,0.452765,0.724061,31,0,28,0

[I 2026-05-23 20:51:12,629] Trial 26 finished with value: 0.0 and parameters: {'n_days': 5, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'random_forest', 'rf_n_estimators': 300, 'rf_max_depth': 7, 'rf_min_samples_leaf': 2, 'rf_max_features': 'sqrt'}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 28/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 3, 'threshold': 0.02, 'top_n': 10, 'pred_threshold': 0.55, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 500, 'learning_rate': 0.1, 'max_leaf_nodes': 31}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 27}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_3d_up_2pct
target_df shape: (1540, 31)
target 분포:
target_3d_up_2pct
0    1034
1     506
Name: count, dtype: int64
lagged_df shape: (1400, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1599

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.159

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1591
TOP feature count: 10
['NVDA_ret_20d_lag1', 'DXY_ret_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma5_ratio_lag10', 'SMH_ma60_ratio_lag1', 'SOXX_ret_5d_lag1', 'VIX_level_lag1', 'VIX_chg_20d_lag40', 'TSM_ret_5d_lag10', 'GOLD_ret_5d_lag120']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,NVDA_ret_20d_lag1,0.097206,0.004106,0.000017,0.090497,0.104698,3,30,0.093100,NVDA_ret_20d,1,1,-0.111781,0.111781,250
1,DXY_ret_20d_lag120,0.070614,0.001475,0.000002,0.067993,0.074612,3,30,0.069139,DXY_ret_20d,120,120,-0.105215,0.105215,131
2,SMH_ma20_ratio_lag1,0.061117,0.001850,0.000003,0.057828,0.065284,3,30,0.059267,SMH_ma20_ratio,1,1,-0.175532,0.175532,250
3,SMH_ma5_ratio_lag10,0.056295,0.001797,0.000003,0.052956,0.059930,3,30,0.054498,SMH_ma5_ratio,10,10,-0.235165,0.235165,241
4,SMH_ma60_ratio_lag1,0.054641,0.001352,0.000002,0.051610,0.056799,3,30,0.053289,SMH_ma60_ratio,1,1,-0.137592,0.137592,250
5,SOXX_ret_5d_lag1,0.052406,0.002972,0.000009,0.046161,0.056209,3,30,0.049434,SOXX_ret_5d,1,1,-0.199028,0.199028,250
6,VIX_level_lag1,0.052427,0.003118,0.000010,0.048047,0.057951,3,30,0.049308,VIX_level,1,1,0.126094,0.126094,250
7,VIX_chg_20d_lag40,0.048218,0.001064,0.000001,0.045217,0.050314,3,30,0.047154,VIX_chg_20d,40,40,0.182643,0.182643,211
8,TSM_ret_5d_lag10,0.044915,0.001040,0.000001,0.043098,0.047615,3,30,0.043874,TSM_ret_5d,10,10,-0.179270,0.179270,241
9,GOLD_ret_5d_lag120,0.044546,0.001121,0.000001,0.042196,0.047571,3,30,0.043425,GOLD_ret_5d,120,120,-0.114377,0.114377,131

============================================================
6. valid_df 생성
============================================================
top feature 수: 10
lag 생성 후 valid_df shape: (1607, 22)
원본 base_feature 제거 후 valid_df shape: (1607, 12)
최종 컬럼 수: 12
target 생성 후 valid_df shape: (1607, 14)
최종 valid_df shape: (64, 14)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 10
train_df shape: (1400, 13)
X_train shape: (1400, 10)
train target 분포:
target_3d_up_2pct
0    942
1    458
Name: count, dtype: int64
target_3d_up_2pct
0    0.672857
1    0.327143
Name: proportion, dtype: float64
valid_df shape: (64, 14)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_3d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                0.0    0.000368     0
1  2026-02-24     419.160004                0.0    0.019108     0
2  2026-02-25     426.160004                0.0    0.000018     0
3  2026-02-26     412.010010                0.0    0.000003     0
4  2026-02-27     406.369995                0.0    0.014330     0
..        ...            ...                ...         ...   ...
59 2026-05-18     546.159973                1.0    0.159240     0
60 2026-05-19     543.960022                1.0    0.563244     1
61 2026-05-20     564.659973                NaN    0.077476     0
62 2026-05-21     567.880005                NaN    0.168016     0
63 2026-05-22     576.320007                NaN    0.003972     0

[64 rows x 5 columns]

예측값 분포:
pred
0    46
1    18
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 61
예측 1 개수: 18
예측 1 중 실제 1 개수: 7
예측 1 기준 정확도 precision: 0.3888888888888889

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,3,0.02,1,10,10,hist_gradient_boosting,"{'max_iter': 500, 'learning_rate': 0.1, 'max_l...",61,18,...,0.442623,0.388889,0.233333,0.291667,0.431183,3.192608,20,11,23,7

[I 2026-05-23 20:51:33,935] Trial 27 finished with value: 0.3888888888888889 and parameters: {'n_days': 3, 'threshold': 0.02, 'top_n': 10, 'pred_threshold': 0.55, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 500, 'hgb_learning_rate': 0.1, 'hgb_max_leaf_nodes': 31}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 29/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 50, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.01, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 28}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 27
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1', 'NVDA_ret_5d_lag60', 'SPY_ret_5d_lag120', 'SOXX_ret_5d_lag120', 'USDKRW_ret_5d_lag40', 'SMH_ma5_ratio_lag60', 'SMH_volume_ratio_20d_lag120', 'SMH_ret_1d_lag60']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251
20,NVDA_ret_5d_lag60,0.026639,0.001112,1.237156e-06,0.024575,0.028571,3,30,0.025526,NVDA_ret_5d,60,60,-0.251682,0.251682,192
21,SPY_ret_5d_lag120,0.025915,0.000723,5.228773e-07,0.024417,0.027251,3,30,0.025192,SPY_ret_5d,120,120,-0.252525,0.252525,132
22,SOXX_ret_5d_lag120,0.025491,0.000480,2.300800e-07,0.024445,0.026427,3,30,0.025011,SOXX_ret_5d,120,120,-0.254602,0.254602,132
23,USDKRW_ret_5d_lag40,0.025065,0.000769,5.909936e-07,0.023745,0.026481,3,30,0.024296,USDKRW_ret_5d,40,40,0.146047,0.146047,212
24,SMH_ma5_ratio_lag60,0.021075,0.000702,4.932835e-07,0.019899,0.022518,3,30,0.020372,SMH_ma5_ratio,60,60,-0.238638,0.238638,192
25,SMH_volume_ratio_20d_lag120,0.020579,0.001005,1.009657e-06,0.018787,0.022134,3,30,0.019574,SMH_volume_ratio_20d,120,120,0.263883,0.263883,132
26,SMH_ret_1d_lag60,0.014771,0.000621,3.856972e-07,0.013554,0.015965,3,30,0.014150,SMH_ret_1d,60,60,-0.167087,0.167087,192

============================================================
6. valid_df 생성
============================================================
top feature 수: 27
lag 생성 후 valid_df shape: (1607, 56)
원본 base_feature 제거 후 valid_df shape: (1607, 29)
최종 컬럼 수: 29
target 생성 후 valid_df shape: (1607, 31)
최종 valid_df shape: (64, 31)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 27
train_df shape: (1383, 30)
X_train shape: (1383, 27)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 31)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.571805     0
1  2026-02-24     419.160004                 0.0    0.588669     0
2  2026-02-25     426.160004                 0.0    0.588378     0
3  2026-02-26     412.010010                 0.0    0.560599     0
4  2026-02-27     406.369995                 0.0    0.568602     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.538289     0
60 2026-05-19     543.960022                 NaN    0.670984     1
61 2026-05-20     564.659973                 NaN    0.399877     0
62 2026-05-21     567.880005                 NaN    0.383407     0
63 2026-05-22     576.320007                 NaN    0.391983     0

[64 rows x 5 columns]

예측값 분포:
pred
0    57
1     7
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 2
예측 1 중 실제 1 개수: 2
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,50,27,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.01, '...",44,2,...,0.272727,1.0,0.058824,0.111111,0.376471,0.680614,10,0,32,2

[I 2026-05-23 20:51:52,414] Trial 28 finished with value: 0.6666666666666666 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 50, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.01, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 30/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 5, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.75, 'model_name': 'random_forest', 'model_params': {'n_estimators': 800, 'max_depth': 5, 'min_samples_leaf': 1, 'max_features': 'log2', 'class_weight': 'balanced'}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 29}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_5d_up_3pct
target_df shape: (1538, 31)
target 분포:
target_5d_up_3pct
0    1051
1     487
Name: count, dtype: int64
lagged_df shape: (1398, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1462

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1467

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1461
TOP feature count: 20
['SMH_ma60_ratio_lag1', 'SMH_vol_20d_lag60', 'TNX_level_lag1', 'GOLD_ret_5d_lag120', 'VIX_level_lag1', 'VIX_chg_20d_lag40', 'OIL_ret_20d_lag60', 'TNX_diff_5d_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag40', 'DXY_ret_20d_lag5', 'USDKRW_ret_20d_lag40', 'USDKRW_ret_5d_lag1', 'GOLD_ret_20d_lag1', 'DXY_ret_5d_lag120', 'TNX_diff_20d_lag5', 'SMH_volume_ratio_20d_lag20', 'SMH_ma20_ratio_lag40', 'OIL_ret_5d_lag60', 'NVDA_ret_20d_lag120']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_ma60_ratio_lag1,0.078441,0.001863,3.470473e-06,0.074815,0.082776,3,30,0.076578,SMH_ma60_ratio,1,1,-0.172629,0.172629,251
1,SMH_vol_20d_lag60,0.069105,0.001919,3.684021e-06,0.065530,0.073300,3,30,0.067185,SMH_vol_20d,60,60,-0.189027,0.189027,192
2,TNX_level_lag1,0.069129,0.002486,6.181890e-06,0.063543,0.073483,3,30,0.066643,TNX_level,1,1,-0.191147,0.191147,251
3,GOLD_ret_5d_lag120,0.060355,0.002163,4.676538e-06,0.055174,0.064143,3,30,0.058193,GOLD_ret_5d,120,120,-0.218877,0.218877,132
4,VIX_level_lag1,0.059673,0.002784,7.752705e-06,0.055123,0.064462,3,30,0.056889,VIX_level,1,1,0.153605,0.153605,251
5,VIX_chg_20d_lag40,0.056407,0.001996,3.983510e-06,0.052414,0.060620,3,30,0.054411,VIX_chg_20d,40,40,0.225283,0.225283,212
6,OIL_ret_20d_lag60,0.053212,0.002001,4.002755e-06,0.049749,0.057240,3,30,0.051212,OIL_ret_20d,60,60,0.237427,0.237427,192
7,TNX_diff_5d_lag20,0.053372,0.002314,5.355884e-06,0.048577,0.056207,3,30,0.051058,TNX_diff_5d,20,20,0.185217,0.185217,232
8,SPY_ret_20d_lag120,0.048811,0.001230,1.513431e-06,0.045170,0.051545,3,30,0.047581,SPY_ret_20d,120,120,-0.195151,0.195151,132
9,TSM_ret_20d_lag40,0.049182,0.002547,6.484842e-06,0.045876,0.055137,3,30,0.046635,TSM_ret_20d,40,40,-0.186887,0.186887,212
10,DXY_ret_20d_lag5,0.044759,0.001859,3.455597e-06,0.040812,0.048252,3,30,0.042900,DXY_ret_20d,5,5,-0.123856,0.123856,247
11,USDKRW_ret_20d_lag40,0.044490,0.001832,3.357242e-06,0.041625,0.048470,3,30,0.042657,USDKRW_ret_20d,40,40,0.204293,0.204293,212
12,USDKRW_ret_5d_lag1,0.042260,0.001278,1.633171e-06,0.039336,0.045023,3,30,0.040982,USDKRW_ret_5d,1,1,-0.135928,0.135928,251
13,GOLD_ret_20d_lag1,0.039152,0.002092,4.374883e-06,0.035630,0.042243,3,30,0.037061,GOLD_ret_20d,1,1,0.185988,0.185988,251
14,DXY_ret_5d_lag120,0.037692,0.000937,8.787204e-07,0.035442,0.040194,3,30,0.036755,DXY_ret_5d,120,120,0.201244,0.201244,132
15,TNX_diff_20d_lag5,0.038099,0.001366,1.866021e-06,0.035694,0.040829,3,30,0.036733,TNX_diff_20d,5,5,0.197432,0.197432,247
16,SMH_volume_ratio_20d_lag20,0.037433,0.000858,7.356760e-07,0.035823,0.038871,3,30,0.036576,SMH_volume_ratio_20d,20,20,-0.106779,0.106779,232
17,SMH_ma20_ratio_lag40,0.036965,0.000649,4.216770e-07,0.035800,0.038710,3,30,0.036315,SMH_ma20_ratio,40,40,-0.224204,0.224204,212
18,OIL_ret_5d_lag60,0.035339,0.000720,5.182253e-07,0.033657,0.036754,3,30,0.034619,OIL_ret_5d,60,60,0.222858,0.222858,192
19,NVDA_ret_20d_lag120,0.035294,0.000913,8.331741e-07,0.033754,0.037211,3,30,0.034381,NVDA_ret_20d,120,120,-0.135504,0.135504,132

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1398, 23)
X_train shape: (1398, 20)
train target 분포:
target_5d_up_3pct
0    958
1    440
Name: count, dtype: int64
target_5d_up_3pct
0    0.685265
1    0.314735
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: random_forest
valid_df 예측 완료

         Date  SMH_adj_close  target_5d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                0.0    0.454077     0
1  2026-02-24     419.160004                0.0    0.456522     0
2  2026-02-25     426.160004                0.0    0.437130     0
3  2026-02-26     412.010010                0.0    0.423387     0
4  2026-02-27     406.369995                0.0    0.412583     0
..        ...            ...                ...         ...   ...
59 2026-05-18     546.159973                NaN    0.405772     0
60 2026-05-19     543.960022                NaN    0.387616     0
61 2026-05-20     564.659973                NaN    0.372239     0
62 2026-05-21     567.880005                NaN    0.400939     0
63 2026-05-22     576.320007                NaN    0.378587     0

[64 rows x 5 columns]

예측값 분포:
pred
0    64
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 59
예측 1 개수: 0
예측 1 중 실제 1 개수: 0
예측 1 기준 정확도 precision: nan

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,5,0.03,1,20,20,random_forest,"{'n_estimators': 800, 'max_depth': 5, 'min_sam...",59,0,...,0.525424,0.0,0.0,0.0,0.502304,0.701172,31,0,28,0

[I 2026-05-23 20:52:09,800] Trial 29 finished with value: 0.0 and parameters: {'n_days': 5, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.75, 'model_name': 'random_forest', 'rf_n_estimators': 800, 'rf_max_depth': 5, 'rf_min_samples_leaf': 1, 'rf_max_features': 'log2'}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 31/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 10, 'threshold': 0.005, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'logistic', 'model_params': {'C': 0.01, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 30}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_10d_up_0pct
target_df shape: (1533, 31)
target 분포:
target_10d_up_0pct
1    882
0    651
Name: count, dtype: int64
lagged_df shape: (1354, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1396

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1396

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1394
TOP feature count: 20
['TNX_level_lag120', 'USDKRW_ret_20d_lag3', 'DXY_ret_20d_lag120', 'SMH_vol_20d_lag40', 'OIL_ret_20d_lag120', 'TNX_diff_20d_lag5', 'GOLD_ret_20d_lag40', 'NVDA_ret_20d_lag120', 'TSM_ret_5d_lag40', 'SPY_ret_20d_lag120', 'VIX_level_lag40', 'VIX_chg_5d_lag60', 'VIX_chg_20d_lag120', 'SMH_ma60_ratio_lag120', 'SMH_volume_ratio_20d_lag5', 'SMH_ma20_ratio_lag120', 'TSM_ret_20d_lag120', 'USDKRW_ret_5d_lag120', 'TNX_diff_5d_lag60', 'DXY_ret_5d_lag120']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.114099,0.005156,2.658068e-05,0.102361,0.121295,3,30,0.108944,TNX_level,120,120,-0.247079,0.247079,132
1,USDKRW_ret_20d_lag3,0.105354,0.006455,4.166613e-05,0.094970,0.115848,3,30,0.098899,USDKRW_ret_20d,3,3,-0.314678,0.314678,249
2,DXY_ret_20d_lag120,0.097480,0.002902,8.420871e-06,0.091990,0.102329,3,30,0.094578,DXY_ret_20d,120,120,-0.300370,0.300370,132
3,SMH_vol_20d_lag40,0.079376,0.002295,5.266172e-06,0.075700,0.083706,3,30,0.077081,SMH_vol_20d,40,40,0.216317,0.216317,212
4,OIL_ret_20d_lag120,0.066135,0.001842,3.394378e-06,0.063081,0.069975,3,30,0.064293,OIL_ret_20d,120,120,-0.229237,0.229237,132
5,TNX_diff_20d_lag5,0.061168,0.001872,3.503907e-06,0.057590,0.065294,3,30,0.059296,TNX_diff_20d,5,5,0.361960,0.361960,247
6,GOLD_ret_20d_lag40,0.057597,0.001910,3.647110e-06,0.053794,0.061701,3,30,0.055687,GOLD_ret_20d,40,40,-0.148102,0.148102,212
7,NVDA_ret_20d_lag120,0.054337,0.001519,2.307904e-06,0.050717,0.058087,3,30,0.052818,NVDA_ret_20d,120,120,-0.253585,0.253585,132
8,TSM_ret_5d_lag40,0.053448,0.001459,2.129743e-06,0.051298,0.056400,3,30,0.051989,TSM_ret_5d,40,40,-0.242780,0.242780,212
9,SPY_ret_20d_lag120,0.051863,0.001866,3.480598e-06,0.047460,0.055409,3,30,0.049998,SPY_ret_20d,120,120,-0.318511,0.318511,132
10,VIX_level_lag40,0.050667,0.001172,1.372871e-06,0.047863,0.052770,3,30,0.049496,VIX_level,40,40,0.151591,0.151591,212
11,VIX_chg_5d_lag60,0.047297,0.003269,1.068507e-05,0.042487,0.052602,3,30,0.044028,VIX_chg_5d,60,60,0.127624,0.127624,192
12,VIX_chg_20d_lag120,0.044215,0.001232,1.516596e-06,0.041359,0.046152,3,30,0.042983,VIX_chg_20d,120,120,0.313103,0.313103,132
13,SMH_ma60_ratio_lag120,0.043850,0.001086,1.179128e-06,0.041431,0.046171,3,30,0.042764,SMH_ma60_ratio,120,120,-0.197638,0.197638,132
14,SMH_volume_ratio_20d_lag5,0.042285,0.001657,2.746598e-06,0.039245,0.045566,3,30,0.040627,SMH_volume_ratio_20d,5,5,0.195126,0.195126,247
15,SMH_ma20_ratio_lag120,0.040721,0.001256,1.578181e-06,0.039018,0.043972,3,30,0.039465,SMH_ma20_ratio,120,120,-0.312656,0.312656,132
16,TSM_ret_20d_lag120,0.039925,0.001511,2.282005e-06,0.037629,0.043307,3,30,0.038415,TSM_ret_20d,120,120,-0.264108,0.264108,132
17,USDKRW_ret_5d_lag120,0.037754,0.001205,1.451256e-06,0.034878,0.039443,3,30,0.036549,USDKRW_ret_5d,120,120,0.236574,0.236574,132
18,TNX_diff_5d_lag60,0.034374,0.000919,8.439244e-07,0.032628,0.036210,3,30,0.033455,TNX_diff_5d,60,60,-0.203933,0.203933,192
19,DXY_ret_5d_lag120,0.032644,0.001161,1.349066e-06,0.030826,0.035434,3,30,0.031482,DXY_ret_5d,120,120,-0.110706,0.110706,132

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1354, 23)
X_train shape: (1354, 20)
train target 분포:
target_10d_up_0pct
1    766
0    588
Name: count, dtype: int64
target_10d_up_0pct
1    0.565731
0    0.434269
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_10d_up_0pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.603519     0
1  2026-02-24     419.160004                 0.0    0.640387     0
2  2026-02-25     426.160004                 0.0    0.599967     0
3  2026-02-26     412.010010                 0.0    0.466235     0
4  2026-02-27     406.369995                 0.0    0.498767     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.471081     0
60 2026-05-19     543.960022                 NaN    0.529242     0
61 2026-05-20     564.659973                 NaN    0.463522     0
62 2026-05-21     567.880005                 NaN    0.513544     0
63 2026-05-22     576.320007                 NaN    0.465128     0

[64 rows x 5 columns]

예측값 분포:
pred
0    58
1     6
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 54
예측 1 개수: 5
예측 1 중 실제 1 개수: 3
예측 1 기준 정확도 precision: 0.6

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,10,0.005,1,20,20,logistic,"{'C': 0.01, 'class_weight': 'balanced', 'max_i...",54,5,...,0.333333,0.6,0.081081,0.142857,0.400636,0.67629,15,2,34,3

[I 2026-05-23 20:52:26,496] Trial 30 finished with value: 0.6 and parameters: {'n_days': 10, 'threshold': 0.005, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'logistic', 'logistic_C': 0.01}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 32/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 31}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 20
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.298517     0
1  2026-02-24     419.160004                 0.0    0.339273     0
2  2026-02-25     426.160004                 0.0    0.612624     0
3  2026-02-26     412.010010                 0.0    0.400821     0
4  2026-02-27     406.369995                 0.0    0.632620     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.808243     1
60 2026-05-19     543.960022                 NaN    0.869996     1
61 2026-05-20     564.659973                 NaN    0.490125     0
62 2026-05-21     567.880005                 NaN    0.353365     0
63 2026-05-22     576.320007                 NaN    0.432212     0

[64 rows x 5 columns]

예측값 분포:
pred
0    39
1    25
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 9
예측 1 중 실제 1 개수: 9
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,20,20,hist_gradient_boosting,"{'max_iter': 300, 'learning_rate': 0.03, 'max_...",44,9,...,0.431818,1.0,0.264706,0.418605,0.55,0.894799,10,0,25,9

[I 2026-05-23 20:52:44,779] Trial 31 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.
[I 2026-05-23 20:52:44,806] Trial 32 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 33/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 32}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204756_optuna_holdout_trial_0012
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 34/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 33}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 20
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.298517     0
1  2026-02-24     419.160004                 0.0    0.339273     0
2  2026-02-25     426.160004                 0.0    0.612624     1
3  2026-02-26     412.010010                 0.0    0.400821     0
4  2026-02-27     406.369995                 0.0    0.632620     1
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.808243     1
60 2026-05-19     543.960022                 NaN    0.869996     1
61 2026-05-20     564.659973                 NaN    0.490125     0
62 2026-05-21     567.880005                 NaN    0.353365     0
63 2026-05-22     576.320007                 NaN    0.432212     0

[64 rows x 5 columns]

예측값 분포:
pred
0    36
1    28
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 12
예측 1 중 실제 1 개수: 10
예측 1 기준 정확도 precision: 0.8333333333333334

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,20,20,hist_gradient_boosting,"{'max_iter': 300, 'learning_rate': 0.03, 'max_...",44,12,...,0.409091,0.833333,0.294118,0.434783,0.55,0.894799,8,2,24,10

[I 2026-05-23 20:53:02,506] Trial 33 finished with value: 0.8333333333333334 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 35/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.01, 'top_n': 30, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 100, 'learning_rate': 0.1, 'max_leaf_nodes': 15}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 34}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_1pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_1pct
1    917
0    606
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1301

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1302

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1305
TOP feature count: 27
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'NVDA_ret_5d_lag120', 'DXY_ret_5d_lag120', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SMH_ma60_ratio_lag1', 'OIL_ret_20d_lag120', 'VIX_chg_5d_lag120', 'SPY_ret_20d_lag1', 'TNX_diff_5d_lag5', 'GOLD_ret_20d_lag120', 'SMH_ma20_ratio_lag120', 'TSM_ret_5d_lag120', 'GOLD_ret_5d_lag40', 'OIL_ret_5d_lag10', 'USDKRW_ret_5d_lag10', 'SPY_ret_5d_lag120', 'SOXX_ret_5d_lag120', 'SMH_volume_ratio_20d_lag120', 'SMH_ma5_ratio_lag120', 'SMH_ret_1d_lag120']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.113199,0.003130,9.798652e-06,0.105366,0.117758,3,30,0.110069,SMH_vol_20d,120,120,-0.305565,0.305565,132
1,TNX_level_lag20,0.111395,0.001966,3.863856e-06,0.107542,0.114334,3,30,0.109430,TNX_level,20,20,-0.282349,0.282349,232
2,NVDA_ret_20d_lag1,0.080573,0.003084,9.508619e-06,0.075624,0.086273,3,30,0.077490,NVDA_ret_20d,1,1,0.282168,0.282168,251
3,VIX_chg_20d_lag120,0.077843,0.001462,2.138529e-06,0.074670,0.080400,3,30,0.076381,VIX_chg_20d,120,120,0.371232,0.371232,132
4,DXY_ret_20d_lag60,0.073491,0.002177,4.737914e-06,0.068070,0.077471,3,30,0.071314,DXY_ret_20d,60,60,-0.256904,0.256904,192
5,TNX_diff_20d_lag1,0.066654,0.002093,4.380060e-06,0.062034,0.070705,3,30,0.064561,TNX_diff_20d,1,1,0.416622,0.416622,251
6,NVDA_ret_5d_lag120,0.056072,0.001459,2.128896e-06,0.052971,0.058355,3,30,0.054613,NVDA_ret_5d,120,120,-0.233880,0.233880,132
7,DXY_ret_5d_lag120,0.053295,0.001976,3.904778e-06,0.049647,0.058129,3,30,0.051319,DXY_ret_5d,120,120,-0.267096,0.267096,132
8,VIX_level_lag20,0.051839,0.001035,1.070311e-06,0.049900,0.053607,3,30,0.050805,VIX_level,20,20,0.239784,0.239784,232
9,USDKRW_ret_20d_lag40,0.051299,0.001162,1.350872e-06,0.049044,0.053384,3,30,0.050136,USDKRW_ret_20d,40,40,0.281470,0.281470,212
10,TSM_ret_20d_lag1,0.050516,0.002066,4.268228e-06,0.047785,0.054069,3,30,0.048450,TSM_ret_20d,1,1,0.339692,0.339692,251
11,SMH_ma60_ratio_lag1,0.047034,0.001847,3.412431e-06,0.043919,0.049834,3,30,0.045187,SMH_ma60_ratio,1,1,0.226498,0.226498,251
12,OIL_ret_20d_lag120,0.044614,0.001553,2.410659e-06,0.041020,0.048293,3,30,0.043061,OIL_ret_20d,120,120,0.291387,0.291387,132
13,VIX_chg_5d_lag120,0.042947,0.001208,1.459362e-06,0.040616,0.045759,3,30,0.041739,VIX_chg_5d,120,120,0.143824,0.143824,132
14,SPY_ret_20d_lag1,0.043100,0.001912,3.657161e-06,0.039473,0.046173,3,30,0.041188,SPY_ret_20d,1,1,0.273031,0.273031,251
15,TNX_diff_5d_lag5,0.041964,0.001642,2.694547e-06,0.039434,0.045450,3,30,0.040323,TNX_diff_5d,5,5,0.182059,0.182059,247
16,GOLD_ret_20d_lag120,0.037065,0.001167,1.361693e-06,0.034635,0.040013,3,30,0.035898,GOLD_ret_20d,120,120,-0.306548,0.306548,132
17,SMH_ma20_ratio_lag120,0.034339,0.000618,3.813267e-07,0.033254,0.035764,3,30,0.033721,SMH_ma20_ratio,120,120,-0.303183,0.303183,132
18,TSM_ret_5d_lag120,0.034178,0.001041,1.084444e-06,0.032365,0.036477,3,30,0.033136,TSM_ret_5d,120,120,-0.251775,0.251775,132
19,GOLD_ret_5d_lag40,0.031021,0.001323,1.750672e-06,0.028289,0.032956,3,30,0.029698,GOLD_ret_5d,40,40,-0.185968,0.185968,212
20,OIL_ret_5d_lag10,0.029586,0.001875,3.517040e-06,0.027166,0.032706,3,30,0.027711,OIL_ret_5d,10,10,0.146724,0.146724,242
21,USDKRW_ret_5d_lag10,0.027594,0.000588,3.460618e-07,0.026296,0.028759,3,30,0.027005,USDKRW_ret_5d,10,10,-0.121963,0.121963,242
22,SPY_ret_5d_lag120,0.028773,0.001908,3.640026e-06,0.025646,0.031853,3,30,0.026865,SPY_ret_5d,120,120,-0.246520,0.246520,132
23,SOXX_ret_5d_lag120,0.025931,0.000598,3.576511e-07,0.024603,0.027262,3,30,0.025333,SOXX_ret_5d,120,120,-0.291324,0.291324,132
24,SMH_volume_ratio_20d_lag120,0.020064,0.000543,2.953606e-07,0.018983,0.021253,3,30,0.019521,SMH_volume_ratio_20d,120,120,0.253841,0.253841,132
25,SMH_ma5_ratio_lag120,0.018507,0.000645,4.156173e-07,0.017517,0.019844,3,30,0.017862,SMH_ma5_ratio,120,120,-0.227259,0.227259,132
26,SMH_ret_1d_lag120,0.016140,0.000249,6.191607e-08,0.015550,0.016531,3,30,0.015892,SMH_ret_1d,120,120,-0.110756,0.110756,132

============================================================
6. valid_df 생성
============================================================
top feature 수: 27
lag 생성 후 valid_df shape: (1607, 56)
원본 base_feature 제거 후 valid_df shape: (1607, 29)
최종 컬럼 수: 29
target 생성 후 valid_df shape: (1607, 31)
최종 valid_df shape: (64, 31)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 27
train_df shape: (1383, 30)
X_train shape: (1383, 27)
train target 분포:
target_20d_up_1pct
1    815
0    568
Name: count, dtype: int64
target_20d_up_1pct
1    0.589299
0    0.410701
Name: proportion, dtype: float64
valid_df shape: (64, 31)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_1pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.653156     1
1  2026-02-24     419.160004                 0.0    0.772373     1
2  2026-02-25     426.160004                 0.0    0.721359     1
3  2026-02-26     412.010010                 0.0    0.710150     1
4  2026-02-27     406.369995                 0.0    0.721763     1
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.554308     0
60 2026-05-19     543.960022                 NaN    0.689301     1
61 2026-05-20     564.659973                 NaN    0.896855     1
62 2026-05-21     567.880005                 NaN    0.914621     1
63 2026-05-22     576.320007                 NaN    0.866385     1

[64 rows x 5 columns]

예측값 분포:
pred
1    32
0    32
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 16
예측 1 중 실제 1 개수: 8
예측 1 기준 정확도 precision: 0.5

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.01,1,30,27,hist_gradient_boosting,"{'max_iter': 100, 'learning_rate': 0.1, 'max_l...",44,16,...,0.204545,0.5,0.228571,0.313725,0.155556,0.750181,1,8,27,8

[I 2026-05-23 20:53:18,923] Trial 34 finished with value: 0.5 and parameters: {'n_days': 20, 'threshold': 0.01, 'top_n': 30, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 100, 'hgb_learning_rate': 0.1, 'hgb_max_leaf_nodes': 15}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 36/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.75, 'model_name': 'logistic', 'model_params': {'C': 10.0, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 35}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 20
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.374544     0
1  2026-02-24     419.160004                 0.0    0.411243     0
2  2026-02-25     426.160004                 0.0    0.463804     0
3  2026-02-26     412.010010                 0.0    0.500331     0
4  2026-02-27     406.369995                 0.0    0.575157     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.544210     0
60 2026-05-19     543.960022                 NaN    0.614863     0
61 2026-05-20     564.659973                 NaN    0.634410     0
62 2026-05-21     567.880005                 NaN    0.682011     0
63 2026-05-22     576.320007                 NaN    0.633351     0

[64 rows x 5 columns]

예측값 분포:
pred
0    59
1     5
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 3
예측 1 중 실제 1 개수: 3
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,20,20,logistic,"{'C': 10.0, 'class_weight': 'balanced', 'max_i...",44,3,...,0.295455,1.0,0.088235,0.162162,0.755882,0.578949,10,0,31,3

[I 2026-05-23 20:53:35,883] Trial 35 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.75, 'model_name': 'logistic', 'logistic_C': 10.0}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 37/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 3, 'threshold': 0.01, 'top_n': 30, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 500, 'learning_rate': 0.03, 'max_depth': 5}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 36}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_3d_up_1pct
target_df shape: (1540, 31)
target 분포:
target_3d_up_1pct
0    858
1    682
Name: count, dtype: int64
lagged_df shape: (1361, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1775

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.178

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1777
TOP feature count: 27
['DXY_ret_20d_lag120', 'SOXX_ret_5d_lag10', 'TNX_diff_5d_lag20', 'NVDA_ret_5d_lag1', 'USDKRW_ret_20d_lag1', 'SMH_vol_20d_lag60', 'SMH_ma5_ratio_lag10', 'NVDA_ret_20d_lag120', 'VIX_chg_20d_lag120', 'SPY_ret_20d_lag120', 'TSM_ret_5d_lag5', 'OIL_ret_20d_lag60', 'GOLD_ret_20d_lag1', 'OIL_ret_5d_lag20', 'SMH_ma60_ratio_lag120', 'TNX_level_lag1', 'TNX_diff_20d_lag5', 'TSM_ret_20d_lag120', 'VIX_chg_5d_lag40', 'VIX_level_lag40', 'SPY_ret_5d_lag40', 'SMH_ma20_ratio_lag120', 'DXY_ret_5d_lag10', 'USDKRW_ret_5d_lag60', 'GOLD_ret_5d_lag40', 'SMH_ret_1d_lag10', 'SMH_volume_ratio_20d_lag60']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,DXY_ret_20d_lag120,0.099679,0.002438,5.943633e-06,0.094715,0.104590,3,30,0.097242,DXY_ret_20d,120,120,-0.202539,0.202539,131
1,SOXX_ret_5d_lag10,0.077610,0.005324,2.834364e-05,0.069281,0.086203,3,30,0.072286,SOXX_ret_5d,10,10,-0.138531,0.138531,241
2,TNX_diff_5d_lag20,0.057548,0.002587,6.691529e-06,0.052693,0.061019,3,30,0.054961,TNX_diff_5d,20,20,0.185910,0.185910,231
3,NVDA_ret_5d_lag1,0.056908,0.002596,6.739910e-06,0.052460,0.061254,3,30,0.054312,NVDA_ret_5d,1,1,-0.153357,0.153357,250
4,USDKRW_ret_20d_lag1,0.057024,0.002773,7.687779e-06,0.052551,0.060200,3,30,0.054251,USDKRW_ret_20d,1,1,-0.156555,0.156555,250
5,SMH_vol_20d_lag60,0.055205,0.001767,3.122677e-06,0.051758,0.057493,3,30,0.053438,SMH_vol_20d,60,60,-0.119649,0.119649,191
6,SMH_ma5_ratio_lag10,0.054981,0.001559,2.429523e-06,0.052625,0.059181,3,30,0.053423,SMH_ma5_ratio,10,10,-0.198808,0.198808,241
7,NVDA_ret_20d_lag120,0.054383,0.001651,2.726769e-06,0.051834,0.057944,3,30,0.052732,NVDA_ret_20d,120,120,-0.151425,0.151425,131
8,VIX_chg_20d_lag120,0.049870,0.000823,6.780593e-07,0.047655,0.051175,3,30,0.049046,VIX_chg_20d,120,120,0.129767,0.129767,131
9,SPY_ret_20d_lag120,0.050411,0.001498,2.245267e-06,0.047224,0.053040,3,30,0.048913,SPY_ret_20d,120,120,-0.188158,0.188158,131
10,TSM_ret_5d_lag5,0.049761,0.001009,1.017911e-06,0.047816,0.051717,3,30,0.048752,TSM_ret_5d,5,5,0.232924,0.232924,246
11,OIL_ret_20d_lag60,0.051218,0.003152,9.934761e-06,0.046043,0.057292,3,30,0.048066,OIL_ret_20d,60,60,0.207999,0.207999,191
12,GOLD_ret_20d_lag1,0.049863,0.002615,6.840338e-06,0.046775,0.054317,3,30,0.047248,GOLD_ret_20d,1,1,0.109612,0.109612,250
13,OIL_ret_5d_lag20,0.048873,0.002054,4.220476e-06,0.045117,0.052153,3,30,0.046819,OIL_ret_5d,20,20,-0.145432,0.145432,231
14,SMH_ma60_ratio_lag120,0.047406,0.001284,1.648376e-06,0.044350,0.049324,3,30,0.046122,SMH_ma60_ratio,120,120,-0.088680,0.088680,131
15,TNX_level_lag1,0.046193,0.001356,1.837639e-06,0.043787,0.048247,3,30,0.044837,TNX_level,1,1,-0.173322,0.173322,250
16,TNX_diff_20d_lag5,0.046170,0.001424,2.026992e-06,0.043856,0.048976,3,30,0.044746,TNX_diff_20d,5,5,0.153462,0.153462,246
17,TSM_ret_20d_lag120,0.045639,0.000973,9.472751e-07,0.043245,0.047114,3,30,0.044666,TSM_ret_20d,120,120,-0.149607,0.149607,131
18,VIX_chg_5d_lag40,0.045701,0.001570,2.464805e-06,0.043163,0.048905,3,30,0.044131,VIX_chg_5d,40,40,0.164356,0.164356,211
19,VIX_level_lag40,0.044222,0.001178,1.387722e-06,0.041839,0.046441,3,30,0.043044,VIX_level,40,40,0.108848,0.108848,211
20,SPY_ret_5d_lag40,0.042658,0.001605,2.575774e-06,0.040204,0.046719,3,30,0.041053,SPY_ret_5d,40,40,-0.196471,0.196471,211
21,SMH_ma20_ratio_lag120,0.041076,0.000729,5.318602e-07,0.039626,0.042816,3,30,0.040346,SMH_ma20_ratio,120,120,-0.161674,0.161674,131
22,DXY_ret_5d_lag10,0.041448,0.001183,1.398532e-06,0.039747,0.043669,3,30,0.040265,DXY_ret_5d,10,10,-0.106461,0.106461,241
23,USDKRW_ret_5d_lag60,0.040413,0.001389,1.928093e-06,0.037287,0.042835,3,30,0.039024,USDKRW_ret_5d,60,60,0.171187,0.171187,191
24,GOLD_ret_5d_lag40,0.036305,0.001062,1.126799e-06,0.034741,0.038311,3,30,0.035243,GOLD_ret_5d,40,40,-0.142592,0.142592,211
25,SMH_ret_1d_lag10,0.036388,0.001929,3.719899e-06,0.033193,0.040295,3,30,0.034459,SMH_ret_1d,10,10,-0.153831,0.153831,241
26,SMH_volume_ratio_20d_lag60,0.034284,0.000922,8.495581e-07,0.032439,0.036607,3,30,0.033362,SMH_volume_ratio_20d,60,60,0.218922,0.218922,191

============================================================
6. valid_df 생성
============================================================
top feature 수: 27
lag 생성 후 valid_df shape: (1607, 56)
원본 base_feature 제거 후 valid_df shape: (1607, 29)
최종 컬럼 수: 29
target 생성 후 valid_df shape: (1607, 31)
최종 valid_df shape: (64, 31)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 27
train_df shape: (1361, 30)
X_train shape: (1361, 27)
train target 분포:
target_3d_up_1pct
0    758
1    603
Name: count, dtype: int64
target_3d_up_1pct
0    0.556943
1    0.443057
Name: proportion, dtype: float64
valid_df shape: (64, 31)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_3d_up_1pct  pred_proba  pred
0  2026-02-23     412.880005                0.0    0.325089     0
1  2026-02-24     419.160004                0.0    0.348881     0
2  2026-02-25     426.160004                0.0    0.346178     0
3  2026-02-26     412.010010                0.0    0.318384     0
4  2026-02-27     406.369995                0.0    0.378464     0
..        ...            ...                ...         ...   ...
59 2026-05-18     546.159973                1.0    0.452275     0
60 2026-05-19     543.960022                1.0    0.460621     0
61 2026-05-20     564.659973                NaN    0.537590     0
62 2026-05-21     567.880005                NaN    0.579483     0
63 2026-05-22     576.320007                NaN    0.419288     0

[64 rows x 5 columns]

예측값 분포:
pred
0    64
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 61
예측 1 개수: 0
예측 1 중 실제 1 개수: 0
예측 1 기준 정확도 precision: nan

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,3,0.01,1,30,27,gradient_boosting,"{'n_estimators': 500, 'learning_rate': 0.03, '...",61,0,...,0.42623,0.0,0.0,0.0,0.367033,0.921478,26,0,35,0

[I 2026-05-23 20:53:56,916] Trial 36 finished with value: 0.0 and parameters: {'n_days': 3, 'threshold': 0.01, 'top_n': 30, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'gb_n_estimators': 500, 'gb_learning_rate': 0.03, 'gb_max_depth': 5}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 38/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.015, 'top_n': 10, 'pred_threshold': 0.55, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.05, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 37}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_1pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_1pct
1    875
0    648
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1282

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1291

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1292
TOP feature count: 10
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'VIX_chg_20d_lag120', 'NVDA_ret_20d_lag1', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'SMH_ma20_ratio_lag1', 'USDKRW_ret_20d_lag40', 'DXY_ret_5d_lag120', 'SPY_ret_20d_lag120']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118484,0.002821,0.000008,0.109722,0.124056,3,30,0.115663,SMH_vol_20d,120,120,-0.303085,0.303085,132
1,TNX_level_lag20,0.098508,0.003546,0.000013,0.091406,0.103231,3,30,0.094962,TNX_level,20,20,-0.312171,0.312171,232
2,VIX_chg_20d_lag120,0.084307,0.004767,0.000023,0.074815,0.090386,3,30,0.079540,VIX_chg_20d,120,120,0.361218,0.361218,132
3,NVDA_ret_20d_lag1,0.077011,0.002656,0.000007,0.073438,0.082286,3,30,0.074355,NVDA_ret_20d,1,1,0.255267,0.255267,251
4,DXY_ret_20d_lag60,0.073972,0.003501,0.000012,0.065067,0.079207,3,30,0.070471,DXY_ret_20d,60,60,-0.224007,0.224007,192
5,TNX_diff_20d_lag1,0.067782,0.002068,0.000004,0.063536,0.070710,3,30,0.065714,TNX_diff_20d,1,1,0.409580,0.409580,251
6,SMH_ma20_ratio_lag1,0.064028,0.003588,0.000013,0.057455,0.069127,3,30,0.060440,SMH_ma20_ratio,1,1,0.278312,0.278312,251
7,USDKRW_ret_20d_lag40,0.054209,0.001347,0.000002,0.051963,0.056946,3,30,0.052862,USDKRW_ret_20d,40,40,0.344971,0.344971,212
8,DXY_ret_5d_lag120,0.053646,0.002349,0.000006,0.049564,0.057537,3,30,0.051297,DXY_ret_5d,120,120,-0.258618,0.258618,132
9,SPY_ret_20d_lag120,0.053166,0.002152,0.000005,0.049174,0.057806,3,30,0.051015,SPY_ret_20d,120,120,-0.257846,0.257846,132

============================================================
6. valid_df 생성
============================================================
top feature 수: 10
lag 생성 후 valid_df shape: (1607, 22)
원본 base_feature 제거 후 valid_df shape: (1607, 12)
최종 컬럼 수: 12
target 생성 후 valid_df shape: (1607, 14)
최종 valid_df shape: (64, 14)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 10
train_df shape: (1383, 13)
X_train shape: (1383, 10)
train target 분포:
target_20d_up_1pct
1    773
0    610
Name: count, dtype: int64
target_20d_up_1pct
1    0.55893
0    0.44107
Name: proportion, dtype: float64
valid_df shape: (64, 14)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_1pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.883481     1
1  2026-02-24     419.160004                 0.0    0.920341     1
2  2026-02-25     426.160004                 0.0    0.983269     1
3  2026-02-26     412.010010                 0.0    0.978072     1
4  2026-02-27     406.369995                 0.0    0.972956     1
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.793896     1
60 2026-05-19     543.960022                 NaN    0.365623     0
61 2026-05-20     564.659973                 NaN    0.148769     0
62 2026-05-21     567.880005                 NaN    0.346693     0
63 2026-05-22     576.320007                 NaN    0.901328     1

[64 rows x 5 columns]

예측값 분포:
pred
1    47
0    17
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 30
예측 1 중 실제 1 개수: 20
예측 1 기준 정확도 precision: 0.6666666666666666

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.015,1,10,10,hist_gradient_boosting,"{'max_iter': 300, 'learning_rate': 0.05, 'max_...",44,30,...,0.454545,0.666667,0.588235,0.625,0.188235,1.362157,0,10,14,20

[I 2026-05-23 20:54:13,834] Trial 37 finished with value: 0.6666666666666666 and parameters: {'n_days': 20, 'threshold': 0.015, 'top_n': 10, 'pred_threshold': 0.55, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.05, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 39/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 10, 'threshold': 0.005, 'top_n': 20, 'pred_threshold': 0.25, 'model_name': 'random_forest', 'model_params': {'n_estimators': 800, 'max_depth': 3, 'min_samples_leaf': 5, 'max_features': 0.5, 'class_weight': 'balanced'}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 38}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_10d_up_0pct
target_df shape: (1533, 31)
target 분포:
target_10d_up_0pct
1    882
0    651
Name: count, dtype: int64
lagged_df shape: (1354, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1396

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1396

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1394
TOP feature count: 20
['TNX_level_lag120', 'USDKRW_ret_20d_lag3', 'DXY_ret_20d_lag120', 'SMH_vol_20d_lag40', 'OIL_ret_20d_lag120', 'TNX_diff_20d_lag5', 'GOLD_ret_20d_lag40', 'NVDA_ret_20d_lag120', 'TSM_ret_5d_lag40', 'SPY_ret_20d_lag120', 'VIX_level_lag40', 'VIX_chg_5d_lag60', 'VIX_chg_20d_lag120', 'SMH_ma60_ratio_lag120', 'SMH_volume_ratio_20d_lag5', 'SMH_ma20_ratio_lag120', 'TSM_ret_20d_lag120', 'USDKRW_ret_5d_lag120', 'TNX_diff_5d_lag60', 'DXY_ret_5d_lag120']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.114099,0.005156,2.658068e-05,0.102361,0.121295,3,30,0.108944,TNX_level,120,120,-0.247079,0.247079,132
1,USDKRW_ret_20d_lag3,0.105354,0.006455,4.166613e-05,0.094970,0.115848,3,30,0.098899,USDKRW_ret_20d,3,3,-0.314678,0.314678,249
2,DXY_ret_20d_lag120,0.097480,0.002902,8.420871e-06,0.091990,0.102329,3,30,0.094578,DXY_ret_20d,120,120,-0.300370,0.300370,132
3,SMH_vol_20d_lag40,0.079376,0.002295,5.266172e-06,0.075700,0.083706,3,30,0.077081,SMH_vol_20d,40,40,0.216317,0.216317,212
4,OIL_ret_20d_lag120,0.066135,0.001842,3.394378e-06,0.063081,0.069975,3,30,0.064293,OIL_ret_20d,120,120,-0.229237,0.229237,132
5,TNX_diff_20d_lag5,0.061168,0.001872,3.503907e-06,0.057590,0.065294,3,30,0.059296,TNX_diff_20d,5,5,0.361960,0.361960,247
6,GOLD_ret_20d_lag40,0.057597,0.001910,3.647110e-06,0.053794,0.061701,3,30,0.055687,GOLD_ret_20d,40,40,-0.148102,0.148102,212
7,NVDA_ret_20d_lag120,0.054337,0.001519,2.307904e-06,0.050717,0.058087,3,30,0.052818,NVDA_ret_20d,120,120,-0.253585,0.253585,132
8,TSM_ret_5d_lag40,0.053448,0.001459,2.129743e-06,0.051298,0.056400,3,30,0.051989,TSM_ret_5d,40,40,-0.242780,0.242780,212
9,SPY_ret_20d_lag120,0.051863,0.001866,3.480598e-06,0.047460,0.055409,3,30,0.049998,SPY_ret_20d,120,120,-0.318511,0.318511,132
10,VIX_level_lag40,0.050667,0.001172,1.372871e-06,0.047863,0.052770,3,30,0.049496,VIX_level,40,40,0.151591,0.151591,212
11,VIX_chg_5d_lag60,0.047297,0.003269,1.068507e-05,0.042487,0.052602,3,30,0.044028,VIX_chg_5d,60,60,0.127624,0.127624,192
12,VIX_chg_20d_lag120,0.044215,0.001232,1.516596e-06,0.041359,0.046152,3,30,0.042983,VIX_chg_20d,120,120,0.313103,0.313103,132
13,SMH_ma60_ratio_lag120,0.043850,0.001086,1.179128e-06,0.041431,0.046171,3,30,0.042764,SMH_ma60_ratio,120,120,-0.197638,0.197638,132
14,SMH_volume_ratio_20d_lag5,0.042285,0.001657,2.746598e-06,0.039245,0.045566,3,30,0.040627,SMH_volume_ratio_20d,5,5,0.195126,0.195126,247
15,SMH_ma20_ratio_lag120,0.040721,0.001256,1.578181e-06,0.039018,0.043972,3,30,0.039465,SMH_ma20_ratio,120,120,-0.312656,0.312656,132
16,TSM_ret_20d_lag120,0.039925,0.001511,2.282005e-06,0.037629,0.043307,3,30,0.038415,TSM_ret_20d,120,120,-0.264108,0.264108,132
17,USDKRW_ret_5d_lag120,0.037754,0.001205,1.451256e-06,0.034878,0.039443,3,30,0.036549,USDKRW_ret_5d,120,120,0.236574,0.236574,132
18,TNX_diff_5d_lag60,0.034374,0.000919,8.439244e-07,0.032628,0.036210,3,30,0.033455,TNX_diff_5d,60,60,-0.203933,0.203933,192
19,DXY_ret_5d_lag120,0.032644,0.001161,1.349066e-06,0.030826,0.035434,3,30,0.031482,DXY_ret_5d,120,120,-0.110706,0.110706,132

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1354, 23)
X_train shape: (1354, 20)
train target 분포:
target_10d_up_0pct
1    766
0    588
Name: count, dtype: int64
target_10d_up_0pct
1    0.565731
0    0.434269
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: random_forest
valid_df 예측 완료

         Date  SMH_adj_close  target_10d_up_0pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.693581     1
1  2026-02-24     419.160004                 0.0    0.659241     1
2  2026-02-25     426.160004                 0.0    0.591687     1
3  2026-02-26     412.010010                 0.0    0.459249     1
4  2026-02-27     406.369995                 0.0    0.442411     1
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.428261     1
60 2026-05-19     543.960022                 NaN    0.433328     1
61 2026-05-20     564.659973                 NaN    0.424459     1
62 2026-05-21     567.880005                 NaN    0.427818     1
63 2026-05-22     576.320007                 NaN    0.438496     1

[64 rows x 5 columns]

예측값 분포:
pred
1    64
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 54
예측 1 개수: 54
예측 1 중 실제 1 개수: 37
예측 1 기준 정확도 precision: 0.6851851851851852

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,10,0.005,1,20,20,random_forest,"{'n_estimators': 800, 'max_depth': 3, 'min_sam...",54,54,...,0.685185,0.685185,1.0,0.813187,0.370429,0.735024,0,17,0,37

[I 2026-05-23 20:54:30,756] Trial 38 finished with value: 0.6851851851851852 and parameters: {'n_days': 10, 'threshold': 0.005, 'top_n': 20, 'pred_threshold': 0.25, 'model_name': 'random_forest', 'rf_n_estimators': 800, 'rf_max_depth': 3, 'rf_min_samples_leaf': 5, 'rf_max_features': 0.5}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 40/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 3, 'threshold': 0.02, 'top_n': 30, 'pred_threshold': 0.45, 'model_name': 'logistic', 'model_params': {'C': 1.0, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 39}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_3d_up_2pct
target_df shape: (1540, 31)
target 분포:
target_3d_up_2pct
0    1034
1     506
Name: count, dtype: int64
lagged_df shape: (1400, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1599

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.159

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1591
TOP feature count: 27
['NVDA_ret_20d_lag1', 'DXY_ret_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma5_ratio_lag10', 'SMH_ma60_ratio_lag1', 'SOXX_ret_5d_lag1', 'VIX_level_lag1', 'VIX_chg_20d_lag40', 'TSM_ret_5d_lag10', 'GOLD_ret_5d_lag120', 'GOLD_ret_20d_lag120', 'TSM_ret_20d_lag40', 'USDKRW_ret_20d_lag40', 'SMH_ret_1d_lag10', 'TNX_level_lag1', 'VIX_chg_5d_lag40', 'SMH_vol_20d_lag60', 'NVDA_ret_5d_lag1', 'SPY_ret_20d_lag120', 'SPY_ret_5d_lag40', 'OIL_ret_20d_lag60', 'OIL_ret_5d_lag60', 'TNX_diff_5d_lag20', 'TNX_diff_20d_lag5', 'DXY_ret_5d_lag60', 'USDKRW_ret_5d_lag60', 'SMH_volume_ratio_20d_lag60']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,NVDA_ret_20d_lag1,0.097206,0.004106,1.686072e-05,0.090497,0.104698,3,30,0.093100,NVDA_ret_20d,1,1,-0.111781,0.111781,250
1,DXY_ret_20d_lag120,0.070614,0.001475,2.175890e-06,0.067993,0.074612,3,30,0.069139,DXY_ret_20d,120,120,-0.105215,0.105215,131
2,SMH_ma20_ratio_lag1,0.061117,0.001850,3.423071e-06,0.057828,0.065284,3,30,0.059267,SMH_ma20_ratio,1,1,-0.175532,0.175532,250
3,SMH_ma5_ratio_lag10,0.056295,0.001797,3.229324e-06,0.052956,0.059930,3,30,0.054498,SMH_ma5_ratio,10,10,-0.235165,0.235165,241
4,SMH_ma60_ratio_lag1,0.054641,0.001352,1.827155e-06,0.051610,0.056799,3,30,0.053289,SMH_ma60_ratio,1,1,-0.137592,0.137592,250
5,SOXX_ret_5d_lag1,0.052406,0.002972,8.835182e-06,0.046161,0.056209,3,30,0.049434,SOXX_ret_5d,1,1,-0.199028,0.199028,250
6,VIX_level_lag1,0.052427,0.003118,9.723011e-06,0.048047,0.057951,3,30,0.049308,VIX_level,1,1,0.126094,0.126094,250
7,VIX_chg_20d_lag40,0.048218,0.001064,1.132742e-06,0.045217,0.050314,3,30,0.047154,VIX_chg_20d,40,40,0.182643,0.182643,211
8,TSM_ret_5d_lag10,0.044915,0.001040,1.082322e-06,0.043098,0.047615,3,30,0.043874,TSM_ret_5d,10,10,-0.179270,0.179270,241
9,GOLD_ret_5d_lag120,0.044546,0.001121,1.255637e-06,0.042196,0.047571,3,30,0.043425,GOLD_ret_5d,120,120,-0.114377,0.114377,131
10,GOLD_ret_20d_lag120,0.043482,0.001129,1.274155e-06,0.040819,0.045993,3,30,0.042353,GOLD_ret_20d,120,120,-0.107223,0.107223,131
11,TSM_ret_20d_lag40,0.043783,0.002185,4.773945e-06,0.039529,0.046979,3,30,0.041598,TSM_ret_20d,40,40,-0.096849,0.096849,211
12,USDKRW_ret_20d_lag40,0.041263,0.001944,3.778063e-06,0.037834,0.044233,3,30,0.039320,USDKRW_ret_20d,40,40,0.152425,0.152425,211
13,SMH_ret_1d_lag10,0.040061,0.001287,1.656742e-06,0.037420,0.042480,3,30,0.038774,SMH_ret_1d,10,10,-0.169190,0.169190,241
14,TNX_level_lag1,0.039300,0.000939,8.809489e-07,0.036885,0.040442,3,30,0.038361,TNX_level,1,1,-0.130603,0.130603,250
15,VIX_chg_5d_lag40,0.039871,0.001533,2.351359e-06,0.037075,0.042152,3,30,0.038338,VIX_chg_5d,40,40,0.159722,0.159722,211
16,SMH_vol_20d_lag60,0.039652,0.001963,3.852132e-06,0.036112,0.042364,3,30,0.037689,SMH_vol_20d,60,60,-0.150076,0.150076,191
17,NVDA_ret_5d_lag1,0.038617,0.001202,1.445857e-06,0.036307,0.040936,3,30,0.037415,NVDA_ret_5d,1,1,-0.181966,0.181966,250
18,SPY_ret_20d_lag120,0.038898,0.001529,2.338266e-06,0.036068,0.041820,3,30,0.037369,SPY_ret_20d,120,120,-0.124476,0.124476,131
19,SPY_ret_5d_lag40,0.038334,0.001174,1.378602e-06,0.035871,0.040135,3,30,0.037160,SPY_ret_5d,40,40,-0.203227,0.203227,211
20,OIL_ret_20d_lag60,0.037912,0.001164,1.354511e-06,0.035438,0.040192,3,30,0.036748,OIL_ret_20d,60,60,0.176462,0.176462,191
21,OIL_ret_5d_lag60,0.037636,0.000917,8.405872e-07,0.035976,0.039511,3,30,0.036719,OIL_ret_5d,60,60,0.224522,0.224522,191
22,TNX_diff_5d_lag20,0.037207,0.001888,3.564735e-06,0.034148,0.040554,3,30,0.035319,TNX_diff_5d,20,20,0.222956,0.222956,231
23,TNX_diff_20d_lag5,0.034490,0.000810,6.567200e-07,0.032826,0.036143,3,30,0.033680,TNX_diff_20d,5,5,0.199132,0.199132,246
24,DXY_ret_5d_lag60,0.033184,0.001202,1.445225e-06,0.030547,0.035256,3,30,0.031982,DXY_ret_5d,60,60,0.168843,0.168843,191
25,USDKRW_ret_5d_lag60,0.032821,0.001043,1.088258e-06,0.031135,0.035053,3,30,0.031778,USDKRW_ret_5d,60,60,0.165262,0.165262,191
26,SMH_volume_ratio_20d_lag60,0.032462,0.001406,1.977196e-06,0.029638,0.035087,3,30,0.031055,SMH_volume_ratio_20d,60,60,0.088810,0.088810,191

============================================================
6. valid_df 생성
============================================================
top feature 수: 27
lag 생성 후 valid_df shape: (1607, 56)
원본 base_feature 제거 후 valid_df shape: (1607, 29)
최종 컬럼 수: 29
target 생성 후 valid_df shape: (1607, 31)
최종 valid_df shape: (64, 31)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 27
train_df shape: (1400, 30)
X_train shape: (1400, 27)
train target 분포:
target_3d_up_2pct
0    942
1    458
Name: count, dtype: int64
target_3d_up_2pct
0    0.672857
1    0.327143
Name: proportion, dtype: float64
valid_df shape: (64, 31)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_3d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                0.0    0.485272     1
1  2026-02-24     419.160004                0.0    0.361857     0
2  2026-02-25     426.160004                0.0    0.309227     0
3  2026-02-26     412.010010                0.0    0.324902     0
4  2026-02-27     406.369995                0.0    0.413644     0
..        ...            ...                ...         ...   ...
59 2026-05-18     546.159973                1.0    0.497869     1
60 2026-05-19     543.960022                1.0    0.511730     1
61 2026-05-20     564.659973                NaN    0.436925     0
62 2026-05-21     567.880005                NaN    0.333002     0
63 2026-05-22     576.320007                NaN    0.307279     0

[64 rows x 5 columns]

예측값 분포:
pred
1    35
0    29
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 61
예측 1 개수: 35
예측 1 중 실제 1 개수: 17
예측 1 기준 정확도 precision: 0.4857142857142857

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,3,0.02,1,30,27,logistic,"{'C': 1.0, 'class_weight': 'balanced', 'max_it...",61,35,...,0.491803,0.485714,0.566667,0.523077,0.487097,0.738273,13,18,13,17

[I 2026-05-23 20:54:47,006] Trial 39 finished with value: 0.4857142857142857 and parameters: {'n_days': 3, 'threshold': 0.02, 'top_n': 30, 'pred_threshold': 0.45, 'model_name': 'logistic', 'logistic_C': 1.0}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 41/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 5, 'threshold': 0.03, 'top_n': 50, 'pred_threshold': 0.5, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.01, 'max_depth': 5}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 40}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_5d_up_3pct
target_df shape: (1538, 31)
target 분포:
target_5d_up_3pct
0    1051
1     487
Name: count, dtype: int64
lagged_df shape: (1398, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1462

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1467

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1461
TOP feature count: 27
['SMH_ma60_ratio_lag1', 'SMH_vol_20d_lag60', 'TNX_level_lag1', 'GOLD_ret_5d_lag120', 'VIX_level_lag1', 'VIX_chg_20d_lag40', 'OIL_ret_20d_lag60', 'TNX_diff_5d_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag40', 'DXY_ret_20d_lag5', 'USDKRW_ret_20d_lag40', 'USDKRW_ret_5d_lag1', 'GOLD_ret_20d_lag1', 'DXY_ret_5d_lag120', 'TNX_diff_20d_lag5', 'SMH_volume_ratio_20d_lag20', 'SMH_ma20_ratio_lag40', 'OIL_ret_5d_lag60', 'NVDA_ret_20d_lag120', 'TSM_ret_5d_lag40', 'SMH_ret_1d_lag10', 'NVDA_ret_5d_lag40', 'VIX_chg_5d_lag40', 'SMH_ma5_ratio_lag40', 'SPY_ret_5d_lag40', 'SOXX_ret_5d_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_ma60_ratio_lag1,0.078441,0.001863,3.470473e-06,0.074815,0.082776,3,30,0.076578,SMH_ma60_ratio,1,1,-0.172629,0.172629,251
1,SMH_vol_20d_lag60,0.069105,0.001919,3.684021e-06,0.065530,0.073300,3,30,0.067185,SMH_vol_20d,60,60,-0.189027,0.189027,192
2,TNX_level_lag1,0.069129,0.002486,6.181890e-06,0.063543,0.073483,3,30,0.066643,TNX_level,1,1,-0.191147,0.191147,251
3,GOLD_ret_5d_lag120,0.060355,0.002163,4.676538e-06,0.055174,0.064143,3,30,0.058193,GOLD_ret_5d,120,120,-0.218877,0.218877,132
4,VIX_level_lag1,0.059673,0.002784,7.752705e-06,0.055123,0.064462,3,30,0.056889,VIX_level,1,1,0.153605,0.153605,251
5,VIX_chg_20d_lag40,0.056407,0.001996,3.983510e-06,0.052414,0.060620,3,30,0.054411,VIX_chg_20d,40,40,0.225283,0.225283,212
6,OIL_ret_20d_lag60,0.053212,0.002001,4.002755e-06,0.049749,0.057240,3,30,0.051212,OIL_ret_20d,60,60,0.237427,0.237427,192
7,TNX_diff_5d_lag20,0.053372,0.002314,5.355884e-06,0.048577,0.056207,3,30,0.051058,TNX_diff_5d,20,20,0.185217,0.185217,232
8,SPY_ret_20d_lag120,0.048811,0.001230,1.513431e-06,0.045170,0.051545,3,30,0.047581,SPY_ret_20d,120,120,-0.195151,0.195151,132
9,TSM_ret_20d_lag40,0.049182,0.002547,6.484842e-06,0.045876,0.055137,3,30,0.046635,TSM_ret_20d,40,40,-0.186887,0.186887,212
10,DXY_ret_20d_lag5,0.044759,0.001859,3.455597e-06,0.040812,0.048252,3,30,0.042900,DXY_ret_20d,5,5,-0.123856,0.123856,247
11,USDKRW_ret_20d_lag40,0.044490,0.001832,3.357242e-06,0.041625,0.048470,3,30,0.042657,USDKRW_ret_20d,40,40,0.204293,0.204293,212
12,USDKRW_ret_5d_lag1,0.042260,0.001278,1.633171e-06,0.039336,0.045023,3,30,0.040982,USDKRW_ret_5d,1,1,-0.135928,0.135928,251
13,GOLD_ret_20d_lag1,0.039152,0.002092,4.374883e-06,0.035630,0.042243,3,30,0.037061,GOLD_ret_20d,1,1,0.185988,0.185988,251
14,DXY_ret_5d_lag120,0.037692,0.000937,8.787204e-07,0.035442,0.040194,3,30,0.036755,DXY_ret_5d,120,120,0.201244,0.201244,132
15,TNX_diff_20d_lag5,0.038099,0.001366,1.866021e-06,0.035694,0.040829,3,30,0.036733,TNX_diff_20d,5,5,0.197432,0.197432,247
16,SMH_volume_ratio_20d_lag20,0.037433,0.000858,7.356760e-07,0.035823,0.038871,3,30,0.036576,SMH_volume_ratio_20d,20,20,-0.106779,0.106779,232
17,SMH_ma20_ratio_lag40,0.036965,0.000649,4.216770e-07,0.035800,0.038710,3,30,0.036315,SMH_ma20_ratio,40,40,-0.224204,0.224204,212
18,OIL_ret_5d_lag60,0.035339,0.000720,5.182253e-07,0.033657,0.036754,3,30,0.034619,OIL_ret_5d,60,60,0.222858,0.222858,192
19,NVDA_ret_20d_lag120,0.035294,0.000913,8.331741e-07,0.033754,0.037211,3,30,0.034381,NVDA_ret_20d,120,120,-0.135504,0.135504,132
20,TSM_ret_5d_lag40,0.034814,0.001188,1.410571e-06,0.032626,0.037546,3,30,0.033626,TSM_ret_5d,40,40,-0.269283,0.269283,212
21,SMH_ret_1d_lag10,0.034392,0.000863,7.439626e-07,0.033020,0.036370,3,30,0.033530,SMH_ret_1d,10,10,-0.143609,0.143609,242
22,NVDA_ret_5d_lag40,0.031941,0.001019,1.038905e-06,0.029972,0.033729,3,30,0.030922,NVDA_ret_5d,40,40,-0.152996,0.152996,212
23,VIX_chg_5d_lag40,0.032318,0.001417,2.006900e-06,0.029677,0.034358,3,30,0.030901,VIX_chg_5d,40,40,0.243917,0.243917,212
24,SMH_ma5_ratio_lag40,0.030392,0.000914,8.346690e-07,0.028814,0.031679,3,30,0.029479,SMH_ma5_ratio,40,40,-0.185997,0.185997,212
25,SPY_ret_5d_lag40,0.030118,0.000958,9.179304e-07,0.028305,0.032695,3,30,0.029160,SPY_ret_5d,40,40,-0.334969,0.334969,212
26,SOXX_ret_5d_lag40,0.026600,0.001038,1.078219e-06,0.024692,0.028338,3,30,0.025562,SOXX_ret_5d,40,40,-0.234680,0.234680,212

============================================================
6. valid_df 생성
============================================================
top feature 수: 27
lag 생성 후 valid_df shape: (1607, 56)
원본 base_feature 제거 후 valid_df shape: (1607, 29)
최종 컬럼 수: 29
target 생성 후 valid_df shape: (1607, 31)
최종 valid_df shape: (64, 31)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 27
train_df shape: (1398, 30)
X_train shape: (1398, 27)
train target 분포:
target_5d_up_3pct
0    958
1    440
Name: count, dtype: int64
target_5d_up_3pct
0    0.685265
1    0.314735
Name: proportion, dtype: float64
valid_df shape: (64, 31)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_5d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                0.0    0.268633     0
1  2026-02-24     419.160004                0.0    0.290240     0
2  2026-02-25     426.160004                0.0    0.283689     0
3  2026-02-26     412.010010                0.0    0.248604     0
4  2026-02-27     406.369995                0.0    0.215774     0
..        ...            ...                ...         ...   ...
59 2026-05-18     546.159973                NaN    0.203009     0
60 2026-05-19     543.960022                NaN    0.242639     0
61 2026-05-20     564.659973                NaN    0.253673     0
62 2026-05-21     567.880005                NaN    0.424920     0
63 2026-05-22     576.320007                NaN    0.400106     0

[64 rows x 5 columns]

예측값 분포:
pred
0    63
1     1
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 59
예측 1 개수: 1
예측 1 중 실제 1 개수: 1
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,5,0.03,1,50,27,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.01, '...",59,1,...,0.542373,1.0,0.035714,0.068966,0.532258,0.785472,31,0,27,1

[I 2026-05-23 20:55:06,389] Trial 40 finished with value: 0.3333333333333333 and parameters: {'n_days': 5, 'threshold': 0.03, 'top_n': 50, 'pred_threshold': 0.5, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.01, 'gb_max_depth': 5}. Best is trial 6 with value: 1.0.
[I 2026-05-23 20:55:06,406] Trial 41 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.
[I 2026-05-23 20:55:06,423] Trial 42 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 42/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 41}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204741_optuna_holdout_trial_0011
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 43/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 42}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204741_optuna_holdout_trial_0011
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 44/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 43}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.555357     0
1  2026-02-24     419.160004                 0.0    0.646397     1
2  2026-02-25     426.160004                 0.0    0.597912     0
3  2026-02-26     412.010010                 0.0    0.457527     0
4  2026-02-27     406.369995                 0.0    0.545480     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.619136     1
60 2026-05-19     543.960022                 NaN    0.842201     1
61 2026-05-20     564.659973                 NaN    0.492613     0
62 2026-05-21     567.880005                 NaN    0.405804     0
63 2026-05-22     576.320007                 NaN    0.501921     0

[64 rows x 5 columns]

예측값 분포:
pred
0    37
1    27
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 10
예측 1 중 실제 1 개수: 9
예측 1 기준 정확도 precision: 0.9

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.03, '...",44,10,...,0.409091,0.9,0.264706,0.409091,0.370588,0.77784,9,1,25,9

[I 2026-05-23 20:55:23,844] Trial 43 finished with value: 0.9 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 45/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 100, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 44}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.562399     0
1  2026-02-24     419.160004                 0.0    0.582911     0
2  2026-02-25     426.160004                 0.0    0.567501     0
3  2026-02-26     412.010010                 0.0    0.519801     0
4  2026-02-27     406.369995                 0.0    0.543101     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.587647     0
60 2026-05-19     543.960022                 NaN    0.711670     1
61 2026-05-20     564.659973                 NaN    0.377029     0
62 2026-05-21     567.880005                 NaN    0.354426     0
63 2026-05-22     576.320007                 NaN    0.371553     0

[64 rows x 5 columns]

예측값 분포:
pred
0    61
1     3
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 1
예측 1 중 실제 1 개수: 1
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,gradient_boosting,"{'n_estimators': 100, 'learning_rate': 0.03, '...",44,1,...,0.25,1.0,0.029412,0.057143,0.430882,0.688549,10,0,33,1

[I 2026-05-23 20:55:40,331] Trial 44 finished with value: 0.3333333333333333 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'gb_n_estimators': 100, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 46/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 10, 'threshold': 0.01, 'top_n': 20, 'pred_threshold': 0.55, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 45}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_10d_up_1pct
target_df shape: (1533, 31)
target 분포:
target_10d_up_1pct
1    837
0    696
Name: count, dtype: int64
lagged_df shape: (1393, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1422

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1419

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.142
TOP feature count: 20
['TNX_level_lag120', 'USDKRW_ret_20d_lag3', 'DXY_ret_20d_lag120', 'SMH_vol_20d_lag40', 'SMH_ma60_ratio_lag40', 'OIL_ret_20d_lag40', 'TSM_ret_20d_lag1', 'GOLD_ret_20d_lag40', 'TNX_diff_20d_lag5', 'VIX_level_lag40', 'NVDA_ret_20d_lag120', 'SPY_ret_20d_lag120', 'VIX_chg_20d_lag120', 'VIX_chg_5d_lag60', 'USDKRW_ret_5d_lag120', 'TSM_ret_5d_lag40', 'SMH_ma20_ratio_lag120', 'SOXX_ret_5d_lag40', 'SMH_volume_ratio_20d_lag5', 'SPY_ret_5d_lag60']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.103907,0.005387,2.902087e-05,0.094888,0.112756,3,30,0.098520,TNX_level,120,120,-0.277689,0.277689,132
1,USDKRW_ret_20d_lag3,0.096126,0.003008,9.047242e-06,0.089867,0.100682,3,30,0.093118,USDKRW_ret_20d,3,3,-0.343097,0.343097,249
2,DXY_ret_20d_lag120,0.078045,0.003997,1.597614e-05,0.070637,0.084179,3,30,0.074048,DXY_ret_20d,120,120,-0.284585,0.284585,132
3,SMH_vol_20d_lag40,0.076580,0.003149,9.915582e-06,0.071988,0.083066,3,30,0.073431,SMH_vol_20d,40,40,0.227843,0.227843,212
4,SMH_ma60_ratio_lag40,0.074700,0.001793,3.214114e-06,0.071572,0.079336,3,30,0.072907,SMH_ma60_ratio,40,40,-0.197085,0.197085,212
5,OIL_ret_20d_lag40,0.067693,0.002280,5.197514e-06,0.063479,0.071986,3,30,0.065413,OIL_ret_20d,40,40,-0.236786,0.236786,212
6,TSM_ret_20d_lag1,0.064156,0.002883,8.313326e-06,0.059290,0.069357,3,30,0.061273,TSM_ret_20d,1,1,0.262393,0.262393,251
7,GOLD_ret_20d_lag40,0.062099,0.002347,5.510249e-06,0.058111,0.066442,3,30,0.059752,GOLD_ret_20d,40,40,-0.119939,0.119939,212
8,TNX_diff_20d_lag5,0.056086,0.001336,1.783959e-06,0.053196,0.058570,3,30,0.054750,TNX_diff_20d,5,5,0.351351,0.351351,247
9,VIX_level_lag40,0.050925,0.001653,2.730788e-06,0.047678,0.054358,3,30,0.049272,VIX_level,40,40,0.157321,0.157321,212
10,NVDA_ret_20d_lag120,0.049525,0.001208,1.458463e-06,0.046797,0.052494,3,30,0.048318,NVDA_ret_20d,120,120,-0.250247,0.250247,132
11,SPY_ret_20d_lag120,0.048551,0.000909,8.262490e-07,0.047161,0.050575,3,30,0.047642,SPY_ret_20d,120,120,-0.322768,0.322768,132
12,VIX_chg_20d_lag120,0.049007,0.001606,2.577927e-06,0.045453,0.051330,3,30,0.047401,VIX_chg_20d,120,120,0.301368,0.301368,132
13,VIX_chg_5d_lag60,0.047749,0.001725,2.976541e-06,0.044553,0.051420,3,30,0.046024,VIX_chg_5d,60,60,0.117848,0.117848,192
14,USDKRW_ret_5d_lag120,0.047175,0.001310,1.716260e-06,0.043949,0.049513,3,30,0.045865,USDKRW_ret_5d,120,120,0.218012,0.218012,132
15,TSM_ret_5d_lag40,0.045821,0.004358,1.899553e-05,0.038392,0.051741,3,30,0.041463,TSM_ret_5d,40,40,-0.286196,0.286196,212
16,SMH_ma20_ratio_lag120,0.039394,0.001475,2.174494e-06,0.037527,0.041883,3,30,0.037920,SMH_ma20_ratio,120,120,-0.283655,0.283655,132
17,SOXX_ret_5d_lag40,0.038236,0.001906,3.632410e-06,0.034135,0.041498,3,30,0.036330,SOXX_ret_5d,40,40,-0.214943,0.214943,212
18,SMH_volume_ratio_20d_lag5,0.032505,0.001337,1.788600e-06,0.029999,0.035025,3,30,0.031167,SMH_volume_ratio_20d,5,5,0.176130,0.176130,247
19,SPY_ret_5d_lag60,0.031578,0.000775,6.013645e-07,0.030016,0.033016,3,30,0.030803,SPY_ret_5d,60,60,-0.177059,0.177059,192

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1393, 23)
X_train shape: (1393, 20)
train target 분포:
target_10d_up_1pct
1    749
0    644
Name: count, dtype: int64
target_10d_up_1pct
1    0.537688
0    0.462312
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_10d_up_1pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.916824     1
1  2026-02-24     419.160004                 0.0    0.853905     1
2  2026-02-25     426.160004                 0.0    0.807108     1
3  2026-02-26     412.010010                 0.0    0.532035     0
4  2026-02-27     406.369995                 0.0    0.505475     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.382027     0
60 2026-05-19     543.960022                 NaN    0.589140     1
61 2026-05-20     564.659973                 NaN    0.518907     0
62 2026-05-21     567.880005                 NaN    0.447390     0
63 2026-05-22     576.320007                 NaN    0.322792     0

[64 rows x 5 columns]

예측값 분포:
pred
0    37
1    27
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 54
예측 1 개수: 25
예측 1 중 실제 1 개수: 13
예측 1 기준 정확도 precision: 0.52

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,10,0.01,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.03, '...",54,25,...,0.333333,0.52,0.351351,0.419355,0.243243,0.840671,5,12,24,13

[I 2026-05-23 20:55:58,244] Trial 45 finished with value: 0.52 and parameters: {'n_days': 10, 'threshold': 0.01, 'top_n': 20, 'pred_threshold': 0.55, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.
[I 2026-05-23 20:55:58,277] Trial 46 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'logistic', 'logistic_C': 1.0}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 47/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'logistic', 'model_params': {'C': 1.0, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 46}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204639_optuna_holdout_trial_0007
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 48/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 10, 'threshold': 0.03, 'top_n': 10, 'pred_threshold': 0.75, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.01, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 47}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_10d_up_3pct
target_df shape: (1533, 31)
target 분포:
target_10d_up_3pct
0    907
1    626
Name: count, dtype: int64
lagged_df shape: (1393, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1431

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1425

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1433
TOP feature count: 10
['USDKRW_ret_20d_lag1', 'OIL_ret_20d_lag40', 'TNX_level_lag120', 'DXY_ret_20d_lag120', 'SMH_vol_20d_lag40', 'VIX_level_lag1', 'TNX_diff_20d_lag5', 'TSM_ret_20d_lag40', 'SMH_ma20_ratio_lag40', 'SMH_ma60_ratio_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,USDKRW_ret_20d_lag1,0.126034,0.002997,0.000009,0.119453,0.133261,3,30,0.123037,USDKRW_ret_20d,1,1,-0.408214,0.408214,251
1,OIL_ret_20d_lag40,0.096463,0.002678,0.000007,0.091112,0.102565,3,30,0.093785,OIL_ret_20d,40,40,-0.318626,0.318626,212
2,TNX_level_lag120,0.080627,0.002211,0.000005,0.074639,0.086368,3,30,0.078416,TNX_level,120,120,-0.195924,0.195924,132
3,DXY_ret_20d_lag120,0.073622,0.001373,0.000002,0.070474,0.075453,3,30,0.072249,DXY_ret_20d,120,120,-0.293154,0.293154,132
4,SMH_vol_20d_lag40,0.063920,0.001438,0.000002,0.061510,0.067246,3,30,0.062482,SMH_vol_20d,40,40,0.281937,0.281937,212
5,VIX_level_lag1,0.059403,0.001746,0.000003,0.056041,0.063472,3,30,0.057657,VIX_level,1,1,0.240225,0.240225,251
6,TNX_diff_20d_lag5,0.059302,0.002218,0.000005,0.054268,0.064710,3,30,0.057085,TNX_diff_20d,5,5,0.307873,0.307873,247
7,TSM_ret_20d_lag40,0.055242,0.001483,0.000002,0.052429,0.058885,3,30,0.053759,TSM_ret_20d,40,40,-0.349006,0.349006,212
8,SMH_ma20_ratio_lag40,0.054793,0.001213,0.000001,0.052111,0.057220,3,30,0.053580,SMH_ma20_ratio,40,40,-0.288530,0.288530,212
9,SMH_ma60_ratio_lag40,0.053386,0.001023,0.000001,0.051840,0.055668,3,30,0.052363,SMH_ma60_ratio,40,40,-0.297396,0.297396,212

============================================================
6. valid_df 생성
============================================================
top feature 수: 10
lag 생성 후 valid_df shape: (1607, 22)
원본 base_feature 제거 후 valid_df shape: (1607, 12)
최종 컬럼 수: 12
target 생성 후 valid_df shape: (1607, 14)
최종 valid_df shape: (64, 14)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 10
train_df shape: (1393, 13)
X_train shape: (1393, 10)
train target 분포:
target_10d_up_3pct
0    834
1    559
Name: count, dtype: int64
target_10d_up_3pct
0    0.598708
1    0.401292
Name: proportion, dtype: float64
valid_df shape: (64, 14)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_10d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.534647     0
1  2026-02-24     419.160004                 0.0    0.508205     0
2  2026-02-25     426.160004                 0.0    0.673061     0
3  2026-02-26     412.010010                 0.0    0.166515     0
4  2026-02-27     406.369995                 0.0    0.460351     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.134958     0
60 2026-05-19     543.960022                 NaN    0.280482     0
61 2026-05-20     564.659973                 NaN    0.418285     0
62 2026-05-21     567.880005                 NaN    0.352319     0
63 2026-05-22     576.320007                 NaN    0.223617     0

[64 rows x 5 columns]

예측값 분포:
pred
0    58
1     6
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 54
예측 1 개수: 6
예측 1 중 실제 1 개수: 4
예측 1 기준 정확도 precision: 0.6666666666666666

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,10,0.03,1,10,10,hist_gradient_boosting,"{'max_iter': 300, 'learning_rate': 0.01, 'max_...",54,6,...,0.462963,0.666667,0.129032,0.216216,0.291725,1.1109,21,2,27,4

[I 2026-05-23 20:56:16,541] Trial 47 finished with value: 0.6666666666666666 and parameters: {'n_days': 10, 'threshold': 0.03, 'top_n': 10, 'pred_threshold': 0.75, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.01, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 49/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.015, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 4}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 48}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_1pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_1pct
1    875
0    648
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1282

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1291

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1292
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'VIX_chg_20d_lag120', 'NVDA_ret_20d_lag1', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'SMH_ma20_ratio_lag1', 'USDKRW_ret_20d_lag40', 'DXY_ret_5d_lag120', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'VIX_level_lag20', 'VIX_chg_5d_lag120', 'OIL_ret_20d_lag120', 'SMH_ma60_ratio_lag1', 'TNX_diff_5d_lag5', 'GOLD_ret_20d_lag120', 'OIL_ret_5d_lag10', 'GOLD_ret_5d_lag60', 'SPY_ret_5d_lag120']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118484,0.002821,7.957216e-06,0.109722,0.124056,3,30,0.115663,SMH_vol_20d,120,120,-0.303085,0.303085,132
1,TNX_level_lag20,0.098508,0.003546,1.257577e-05,0.091406,0.103231,3,30,0.094962,TNX_level,20,20,-0.312171,0.312171,232
2,VIX_chg_20d_lag120,0.084307,0.004767,2.272657e-05,0.074815,0.090386,3,30,0.079540,VIX_chg_20d,120,120,0.361218,0.361218,132
3,NVDA_ret_20d_lag1,0.077011,0.002656,7.056867e-06,0.073438,0.082286,3,30,0.074355,NVDA_ret_20d,1,1,0.255267,0.255267,251
4,DXY_ret_20d_lag60,0.073972,0.003501,1.226018e-05,0.065067,0.079207,3,30,0.070471,DXY_ret_20d,60,60,-0.224007,0.224007,192
5,TNX_diff_20d_lag1,0.067782,0.002068,4.275689e-06,0.063536,0.070710,3,30,0.065714,TNX_diff_20d,1,1,0.409580,0.409580,251
6,SMH_ma20_ratio_lag1,0.064028,0.003588,1.287606e-05,0.057455,0.069127,3,30,0.060440,SMH_ma20_ratio,1,1,0.278312,0.278312,251
7,USDKRW_ret_20d_lag40,0.054209,0.001347,1.813178e-06,0.051963,0.056946,3,30,0.052862,USDKRW_ret_20d,40,40,0.344971,0.344971,212
8,DXY_ret_5d_lag120,0.053646,0.002349,5.516362e-06,0.049564,0.057537,3,30,0.051297,DXY_ret_5d,120,120,-0.258618,0.258618,132
9,SPY_ret_20d_lag120,0.053166,0.002152,4.629870e-06,0.049174,0.057806,3,30,0.051015,SPY_ret_20d,120,120,-0.257846,0.257846,132
10,TSM_ret_20d_lag1,0.051027,0.002671,7.136912e-06,0.045914,0.054292,3,30,0.048356,TSM_ret_20d,1,1,0.323766,0.323766,251
11,VIX_level_lag20,0.051332,0.003401,1.156368e-05,0.046068,0.056499,3,30,0.047931,VIX_level,20,20,0.256886,0.256886,232
12,VIX_chg_5d_lag120,0.050033,0.002465,6.074460e-06,0.045693,0.053445,3,30,0.047568,VIX_chg_5d,120,120,0.140989,0.140989,132
13,OIL_ret_20d_lag120,0.046951,0.001639,2.685367e-06,0.043890,0.051856,3,30,0.045313,OIL_ret_20d,120,120,0.317093,0.317093,132
14,SMH_ma60_ratio_lag1,0.045240,0.000929,8.634352e-07,0.043842,0.047279,3,30,0.044311,SMH_ma60_ratio,1,1,0.195063,0.195063,251
15,TNX_diff_5d_lag5,0.044214,0.002358,5.561184e-06,0.039888,0.047489,3,30,0.041856,TNX_diff_5d,5,5,0.211260,0.211260,247
16,GOLD_ret_20d_lag120,0.038123,0.001246,1.553398e-06,0.035914,0.041085,3,30,0.036877,GOLD_ret_20d,120,120,-0.347004,0.347004,132
17,OIL_ret_5d_lag10,0.030618,0.000852,7.251870e-07,0.029380,0.032145,3,30,0.029766,OIL_ret_5d,10,10,0.189850,0.189850,242
18,GOLD_ret_5d_lag60,0.029241,0.000940,8.827980e-07,0.027493,0.030948,3,30,0.028301,GOLD_ret_5d,60,60,0.194501,0.194501,192
19,SPY_ret_5d_lag120,0.028214,0.000910,8.287835e-07,0.026523,0.029787,3,30,0.027304,SPY_ret_5d,120,120,-0.236798,0.236798,132

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_1pct
1    773
0    610
Name: count, dtype: int64
target_20d_up_1pct
1    0.55893
0    0.44107
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_1pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.562921     0
1  2026-02-24     419.160004                 0.0    0.832070     1
2  2026-02-25     426.160004                 0.0    0.341512     0
3  2026-02-26     412.010010                 0.0    0.783079     1
4  2026-02-27     406.369995                 0.0    0.375076     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.728955     1
60 2026-05-19     543.960022                 NaN    0.787328     1
61 2026-05-20     564.659973                 NaN    0.614805     1
62 2026-05-21     567.880005                 NaN    0.705325     1
63 2026-05-22     576.320007                 NaN    0.820287     1

[64 rows x 5 columns]

예측값 분포:
pred
1    44
0    20
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 27
예측 1 중 실제 1 개수: 21
예측 1 기준 정확도 precision: 0.7777777777777778

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.015,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.1, 'm...",44,27,...,0.568182,0.777778,0.617647,0.688525,0.579412,0.685769,4,6,13,21

[I 2026-05-23 20:56:35,302] Trial 48 finished with value: 0.7777777777777778 and parameters: {'n_days': 20, 'threshold': 0.015, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.1, 'gb_max_depth': 4}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 50/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 50, 'pred_threshold': 0.7, 'model_name': 'random_forest', 'model_params': {'n_estimators': 300, 'max_depth': 10, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'class_weight': 'balanced'}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 49}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 27
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1', 'NVDA_ret_5d_lag60', 'SPY_ret_5d_lag120', 'SOXX_ret_5d_lag120', 'USDKRW_ret_5d_lag40', 'SMH_ma5_ratio_lag60', 'SMH_volume_ratio_20d_lag120', 'SMH_ret_1d_lag60']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251
20,NVDA_ret_5d_lag60,0.026639,0.001112,1.237156e-06,0.024575,0.028571,3,30,0.025526,NVDA_ret_5d,60,60,-0.251682,0.251682,192
21,SPY_ret_5d_lag120,0.025915,0.000723,5.228773e-07,0.024417,0.027251,3,30,0.025192,SPY_ret_5d,120,120,-0.252525,0.252525,132
22,SOXX_ret_5d_lag120,0.025491,0.000480,2.300800e-07,0.024445,0.026427,3,30,0.025011,SOXX_ret_5d,120,120,-0.254602,0.254602,132
23,USDKRW_ret_5d_lag40,0.025065,0.000769,5.909936e-07,0.023745,0.026481,3,30,0.024296,USDKRW_ret_5d,40,40,0.146047,0.146047,212
24,SMH_ma5_ratio_lag60,0.021075,0.000702,4.932835e-07,0.019899,0.022518,3,30,0.020372,SMH_ma5_ratio,60,60,-0.238638,0.238638,192
25,SMH_volume_ratio_20d_lag120,0.020579,0.001005,1.009657e-06,0.018787,0.022134,3,30,0.019574,SMH_volume_ratio_20d,120,120,0.263883,0.263883,132
26,SMH_ret_1d_lag60,0.014771,0.000621,3.856972e-07,0.013554,0.015965,3,30,0.014150,SMH_ret_1d,60,60,-0.167087,0.167087,192

============================================================
6. valid_df 생성
============================================================
top feature 수: 27
lag 생성 후 valid_df shape: (1607, 56)
원본 base_feature 제거 후 valid_df shape: (1607, 29)
최종 컬럼 수: 29
target 생성 후 valid_df shape: (1607, 31)
최종 valid_df shape: (64, 31)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 27
train_df shape: (1383, 30)
X_train shape: (1383, 27)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 31)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: random_forest
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.559710     0
1  2026-02-24     419.160004                 0.0    0.545041     0
2  2026-02-25     426.160004                 0.0    0.541468     0
3  2026-02-26     412.010010                 0.0    0.551060     0
4  2026-02-27     406.369995                 0.0    0.554390     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.510196     0
60 2026-05-19     543.960022                 NaN    0.561212     0
61 2026-05-20     564.659973                 NaN    0.487823     0
62 2026-05-21     567.880005                 NaN    0.519636     0
63 2026-05-22     576.320007                 NaN    0.497826     0

[64 rows x 5 columns]

예측값 분포:
pred
0    64
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 0
예측 1 중 실제 1 개수: 0
예측 1 기준 정확도 precision: nan

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,50,27,random_forest,"{'n_estimators': 300, 'max_depth': 10, 'min_sa...",44,0,...,0.227273,0.0,0.0,0.0,0.279412,0.719159,10,0,34,0

[I 2026-05-23 20:56:51,722] Trial 49 finished with value: 0.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 50, 'pred_threshold': 0.7, 'model_name': 'random_forest', 'rf_n_estimators': 300, 'rf_max_depth': 10, 'rf_min_samples_leaf': 5, 'rf_max_features': 'sqrt'}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 51/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 3, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'logistic', 'model_params': {'C': 10.0, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 50}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_3d_up_3pct
target_df shape: (1540, 31)
target 분포:
target_3d_up_3pct
0    1195
1     345
Name: count, dtype: int64
lagged_df shape: (1400, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1259

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.127

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1269
TOP feature count: 20
['SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag1', 'TNX_level_lag120', 'VIX_level_lag1', 'SPY_ret_5d_lag1', 'SMH_ma5_ratio_lag1', 'SOXX_ret_5d_lag1', 'SMH_vol_20d_lag3', 'GOLD_ret_5d_lag120', 'SMH_ret_1d_lag1', 'SPY_ret_20d_lag40', 'TNX_diff_20d_lag5', 'DXY_ret_5d_lag60', 'OIL_ret_20d_lag20', 'NVDA_ret_20d_lag40', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag20', 'VIX_chg_5d_lag120', 'NVDA_ret_5d_lag1', 'DXY_ret_20d_lag5']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_ma20_ratio_lag1,0.056589,0.001591,2.531595e-06,0.053024,0.059396,3,30,0.054998,SMH_ma20_ratio,1,1,-0.221458,0.221458,250
1,SMH_ma60_ratio_lag1,0.052707,0.002447,5.987327e-06,0.049894,0.057618,3,30,0.050260,SMH_ma60_ratio,1,1,-0.210906,0.210906,250
2,TNX_level_lag120,0.050870,0.001302,1.695808e-06,0.048159,0.053889,3,30,0.049568,TNX_level,120,120,-0.095157,0.095157,131
3,VIX_level_lag1,0.045134,0.001281,1.639994e-06,0.042055,0.047115,3,30,0.043854,VIX_level,1,1,0.247865,0.247865,250
4,SPY_ret_5d_lag1,0.044011,0.001323,1.750608e-06,0.041346,0.046226,3,30,0.042688,SPY_ret_5d,1,1,-0.218958,0.218958,250
5,SMH_ma5_ratio_lag1,0.042944,0.001415,2.002289e-06,0.041179,0.046525,3,30,0.041529,SMH_ma5_ratio,1,1,-0.216861,0.216861,250
6,SOXX_ret_5d_lag1,0.041604,0.001194,1.425218e-06,0.039081,0.044079,3,30,0.040410,SOXX_ret_5d,1,1,-0.250730,0.250730,250
7,SMH_vol_20d_lag3,0.039820,0.001543,2.381931e-06,0.036781,0.043012,3,30,0.038277,SMH_vol_20d,3,3,0.174897,0.174897,248
8,GOLD_ret_5d_lag120,0.037840,0.000945,8.938618e-07,0.035847,0.040030,3,30,0.036894,GOLD_ret_5d,120,120,-0.241289,0.241289,131
9,SMH_ret_1d_lag1,0.036673,0.001014,1.028800e-06,0.034861,0.039198,3,30,0.035659,SMH_ret_1d,1,1,-0.122369,0.122369,250
10,SPY_ret_20d_lag40,0.036011,0.001082,1.169956e-06,0.033436,0.038535,3,30,0.034930,SPY_ret_20d,40,40,-0.196954,0.196954,211
11,TNX_diff_20d_lag5,0.036665,0.002214,4.899699e-06,0.032652,0.040637,3,30,0.034451,TNX_diff_20d,5,5,0.221646,0.221646,246
12,DXY_ret_5d_lag60,0.035643,0.001253,1.570409e-06,0.032152,0.037665,3,30,0.034390,DXY_ret_5d,60,60,0.192636,0.192636,191
13,OIL_ret_20d_lag20,0.036393,0.002864,8.205027e-06,0.033187,0.041896,3,30,0.033529,OIL_ret_20d,20,20,-0.144221,0.144221,231
14,NVDA_ret_20d_lag40,0.034605,0.001088,1.183386e-06,0.032135,0.037136,3,30,0.033517,NVDA_ret_20d,40,40,-0.144158,0.144158,211
15,GOLD_ret_20d_lag120,0.033901,0.000752,5.650846e-07,0.032428,0.035390,3,30,0.033149,GOLD_ret_20d,120,120,-0.163086,0.163086,131
16,TNX_diff_5d_lag20,0.033100,0.001087,1.182453e-06,0.031154,0.035631,3,30,0.032013,TNX_diff_5d,20,20,0.229786,0.229786,231
17,VIX_chg_5d_lag120,0.033648,0.002350,5.522816e-06,0.029115,0.038062,3,30,0.031298,VIX_chg_5d,120,120,0.188099,0.188099,131
18,NVDA_ret_5d_lag1,0.031730,0.000798,6.363294e-07,0.030435,0.033592,3,30,0.030932,NVDA_ret_5d,1,1,-0.199486,0.199486,250
19,DXY_ret_20d_lag5,0.031600,0.000716,5.126522e-07,0.030105,0.032995,3,30,0.030884,DXY_ret_20d,5,5,-0.135316,0.135316,246

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1400, 23)
X_train shape: (1400, 20)
train target 분포:
target_3d_up_3pct
0    1087
1     313
Name: count, dtype: int64
target_3d_up_3pct
0    0.776429
1    0.223571
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_3d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                0.0    0.453375     0
1  2026-02-24     419.160004                0.0    0.466036     0
2  2026-02-25     426.160004                0.0    0.355999     0
3  2026-02-26     412.010010                0.0    0.359766     0
4  2026-02-27     406.369995                0.0    0.372174     0
..        ...            ...                ...         ...   ...
59 2026-05-18     546.159973                1.0    0.570597     0
60 2026-05-19     543.960022                1.0    0.585188     0
61 2026-05-20     564.659973                NaN    0.560814     0
62 2026-05-21     567.880005                NaN    0.437840     0
63 2026-05-22     576.320007                NaN    0.358474     0

[64 rows x 5 columns]

예측값 분포:
pred
0    62
1     2
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 61
예측 1 개수: 2
예측 1 중 실제 1 개수: 1
예측 1 기준 정확도 precision: 0.5

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,3,0.03,1,20,20,logistic,"{'C': 10.0, 'class_weight': 'balanced', 'max_i...",61,2,...,0.622951,0.5,0.043478,0.08,0.447368,0.729479,37,1,22,1

[I 2026-05-23 20:57:08,192] Trial 50 finished with value: 0.3333333333333333 and parameters: {'n_days': 3, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'logistic', 'logistic_C': 10.0}. Best is trial 6 with value: 1.0.
[I 2026-05-23 20:57:08,214] Trial 51 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.
[I 2026-05-23 20:57:08,235] Trial 52 finished with value: 0.9 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 52/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 51}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204741_optuna_holdout_trial_0011
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 53/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 52}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_205523_optuna_holdout_trial_0043
기존 test_precision: 0.9

====================================================================================================
OPTUNA HOLDOUT TRIAL 54/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.8, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 53}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.555357     0
1  2026-02-24     419.160004                 0.0    0.646397     0
2  2026-02-25     426.160004                 0.0    0.597912     0
3  2026-02-26     412.010010                 0.0    0.457527     0
4  2026-02-27     406.369995                 0.0    0.545480     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.619136     0
60 2026-05-19     543.960022                 NaN    0.842201     1
61 2026-05-20     564.659973                 NaN    0.492613     0
62 2026-05-21     567.880005                 NaN    0.405804     0
63 2026-05-22     576.320007                 NaN    0.501921     0

[64 rows x 5 columns]

예측값 분포:
pred
0    61
1     3
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 0
예측 1 중 실제 1 개수: 0
예측 1 기준 정확도 precision: nan

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.03, '...",44,0,...,0.227273,0.0,0.0,0.0,0.370588,0.77784,10,0,34,0

[I 2026-05-23 20:57:25,780] Trial 53 finished with value: 0.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.8, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 55/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 2}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 54}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.580681     0
1  2026-02-24     419.160004                 0.0    0.650420     0
2  2026-02-25     426.160004                 0.0    0.553575     0
3  2026-02-26     412.010010                 0.0    0.579512     0
4  2026-02-27     406.369995                 0.0    0.512659     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.400506     0
60 2026-05-19     543.960022                 NaN    0.479958     0
61 2026-05-20     564.659973                 NaN    0.226905     0
62 2026-05-21     567.880005                 NaN    0.428191     0
63 2026-05-22     576.320007                 NaN    0.455400     0

[64 rows x 5 columns]

예측값 분포:
pred
0    57
1     7
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 2
예측 1 중 실제 1 개수: 2
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.05, '...",44,2,...,0.272727,1.0,0.058824,0.111111,0.394118,0.742464,10,0,32,2

[I 2026-05-23 20:57:42,471] Trial 54 finished with value: 0.6666666666666666 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.05, 'gb_max_depth': 2}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 56/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 10, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.75, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 55}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_10d_up_2pct
target_df shape: (1533, 31)
target 분포:
target_10d_up_2pct
0    796
1    737
Name: count, dtype: int64
lagged_df shape: (1393, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1451

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1444

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.145
TOP feature count: 20
['USDKRW_ret_20d_lag3', 'TNX_level_lag120', 'NVDA_ret_20d_lag60', 'DXY_ret_20d_lag120', 'OIL_ret_20d_lag40', 'SMH_vol_20d_lag40', 'SMH_ma60_ratio_lag40', 'VIX_chg_5d_lag60', 'VIX_level_lag40', 'TSM_ret_20d_lag40', 'VIX_chg_20d_lag120', 'TNX_diff_20d_lag5', 'SPY_ret_20d_lag120', 'TSM_ret_5d_lag40', 'SMH_volume_ratio_20d_lag5', 'GOLD_ret_20d_lag120', 'USDKRW_ret_5d_lag1', 'SMH_ma20_ratio_lag60', 'NVDA_ret_5d_lag60', 'TNX_diff_5d_lag60']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,USDKRW_ret_20d_lag3,0.109887,0.002912,8.481039e-06,0.104706,0.114723,3,30,0.106975,USDKRW_ret_20d,3,3,-0.361488,0.361488,249
1,TNX_level_lag120,0.100155,0.003176,1.008583e-05,0.095000,0.107899,3,30,0.096979,TNX_level,120,120,-0.215120,0.215120,132
2,NVDA_ret_20d_lag60,0.090154,0.002180,4.751487e-06,0.086989,0.095382,3,30,0.087975,NVDA_ret_20d,60,60,-0.177262,0.177262,192
3,DXY_ret_20d_lag120,0.080840,0.002467,6.088314e-06,0.077294,0.086061,3,30,0.078372,DXY_ret_20d,120,120,-0.296418,0.296418,132
4,OIL_ret_20d_lag40,0.078288,0.003562,1.268433e-05,0.073828,0.086503,3,30,0.074726,OIL_ret_20d,40,40,-0.298890,0.298890,212
5,SMH_vol_20d_lag40,0.072109,0.001926,3.711302e-06,0.067649,0.075586,3,30,0.070182,SMH_vol_20d,40,40,0.280782,0.280782,212
6,SMH_ma60_ratio_lag40,0.061142,0.001488,2.212750e-06,0.057642,0.064227,3,30,0.059654,SMH_ma60_ratio,40,40,-0.243144,0.243144,212
7,VIX_chg_5d_lag60,0.054753,0.001912,3.656073e-06,0.051218,0.059758,3,30,0.052840,VIX_chg_5d,60,60,0.163074,0.163074,192
8,VIX_level_lag40,0.054488,0.002225,4.952720e-06,0.050400,0.058960,3,30,0.052262,VIX_level,40,40,0.186078,0.186078,212
9,TSM_ret_20d_lag40,0.051417,0.001871,3.499977e-06,0.047055,0.054811,3,30,0.049546,TSM_ret_20d,40,40,-0.254788,0.254788,212
10,VIX_chg_20d_lag120,0.051087,0.001558,2.428675e-06,0.047775,0.053728,3,30,0.049528,VIX_chg_20d,120,120,0.185950,0.185950,132
11,TNX_diff_20d_lag5,0.050659,0.001669,2.784308e-06,0.048160,0.053837,3,30,0.048991,TNX_diff_20d,5,5,0.308024,0.308024,247
12,SPY_ret_20d_lag120,0.048496,0.001586,2.514639e-06,0.046030,0.051593,3,30,0.046910,SPY_ret_20d,120,120,-0.226313,0.226313,132
13,TSM_ret_5d_lag40,0.045115,0.002161,4.669765e-06,0.040066,0.049758,3,30,0.042954,TSM_ret_5d,40,40,-0.294518,0.294518,212
14,SMH_volume_ratio_20d_lag5,0.043978,0.001663,2.765708e-06,0.041877,0.048184,3,30,0.042315,SMH_volume_ratio_20d,5,5,0.191430,0.191430,247
15,GOLD_ret_20d_lag120,0.041700,0.000888,7.877742e-07,0.039999,0.043321,3,30,0.040812,GOLD_ret_20d,120,120,-0.133494,0.133494,132
16,USDKRW_ret_5d_lag1,0.041480,0.000973,9.460302e-07,0.039754,0.042967,3,30,0.040507,USDKRW_ret_5d,1,1,-0.211688,0.211688,251
17,SMH_ma20_ratio_lag60,0.040265,0.001165,1.357070e-06,0.038261,0.042918,3,30,0.039100,SMH_ma20_ratio,60,60,-0.229933,0.229933,192
18,NVDA_ret_5d_lag60,0.039416,0.001771,3.135534e-06,0.035831,0.042566,3,30,0.037645,NVDA_ret_5d,60,60,-0.242738,0.242738,192
19,TNX_diff_5d_lag60,0.031712,0.001260,1.588339e-06,0.030119,0.034277,3,30,0.030452,TNX_diff_5d,60,60,-0.158170,0.158170,192

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1393, 23)
X_train shape: (1393, 20)
train target 분포:
target_10d_up_2pct
0    734
1    659
Name: count, dtype: int64
target_10d_up_2pct
0    0.52692
1    0.47308
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_10d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.806809     1
1  2026-02-24     419.160004                 0.0    0.658803     0
2  2026-02-25     426.160004                 0.0    0.267482     0
3  2026-02-26     412.010010                 0.0    0.164277     0
4  2026-02-27     406.369995                 0.0    0.265473     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.386299     0
60 2026-05-19     543.960022                 NaN    0.437395     0
61 2026-05-20     564.659973                 NaN    0.340691     0
62 2026-05-21     567.880005                 NaN    0.375287     0
63 2026-05-22     576.320007                 NaN    0.512086     0

[64 rows x 5 columns]

예측값 분포:
pred
0    63
1     1
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 54
예측 1 개수: 1
예측 1 중 실제 1 개수: 0
예측 1 기준 정확도 precision: 0.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,10,0.02,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.03, '...",54,1,...,0.351852,0.0,0.0,0.0,0.426471,0.84915,19,1,34,0

[I 2026-05-23 20:57:59,999] Trial 55 finished with value: 0.0 and parameters: {'n_days': 10, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.75, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 57/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.005, 'top_n': 20, 'pred_threshold': 0.4, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 500, 'learning_rate': 0.01, 'max_depth': 5}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 56}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_0pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_0pct
1    954
0    569
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1268

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1266

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1268
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'NVDA_ret_20d_lag3', 'TNX_diff_20d_lag1', 'USDKRW_ret_20d_lag40', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'TSM_ret_20d_lag1', 'SMH_ma60_ratio_lag1', 'NVDA_ret_5d_lag120', 'OIL_ret_20d_lag120', 'VIX_chg_5d_lag120', 'SPY_ret_20d_lag1', 'GOLD_ret_20d_lag120', 'SMH_ma20_ratio_lag120', 'GOLD_ret_5d_lag40', 'OIL_ret_5d_lag10', 'SPY_ret_5d_lag120']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.121135,0.003648,1.330842e-05,0.109618,0.129014,3,30,0.117487,SMH_vol_20d,120,120,-0.311759,0.311759,132
1,TNX_level_lag20,0.114853,0.004163,1.733076e-05,0.107622,0.122139,3,30,0.110690,TNX_level,20,20,-0.293715,0.293715,232
2,VIX_chg_20d_lag120,0.075229,0.001942,3.773054e-06,0.071615,0.078600,3,30,0.073287,VIX_chg_20d,120,120,0.412213,0.412213,132
3,DXY_ret_20d_lag60,0.074905,0.003362,1.130159e-05,0.069638,0.081821,3,30,0.071543,DXY_ret_20d,60,60,-0.259348,0.259348,192
4,NVDA_ret_20d_lag3,0.073374,0.002196,4.823227e-06,0.070062,0.078038,3,30,0.071178,NVDA_ret_20d,3,3,0.322984,0.322984,249
5,TNX_diff_20d_lag1,0.063939,0.001889,3.567327e-06,0.060603,0.067850,3,30,0.062050,TNX_diff_20d,1,1,0.412756,0.412756,251
6,USDKRW_ret_20d_lag40,0.055286,0.001816,3.297786e-06,0.051478,0.058858,3,30,0.053470,USDKRW_ret_20d,40,40,0.237516,0.237516,212
7,VIX_level_lag20,0.053933,0.001508,2.275346e-06,0.050630,0.056676,3,30,0.052424,VIX_level,20,20,0.211435,0.211435,232
8,DXY_ret_5d_lag120,0.053468,0.001693,2.865333e-06,0.051128,0.056476,3,30,0.051775,DXY_ret_5d,120,120,-0.259682,0.259682,132
9,TSM_ret_20d_lag1,0.049539,0.001233,1.519779e-06,0.046883,0.051635,3,30,0.048307,TSM_ret_20d,1,1,0.350834,0.350834,251
10,SMH_ma60_ratio_lag1,0.044980,0.000874,7.642111e-07,0.043502,0.046916,3,30,0.044105,SMH_ma60_ratio,1,1,0.270469,0.270469,251
11,NVDA_ret_5d_lag120,0.044919,0.002015,4.061710e-06,0.041612,0.047743,3,30,0.042903,NVDA_ret_5d,120,120,-0.236112,0.236112,132
12,OIL_ret_20d_lag120,0.043717,0.001090,1.189020e-06,0.041483,0.046336,3,30,0.042627,OIL_ret_20d,120,120,0.297308,0.297308,132
13,VIX_chg_5d_lag120,0.043598,0.001920,3.687077e-06,0.040590,0.047291,3,30,0.041678,VIX_chg_5d,120,120,0.136185,0.136185,132
14,SPY_ret_20d_lag1,0.039645,0.001075,1.154729e-06,0.037617,0.041323,3,30,0.038570,SPY_ret_20d,1,1,0.295942,0.295942,251
15,GOLD_ret_20d_lag120,0.039191,0.000941,8.862690e-07,0.037270,0.040738,3,30,0.038250,GOLD_ret_20d,120,120,-0.270509,0.270509,132
16,SMH_ma20_ratio_lag120,0.033019,0.000644,4.153287e-07,0.031743,0.034503,3,30,0.032375,SMH_ma20_ratio,120,120,-0.304257,0.304257,132
17,GOLD_ret_5d_lag40,0.032577,0.001829,3.344906e-06,0.029740,0.035973,3,30,0.030748,GOLD_ret_5d,40,40,-0.170849,0.170849,212
18,OIL_ret_5d_lag10,0.030413,0.000487,2.374386e-07,0.029503,0.031796,3,30,0.029926,OIL_ret_5d,10,10,0.168223,0.168223,242
19,SPY_ret_5d_lag120,0.030516,0.001083,1.171994e-06,0.028516,0.032213,3,30,0.029433,SPY_ret_5d,120,120,-0.215256,0.215256,132

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_0pct
1    851
0    532
Name: count, dtype: int64
target_20d_up_0pct
1    0.615329
0    0.384671
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_0pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.783207     1
1  2026-02-24     419.160004                 0.0    0.742143     1
2  2026-02-25     426.160004                 0.0    0.781837     1
3  2026-02-26     412.010010                 0.0    0.704796     1
4  2026-02-27     406.369995                 0.0    0.728109     1
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.713453     1
60 2026-05-19     543.960022                 NaN    0.732766     1
61 2026-05-20     564.659973                 NaN    0.743513     1
62 2026-05-21     567.880005                 NaN    0.875358     1
63 2026-05-22     576.320007                 NaN    0.870848     1

[64 rows x 5 columns]

예측값 분포:
pred
1    62
0     2
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 42
예측 1 중 실제 1 개수: 33
예측 1 기준 정확도 precision: 0.7857142857142857

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.005,1,20,20,gradient_boosting,"{'n_estimators': 500, 'learning_rate': 0.01, '...",44,42,...,0.75,0.785714,0.942857,0.857143,0.27619,0.676415,0,9,2,33

[I 2026-05-23 20:58:18,970] Trial 56 finished with value: 0.7857142857142857 and parameters: {'n_days': 20, 'threshold': 0.005, 'top_n': 20, 'pred_threshold': 0.4, 'model_name': 'gradient_boosting', 'gb_n_estimators': 500, 'gb_learning_rate': 0.01, 'gb_max_depth': 5}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 58/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 5, 'threshold': 0.02, 'top_n': 30, 'pred_threshold': 0.6000000000000001, 'model_name': 'logistic', 'model_params': {'C': 0.1, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 57}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_5d_up_2pct
target_df shape: (1538, 31)
target 분포:
target_5d_up_2pct
0    919
1    619
Name: count, dtype: int64
lagged_df shape: (1398, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1646

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1648

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1651
TOP feature count: 27
['DXY_ret_20d_lag120', 'SMH_vol_20d_lag60', 'TNX_diff_5d_lag1', 'TNX_level_lag1', 'GOLD_ret_5d_lag120', 'VIX_level_lag40', 'VIX_chg_20d_lag120', 'DXY_ret_5d_lag120', 'TNX_diff_20d_lag5', 'SPY_ret_20d_lag120', 'OIL_ret_20d_lag60', 'GOLD_ret_20d_lag1', 'USDKRW_ret_5d_lag40', 'TSM_ret_20d_lag40', 'VIX_chg_5d_lag40', 'USDKRW_ret_20d_lag40', 'TSM_ret_5d_lag40', 'SPY_ret_5d_lag40', 'SMH_ma20_ratio_lag40', 'SMH_ma60_ratio_lag20', 'NVDA_ret_20d_lag120', 'OIL_ret_5d_lag60', 'SMH_volume_ratio_20d_lag60', 'NVDA_ret_5d_lag40', 'SMH_ma5_ratio_lag40', 'SOXX_ret_5d_lag40', 'SMH_ret_1d_lag10']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,DXY_ret_20d_lag120,0.097643,0.003116,9.710753e-06,0.091485,0.102341,3,30,0.094526,DXY_ret_20d,120,120,-0.177627,0.177627,132
1,SMH_vol_20d_lag60,0.073933,0.001638,2.684309e-06,0.071582,0.077448,3,30,0.072294,SMH_vol_20d,60,60,-0.200945,0.200945,192
2,TNX_diff_5d_lag1,0.072014,0.003887,1.510828e-05,0.064915,0.076751,3,30,0.068127,TNX_diff_5d,1,1,-0.194687,0.194687,251
3,TNX_level_lag1,0.070761,0.003199,1.023364e-05,0.063743,0.075185,3,30,0.067562,TNX_level,1,1,-0.214996,0.214996,251
4,GOLD_ret_5d_lag120,0.061778,0.001114,1.241156e-06,0.059052,0.064708,3,30,0.060664,GOLD_ret_5d,120,120,-0.197469,0.197469,132
5,VIX_level_lag40,0.057051,0.001657,2.746894e-06,0.053453,0.059921,3,30,0.055394,VIX_level,40,40,0.129031,0.129031,212
6,VIX_chg_20d_lag120,0.051215,0.001738,3.018957e-06,0.048241,0.053650,3,30,0.049477,VIX_chg_20d,120,120,0.178242,0.178242,132
7,DXY_ret_5d_lag120,0.050292,0.001078,1.163088e-06,0.048544,0.052323,3,30,0.049214,DXY_ret_5d,120,120,0.144858,0.144858,132
8,TNX_diff_20d_lag5,0.049925,0.001771,3.135040e-06,0.046680,0.052575,3,30,0.048155,TNX_diff_20d,5,5,0.233782,0.233782,247
9,SPY_ret_20d_lag120,0.049587,0.001888,3.563241e-06,0.047120,0.053090,3,30,0.047699,SPY_ret_20d,120,120,-0.184210,0.184210,132
10,OIL_ret_20d_lag60,0.049609,0.002562,6.566202e-06,0.046023,0.054144,3,30,0.047046,OIL_ret_20d,60,60,0.183668,0.183668,192
11,GOLD_ret_20d_lag1,0.049299,0.002614,6.835072e-06,0.045773,0.053670,3,30,0.046685,GOLD_ret_20d,1,1,0.156010,0.156010,251
12,USDKRW_ret_5d_lag40,0.047465,0.000926,8.578479e-07,0.045333,0.048986,3,30,0.046538,USDKRW_ret_5d,40,40,0.194949,0.194949,212
13,TSM_ret_20d_lag40,0.046758,0.001039,1.080266e-06,0.044701,0.048959,3,30,0.045719,TSM_ret_20d,40,40,-0.156042,0.156042,212
14,VIX_chg_5d_lag40,0.046637,0.001318,1.737261e-06,0.043782,0.049049,3,30,0.045319,VIX_chg_5d,40,40,0.213755,0.213755,212
15,USDKRW_ret_20d_lag40,0.044589,0.000760,5.781988e-07,0.043431,0.046596,3,30,0.043829,USDKRW_ret_20d,40,40,0.230330,0.230330,212
16,TSM_ret_5d_lag40,0.044796,0.001053,1.108525e-06,0.042784,0.046687,3,30,0.043743,TSM_ret_5d,40,40,-0.250401,0.250401,212
17,SPY_ret_5d_lag40,0.045185,0.001809,3.272031e-06,0.041485,0.048565,3,30,0.043376,SPY_ret_5d,40,40,-0.271129,0.271129,212
18,SMH_ma20_ratio_lag40,0.042832,0.000860,7.400631e-07,0.041198,0.044580,3,30,0.041972,SMH_ma20_ratio,40,40,-0.200945,0.200945,212
19,SMH_ma60_ratio_lag20,0.039862,0.000882,7.786455e-07,0.037686,0.041883,3,30,0.038980,SMH_ma60_ratio,20,20,-0.095011,0.095011,232
20,NVDA_ret_20d_lag120,0.037676,0.001378,1.899688e-06,0.035413,0.039635,3,30,0.036297,NVDA_ret_20d,120,120,-0.109313,0.109313,132
21,OIL_ret_5d_lag60,0.037094,0.001530,2.340370e-06,0.034731,0.040008,3,30,0.035564,OIL_ret_5d,60,60,0.162607,0.162607,192
22,SMH_volume_ratio_20d_lag60,0.036327,0.001550,2.403041e-06,0.033251,0.039058,3,30,0.034777,SMH_volume_ratio_20d,60,60,0.119552,0.119552,192
23,NVDA_ret_5d_lag40,0.035022,0.001888,3.563596e-06,0.032714,0.038933,3,30,0.033134,NVDA_ret_5d,40,40,-0.159992,0.159992,212
24,SMH_ma5_ratio_lag40,0.034321,0.001210,1.464483e-06,0.032805,0.036595,3,30,0.033110,SMH_ma5_ratio,40,40,-0.197677,0.197677,212
25,SOXX_ret_5d_lag40,0.032909,0.001147,1.314949e-06,0.030857,0.034877,3,30,0.031762,SOXX_ret_5d,40,40,-0.211367,0.211367,212
26,SMH_ret_1d_lag10,0.032574,0.001488,2.214505e-06,0.030357,0.035630,3,30,0.031086,SMH_ret_1d,10,10,-0.139697,0.139697,242

============================================================
6. valid_df 생성
============================================================
top feature 수: 27
lag 생성 후 valid_df shape: (1607, 56)
원본 base_feature 제거 후 valid_df shape: (1607, 29)
최종 컬럼 수: 29
target 생성 후 valid_df shape: (1607, 31)
최종 valid_df shape: (64, 31)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 27
train_df shape: (1398, 30)
X_train shape: (1398, 27)
train target 분포:
target_5d_up_2pct
0    841
1    557
Name: count, dtype: int64
target_5d_up_2pct
0    0.601574
1    0.398426
Name: proportion, dtype: float64
valid_df shape: (64, 31)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_5d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                0.0    0.306280     0
1  2026-02-24     419.160004                0.0    0.254325     0
2  2026-02-25     426.160004                0.0    0.304284     0
3  2026-02-26     412.010010                0.0    0.311220     0
4  2026-02-27     406.369995                0.0    0.400089     0
..        ...            ...                ...         ...   ...
59 2026-05-18     546.159973                NaN    0.416562     0
60 2026-05-19     543.960022                NaN    0.408576     0
61 2026-05-20     564.659973                NaN    0.424188     0
62 2026-05-21     567.880005                NaN    0.484309     0
63 2026-05-22     576.320007                NaN    0.333642     0

[64 rows x 5 columns]

예측값 분포:
pred
0    58
1     6
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 59
예측 1 개수: 6
예측 1 중 실제 1 개수: 4
예측 1 기준 정확도 precision: 0.6666666666666666

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,5,0.02,1,30,27,logistic,"{'C': 0.1, 'class_weight': 'balanced', 'max_it...",59,6,...,0.542373,0.666667,0.137931,0.228571,0.644828,0.652186,28,2,25,4

[I 2026-05-23 20:58:36,012] Trial 57 finished with value: 0.6666666666666666 and parameters: {'n_days': 5, 'threshold': 0.02, 'top_n': 30, 'pred_threshold': 0.6000000000000001, 'model_name': 'logistic', 'logistic_C': 0.1}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 59/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 100, 'learning_rate': 0.03, 'max_leaf_nodes': 15}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 58}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 20
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.460951     0
1  2026-02-24     419.160004                 0.0    0.529672     0
2  2026-02-25     426.160004                 0.0    0.566028     0
3  2026-02-26     412.010010                 0.0    0.550579     0
4  2026-02-27     406.369995                 0.0    0.604870     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.567676     0
60 2026-05-19     543.960022                 NaN    0.642505     0
61 2026-05-20     564.659973                 NaN    0.311121     0
62 2026-05-21     567.880005                 NaN    0.296108     0
63 2026-05-22     576.320007                 NaN    0.301338     0

[64 rows x 5 columns]

예측값 분포:
pred
0    49
1    15
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 4
예측 1 중 실제 1 개수: 3
예측 1 기준 정확도 precision: 0.75

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,20,20,hist_gradient_boosting,"{'max_iter': 100, 'learning_rate': 0.03, 'max_...",44,4,...,0.272727,0.75,0.088235,0.157895,0.314706,0.844458,9,1,31,3

[I 2026-05-23 20:58:53,311] Trial 58 finished with value: 0.75 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 100, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 15}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 60/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 10, 'threshold': 0.015, 'top_n': 10, 'pred_threshold': 0.55, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 100, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 59}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_10d_up_1pct
target_df shape: (1533, 31)
target 분포:
target_10d_up_1pct
1    789
0    744
Name: count, dtype: int64
lagged_df shape: (1393, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1435

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.143

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1436
TOP feature count: 10
['USDKRW_ret_20d_lag3', 'TNX_level_lag120', 'DXY_ret_20d_lag120', 'OIL_ret_20d_lag40', 'SMH_vol_20d_lag40', 'SMH_ma60_ratio_lag40', 'SMH_ma20_ratio_lag40', 'TNX_diff_20d_lag5', 'TSM_ret_20d_lag40', 'NVDA_ret_20d_lag120']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,USDKRW_ret_20d_lag3,0.120179,0.003203,0.000010,0.114064,0.127153,3,30,0.116976,USDKRW_ret_20d,3,3,-0.357632,0.357632,249
1,TNX_level_lag120,0.098635,0.002875,0.000008,0.089594,0.103376,3,30,0.095760,TNX_level,120,120,-0.209417,0.209417,132
2,DXY_ret_20d_lag120,0.089309,0.002229,0.000005,0.083745,0.092958,3,30,0.087080,DXY_ret_20d,120,120,-0.244463,0.244463,132
3,OIL_ret_20d_lag40,0.069472,0.001444,0.000002,0.066390,0.072341,3,30,0.068028,OIL_ret_20d,40,40,-0.261638,0.261638,212
4,SMH_vol_20d_lag40,0.068675,0.001826,0.000003,0.065220,0.072490,3,30,0.066849,SMH_vol_20d,40,40,0.258244,0.258244,212
5,SMH_ma60_ratio_lag40,0.066721,0.001533,0.000002,0.063232,0.069945,3,30,0.065187,SMH_ma60_ratio,40,40,-0.236194,0.236194,212
6,SMH_ma20_ratio_lag40,0.057550,0.001558,0.000002,0.053863,0.060871,3,30,0.055992,SMH_ma20_ratio,40,40,-0.241800,0.241800,212
7,TNX_diff_20d_lag5,0.055415,0.001547,0.000002,0.052586,0.058614,3,30,0.053869,TNX_diff_20d,5,5,0.323838,0.323838,247
8,TSM_ret_20d_lag40,0.054409,0.001754,0.000003,0.050440,0.058271,3,30,0.052655,TSM_ret_20d,40,40,-0.276363,0.276363,212
9,NVDA_ret_20d_lag120,0.054923,0.002644,0.000007,0.049354,0.059768,3,30,0.052279,NVDA_ret_20d,120,120,-0.174684,0.174684,132

============================================================
6. valid_df 생성
============================================================
top feature 수: 10
lag 생성 후 valid_df shape: (1607, 22)
원본 base_feature 제거 후 valid_df shape: (1607, 12)
최종 컬럼 수: 12
target 생성 후 valid_df shape: (1607, 14)
최종 valid_df shape: (64, 14)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 10
train_df shape: (1393, 13)
X_train shape: (1393, 10)
train target 분포:
target_10d_up_1pct
1    706
0    687
Name: count, dtype: int64
target_10d_up_1pct
1    0.50682
0    0.49318
Name: proportion, dtype: float64
valid_df shape: (64, 14)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_10d_up_1pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.743743     1
1  2026-02-24     419.160004                 0.0    0.746100     1
2  2026-02-25     426.160004                 0.0    0.684836     1
3  2026-02-26     412.010010                 0.0    0.451786     0
4  2026-02-27     406.369995                 0.0    0.487755     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.324121     0
60 2026-05-19     543.960022                 NaN    0.475946     0
61 2026-05-20     564.659973                 NaN    0.498674     0
62 2026-05-21     567.880005                 NaN    0.498674     0
63 2026-05-22     576.320007                 NaN    0.351398     0

[64 rows x 5 columns]

예측값 분포:
pred
0    59
1     5
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 54
예측 1 개수: 4
예측 1 중 실제 1 개수: 1
예측 1 기준 정확도 precision: 0.25

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,10,0.015,1,10,10,gradient_boosting,"{'n_estimators': 100, 'learning_rate': 0.03, '...",54,4,...,0.314815,0.25,0.028571,0.051282,0.206767,0.824018,16,3,34,1

[I 2026-05-23 20:59:11,856] Trial 59 finished with value: 0.25 and parameters: {'n_days': 10, 'threshold': 0.015, 'top_n': 10, 'pred_threshold': 0.55, 'model_name': 'gradient_boosting', 'gb_n_estimators': 100, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 61/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 60}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.555357     0
1  2026-02-24     419.160004                 0.0    0.646397     0
2  2026-02-25     426.160004                 0.0    0.597912     0
3  2026-02-26     412.010010                 0.0    0.457527     0
4  2026-02-27     406.369995                 0.0    0.545480     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.619136     0
60 2026-05-19     543.960022                 NaN    0.842201     1
61 2026-05-20     564.659973                 NaN    0.492613     0
62 2026-05-21     567.880005                 NaN    0.405804     0
63 2026-05-22     576.320007                 NaN    0.501921     0

[64 rows x 5 columns]

예측값 분포:
pred
0    49
1    15
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 4
예측 1 중 실제 1 개수: 4
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.03, '...",44,4,...,0.318182,1.0,0.117647,0.210526,0.370588,0.77784,10,0,30,4

[I 2026-05-23 20:59:32,233] Trial 60 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.
[I 2026-05-23 20:59:32,253] Trial 61 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.
[I 2026-05-23 20:59:32,273] Trial 62 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.
[I 2026-05-23 20:59:32,293] Trial 63 finished with value: 0.8333333333333334 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.
[I 2026-05-23 20:59:32,312] Trial 64 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 62/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 61}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_205244_optuna_holdout_trial_0031
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 63/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 62}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_205244_optuna_holdout_trial_0031
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 64/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 63}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_205302_optuna_holdout_trial_0033
기존 test_precision: 0.8333333333333334

====================================================================================================
OPTUNA HOLDOUT TRIAL 65/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 64}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204756_optuna_holdout_trial_0012
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 66/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 500, 'learning_rate': 0.03, 'max_leaf_nodes': 31}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 65}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 20
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.282533     0
1  2026-02-24     419.160004                 0.0    0.452797     0
2  2026-02-25     426.160004                 0.0    0.312552     0
3  2026-02-26     412.010010                 0.0    0.366741     0
4  2026-02-27     406.369995                 0.0    0.564132     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.799440     1
60 2026-05-19     543.960022                 NaN    0.732502     1
61 2026-05-20     564.659973                 NaN    0.239953     0
62 2026-05-21     567.880005                 NaN    0.437201     0
63 2026-05-22     576.320007                 NaN    0.406977     0

[64 rows x 5 columns]

예측값 분포:
pred
0    41
1    23
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 9
예측 1 중 실제 1 개수: 9
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,20,20,hist_gradient_boosting,"{'max_iter': 500, 'learning_rate': 0.03, 'max_...",44,9,...,0.431818,1.0,0.264706,0.418605,0.511765,1.127822,10,0,25,9

[I 2026-05-23 20:59:50,880] Trial 65 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 500, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 31}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 67/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.01, 'top_n': 50, 'pred_threshold': 0.6000000000000001, 'model_name': 'random_forest', 'model_params': {'n_estimators': 800, 'max_depth': 7, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight': 'balanced'}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 66}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_1pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_1pct
1    917
0    606
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1301

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1302

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1305
TOP feature count: 27
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'NVDA_ret_5d_lag120', 'DXY_ret_5d_lag120', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SMH_ma60_ratio_lag1', 'OIL_ret_20d_lag120', 'VIX_chg_5d_lag120', 'SPY_ret_20d_lag1', 'TNX_diff_5d_lag5', 'GOLD_ret_20d_lag120', 'SMH_ma20_ratio_lag120', 'TSM_ret_5d_lag120', 'GOLD_ret_5d_lag40', 'OIL_ret_5d_lag10', 'USDKRW_ret_5d_lag10', 'SPY_ret_5d_lag120', 'SOXX_ret_5d_lag120', 'SMH_volume_ratio_20d_lag120', 'SMH_ma5_ratio_lag120', 'SMH_ret_1d_lag120']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.113199,0.003130,9.798652e-06,0.105366,0.117758,3,30,0.110069,SMH_vol_20d,120,120,-0.305565,0.305565,132
1,TNX_level_lag20,0.111395,0.001966,3.863856e-06,0.107542,0.114334,3,30,0.109430,TNX_level,20,20,-0.282349,0.282349,232
2,NVDA_ret_20d_lag1,0.080573,0.003084,9.508619e-06,0.075624,0.086273,3,30,0.077490,NVDA_ret_20d,1,1,0.282168,0.282168,251
3,VIX_chg_20d_lag120,0.077843,0.001462,2.138529e-06,0.074670,0.080400,3,30,0.076381,VIX_chg_20d,120,120,0.371232,0.371232,132
4,DXY_ret_20d_lag60,0.073491,0.002177,4.737914e-06,0.068070,0.077471,3,30,0.071314,DXY_ret_20d,60,60,-0.256904,0.256904,192
5,TNX_diff_20d_lag1,0.066654,0.002093,4.380060e-06,0.062034,0.070705,3,30,0.064561,TNX_diff_20d,1,1,0.416622,0.416622,251
6,NVDA_ret_5d_lag120,0.056072,0.001459,2.128896e-06,0.052971,0.058355,3,30,0.054613,NVDA_ret_5d,120,120,-0.233880,0.233880,132
7,DXY_ret_5d_lag120,0.053295,0.001976,3.904778e-06,0.049647,0.058129,3,30,0.051319,DXY_ret_5d,120,120,-0.267096,0.267096,132
8,VIX_level_lag20,0.051839,0.001035,1.070311e-06,0.049900,0.053607,3,30,0.050805,VIX_level,20,20,0.239784,0.239784,232
9,USDKRW_ret_20d_lag40,0.051299,0.001162,1.350872e-06,0.049044,0.053384,3,30,0.050136,USDKRW_ret_20d,40,40,0.281470,0.281470,212
10,TSM_ret_20d_lag1,0.050516,0.002066,4.268228e-06,0.047785,0.054069,3,30,0.048450,TSM_ret_20d,1,1,0.339692,0.339692,251
11,SMH_ma60_ratio_lag1,0.047034,0.001847,3.412431e-06,0.043919,0.049834,3,30,0.045187,SMH_ma60_ratio,1,1,0.226498,0.226498,251
12,OIL_ret_20d_lag120,0.044614,0.001553,2.410659e-06,0.041020,0.048293,3,30,0.043061,OIL_ret_20d,120,120,0.291387,0.291387,132
13,VIX_chg_5d_lag120,0.042947,0.001208,1.459362e-06,0.040616,0.045759,3,30,0.041739,VIX_chg_5d,120,120,0.143824,0.143824,132
14,SPY_ret_20d_lag1,0.043100,0.001912,3.657161e-06,0.039473,0.046173,3,30,0.041188,SPY_ret_20d,1,1,0.273031,0.273031,251
15,TNX_diff_5d_lag5,0.041964,0.001642,2.694547e-06,0.039434,0.045450,3,30,0.040323,TNX_diff_5d,5,5,0.182059,0.182059,247
16,GOLD_ret_20d_lag120,0.037065,0.001167,1.361693e-06,0.034635,0.040013,3,30,0.035898,GOLD_ret_20d,120,120,-0.306548,0.306548,132
17,SMH_ma20_ratio_lag120,0.034339,0.000618,3.813267e-07,0.033254,0.035764,3,30,0.033721,SMH_ma20_ratio,120,120,-0.303183,0.303183,132
18,TSM_ret_5d_lag120,0.034178,0.001041,1.084444e-06,0.032365,0.036477,3,30,0.033136,TSM_ret_5d,120,120,-0.251775,0.251775,132
19,GOLD_ret_5d_lag40,0.031021,0.001323,1.750672e-06,0.028289,0.032956,3,30,0.029698,GOLD_ret_5d,40,40,-0.185968,0.185968,212
20,OIL_ret_5d_lag10,0.029586,0.001875,3.517040e-06,0.027166,0.032706,3,30,0.027711,OIL_ret_5d,10,10,0.146724,0.146724,242
21,USDKRW_ret_5d_lag10,0.027594,0.000588,3.460618e-07,0.026296,0.028759,3,30,0.027005,USDKRW_ret_5d,10,10,-0.121963,0.121963,242
22,SPY_ret_5d_lag120,0.028773,0.001908,3.640026e-06,0.025646,0.031853,3,30,0.026865,SPY_ret_5d,120,120,-0.246520,0.246520,132
23,SOXX_ret_5d_lag120,0.025931,0.000598,3.576511e-07,0.024603,0.027262,3,30,0.025333,SOXX_ret_5d,120,120,-0.291324,0.291324,132
24,SMH_volume_ratio_20d_lag120,0.020064,0.000543,2.953606e-07,0.018983,0.021253,3,30,0.019521,SMH_volume_ratio_20d,120,120,0.253841,0.253841,132
25,SMH_ma5_ratio_lag120,0.018507,0.000645,4.156173e-07,0.017517,0.019844,3,30,0.017862,SMH_ma5_ratio,120,120,-0.227259,0.227259,132
26,SMH_ret_1d_lag120,0.016140,0.000249,6.191607e-08,0.015550,0.016531,3,30,0.015892,SMH_ret_1d,120,120,-0.110756,0.110756,132

============================================================
6. valid_df 생성
============================================================
top feature 수: 27
lag 생성 후 valid_df shape: (1607, 56)
원본 base_feature 제거 후 valid_df shape: (1607, 29)
최종 컬럼 수: 29
target 생성 후 valid_df shape: (1607, 31)
최종 valid_df shape: (64, 31)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 27
train_df shape: (1383, 30)
X_train shape: (1383, 27)
train target 분포:
target_20d_up_1pct
1    815
0    568
Name: count, dtype: int64
target_20d_up_1pct
1    0.589299
0    0.410701
Name: proportion, dtype: float64
valid_df shape: (64, 31)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: random_forest
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_1pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.575177     0
1  2026-02-24     419.160004                 0.0    0.577863     0
2  2026-02-25     426.160004                 0.0    0.553461     0
3  2026-02-26     412.010010                 0.0    0.531669     0
4  2026-02-27     406.369995                 0.0    0.566983     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.526228     0
60 2026-05-19     543.960022                 NaN    0.577447     0
61 2026-05-20     564.659973                 NaN    0.597817     0
62 2026-05-21     567.880005                 NaN    0.678840     1
63 2026-05-22     576.320007                 NaN    0.697574     1

[64 rows x 5 columns]

예측값 분포:
pred
0    44
1    20
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 7
예측 1 중 실제 1 개수: 5
예측 1 기준 정확도 precision: 0.7142857142857143

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.01,1,50,27,random_forest,"{'n_estimators': 800, 'max_depth': 7, 'min_sam...",44,7,...,0.272727,0.714286,0.142857,0.238095,0.206349,0.693116,7,2,30,5

[I 2026-05-23 21:00:08,613] Trial 66 finished with value: 0.7142857142857143 and parameters: {'n_days': 20, 'threshold': 0.01, 'top_n': 50, 'pred_threshold': 0.6000000000000001, 'model_name': 'random_forest', 'rf_n_estimators': 800, 'rf_max_depth': 7, 'rf_min_samples_leaf': 2, 'rf_max_features': 0.5}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 68/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 5, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'logistic', 'model_params': {'C': 0.01, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 67}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_5d_up_3pct
target_df shape: (1538, 31)
target 분포:
target_5d_up_3pct
0    1051
1     487
Name: count, dtype: int64
lagged_df shape: (1398, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1462

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1467

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1461
TOP feature count: 20
['SMH_ma60_ratio_lag1', 'SMH_vol_20d_lag60', 'TNX_level_lag1', 'GOLD_ret_5d_lag120', 'VIX_level_lag1', 'VIX_chg_20d_lag40', 'OIL_ret_20d_lag60', 'TNX_diff_5d_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag40', 'DXY_ret_20d_lag5', 'USDKRW_ret_20d_lag40', 'USDKRW_ret_5d_lag1', 'GOLD_ret_20d_lag1', 'DXY_ret_5d_lag120', 'TNX_diff_20d_lag5', 'SMH_volume_ratio_20d_lag20', 'SMH_ma20_ratio_lag40', 'OIL_ret_5d_lag60', 'NVDA_ret_20d_lag120']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_ma60_ratio_lag1,0.078441,0.001863,3.470473e-06,0.074815,0.082776,3,30,0.076578,SMH_ma60_ratio,1,1,-0.172629,0.172629,251
1,SMH_vol_20d_lag60,0.069105,0.001919,3.684021e-06,0.065530,0.073300,3,30,0.067185,SMH_vol_20d,60,60,-0.189027,0.189027,192
2,TNX_level_lag1,0.069129,0.002486,6.181890e-06,0.063543,0.073483,3,30,0.066643,TNX_level,1,1,-0.191147,0.191147,251
3,GOLD_ret_5d_lag120,0.060355,0.002163,4.676538e-06,0.055174,0.064143,3,30,0.058193,GOLD_ret_5d,120,120,-0.218877,0.218877,132
4,VIX_level_lag1,0.059673,0.002784,7.752705e-06,0.055123,0.064462,3,30,0.056889,VIX_level,1,1,0.153605,0.153605,251
5,VIX_chg_20d_lag40,0.056407,0.001996,3.983510e-06,0.052414,0.060620,3,30,0.054411,VIX_chg_20d,40,40,0.225283,0.225283,212
6,OIL_ret_20d_lag60,0.053212,0.002001,4.002755e-06,0.049749,0.057240,3,30,0.051212,OIL_ret_20d,60,60,0.237427,0.237427,192
7,TNX_diff_5d_lag20,0.053372,0.002314,5.355884e-06,0.048577,0.056207,3,30,0.051058,TNX_diff_5d,20,20,0.185217,0.185217,232
8,SPY_ret_20d_lag120,0.048811,0.001230,1.513431e-06,0.045170,0.051545,3,30,0.047581,SPY_ret_20d,120,120,-0.195151,0.195151,132
9,TSM_ret_20d_lag40,0.049182,0.002547,6.484842e-06,0.045876,0.055137,3,30,0.046635,TSM_ret_20d,40,40,-0.186887,0.186887,212
10,DXY_ret_20d_lag5,0.044759,0.001859,3.455597e-06,0.040812,0.048252,3,30,0.042900,DXY_ret_20d,5,5,-0.123856,0.123856,247
11,USDKRW_ret_20d_lag40,0.044490,0.001832,3.357242e-06,0.041625,0.048470,3,30,0.042657,USDKRW_ret_20d,40,40,0.204293,0.204293,212
12,USDKRW_ret_5d_lag1,0.042260,0.001278,1.633171e-06,0.039336,0.045023,3,30,0.040982,USDKRW_ret_5d,1,1,-0.135928,0.135928,251
13,GOLD_ret_20d_lag1,0.039152,0.002092,4.374883e-06,0.035630,0.042243,3,30,0.037061,GOLD_ret_20d,1,1,0.185988,0.185988,251
14,DXY_ret_5d_lag120,0.037692,0.000937,8.787204e-07,0.035442,0.040194,3,30,0.036755,DXY_ret_5d,120,120,0.201244,0.201244,132
15,TNX_diff_20d_lag5,0.038099,0.001366,1.866021e-06,0.035694,0.040829,3,30,0.036733,TNX_diff_20d,5,5,0.197432,0.197432,247
16,SMH_volume_ratio_20d_lag20,0.037433,0.000858,7.356760e-07,0.035823,0.038871,3,30,0.036576,SMH_volume_ratio_20d,20,20,-0.106779,0.106779,232
17,SMH_ma20_ratio_lag40,0.036965,0.000649,4.216770e-07,0.035800,0.038710,3,30,0.036315,SMH_ma20_ratio,40,40,-0.224204,0.224204,212
18,OIL_ret_5d_lag60,0.035339,0.000720,5.182253e-07,0.033657,0.036754,3,30,0.034619,OIL_ret_5d,60,60,0.222858,0.222858,192
19,NVDA_ret_20d_lag120,0.035294,0.000913,8.331741e-07,0.033754,0.037211,3,30,0.034381,NVDA_ret_20d,120,120,-0.135504,0.135504,132

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1398, 23)
X_train shape: (1398, 20)
train target 분포:
target_5d_up_3pct
0    958
1    440
Name: count, dtype: int64
target_5d_up_3pct
0    0.685265
1    0.314735
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_5d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                0.0    0.433608     0
1  2026-02-24     419.160004                0.0    0.422463     0
2  2026-02-25     426.160004                0.0    0.363731     0
3  2026-02-26     412.010010                0.0    0.379670     0
4  2026-02-27     406.369995                0.0    0.405130     0
..        ...            ...                ...         ...   ...
59 2026-05-18     546.159973                NaN    0.328090     0
60 2026-05-19     543.960022                NaN    0.344226     0
61 2026-05-20     564.659973                NaN    0.337699     0
62 2026-05-21     567.880005                NaN    0.341716     0
63 2026-05-22     576.320007                NaN    0.272442     0

[64 rows x 5 columns]

예측값 분포:
pred
0    62
1     2
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 59
예측 1 개수: 2
예측 1 중 실제 1 개수: 2
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,5,0.03,1,20,20,logistic,"{'C': 0.01, 'class_weight': 'balanced', 'max_i...",59,2,...,0.559322,1.0,0.071429,0.133333,0.506912,0.697389,31,0,26,2

[I 2026-05-23 21:00:25,595] Trial 67 finished with value: 0.6666666666666666 and parameters: {'n_days': 5, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'logistic', 'logistic_C': 0.01}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 69/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 3, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.75, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.1, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 68}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_3d_up_2pct
target_df shape: (1540, 31)
target 분포:
target_3d_up_2pct
0    1034
1     506
Name: count, dtype: int64
lagged_df shape: (1400, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1599

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.159

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1591
TOP feature count: 20
['NVDA_ret_20d_lag1', 'DXY_ret_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma5_ratio_lag10', 'SMH_ma60_ratio_lag1', 'SOXX_ret_5d_lag1', 'VIX_level_lag1', 'VIX_chg_20d_lag40', 'TSM_ret_5d_lag10', 'GOLD_ret_5d_lag120', 'GOLD_ret_20d_lag120', 'TSM_ret_20d_lag40', 'USDKRW_ret_20d_lag40', 'SMH_ret_1d_lag10', 'TNX_level_lag1', 'VIX_chg_5d_lag40', 'SMH_vol_20d_lag60', 'NVDA_ret_5d_lag1', 'SPY_ret_20d_lag120', 'SPY_ret_5d_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,NVDA_ret_20d_lag1,0.097206,0.004106,1.686072e-05,0.090497,0.104698,3,30,0.093100,NVDA_ret_20d,1,1,-0.111781,0.111781,250
1,DXY_ret_20d_lag120,0.070614,0.001475,2.175890e-06,0.067993,0.074612,3,30,0.069139,DXY_ret_20d,120,120,-0.105215,0.105215,131
2,SMH_ma20_ratio_lag1,0.061117,0.001850,3.423071e-06,0.057828,0.065284,3,30,0.059267,SMH_ma20_ratio,1,1,-0.175532,0.175532,250
3,SMH_ma5_ratio_lag10,0.056295,0.001797,3.229324e-06,0.052956,0.059930,3,30,0.054498,SMH_ma5_ratio,10,10,-0.235165,0.235165,241
4,SMH_ma60_ratio_lag1,0.054641,0.001352,1.827155e-06,0.051610,0.056799,3,30,0.053289,SMH_ma60_ratio,1,1,-0.137592,0.137592,250
5,SOXX_ret_5d_lag1,0.052406,0.002972,8.835182e-06,0.046161,0.056209,3,30,0.049434,SOXX_ret_5d,1,1,-0.199028,0.199028,250
6,VIX_level_lag1,0.052427,0.003118,9.723011e-06,0.048047,0.057951,3,30,0.049308,VIX_level,1,1,0.126094,0.126094,250
7,VIX_chg_20d_lag40,0.048218,0.001064,1.132742e-06,0.045217,0.050314,3,30,0.047154,VIX_chg_20d,40,40,0.182643,0.182643,211
8,TSM_ret_5d_lag10,0.044915,0.001040,1.082322e-06,0.043098,0.047615,3,30,0.043874,TSM_ret_5d,10,10,-0.179270,0.179270,241
9,GOLD_ret_5d_lag120,0.044546,0.001121,1.255637e-06,0.042196,0.047571,3,30,0.043425,GOLD_ret_5d,120,120,-0.114377,0.114377,131
10,GOLD_ret_20d_lag120,0.043482,0.001129,1.274155e-06,0.040819,0.045993,3,30,0.042353,GOLD_ret_20d,120,120,-0.107223,0.107223,131
11,TSM_ret_20d_lag40,0.043783,0.002185,4.773945e-06,0.039529,0.046979,3,30,0.041598,TSM_ret_20d,40,40,-0.096849,0.096849,211
12,USDKRW_ret_20d_lag40,0.041263,0.001944,3.778063e-06,0.037834,0.044233,3,30,0.039320,USDKRW_ret_20d,40,40,0.152425,0.152425,211
13,SMH_ret_1d_lag10,0.040061,0.001287,1.656742e-06,0.037420,0.042480,3,30,0.038774,SMH_ret_1d,10,10,-0.169190,0.169190,241
14,TNX_level_lag1,0.039300,0.000939,8.809489e-07,0.036885,0.040442,3,30,0.038361,TNX_level,1,1,-0.130603,0.130603,250
15,VIX_chg_5d_lag40,0.039871,0.001533,2.351359e-06,0.037075,0.042152,3,30,0.038338,VIX_chg_5d,40,40,0.159722,0.159722,211
16,SMH_vol_20d_lag60,0.039652,0.001963,3.852132e-06,0.036112,0.042364,3,30,0.037689,SMH_vol_20d,60,60,-0.150076,0.150076,191
17,NVDA_ret_5d_lag1,0.038617,0.001202,1.445857e-06,0.036307,0.040936,3,30,0.037415,NVDA_ret_5d,1,1,-0.181966,0.181966,250
18,SPY_ret_20d_lag120,0.038898,0.001529,2.338266e-06,0.036068,0.041820,3,30,0.037369,SPY_ret_20d,120,120,-0.124476,0.124476,131
19,SPY_ret_5d_lag40,0.038334,0.001174,1.378602e-06,0.035871,0.040135,3,30,0.037160,SPY_ret_5d,40,40,-0.203227,0.203227,211

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1400, 23)
X_train shape: (1400, 20)
train target 분포:
target_3d_up_2pct
0    942
1    458
Name: count, dtype: int64
target_3d_up_2pct
0    0.672857
1    0.327143
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_3d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                0.0    0.000027     0
1  2026-02-24     419.160004                0.0    0.000222     0
2  2026-02-25     426.160004                0.0    0.000042     0
3  2026-02-26     412.010010                0.0    0.000002     0
4  2026-02-27     406.369995                0.0    0.006734     0
..        ...            ...                ...         ...   ...
59 2026-05-18     546.159973                1.0    0.336222     0
60 2026-05-19     543.960022                1.0    0.042135     0
61 2026-05-20     564.659973                NaN    0.005206     0
62 2026-05-21     567.880005                NaN    0.973400     1
63 2026-05-22     576.320007                NaN    0.001537     0

[64 rows x 5 columns]

예측값 분포:
pred
0    57
1     7
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 61
예측 1 개수: 6
예측 1 중 실제 1 개수: 1
예측 1 기준 정확도 precision: 0.16666666666666666

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,3,0.02,1,20,20,hist_gradient_boosting,"{'max_iter': 300, 'learning_rate': 0.1, 'max_l...",61,6,...,0.442623,0.166667,0.033333,0.055556,0.417204,3.336763,26,5,29,1

[I 2026-05-23 21:00:45,742] Trial 68 finished with value: 0.16666666666666666 and parameters: {'n_days': 3, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.75, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.1, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 70/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 10, 'threshold': 0.005, 'top_n': 30, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.01, 'max_depth': 5}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 69}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_10d_up_0pct
target_df shape: (1533, 31)
target 분포:
target_10d_up_0pct
1    882
0    651
Name: count, dtype: int64
lagged_df shape: (1354, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1396

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1396

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1394
TOP feature count: 27
['TNX_level_lag120', 'USDKRW_ret_20d_lag3', 'DXY_ret_20d_lag120', 'SMH_vol_20d_lag40', 'OIL_ret_20d_lag120', 'TNX_diff_20d_lag5', 'GOLD_ret_20d_lag40', 'NVDA_ret_20d_lag120', 'TSM_ret_5d_lag40', 'SPY_ret_20d_lag120', 'VIX_level_lag40', 'VIX_chg_5d_lag60', 'VIX_chg_20d_lag120', 'SMH_ma60_ratio_lag120', 'SMH_volume_ratio_20d_lag5', 'SMH_ma20_ratio_lag120', 'TSM_ret_20d_lag120', 'USDKRW_ret_5d_lag120', 'TNX_diff_5d_lag60', 'DXY_ret_5d_lag120', 'NVDA_ret_5d_lag60', 'SPY_ret_5d_lag60', 'OIL_ret_5d_lag120', 'GOLD_ret_5d_lag40', 'SOXX_ret_5d_lag60', 'SMH_ma5_ratio_lag60', 'SMH_ret_1d_lag120']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.114099,0.005156,2.658068e-05,0.102361,0.121295,3,30,0.108944,TNX_level,120,120,-0.247079,0.247079,132
1,USDKRW_ret_20d_lag3,0.105354,0.006455,4.166613e-05,0.094970,0.115848,3,30,0.098899,USDKRW_ret_20d,3,3,-0.314678,0.314678,249
2,DXY_ret_20d_lag120,0.097480,0.002902,8.420871e-06,0.091990,0.102329,3,30,0.094578,DXY_ret_20d,120,120,-0.300370,0.300370,132
3,SMH_vol_20d_lag40,0.079376,0.002295,5.266172e-06,0.075700,0.083706,3,30,0.077081,SMH_vol_20d,40,40,0.216317,0.216317,212
4,OIL_ret_20d_lag120,0.066135,0.001842,3.394378e-06,0.063081,0.069975,3,30,0.064293,OIL_ret_20d,120,120,-0.229237,0.229237,132
5,TNX_diff_20d_lag5,0.061168,0.001872,3.503907e-06,0.057590,0.065294,3,30,0.059296,TNX_diff_20d,5,5,0.361960,0.361960,247
6,GOLD_ret_20d_lag40,0.057597,0.001910,3.647110e-06,0.053794,0.061701,3,30,0.055687,GOLD_ret_20d,40,40,-0.148102,0.148102,212
7,NVDA_ret_20d_lag120,0.054337,0.001519,2.307904e-06,0.050717,0.058087,3,30,0.052818,NVDA_ret_20d,120,120,-0.253585,0.253585,132
8,TSM_ret_5d_lag40,0.053448,0.001459,2.129743e-06,0.051298,0.056400,3,30,0.051989,TSM_ret_5d,40,40,-0.242780,0.242780,212
9,SPY_ret_20d_lag120,0.051863,0.001866,3.480598e-06,0.047460,0.055409,3,30,0.049998,SPY_ret_20d,120,120,-0.318511,0.318511,132
10,VIX_level_lag40,0.050667,0.001172,1.372871e-06,0.047863,0.052770,3,30,0.049496,VIX_level,40,40,0.151591,0.151591,212
11,VIX_chg_5d_lag60,0.047297,0.003269,1.068507e-05,0.042487,0.052602,3,30,0.044028,VIX_chg_5d,60,60,0.127624,0.127624,192
12,VIX_chg_20d_lag120,0.044215,0.001232,1.516596e-06,0.041359,0.046152,3,30,0.042983,VIX_chg_20d,120,120,0.313103,0.313103,132
13,SMH_ma60_ratio_lag120,0.043850,0.001086,1.179128e-06,0.041431,0.046171,3,30,0.042764,SMH_ma60_ratio,120,120,-0.197638,0.197638,132
14,SMH_volume_ratio_20d_lag5,0.042285,0.001657,2.746598e-06,0.039245,0.045566,3,30,0.040627,SMH_volume_ratio_20d,5,5,0.195126,0.195126,247
15,SMH_ma20_ratio_lag120,0.040721,0.001256,1.578181e-06,0.039018,0.043972,3,30,0.039465,SMH_ma20_ratio,120,120,-0.312656,0.312656,132
16,TSM_ret_20d_lag120,0.039925,0.001511,2.282005e-06,0.037629,0.043307,3,30,0.038415,TSM_ret_20d,120,120,-0.264108,0.264108,132
17,USDKRW_ret_5d_lag120,0.037754,0.001205,1.451256e-06,0.034878,0.039443,3,30,0.036549,USDKRW_ret_5d,120,120,0.236574,0.236574,132
18,TNX_diff_5d_lag60,0.034374,0.000919,8.439244e-07,0.032628,0.036210,3,30,0.033455,TNX_diff_5d,60,60,-0.203933,0.203933,192
19,DXY_ret_5d_lag120,0.032644,0.001161,1.349066e-06,0.030826,0.035434,3,30,0.031482,DXY_ret_5d,120,120,-0.110706,0.110706,132
20,NVDA_ret_5d_lag60,0.030858,0.001243,1.544605e-06,0.028630,0.033331,3,30,0.029615,NVDA_ret_5d,60,60,-0.202661,0.202661,192
21,SPY_ret_5d_lag60,0.029922,0.000682,4.650514e-07,0.028788,0.031431,3,30,0.029240,SPY_ret_5d,60,60,-0.196864,0.196864,192
22,OIL_ret_5d_lag120,0.027535,0.001028,1.056888e-06,0.025543,0.029770,3,30,0.026507,OIL_ret_5d,120,120,-0.276159,0.276159,132
23,GOLD_ret_5d_lag40,0.024069,0.000628,3.944623e-07,0.022750,0.025236,3,30,0.023441,GOLD_ret_5d,40,40,-0.226895,0.226895,212
24,SOXX_ret_5d_lag60,0.023024,0.000669,4.469725e-07,0.021511,0.024265,3,30,0.022355,SOXX_ret_5d,60,60,-0.210736,0.210736,192
25,SMH_ma5_ratio_lag60,0.022574,0.000547,2.986965e-07,0.021591,0.023648,3,30,0.022027,SMH_ma5_ratio,60,60,-0.159264,0.159264,192
26,SMH_ret_1d_lag120,0.020975,0.000491,2.410395e-07,0.020075,0.022009,3,30,0.020484,SMH_ret_1d,120,120,0.076873,0.076873,132

============================================================
6. valid_df 생성
============================================================
top feature 수: 27
lag 생성 후 valid_df shape: (1607, 56)
원본 base_feature 제거 후 valid_df shape: (1607, 29)
최종 컬럼 수: 29
target 생성 후 valid_df shape: (1607, 31)
최종 valid_df shape: (64, 31)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 27
train_df shape: (1354, 30)
X_train shape: (1354, 27)
train target 분포:
target_10d_up_0pct
1    766
0    588
Name: count, dtype: int64
target_10d_up_0pct
1    0.565731
0    0.434269
Name: proportion, dtype: float64
valid_df shape: (64, 31)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_10d_up_0pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.833452     1
1  2026-02-24     419.160004                 0.0    0.785086     1
2  2026-02-25     426.160004                 0.0    0.774241     1
3  2026-02-26     412.010010                 0.0    0.474821     0
4  2026-02-27     406.369995                 0.0    0.361602     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.474444     0
60 2026-05-19     543.960022                 NaN    0.529572     0
61 2026-05-20     564.659973                 NaN    0.519716     0
62 2026-05-21     567.880005                 NaN    0.497748     0
63 2026-05-22     576.320007                 NaN    0.561437     0

[64 rows x 5 columns]

예측값 분포:
pred
0    55
1     9
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 54
예측 1 개수: 9
예측 1 중 실제 1 개수: 4
예측 1 기준 정확도 precision: 0.4444444444444444

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,10,0.005,1,30,27,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.01, '...",54,9,...,0.296296,0.444444,0.108108,0.173913,0.300477,0.762477,12,5,33,4

[I 2026-05-23 21:01:05,548] Trial 69 finished with value: 0.4444444444444444 and parameters: {'n_days': 10, 'threshold': 0.005, 'top_n': 30, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.01, 'gb_max_depth': 5}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 71/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.55, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 100, 'learning_rate': 0.1, 'max_depth': 5}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 70}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.513726     0
1  2026-02-24     419.160004                 0.0    0.787307     1
2  2026-02-25     426.160004                 0.0    0.687689     1
3  2026-02-26     412.010010                 0.0    0.387594     0
4  2026-02-27     406.369995                 0.0    0.399038     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.870875     1
60 2026-05-19     543.960022                 NaN    0.826351     1
61 2026-05-20     564.659973                 NaN    0.646852     1
62 2026-05-21     567.880005                 NaN    0.521517     0
63 2026-05-22     576.320007                 NaN    0.677016     1

[64 rows x 5 columns]

예측값 분포:
pred
1    40
0    24
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 22
예측 1 중 실제 1 개수: 18
예측 1 기준 정확도 precision: 0.8181818181818182

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,gradient_boosting,"{'n_estimators': 100, 'learning_rate': 0.1, 'm...",44,22,...,0.545455,0.818182,0.529412,0.642857,0.458824,0.795597,6,4,16,18

[I 2026-05-23 21:01:22,238] Trial 70 finished with value: 0.8181818181818182 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.55, 'model_name': 'gradient_boosting', 'gb_n_estimators': 100, 'gb_learning_rate': 0.1, 'gb_max_depth': 5}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:01:22,259] Trial 71 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:01:22,326] Trial 72 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:01:22,346] Trial 73 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 72/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 71}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204756_optuna_holdout_trial_0012
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 73/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 72}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_205244_optuna_holdout_trial_0031
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 74/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 73}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204756_optuna_holdout_trial_0012
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 75/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.05, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 74}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 20
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.139380     0
1  2026-02-24     419.160004                 0.0    0.434117     0
2  2026-02-25     426.160004                 0.0    0.226121     0
3  2026-02-26     412.010010                 0.0    0.515713     0
4  2026-02-27     406.369995                 0.0    0.640484     1
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.845461     1
60 2026-05-19     543.960022                 NaN    0.871821     1
61 2026-05-20     564.659973                 NaN    0.313590     0
62 2026-05-21     567.880005                 NaN    0.394127     0
63 2026-05-22     576.320007                 NaN    0.286276     0

[64 rows x 5 columns]

예측값 분포:
pred
0    34
1    30
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 14
예측 1 중 실제 1 개수: 13
예측 1 기준 정확도 precision: 0.9285714285714286

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,20,20,hist_gradient_boosting,"{'max_iter': 300, 'learning_rate': 0.05, 'max_...",44,14,...,0.5,0.928571,0.382353,0.541667,0.579412,1.017601,9,1,21,13

[I 2026-05-23 21:01:40,332] Trial 74 finished with value: 0.9285714285714286 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.05, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 76/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.75, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.01, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 75}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 20
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.360383     0
1  2026-02-24     419.160004                 0.0    0.560258     0
2  2026-02-25     426.160004                 0.0    0.595351     0
3  2026-02-26     412.010010                 0.0    0.509499     0
4  2026-02-27     406.369995                 0.0    0.640508     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.780320     1
60 2026-05-19     543.960022                 NaN    0.692659     0
61 2026-05-20     564.659973                 NaN    0.346477     0
62 2026-05-21     567.880005                 NaN    0.298012     0
63 2026-05-22     576.320007                 NaN    0.342583     0

[64 rows x 5 columns]

예측값 분포:
pred
0    52
1    12
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 1
예측 1 중 실제 1 개수: 1
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,20,20,hist_gradient_boosting,"{'max_iter': 300, 'learning_rate': 0.01, 'max_...",44,1,...,0.25,1.0,0.029412,0.057143,0.479412,0.750127,10,0,33,1

[I 2026-05-23 21:01:58,417] Trial 75 finished with value: 0.3333333333333333 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.75, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.01, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 77/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 10, 'pred_threshold': 0.7, 'model_name': 'logistic', 'model_params': {'C': 1.0, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 76}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 10
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,0.000006,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,0.000023,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,0.000009,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,0.000006,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,0.000003,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,0.000005,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,0.000002,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,0.000005,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,0.000003,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,0.000003,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212

============================================================
6. valid_df 생성
============================================================
top feature 수: 10
lag 생성 후 valid_df shape: (1607, 22)
원본 base_feature 제거 후 valid_df shape: (1607, 12)
최종 컬럼 수: 12
target 생성 후 valid_df shape: (1607, 14)
최종 valid_df shape: (64, 14)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 10
train_df shape: (1383, 13)
X_train shape: (1383, 10)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 14)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.491692     0
1  2026-02-24     419.160004                 0.0    0.500822     0
2  2026-02-25     426.160004                 0.0    0.513968     0
3  2026-02-26     412.010010                 0.0    0.536488     0
4  2026-02-27     406.369995                 0.0    0.536965     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.466106     0
60 2026-05-19     543.960022                 NaN    0.446807     0
61 2026-05-20     564.659973                 NaN    0.391158     0
62 2026-05-21     567.880005                 NaN    0.413288     0
63 2026-05-22     576.320007                 NaN    0.417234     0

[64 rows x 5 columns]

예측값 분포:
pred
0    64
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 0
예측 1 중 실제 1 개수: 0
예측 1 기준 정확도 precision: nan

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,10,10,logistic,"{'C': 1.0, 'class_weight': 'balanced', 'max_it...",44,0,...,0.227273,0.0,0.0,0.0,0.567647,0.646427,10,0,34,0

[I 2026-05-23 21:02:14,917] Trial 76 finished with value: 0.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 10, 'pred_threshold': 0.7, 'model_name': 'logistic', 'logistic_C': 1.0}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 78/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 10, 'threshold': 0.015, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 77}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_10d_up_1pct
target_df shape: (1533, 31)
target 분포:
target_10d_up_1pct
1    789
0    744
Name: count, dtype: int64
lagged_df shape: (1393, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1435

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.143

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1436
TOP feature count: 20
['USDKRW_ret_20d_lag3', 'TNX_level_lag120', 'DXY_ret_20d_lag120', 'OIL_ret_20d_lag40', 'SMH_vol_20d_lag40', 'SMH_ma60_ratio_lag40', 'SMH_ma20_ratio_lag40', 'TNX_diff_20d_lag5', 'TSM_ret_20d_lag40', 'NVDA_ret_20d_lag120', 'VIX_chg_20d_lag120', 'VIX_level_lag40', 'SPY_ret_20d_lag120', 'GOLD_ret_20d_lag120', 'VIX_chg_5d_lag60', 'USDKRW_ret_5d_lag120', 'TSM_ret_5d_lag40', 'SMH_volume_ratio_20d_lag5', 'NVDA_ret_5d_lag60', 'SOXX_ret_5d_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,USDKRW_ret_20d_lag3,0.120179,0.003203,1.025687e-05,0.114064,0.127153,3,30,0.116976,USDKRW_ret_20d,3,3,-0.357632,0.357632,249
1,TNX_level_lag120,0.098635,0.002875,8.264090e-06,0.089594,0.103376,3,30,0.095760,TNX_level,120,120,-0.209417,0.209417,132
2,DXY_ret_20d_lag120,0.089309,0.002229,4.967756e-06,0.083745,0.092958,3,30,0.087080,DXY_ret_20d,120,120,-0.244463,0.244463,132
3,OIL_ret_20d_lag40,0.069472,0.001444,2.086402e-06,0.066390,0.072341,3,30,0.068028,OIL_ret_20d,40,40,-0.261638,0.261638,212
4,SMH_vol_20d_lag40,0.068675,0.001826,3.334384e-06,0.065220,0.072490,3,30,0.066849,SMH_vol_20d,40,40,0.258244,0.258244,212
5,SMH_ma60_ratio_lag40,0.066721,0.001533,2.351514e-06,0.063232,0.069945,3,30,0.065187,SMH_ma60_ratio,40,40,-0.236194,0.236194,212
6,SMH_ma20_ratio_lag40,0.057550,0.001558,2.426530e-06,0.053863,0.060871,3,30,0.055992,SMH_ma20_ratio,40,40,-0.241800,0.241800,212
7,TNX_diff_20d_lag5,0.055415,0.001547,2.392637e-06,0.052586,0.058614,3,30,0.053869,TNX_diff_20d,5,5,0.323838,0.323838,247
8,TSM_ret_20d_lag40,0.054409,0.001754,3.076881e-06,0.050440,0.058271,3,30,0.052655,TSM_ret_20d,40,40,-0.276363,0.276363,212
9,NVDA_ret_20d_lag120,0.054923,0.002644,6.989798e-06,0.049354,0.059768,3,30,0.052279,NVDA_ret_20d,120,120,-0.174684,0.174684,132
10,VIX_chg_20d_lag120,0.052718,0.001795,3.222371e-06,0.050121,0.057159,3,30,0.050923,VIX_chg_20d,120,120,0.179828,0.179828,132
11,VIX_level_lag40,0.050085,0.001329,1.765036e-06,0.047345,0.052508,3,30,0.048756,VIX_level,40,40,0.190705,0.190705,212
12,SPY_ret_20d_lag120,0.048621,0.000906,8.215688e-07,0.046890,0.050990,3,30,0.047715,SPY_ret_20d,120,120,-0.230254,0.230254,132
13,GOLD_ret_20d_lag120,0.045884,0.002215,4.904031e-06,0.041327,0.048565,3,30,0.043669,GOLD_ret_20d,120,120,-0.137286,0.137286,132
14,VIX_chg_5d_lag60,0.044085,0.001796,3.227083e-06,0.041035,0.047028,3,30,0.042289,VIX_chg_5d,60,60,0.141418,0.141418,192
15,USDKRW_ret_5d_lag120,0.044194,0.002562,6.566231e-06,0.040713,0.049551,3,30,0.041632,USDKRW_ret_5d,120,120,0.211443,0.211443,132
16,TSM_ret_5d_lag40,0.039475,0.001123,1.262164e-06,0.037073,0.042047,3,30,0.038352,TSM_ret_5d,40,40,-0.314300,0.314300,212
17,SMH_volume_ratio_20d_lag5,0.036161,0.001115,1.243013e-06,0.033575,0.038225,3,30,0.035046,SMH_volume_ratio_20d,5,5,0.179281,0.179281,247
18,NVDA_ret_5d_lag60,0.036037,0.001161,1.349002e-06,0.034426,0.039001,3,30,0.034876,NVDA_ret_5d,60,60,-0.223746,0.223746,192
19,SOXX_ret_5d_lag40,0.034374,0.001140,1.299101e-06,0.032316,0.037244,3,30,0.033234,SOXX_ret_5d,40,40,-0.229707,0.229707,212

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1393, 23)
X_train shape: (1393, 20)
train target 분포:
target_10d_up_1pct
1    706
0    687
Name: count, dtype: int64
target_10d_up_1pct
1    0.50682
0    0.49318
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_10d_up_1pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.821123     1
1  2026-02-24     419.160004                 0.0    0.753653     1
2  2026-02-25     426.160004                 0.0    0.607755     0
3  2026-02-26     412.010010                 0.0    0.348093     0
4  2026-02-27     406.369995                 0.0    0.431083     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.412794     0
60 2026-05-19     543.960022                 NaN    0.508457     0
61 2026-05-20     564.659973                 NaN    0.551084     0
62 2026-05-21     567.880005                 NaN    0.483053     0
63 2026-05-22     576.320007                 NaN    0.370945     0

[64 rows x 5 columns]

예측값 분포:
pred
0    57
1     7
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 54
예측 1 개수: 4
예측 1 중 실제 1 개수: 2
예측 1 기준 정확도 precision: 0.5

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,10,0.015,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.03, '...",54,4,...,0.351852,0.5,0.057143,0.102564,0.314286,0.872327,17,2,33,2

[I 2026-05-23 21:02:33,088] Trial 77 finished with value: 0.5 and parameters: {'n_days': 10, 'threshold': 0.015, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 79/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.01, 'top_n': 50, 'pred_threshold': 0.75, 'model_name': 'random_forest', 'model_params': {'n_estimators': 300, 'max_depth': 5, 'min_samples_leaf': 1, 'max_features': 'log2', 'class_weight': 'balanced'}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 78}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_1pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_1pct
1    917
0    606
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1301

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1302

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1305
TOP feature count: 27
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'NVDA_ret_5d_lag120', 'DXY_ret_5d_lag120', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SMH_ma60_ratio_lag1', 'OIL_ret_20d_lag120', 'VIX_chg_5d_lag120', 'SPY_ret_20d_lag1', 'TNX_diff_5d_lag5', 'GOLD_ret_20d_lag120', 'SMH_ma20_ratio_lag120', 'TSM_ret_5d_lag120', 'GOLD_ret_5d_lag40', 'OIL_ret_5d_lag10', 'USDKRW_ret_5d_lag10', 'SPY_ret_5d_lag120', 'SOXX_ret_5d_lag120', 'SMH_volume_ratio_20d_lag120', 'SMH_ma5_ratio_lag120', 'SMH_ret_1d_lag120']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.113199,0.003130,9.798652e-06,0.105366,0.117758,3,30,0.110069,SMH_vol_20d,120,120,-0.305565,0.305565,132
1,TNX_level_lag20,0.111395,0.001966,3.863856e-06,0.107542,0.114334,3,30,0.109430,TNX_level,20,20,-0.282349,0.282349,232
2,NVDA_ret_20d_lag1,0.080573,0.003084,9.508619e-06,0.075624,0.086273,3,30,0.077490,NVDA_ret_20d,1,1,0.282168,0.282168,251
3,VIX_chg_20d_lag120,0.077843,0.001462,2.138529e-06,0.074670,0.080400,3,30,0.076381,VIX_chg_20d,120,120,0.371232,0.371232,132
4,DXY_ret_20d_lag60,0.073491,0.002177,4.737914e-06,0.068070,0.077471,3,30,0.071314,DXY_ret_20d,60,60,-0.256904,0.256904,192
5,TNX_diff_20d_lag1,0.066654,0.002093,4.380060e-06,0.062034,0.070705,3,30,0.064561,TNX_diff_20d,1,1,0.416622,0.416622,251
6,NVDA_ret_5d_lag120,0.056072,0.001459,2.128896e-06,0.052971,0.058355,3,30,0.054613,NVDA_ret_5d,120,120,-0.233880,0.233880,132
7,DXY_ret_5d_lag120,0.053295,0.001976,3.904778e-06,0.049647,0.058129,3,30,0.051319,DXY_ret_5d,120,120,-0.267096,0.267096,132
8,VIX_level_lag20,0.051839,0.001035,1.070311e-06,0.049900,0.053607,3,30,0.050805,VIX_level,20,20,0.239784,0.239784,232
9,USDKRW_ret_20d_lag40,0.051299,0.001162,1.350872e-06,0.049044,0.053384,3,30,0.050136,USDKRW_ret_20d,40,40,0.281470,0.281470,212
10,TSM_ret_20d_lag1,0.050516,0.002066,4.268228e-06,0.047785,0.054069,3,30,0.048450,TSM_ret_20d,1,1,0.339692,0.339692,251
11,SMH_ma60_ratio_lag1,0.047034,0.001847,3.412431e-06,0.043919,0.049834,3,30,0.045187,SMH_ma60_ratio,1,1,0.226498,0.226498,251
12,OIL_ret_20d_lag120,0.044614,0.001553,2.410659e-06,0.041020,0.048293,3,30,0.043061,OIL_ret_20d,120,120,0.291387,0.291387,132
13,VIX_chg_5d_lag120,0.042947,0.001208,1.459362e-06,0.040616,0.045759,3,30,0.041739,VIX_chg_5d,120,120,0.143824,0.143824,132
14,SPY_ret_20d_lag1,0.043100,0.001912,3.657161e-06,0.039473,0.046173,3,30,0.041188,SPY_ret_20d,1,1,0.273031,0.273031,251
15,TNX_diff_5d_lag5,0.041964,0.001642,2.694547e-06,0.039434,0.045450,3,30,0.040323,TNX_diff_5d,5,5,0.182059,0.182059,247
16,GOLD_ret_20d_lag120,0.037065,0.001167,1.361693e-06,0.034635,0.040013,3,30,0.035898,GOLD_ret_20d,120,120,-0.306548,0.306548,132
17,SMH_ma20_ratio_lag120,0.034339,0.000618,3.813267e-07,0.033254,0.035764,3,30,0.033721,SMH_ma20_ratio,120,120,-0.303183,0.303183,132
18,TSM_ret_5d_lag120,0.034178,0.001041,1.084444e-06,0.032365,0.036477,3,30,0.033136,TSM_ret_5d,120,120,-0.251775,0.251775,132
19,GOLD_ret_5d_lag40,0.031021,0.001323,1.750672e-06,0.028289,0.032956,3,30,0.029698,GOLD_ret_5d,40,40,-0.185968,0.185968,212
20,OIL_ret_5d_lag10,0.029586,0.001875,3.517040e-06,0.027166,0.032706,3,30,0.027711,OIL_ret_5d,10,10,0.146724,0.146724,242
21,USDKRW_ret_5d_lag10,0.027594,0.000588,3.460618e-07,0.026296,0.028759,3,30,0.027005,USDKRW_ret_5d,10,10,-0.121963,0.121963,242
22,SPY_ret_5d_lag120,0.028773,0.001908,3.640026e-06,0.025646,0.031853,3,30,0.026865,SPY_ret_5d,120,120,-0.246520,0.246520,132
23,SOXX_ret_5d_lag120,0.025931,0.000598,3.576511e-07,0.024603,0.027262,3,30,0.025333,SOXX_ret_5d,120,120,-0.291324,0.291324,132
24,SMH_volume_ratio_20d_lag120,0.020064,0.000543,2.953606e-07,0.018983,0.021253,3,30,0.019521,SMH_volume_ratio_20d,120,120,0.253841,0.253841,132
25,SMH_ma5_ratio_lag120,0.018507,0.000645,4.156173e-07,0.017517,0.019844,3,30,0.017862,SMH_ma5_ratio,120,120,-0.227259,0.227259,132
26,SMH_ret_1d_lag120,0.016140,0.000249,6.191607e-08,0.015550,0.016531,3,30,0.015892,SMH_ret_1d,120,120,-0.110756,0.110756,132

============================================================
6. valid_df 생성
============================================================
top feature 수: 27
lag 생성 후 valid_df shape: (1607, 56)
원본 base_feature 제거 후 valid_df shape: (1607, 29)
최종 컬럼 수: 29
target 생성 후 valid_df shape: (1607, 31)
최종 valid_df shape: (64, 31)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 27
train_df shape: (1383, 30)
X_train shape: (1383, 27)
train target 분포:
target_20d_up_1pct
1    815
0    568
Name: count, dtype: int64
target_20d_up_1pct
1    0.589299
0    0.410701
Name: proportion, dtype: float64
valid_df shape: (64, 31)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: random_forest
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_1pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.586595     0
1  2026-02-24     419.160004                 0.0    0.563838     0
2  2026-02-25     426.160004                 0.0    0.575148     0
3  2026-02-26     412.010010                 0.0    0.558561     0
4  2026-02-27     406.369995                 0.0    0.571143     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.512396     0
60 2026-05-19     543.960022                 NaN    0.537124     0
61 2026-05-20     564.659973                 NaN    0.530979     0
62 2026-05-21     567.880005                 NaN    0.582567     0
63 2026-05-22     576.320007                 NaN    0.592578     0

[64 rows x 5 columns]

예측값 분포:
pred
0    64
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 0
예측 1 중 실제 1 개수: 0
예측 1 기준 정확도 precision: nan

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.01,1,50,27,random_forest,"{'n_estimators': 300, 'max_depth': 5, 'min_sam...",44,0,...,0.204545,0.0,0.0,0.0,0.161905,0.707428,9,0,35,0

[I 2026-05-23 21:02:50,849] Trial 78 finished with value: 0.0 and parameters: {'n_days': 20, 'threshold': 0.01, 'top_n': 50, 'pred_threshold': 0.75, 'model_name': 'random_forest', 'rf_n_estimators': 300, 'rf_max_depth': 5, 'rf_min_samples_leaf': 1, 'rf_max_features': 'log2'}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 80/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 500, 'learning_rate': 0.03, 'max_leaf_nodes': 31}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 79}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 20
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.282533     0
1  2026-02-24     419.160004                 0.0    0.452797     0
2  2026-02-25     426.160004                 0.0    0.312552     0
3  2026-02-26     412.010010                 0.0    0.366741     0
4  2026-02-27     406.369995                 0.0    0.564132     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.799440     1
60 2026-05-19     543.960022                 NaN    0.732502     1
61 2026-05-20     564.659973                 NaN    0.239953     0
62 2026-05-21     567.880005                 NaN    0.437201     0
63 2026-05-22     576.320007                 NaN    0.406977     0

[64 rows x 5 columns]

예측값 분포:
pred
0    45
1    19
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 5
예측 1 중 실제 1 개수: 5
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,20,20,hist_gradient_boosting,"{'max_iter': 500, 'learning_rate': 0.03, 'max_...",44,5,...,0.340909,1.0,0.147059,0.25641,0.511765,1.127822,10,0,29,5

[I 2026-05-23 21:03:12,811] Trial 79 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 500, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 31}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 81/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 3, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 2}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 80}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_3d_up_2pct
target_df shape: (1540, 31)
target 분포:
target_3d_up_2pct
0    1034
1     506
Name: count, dtype: int64
lagged_df shape: (1400, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1599

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.159

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1591
TOP feature count: 20
['NVDA_ret_20d_lag1', 'DXY_ret_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma5_ratio_lag10', 'SMH_ma60_ratio_lag1', 'SOXX_ret_5d_lag1', 'VIX_level_lag1', 'VIX_chg_20d_lag40', 'TSM_ret_5d_lag10', 'GOLD_ret_5d_lag120', 'GOLD_ret_20d_lag120', 'TSM_ret_20d_lag40', 'USDKRW_ret_20d_lag40', 'SMH_ret_1d_lag10', 'TNX_level_lag1', 'VIX_chg_5d_lag40', 'SMH_vol_20d_lag60', 'NVDA_ret_5d_lag1', 'SPY_ret_20d_lag120', 'SPY_ret_5d_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,NVDA_ret_20d_lag1,0.097206,0.004106,1.686072e-05,0.090497,0.104698,3,30,0.093100,NVDA_ret_20d,1,1,-0.111781,0.111781,250
1,DXY_ret_20d_lag120,0.070614,0.001475,2.175890e-06,0.067993,0.074612,3,30,0.069139,DXY_ret_20d,120,120,-0.105215,0.105215,131
2,SMH_ma20_ratio_lag1,0.061117,0.001850,3.423071e-06,0.057828,0.065284,3,30,0.059267,SMH_ma20_ratio,1,1,-0.175532,0.175532,250
3,SMH_ma5_ratio_lag10,0.056295,0.001797,3.229324e-06,0.052956,0.059930,3,30,0.054498,SMH_ma5_ratio,10,10,-0.235165,0.235165,241
4,SMH_ma60_ratio_lag1,0.054641,0.001352,1.827155e-06,0.051610,0.056799,3,30,0.053289,SMH_ma60_ratio,1,1,-0.137592,0.137592,250
5,SOXX_ret_5d_lag1,0.052406,0.002972,8.835182e-06,0.046161,0.056209,3,30,0.049434,SOXX_ret_5d,1,1,-0.199028,0.199028,250
6,VIX_level_lag1,0.052427,0.003118,9.723011e-06,0.048047,0.057951,3,30,0.049308,VIX_level,1,1,0.126094,0.126094,250
7,VIX_chg_20d_lag40,0.048218,0.001064,1.132742e-06,0.045217,0.050314,3,30,0.047154,VIX_chg_20d,40,40,0.182643,0.182643,211
8,TSM_ret_5d_lag10,0.044915,0.001040,1.082322e-06,0.043098,0.047615,3,30,0.043874,TSM_ret_5d,10,10,-0.179270,0.179270,241
9,GOLD_ret_5d_lag120,0.044546,0.001121,1.255637e-06,0.042196,0.047571,3,30,0.043425,GOLD_ret_5d,120,120,-0.114377,0.114377,131
10,GOLD_ret_20d_lag120,0.043482,0.001129,1.274155e-06,0.040819,0.045993,3,30,0.042353,GOLD_ret_20d,120,120,-0.107223,0.107223,131
11,TSM_ret_20d_lag40,0.043783,0.002185,4.773945e-06,0.039529,0.046979,3,30,0.041598,TSM_ret_20d,40,40,-0.096849,0.096849,211
12,USDKRW_ret_20d_lag40,0.041263,0.001944,3.778063e-06,0.037834,0.044233,3,30,0.039320,USDKRW_ret_20d,40,40,0.152425,0.152425,211
13,SMH_ret_1d_lag10,0.040061,0.001287,1.656742e-06,0.037420,0.042480,3,30,0.038774,SMH_ret_1d,10,10,-0.169190,0.169190,241
14,TNX_level_lag1,0.039300,0.000939,8.809489e-07,0.036885,0.040442,3,30,0.038361,TNX_level,1,1,-0.130603,0.130603,250
15,VIX_chg_5d_lag40,0.039871,0.001533,2.351359e-06,0.037075,0.042152,3,30,0.038338,VIX_chg_5d,40,40,0.159722,0.159722,211
16,SMH_vol_20d_lag60,0.039652,0.001963,3.852132e-06,0.036112,0.042364,3,30,0.037689,SMH_vol_20d,60,60,-0.150076,0.150076,191
17,NVDA_ret_5d_lag1,0.038617,0.001202,1.445857e-06,0.036307,0.040936,3,30,0.037415,NVDA_ret_5d,1,1,-0.181966,0.181966,250
18,SPY_ret_20d_lag120,0.038898,0.001529,2.338266e-06,0.036068,0.041820,3,30,0.037369,SPY_ret_20d,120,120,-0.124476,0.124476,131
19,SPY_ret_5d_lag40,0.038334,0.001174,1.378602e-06,0.035871,0.040135,3,30,0.037160,SPY_ret_5d,40,40,-0.203227,0.203227,211

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1400, 23)
X_train shape: (1400, 20)
train target 분포:
target_3d_up_2pct
0    942
1    458
Name: count, dtype: int64
target_3d_up_2pct
0    0.672857
1    0.327143
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_3d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                0.0    0.208795     0
1  2026-02-24     419.160004                0.0    0.194127     0
2  2026-02-25     426.160004                0.0    0.210091     0
3  2026-02-26     412.010010                0.0    0.198408     0
4  2026-02-27     406.369995                0.0    0.312399     0
..        ...            ...                ...         ...   ...
59 2026-05-18     546.159973                1.0    0.373228     0
60 2026-05-19     543.960022                1.0    0.242493     0
61 2026-05-20     564.659973                NaN    0.222768     0
62 2026-05-21     567.880005                NaN    0.322273     0
63 2026-05-22     576.320007                NaN    0.205761     0

[64 rows x 5 columns]

예측값 분포:
pred
0    63
1     1
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 61
예측 1 개수: 1
예측 1 중 실제 1 개수: 1
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,3,0.02,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.05, '...",61,1,...,0.52459,1.0,0.033333,0.064516,0.367742,0.978035,31,0,29,1

[I 2026-05-23 21:03:31,069] Trial 80 finished with value: 0.3333333333333333 and parameters: {'n_days': 3, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.05, 'gb_max_depth': 2}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 82/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.8, 'model_name': 'logistic', 'model_params': {'C': 10.0, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 81}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 20
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.374544     0
1  2026-02-24     419.160004                 0.0    0.411243     0
2  2026-02-25     426.160004                 0.0    0.463804     0
3  2026-02-26     412.010010                 0.0    0.500331     0
4  2026-02-27     406.369995                 0.0    0.575157     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.544210     0
60 2026-05-19     543.960022                 NaN    0.614863     0
61 2026-05-20     564.659973                 NaN    0.634410     0
62 2026-05-21     567.880005                 NaN    0.682011     0
63 2026-05-22     576.320007                 NaN    0.633351     0

[64 rows x 5 columns]

예측값 분포:
pred
0    61
1     3
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 2
예측 1 중 실제 1 개수: 2
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,20,20,logistic,"{'C': 10.0, 'class_weight': 'balanced', 'max_i...",44,2,...,0.272727,1.0,0.058824,0.111111,0.755882,0.578949,10,0,32,2

[I 2026-05-23 21:03:47,711] Trial 81 finished with value: 0.6666666666666666 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.8, 'model_name': 'logistic', 'logistic_C': 10.0}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:03:47,736] Trial 82 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.75, 'model_name': 'logistic', 'logistic_C': 10.0}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 83/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.75, 'model_name': 'logistic', 'model_params': {'C': 10.0, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 82}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_205335_optuna_holdout_trial_0035
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 84/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'logistic', 'model_params': {'C': 10.0, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 83}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 20
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.374544     0
1  2026-02-24     419.160004                 0.0    0.411243     0
2  2026-02-25     426.160004                 0.0    0.463804     0
3  2026-02-26     412.010010                 0.0    0.500331     0
4  2026-02-27     406.369995                 0.0    0.575157     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.544210     0
60 2026-05-19     543.960022                 NaN    0.614863     0
61 2026-05-20     564.659973                 NaN    0.634410     0
62 2026-05-21     567.880005                 NaN    0.682011     1
63 2026-05-22     576.320007                 NaN    0.633351     0

[64 rows x 5 columns]

예측값 분포:
pred
0    46
1    18
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 12
예측 1 중 실제 1 개수: 12
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,20,20,logistic,"{'C': 10.0, 'class_weight': 'balanced', 'max_i...",44,12,...,0.5,1.0,0.352941,0.521739,0.755882,0.578949,10,0,22,12

[I 2026-05-23 21:04:04,430] Trial 83 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'logistic', 'logistic_C': 10.0}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:04:04,457] Trial 84 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.75, 'model_name': 'logistic', 'logistic_C': 10.0}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 85/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.75, 'model_name': 'logistic', 'model_params': {'C': 10.0, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 84}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_205335_optuna_holdout_trial_0035
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 86/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'logistic', 'model_params': {'C': 1.0, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 85}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.476654     0
1  2026-02-24     419.160004                 0.0    0.471490     0
2  2026-02-25     426.160004                 0.0    0.503152     0
3  2026-02-26     412.010010                 0.0    0.561370     0
4  2026-02-27     406.369995                 0.0    0.573927     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.452401     0
60 2026-05-19     543.960022                 NaN    0.504150     0
61 2026-05-20     564.659973                 NaN    0.565276     0
62 2026-05-21     567.880005                 NaN    0.585366     0
63 2026-05-22     576.320007                 NaN    0.566451     0

[64 rows x 5 columns]

예측값 분포:
pred
0    59
1     5
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 3
예측 1 중 실제 1 개수: 3
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,logistic,"{'C': 1.0, 'class_weight': 'balanced', 'max_it...",44,3,...,0.295455,1.0,0.088235,0.162162,0.3,0.770975,10,0,31,3

[I 2026-05-23 21:04:21,185] Trial 85 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'logistic', 'logistic_C': 1.0}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 87/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 30, 'pred_threshold': 0.8, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 500, 'learning_rate': 0.01, 'max_depth': 4}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 86}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 27
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1', 'TNX_diff_5d_lag5', 'SPY_ret_5d_lag120', 'NVDA_ret_5d_lag60', 'SOXX_ret_5d_lag120', 'SMH_volume_ratio_20d_lag40', 'SMH_ma5_ratio_lag60', 'SMH_ret_1d_lag60']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251
20,TNX_diff_5d_lag5,0.028148,0.001107,1.226237e-06,0.026030,0.029843,3,30,0.027041,TNX_diff_5d,5,5,0.205918,0.205918,247
21,SPY_ret_5d_lag120,0.027266,0.000982,9.634165e-07,0.025657,0.029503,3,30,0.026284,SPY_ret_5d,120,120,-0.226060,0.226060,132
22,NVDA_ret_5d_lag60,0.026746,0.001502,2.255625e-06,0.024752,0.029620,3,30,0.025244,NVDA_ret_5d,60,60,-0.230714,0.230714,192
23,SOXX_ret_5d_lag120,0.025377,0.000772,5.958999e-07,0.023624,0.026787,3,30,0.024605,SOXX_ret_5d,120,120,-0.180724,0.180724,132
24,SMH_volume_ratio_20d_lag40,0.023451,0.000495,2.454801e-07,0.022375,0.024293,3,30,0.022956,SMH_volume_ratio_20d,40,40,-0.175235,0.175235,212
25,SMH_ma5_ratio_lag60,0.020131,0.000685,4.688208e-07,0.018742,0.021058,3,30,0.019447,SMH_ma5_ratio,60,60,-0.179975,0.179975,192
26,SMH_ret_1d_lag60,0.015072,0.000675,4.562163e-07,0.013999,0.016328,3,30,0.014397,SMH_ret_1d,60,60,-0.127110,0.127110,192

============================================================
6. valid_df 생성
============================================================
top feature 수: 27
lag 생성 후 valid_df shape: (1607, 56)
원본 base_feature 제거 후 valid_df shape: (1607, 29)
최종 컬럼 수: 29
target 생성 후 valid_df shape: (1607, 31)
최종 valid_df shape: (64, 31)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 27
train_df shape: (1383, 30)
X_train shape: (1383, 27)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 31)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.560234     0
1  2026-02-24     419.160004                 0.0    0.612547     0
2  2026-02-25     426.160004                 0.0    0.512276     0
3  2026-02-26     412.010010                 0.0    0.539997     0
4  2026-02-27     406.369995                 0.0    0.626032     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.562885     0
60 2026-05-19     543.960022                 NaN    0.524178     0
61 2026-05-20     564.659973                 NaN    0.255263     0
62 2026-05-21     567.880005                 NaN    0.400720     0
63 2026-05-22     576.320007                 NaN    0.781956     0

[64 rows x 5 columns]

예측값 분포:
pred
0    60
1     4
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 0
예측 1 중 실제 1 개수: 0
예측 1 기준 정확도 precision: nan

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,30,27,gradient_boosting,"{'n_estimators': 500, 'learning_rate': 0.01, '...",44,0,...,0.227273,0.0,0.0,0.0,0.291176,0.828406,10,0,34,0

[I 2026-05-23 21:04:41,338] Trial 86 finished with value: 0.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 30, 'pred_threshold': 0.8, 'model_name': 'gradient_boosting', 'gb_n_estimators': 500, 'gb_learning_rate': 0.01, 'gb_max_depth': 4}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 88/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.005, 'top_n': 20, 'pred_threshold': 0.3, 'model_name': 'logistic', 'model_params': {'C': 10.0, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 87}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_0pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_0pct
1    954
0    569
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1268

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1266

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1268
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'NVDA_ret_20d_lag3', 'TNX_diff_20d_lag1', 'USDKRW_ret_20d_lag40', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'TSM_ret_20d_lag1', 'SMH_ma60_ratio_lag1', 'NVDA_ret_5d_lag120', 'OIL_ret_20d_lag120', 'VIX_chg_5d_lag120', 'SPY_ret_20d_lag1', 'GOLD_ret_20d_lag120', 'SMH_ma20_ratio_lag120', 'GOLD_ret_5d_lag40', 'OIL_ret_5d_lag10', 'SPY_ret_5d_lag120']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.121135,0.003648,1.330842e-05,0.109618,0.129014,3,30,0.117487,SMH_vol_20d,120,120,-0.311759,0.311759,132
1,TNX_level_lag20,0.114853,0.004163,1.733076e-05,0.107622,0.122139,3,30,0.110690,TNX_level,20,20,-0.293715,0.293715,232
2,VIX_chg_20d_lag120,0.075229,0.001942,3.773054e-06,0.071615,0.078600,3,30,0.073287,VIX_chg_20d,120,120,0.412213,0.412213,132
3,DXY_ret_20d_lag60,0.074905,0.003362,1.130159e-05,0.069638,0.081821,3,30,0.071543,DXY_ret_20d,60,60,-0.259348,0.259348,192
4,NVDA_ret_20d_lag3,0.073374,0.002196,4.823227e-06,0.070062,0.078038,3,30,0.071178,NVDA_ret_20d,3,3,0.322984,0.322984,249
5,TNX_diff_20d_lag1,0.063939,0.001889,3.567327e-06,0.060603,0.067850,3,30,0.062050,TNX_diff_20d,1,1,0.412756,0.412756,251
6,USDKRW_ret_20d_lag40,0.055286,0.001816,3.297786e-06,0.051478,0.058858,3,30,0.053470,USDKRW_ret_20d,40,40,0.237516,0.237516,212
7,VIX_level_lag20,0.053933,0.001508,2.275346e-06,0.050630,0.056676,3,30,0.052424,VIX_level,20,20,0.211435,0.211435,232
8,DXY_ret_5d_lag120,0.053468,0.001693,2.865333e-06,0.051128,0.056476,3,30,0.051775,DXY_ret_5d,120,120,-0.259682,0.259682,132
9,TSM_ret_20d_lag1,0.049539,0.001233,1.519779e-06,0.046883,0.051635,3,30,0.048307,TSM_ret_20d,1,1,0.350834,0.350834,251
10,SMH_ma60_ratio_lag1,0.044980,0.000874,7.642111e-07,0.043502,0.046916,3,30,0.044105,SMH_ma60_ratio,1,1,0.270469,0.270469,251
11,NVDA_ret_5d_lag120,0.044919,0.002015,4.061710e-06,0.041612,0.047743,3,30,0.042903,NVDA_ret_5d,120,120,-0.236112,0.236112,132
12,OIL_ret_20d_lag120,0.043717,0.001090,1.189020e-06,0.041483,0.046336,3,30,0.042627,OIL_ret_20d,120,120,0.297308,0.297308,132
13,VIX_chg_5d_lag120,0.043598,0.001920,3.687077e-06,0.040590,0.047291,3,30,0.041678,VIX_chg_5d,120,120,0.136185,0.136185,132
14,SPY_ret_20d_lag1,0.039645,0.001075,1.154729e-06,0.037617,0.041323,3,30,0.038570,SPY_ret_20d,1,1,0.295942,0.295942,251
15,GOLD_ret_20d_lag120,0.039191,0.000941,8.862690e-07,0.037270,0.040738,3,30,0.038250,GOLD_ret_20d,120,120,-0.270509,0.270509,132
16,SMH_ma20_ratio_lag120,0.033019,0.000644,4.153287e-07,0.031743,0.034503,3,30,0.032375,SMH_ma20_ratio,120,120,-0.304257,0.304257,132
17,GOLD_ret_5d_lag40,0.032577,0.001829,3.344906e-06,0.029740,0.035973,3,30,0.030748,GOLD_ret_5d,40,40,-0.170849,0.170849,212
18,OIL_ret_5d_lag10,0.030413,0.000487,2.374386e-07,0.029503,0.031796,3,30,0.029926,OIL_ret_5d,10,10,0.168223,0.168223,242
19,SPY_ret_5d_lag120,0.030516,0.001083,1.171994e-06,0.028516,0.032213,3,30,0.029433,SPY_ret_5d,120,120,-0.215256,0.215256,132

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_0pct
1    851
0    532
Name: count, dtype: int64
target_20d_up_0pct
1    0.615329
0    0.384671
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_0pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.503002     1
1  2026-02-24     419.160004                 0.0    0.491334     1
2  2026-02-25     426.160004                 0.0    0.568955     1
3  2026-02-26     412.010010                 0.0    0.543382     1
4  2026-02-27     406.369995                 0.0    0.634003     1
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.369040     1
60 2026-05-19     543.960022                 NaN    0.425268     1
61 2026-05-20     564.659973                 NaN    0.508682     1
62 2026-05-21     567.880005                 NaN    0.651624     1
63 2026-05-22     576.320007                 NaN    0.621592     1

[64 rows x 5 columns]

예측값 분포:
pred
1    64
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 44
예측 1 중 실제 1 개수: 35
예측 1 기준 정확도 precision: 0.7954545454545454

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.005,1,20,20,logistic,"{'C': 10.0, 'class_weight': 'balanced', 'max_i...",44,44,...,0.795455,0.795455,1.0,0.886076,0.485714,0.635841,0,9,0,35

[I 2026-05-23 21:04:57,492] Trial 87 finished with value: 0.7954545454545454 and parameters: {'n_days': 20, 'threshold': 0.005, 'top_n': 20, 'pred_threshold': 0.3, 'model_name': 'logistic', 'logistic_C': 10.0}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 89/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 5, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.5, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 5}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 88}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_5d_up_2pct
target_df shape: (1538, 31)
target 분포:
target_5d_up_2pct
0    919
1    619
Name: count, dtype: int64
lagged_df shape: (1398, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1646

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1648

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1651
TOP feature count: 20
['DXY_ret_20d_lag120', 'SMH_vol_20d_lag60', 'TNX_diff_5d_lag1', 'TNX_level_lag1', 'GOLD_ret_5d_lag120', 'VIX_level_lag40', 'VIX_chg_20d_lag120', 'DXY_ret_5d_lag120', 'TNX_diff_20d_lag5', 'SPY_ret_20d_lag120', 'OIL_ret_20d_lag60', 'GOLD_ret_20d_lag1', 'USDKRW_ret_5d_lag40', 'TSM_ret_20d_lag40', 'VIX_chg_5d_lag40', 'USDKRW_ret_20d_lag40', 'TSM_ret_5d_lag40', 'SPY_ret_5d_lag40', 'SMH_ma20_ratio_lag40', 'SMH_ma60_ratio_lag20']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,DXY_ret_20d_lag120,0.097643,0.003116,9.710753e-06,0.091485,0.102341,3,30,0.094526,DXY_ret_20d,120,120,-0.177627,0.177627,132
1,SMH_vol_20d_lag60,0.073933,0.001638,2.684309e-06,0.071582,0.077448,3,30,0.072294,SMH_vol_20d,60,60,-0.200945,0.200945,192
2,TNX_diff_5d_lag1,0.072014,0.003887,1.510828e-05,0.064915,0.076751,3,30,0.068127,TNX_diff_5d,1,1,-0.194687,0.194687,251
3,TNX_level_lag1,0.070761,0.003199,1.023364e-05,0.063743,0.075185,3,30,0.067562,TNX_level,1,1,-0.214996,0.214996,251
4,GOLD_ret_5d_lag120,0.061778,0.001114,1.241156e-06,0.059052,0.064708,3,30,0.060664,GOLD_ret_5d,120,120,-0.197469,0.197469,132
5,VIX_level_lag40,0.057051,0.001657,2.746894e-06,0.053453,0.059921,3,30,0.055394,VIX_level,40,40,0.129031,0.129031,212
6,VIX_chg_20d_lag120,0.051215,0.001738,3.018957e-06,0.048241,0.053650,3,30,0.049477,VIX_chg_20d,120,120,0.178242,0.178242,132
7,DXY_ret_5d_lag120,0.050292,0.001078,1.163088e-06,0.048544,0.052323,3,30,0.049214,DXY_ret_5d,120,120,0.144858,0.144858,132
8,TNX_diff_20d_lag5,0.049925,0.001771,3.135040e-06,0.046680,0.052575,3,30,0.048155,TNX_diff_20d,5,5,0.233782,0.233782,247
9,SPY_ret_20d_lag120,0.049587,0.001888,3.563241e-06,0.047120,0.053090,3,30,0.047699,SPY_ret_20d,120,120,-0.184210,0.184210,132
10,OIL_ret_20d_lag60,0.049609,0.002562,6.566202e-06,0.046023,0.054144,3,30,0.047046,OIL_ret_20d,60,60,0.183668,0.183668,192
11,GOLD_ret_20d_lag1,0.049299,0.002614,6.835072e-06,0.045773,0.053670,3,30,0.046685,GOLD_ret_20d,1,1,0.156010,0.156010,251
12,USDKRW_ret_5d_lag40,0.047465,0.000926,8.578479e-07,0.045333,0.048986,3,30,0.046538,USDKRW_ret_5d,40,40,0.194949,0.194949,212
13,TSM_ret_20d_lag40,0.046758,0.001039,1.080266e-06,0.044701,0.048959,3,30,0.045719,TSM_ret_20d,40,40,-0.156042,0.156042,212
14,VIX_chg_5d_lag40,0.046637,0.001318,1.737261e-06,0.043782,0.049049,3,30,0.045319,VIX_chg_5d,40,40,0.213755,0.213755,212
15,USDKRW_ret_20d_lag40,0.044589,0.000760,5.781988e-07,0.043431,0.046596,3,30,0.043829,USDKRW_ret_20d,40,40,0.230330,0.230330,212
16,TSM_ret_5d_lag40,0.044796,0.001053,1.108525e-06,0.042784,0.046687,3,30,0.043743,TSM_ret_5d,40,40,-0.250401,0.250401,212
17,SPY_ret_5d_lag40,0.045185,0.001809,3.272031e-06,0.041485,0.048565,3,30,0.043376,SPY_ret_5d,40,40,-0.271129,0.271129,212
18,SMH_ma20_ratio_lag40,0.042832,0.000860,7.400631e-07,0.041198,0.044580,3,30,0.041972,SMH_ma20_ratio,40,40,-0.200945,0.200945,212
19,SMH_ma60_ratio_lag20,0.039862,0.000882,7.786455e-07,0.037686,0.041883,3,30,0.038980,SMH_ma60_ratio,20,20,-0.095011,0.095011,232

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1398, 23)
X_train shape: (1398, 20)
train target 분포:
target_5d_up_2pct
0    841
1    557
Name: count, dtype: int64
target_5d_up_2pct
0    0.601574
1    0.398426
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_5d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                0.0    0.106634     0
1  2026-02-24     419.160004                0.0    0.052695     0
2  2026-02-25     426.160004                0.0    0.035253     0
3  2026-02-26     412.010010                0.0    0.035817     0
4  2026-02-27     406.369995                0.0    0.021874     0
..        ...            ...                ...         ...   ...
59 2026-05-18     546.159973                NaN    0.115891     0
60 2026-05-19     543.960022                NaN    0.629015     1
61 2026-05-20     564.659973                NaN    0.109621     0
62 2026-05-21     567.880005                NaN    0.108502     0
63 2026-05-22     576.320007                NaN    0.538520     1

[64 rows x 5 columns]

예측값 분포:
pred
0    58
1     6
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 59
예측 1 개수: 4
예측 1 중 실제 1 개수: 2
예측 1 기준 정확도 precision: 0.5

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,5,0.02,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.1, 'm...",59,4,...,0.508475,0.5,0.068966,0.121212,0.349425,1.285673,28,2,27,2

[I 2026-05-23 21:05:16,562] Trial 88 finished with value: 0.5 and parameters: {'n_days': 5, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.5, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.1, 'gb_max_depth': 5}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 90/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 10, 'threshold': 0.03, 'top_n': 10, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 100, 'learning_rate': 0.03, 'max_leaf_nodes': 15}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 89}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_10d_up_3pct
target_df shape: (1533, 31)
target 분포:
target_10d_up_3pct
0    907
1    626
Name: count, dtype: int64
lagged_df shape: (1393, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1431

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1425

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1433
TOP feature count: 10
['USDKRW_ret_20d_lag1', 'OIL_ret_20d_lag40', 'TNX_level_lag120', 'DXY_ret_20d_lag120', 'SMH_vol_20d_lag40', 'VIX_level_lag1', 'TNX_diff_20d_lag5', 'TSM_ret_20d_lag40', 'SMH_ma20_ratio_lag40', 'SMH_ma60_ratio_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,USDKRW_ret_20d_lag1,0.126034,0.002997,0.000009,0.119453,0.133261,3,30,0.123037,USDKRW_ret_20d,1,1,-0.408214,0.408214,251
1,OIL_ret_20d_lag40,0.096463,0.002678,0.000007,0.091112,0.102565,3,30,0.093785,OIL_ret_20d,40,40,-0.318626,0.318626,212
2,TNX_level_lag120,0.080627,0.002211,0.000005,0.074639,0.086368,3,30,0.078416,TNX_level,120,120,-0.195924,0.195924,132
3,DXY_ret_20d_lag120,0.073622,0.001373,0.000002,0.070474,0.075453,3,30,0.072249,DXY_ret_20d,120,120,-0.293154,0.293154,132
4,SMH_vol_20d_lag40,0.063920,0.001438,0.000002,0.061510,0.067246,3,30,0.062482,SMH_vol_20d,40,40,0.281937,0.281937,212
5,VIX_level_lag1,0.059403,0.001746,0.000003,0.056041,0.063472,3,30,0.057657,VIX_level,1,1,0.240225,0.240225,251
6,TNX_diff_20d_lag5,0.059302,0.002218,0.000005,0.054268,0.064710,3,30,0.057085,TNX_diff_20d,5,5,0.307873,0.307873,247
7,TSM_ret_20d_lag40,0.055242,0.001483,0.000002,0.052429,0.058885,3,30,0.053759,TSM_ret_20d,40,40,-0.349006,0.349006,212
8,SMH_ma20_ratio_lag40,0.054793,0.001213,0.000001,0.052111,0.057220,3,30,0.053580,SMH_ma20_ratio,40,40,-0.288530,0.288530,212
9,SMH_ma60_ratio_lag40,0.053386,0.001023,0.000001,0.051840,0.055668,3,30,0.052363,SMH_ma60_ratio,40,40,-0.297396,0.297396,212

============================================================
6. valid_df 생성
============================================================
top feature 수: 10
lag 생성 후 valid_df shape: (1607, 22)
원본 base_feature 제거 후 valid_df shape: (1607, 12)
최종 컬럼 수: 12
target 생성 후 valid_df shape: (1607, 14)
최종 valid_df shape: (64, 14)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 10
train_df shape: (1393, 13)
X_train shape: (1393, 10)
train target 분포:
target_10d_up_3pct
0    834
1    559
Name: count, dtype: int64
target_10d_up_3pct
0    0.598708
1    0.401292
Name: proportion, dtype: float64
valid_df shape: (64, 14)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_10d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.458217     0
1  2026-02-24     419.160004                 0.0    0.506992     0
2  2026-02-25     426.160004                 0.0    0.518116     0
3  2026-02-26     412.010010                 0.0    0.250920     0
4  2026-02-27     406.369995                 0.0    0.386604     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.160440     0
60 2026-05-19     543.960022                 NaN    0.266076     0
61 2026-05-20     564.659973                 NaN    0.406112     0
62 2026-05-21     567.880005                 NaN    0.333466     0
63 2026-05-22     576.320007                 NaN    0.204976     0

[64 rows x 5 columns]

예측값 분포:
pred
0    55
1     9
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 54
예측 1 개수: 9
예측 1 중 실제 1 개수: 7
예측 1 기준 정확도 precision: 0.7777777777777778

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,10,0.03,1,10,10,hist_gradient_boosting,"{'max_iter': 100, 'learning_rate': 0.03, 'max_...",54,9,...,0.518519,0.777778,0.225806,0.35,0.330996,0.916198,21,2,24,7

[I 2026-05-23 21:05:33,184] Trial 89 finished with value: 0.7777777777777778 and parameters: {'n_days': 10, 'threshold': 0.03, 'top_n': 10, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 100, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 15}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 91/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 100, 'learning_rate': 0.01, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 90}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.553790     0
1  2026-02-24     419.160004                 0.0    0.543228     0
2  2026-02-25     426.160004                 0.0    0.561163     0
3  2026-02-26     412.010010                 0.0    0.536731     0
4  2026-02-27     406.369995                 0.0    0.532967     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.561723     0
60 2026-05-19     543.960022                 NaN    0.620408     0
61 2026-05-20     564.659973                 NaN    0.475770     0
62 2026-05-21     567.880005                 NaN    0.433038     0
63 2026-05-22     576.320007                 NaN    0.433038     0

[64 rows x 5 columns]

예측값 분포:
pred
0    64
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 0
예측 1 중 실제 1 개수: 0
예측 1 기준 정확도 precision: nan

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,gradient_boosting,"{'n_estimators': 100, 'learning_rate': 0.01, '...",44,0,...,0.227273,0.0,0.0,0.0,0.405882,0.661572,10,0,34,0

[I 2026-05-23 21:05:50,400] Trial 90 finished with value: 0.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'gb_n_estimators': 100, 'gb_learning_rate': 0.01, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:05:50,423] Trial 91 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:05:50,445] Trial 92 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:05:50,467] Trial 93 finished with value: 0.9 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 92/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 91}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204741_optuna_holdout_trial_0011
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 93/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 92}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204741_optuna_holdout_trial_0011
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 94/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 93}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_205523_optuna_holdout_trial_0043
기존 test_precision: 0.9

====================================================================================================
OPTUNA HOLDOUT TRIAL 95/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 94}
====================================================================================================

[I 2026-05-23 21:05:50,489] Trial 94 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204741_optuna_holdout_trial_0011
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 96/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 4}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 95}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.504989     0
1  2026-02-24     419.160004                 0.0    0.739353     1
2  2026-02-25     426.160004                 0.0    0.618586     0
3  2026-02-26     412.010010                 0.0    0.431028     0
4  2026-02-27     406.369995                 0.0    0.443173     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.610421     0
60 2026-05-19     543.960022                 NaN    0.790912     1
61 2026-05-20     564.659973                 NaN    0.505732     0
62 2026-05-21     567.880005                 NaN    0.520876     0
63 2026-05-22     576.320007                 NaN    0.619263     0

[64 rows x 5 columns]

예측값 분포:
pred
0    47
1    17
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 5
예측 1 중 실제 1 개수: 4
예측 1 기준 정확도 precision: 0.8

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.03, '...",44,5,...,0.295455,0.8,0.117647,0.205128,0.444118,0.760315,9,1,30,4

[I 2026-05-23 21:06:08,673] Trial 95 finished with value: 0.8 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 4}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 97/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 10, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'random_forest', 'model_params': {'n_estimators': 500, 'max_depth': None, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'class_weight': 'balanced'}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 96}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_10d_up_3pct
target_df shape: (1533, 31)
target 분포:
target_10d_up_3pct
0    907
1    626
Name: count, dtype: int64
lagged_df shape: (1393, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1431

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1425

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1433
TOP feature count: 20
['USDKRW_ret_20d_lag1', 'OIL_ret_20d_lag40', 'TNX_level_lag120', 'DXY_ret_20d_lag120', 'SMH_vol_20d_lag40', 'VIX_level_lag1', 'TNX_diff_20d_lag5', 'TSM_ret_20d_lag40', 'SMH_ma20_ratio_lag40', 'SMH_ma60_ratio_lag40', 'SMH_volume_ratio_20d_lag1', 'NVDA_ret_20d_lag40', 'SPY_ret_20d_lag40', 'VIX_chg_5d_lag60', 'VIX_chg_20d_lag40', 'GOLD_ret_20d_lag1', 'USDKRW_ret_5d_lag3', 'DXY_ret_5d_lag5', 'SOXX_ret_5d_lag40', 'TSM_ret_5d_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,USDKRW_ret_20d_lag1,0.126034,0.002997,8.980695e-06,0.119453,0.133261,3,30,0.123037,USDKRW_ret_20d,1,1,-0.408214,0.408214,251
1,OIL_ret_20d_lag40,0.096463,0.002678,7.170844e-06,0.091112,0.102565,3,30,0.093785,OIL_ret_20d,40,40,-0.318626,0.318626,212
2,TNX_level_lag120,0.080627,0.002211,4.888913e-06,0.074639,0.086368,3,30,0.078416,TNX_level,120,120,-0.195924,0.195924,132
3,DXY_ret_20d_lag120,0.073622,0.001373,1.884736e-06,0.070474,0.075453,3,30,0.072249,DXY_ret_20d,120,120,-0.293154,0.293154,132
4,SMH_vol_20d_lag40,0.063920,0.001438,2.066961e-06,0.061510,0.067246,3,30,0.062482,SMH_vol_20d,40,40,0.281937,0.281937,212
5,VIX_level_lag1,0.059403,0.001746,3.047977e-06,0.056041,0.063472,3,30,0.057657,VIX_level,1,1,0.240225,0.240225,251
6,TNX_diff_20d_lag5,0.059302,0.002218,4.918486e-06,0.054268,0.064710,3,30,0.057085,TNX_diff_20d,5,5,0.307873,0.307873,247
7,TSM_ret_20d_lag40,0.055242,0.001483,2.198098e-06,0.052429,0.058885,3,30,0.053759,TSM_ret_20d,40,40,-0.349006,0.349006,212
8,SMH_ma20_ratio_lag40,0.054793,0.001213,1.471149e-06,0.052111,0.057220,3,30,0.053580,SMH_ma20_ratio,40,40,-0.288530,0.288530,212
9,SMH_ma60_ratio_lag40,0.053386,0.001023,1.046921e-06,0.051840,0.055668,3,30,0.052363,SMH_ma60_ratio,40,40,-0.297396,0.297396,212
10,SMH_volume_ratio_20d_lag1,0.051650,0.002090,4.367474e-06,0.048032,0.055660,3,30,0.049560,SMH_volume_ratio_20d,1,1,0.186136,0.186136,251
11,NVDA_ret_20d_lag40,0.047124,0.001591,2.531745e-06,0.043689,0.049773,3,30,0.045533,NVDA_ret_20d,40,40,-0.192054,0.192054,212
12,SPY_ret_20d_lag40,0.049969,0.004929,2.429532e-05,0.042242,0.057221,3,30,0.045040,SPY_ret_20d,40,40,-0.270977,0.270977,212
13,VIX_chg_5d_lag60,0.043663,0.001981,3.925745e-06,0.039731,0.047597,3,30,0.041682,VIX_chg_5d,60,60,0.176557,0.176557,192
14,VIX_chg_20d_lag40,0.042420,0.001552,2.410066e-06,0.039666,0.045644,3,30,0.040867,VIX_chg_20d,40,40,0.240142,0.240142,212
15,GOLD_ret_20d_lag1,0.039796,0.000720,5.186415e-07,0.038508,0.041410,3,30,0.039076,GOLD_ret_20d,1,1,0.150955,0.150955,251
16,USDKRW_ret_5d_lag3,0.037802,0.001225,1.500943e-06,0.035512,0.039620,3,30,0.036577,USDKRW_ret_5d,3,3,-0.270483,0.270483,249
17,DXY_ret_5d_lag5,0.036078,0.000914,8.350636e-07,0.034211,0.037683,3,30,0.035164,DXY_ret_5d,5,5,-0.186237,0.186237,247
18,SOXX_ret_5d_lag40,0.034375,0.001310,1.716438e-06,0.032454,0.036978,3,30,0.033064,SOXX_ret_5d,40,40,-0.243564,0.243564,212
19,TSM_ret_5d_lag40,0.034537,0.001604,2.573093e-06,0.031413,0.037121,3,30,0.032933,TSM_ret_5d,40,40,-0.332453,0.332453,212

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1393, 23)
X_train shape: (1393, 20)
train target 분포:
target_10d_up_3pct
0    834
1    559
Name: count, dtype: int64
target_10d_up_3pct
0    0.598708
1    0.401292
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: random_forest
valid_df 예측 완료

         Date  SMH_adj_close  target_10d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.391612     0
1  2026-02-24     419.160004                 0.0    0.334863     0
2  2026-02-25     426.160004                 0.0    0.383047     0
3  2026-02-26     412.010010                 0.0    0.269404     0
4  2026-02-27     406.369995                 0.0    0.535915     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.308633     0
60 2026-05-19     543.960022                 NaN    0.281808     0
61 2026-05-20     564.659973                 NaN    0.411749     0
62 2026-05-21     567.880005                 NaN    0.385180     0
63 2026-05-22     576.320007                 NaN    0.212131     0

[64 rows x 5 columns]

예측값 분포:
pred
0    63
1     1
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 54
예측 1 개수: 1
예측 1 중 실제 1 개수: 0
예측 1 기준 정확도 precision: 0.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,10,0.03,1,20,20,random_forest,"{'n_estimators': 500, 'max_depth': None, 'min_...",54,1,...,0.407407,0.0,0.0,0.0,0.347826,0.813794,22,1,31,0

[I 2026-05-23 21:06:25,705] Trial 96 finished with value: 0.0 and parameters: {'n_days': 10, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'random_forest', 'rf_n_estimators': 500, 'rf_max_depth': None, 'rf_min_samples_leaf': 2, 'rf_max_features': 'sqrt'}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 98/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.015, 'top_n': 50, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 97}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_1pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_1pct
1    875
0    648
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1282

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1291

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1292
TOP feature count: 27
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'VIX_chg_20d_lag120', 'NVDA_ret_20d_lag1', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'SMH_ma20_ratio_lag1', 'USDKRW_ret_20d_lag40', 'DXY_ret_5d_lag120', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'VIX_level_lag20', 'VIX_chg_5d_lag120', 'OIL_ret_20d_lag120', 'SMH_ma60_ratio_lag1', 'TNX_diff_5d_lag5', 'GOLD_ret_20d_lag120', 'OIL_ret_5d_lag10', 'GOLD_ret_5d_lag60', 'SPY_ret_5d_lag120', 'TSM_ret_5d_lag1', 'NVDA_ret_5d_lag60', 'SOXX_ret_5d_lag120', 'USDKRW_ret_5d_lag40', 'SMH_volume_ratio_20d_lag120', 'SMH_ma5_ratio_lag120', 'SMH_ret_1d_lag60']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118484,0.002821,7.957216e-06,0.109722,0.124056,3,30,0.115663,SMH_vol_20d,120,120,-0.303085,0.303085,132
1,TNX_level_lag20,0.098508,0.003546,1.257577e-05,0.091406,0.103231,3,30,0.094962,TNX_level,20,20,-0.312171,0.312171,232
2,VIX_chg_20d_lag120,0.084307,0.004767,2.272657e-05,0.074815,0.090386,3,30,0.079540,VIX_chg_20d,120,120,0.361218,0.361218,132
3,NVDA_ret_20d_lag1,0.077011,0.002656,7.056867e-06,0.073438,0.082286,3,30,0.074355,NVDA_ret_20d,1,1,0.255267,0.255267,251
4,DXY_ret_20d_lag60,0.073972,0.003501,1.226018e-05,0.065067,0.079207,3,30,0.070471,DXY_ret_20d,60,60,-0.224007,0.224007,192
5,TNX_diff_20d_lag1,0.067782,0.002068,4.275689e-06,0.063536,0.070710,3,30,0.065714,TNX_diff_20d,1,1,0.409580,0.409580,251
6,SMH_ma20_ratio_lag1,0.064028,0.003588,1.287606e-05,0.057455,0.069127,3,30,0.060440,SMH_ma20_ratio,1,1,0.278312,0.278312,251
7,USDKRW_ret_20d_lag40,0.054209,0.001347,1.813178e-06,0.051963,0.056946,3,30,0.052862,USDKRW_ret_20d,40,40,0.344971,0.344971,212
8,DXY_ret_5d_lag120,0.053646,0.002349,5.516362e-06,0.049564,0.057537,3,30,0.051297,DXY_ret_5d,120,120,-0.258618,0.258618,132
9,SPY_ret_20d_lag120,0.053166,0.002152,4.629870e-06,0.049174,0.057806,3,30,0.051015,SPY_ret_20d,120,120,-0.257846,0.257846,132
10,TSM_ret_20d_lag1,0.051027,0.002671,7.136912e-06,0.045914,0.054292,3,30,0.048356,TSM_ret_20d,1,1,0.323766,0.323766,251
11,VIX_level_lag20,0.051332,0.003401,1.156368e-05,0.046068,0.056499,3,30,0.047931,VIX_level,20,20,0.256886,0.256886,232
12,VIX_chg_5d_lag120,0.050033,0.002465,6.074460e-06,0.045693,0.053445,3,30,0.047568,VIX_chg_5d,120,120,0.140989,0.140989,132
13,OIL_ret_20d_lag120,0.046951,0.001639,2.685367e-06,0.043890,0.051856,3,30,0.045313,OIL_ret_20d,120,120,0.317093,0.317093,132
14,SMH_ma60_ratio_lag1,0.045240,0.000929,8.634352e-07,0.043842,0.047279,3,30,0.044311,SMH_ma60_ratio,1,1,0.195063,0.195063,251
15,TNX_diff_5d_lag5,0.044214,0.002358,5.561184e-06,0.039888,0.047489,3,30,0.041856,TNX_diff_5d,5,5,0.211260,0.211260,247
16,GOLD_ret_20d_lag120,0.038123,0.001246,1.553398e-06,0.035914,0.041085,3,30,0.036877,GOLD_ret_20d,120,120,-0.347004,0.347004,132
17,OIL_ret_5d_lag10,0.030618,0.000852,7.251870e-07,0.029380,0.032145,3,30,0.029766,OIL_ret_5d,10,10,0.189850,0.189850,242
18,GOLD_ret_5d_lag60,0.029241,0.000940,8.827980e-07,0.027493,0.030948,3,30,0.028301,GOLD_ret_5d,60,60,0.194501,0.194501,192
19,SPY_ret_5d_lag120,0.028214,0.000910,8.287835e-07,0.026523,0.029787,3,30,0.027304,SPY_ret_5d,120,120,-0.236798,0.236798,132
20,TSM_ret_5d_lag1,0.028039,0.001019,1.038970e-06,0.026330,0.029798,3,30,0.027020,TSM_ret_5d,1,1,0.260895,0.260895,251
21,NVDA_ret_5d_lag60,0.027845,0.000884,7.817632e-07,0.026495,0.029704,3,30,0.026960,NVDA_ret_5d,60,60,-0.256250,0.256250,192
22,SOXX_ret_5d_lag120,0.026760,0.001197,1.433418e-06,0.024435,0.028451,3,30,0.025563,SOXX_ret_5d,120,120,-0.288594,0.288594,132
23,USDKRW_ret_5d_lag40,0.023375,0.000731,5.336340e-07,0.022434,0.025030,3,30,0.022644,USDKRW_ret_5d,40,40,0.114054,0.114054,212
24,SMH_volume_ratio_20d_lag120,0.022116,0.000534,2.850611e-07,0.021068,0.023208,3,30,0.021583,SMH_volume_ratio_20d,120,120,0.289975,0.289975,132
25,SMH_ma5_ratio_lag120,0.018352,0.000836,6.982680e-07,0.016641,0.019708,3,30,0.017517,SMH_ma5_ratio,120,120,-0.220128,0.220128,132
26,SMH_ret_1d_lag60,0.015269,0.000433,1.877810e-07,0.014436,0.016025,3,30,0.014835,SMH_ret_1d,60,60,-0.144449,0.144449,192

============================================================
6. valid_df 생성
============================================================
top feature 수: 27
lag 생성 후 valid_df shape: (1607, 56)
원본 base_feature 제거 후 valid_df shape: (1607, 29)
최종 컬럼 수: 29
target 생성 후 valid_df shape: (1607, 31)
최종 valid_df shape: (64, 31)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 27
train_df shape: (1383, 30)
X_train shape: (1383, 27)
train target 분포:
target_20d_up_1pct
1    773
0    610
Name: count, dtype: int64
target_20d_up_1pct
1    0.55893
0    0.44107
Name: proportion, dtype: float64
valid_df shape: (64, 31)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_1pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.522575     0
1  2026-02-24     419.160004                 0.0    0.694064     0
2  2026-02-25     426.160004                 0.0    0.335202     0
3  2026-02-26     412.010010                 0.0    0.420073     0
4  2026-02-27     406.369995                 0.0    0.355483     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.722976     1
60 2026-05-19     543.960022                 NaN    0.753578     1
61 2026-05-20     564.659973                 NaN    0.292947     0
62 2026-05-21     567.880005                 NaN    0.658215     0
63 2026-05-22     576.320007                 NaN    0.802403     1

[64 rows x 5 columns]

예측값 분포:
pred
0    43
1    21
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 6
예측 1 중 실제 1 개수: 4
예측 1 기준 정확도 precision: 0.6666666666666666

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.015,1,50,27,hist_gradient_boosting,"{'max_iter': 300, 'learning_rate': 0.03, 'max_...",44,6,...,0.272727,0.666667,0.117647,0.2,0.397059,0.859143,8,2,30,4

[I 2026-05-23 21:06:44,200] Trial 97 finished with value: 0.6666666666666666 and parameters: {'n_days': 20, 'threshold': 0.015, 'top_n': 50, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 99/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.01, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 500, 'learning_rate': 0.05, 'max_depth': 2}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 98}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_1pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_1pct
1    917
0    606
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1301

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1302

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1305
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'NVDA_ret_5d_lag120', 'DXY_ret_5d_lag120', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SMH_ma60_ratio_lag1', 'OIL_ret_20d_lag120', 'VIX_chg_5d_lag120', 'SPY_ret_20d_lag1', 'TNX_diff_5d_lag5', 'GOLD_ret_20d_lag120', 'SMH_ma20_ratio_lag120', 'TSM_ret_5d_lag120', 'GOLD_ret_5d_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.113199,0.003130,9.798652e-06,0.105366,0.117758,3,30,0.110069,SMH_vol_20d,120,120,-0.305565,0.305565,132
1,TNX_level_lag20,0.111395,0.001966,3.863856e-06,0.107542,0.114334,3,30,0.109430,TNX_level,20,20,-0.282349,0.282349,232
2,NVDA_ret_20d_lag1,0.080573,0.003084,9.508619e-06,0.075624,0.086273,3,30,0.077490,NVDA_ret_20d,1,1,0.282168,0.282168,251
3,VIX_chg_20d_lag120,0.077843,0.001462,2.138529e-06,0.074670,0.080400,3,30,0.076381,VIX_chg_20d,120,120,0.371232,0.371232,132
4,DXY_ret_20d_lag60,0.073491,0.002177,4.737914e-06,0.068070,0.077471,3,30,0.071314,DXY_ret_20d,60,60,-0.256904,0.256904,192
5,TNX_diff_20d_lag1,0.066654,0.002093,4.380060e-06,0.062034,0.070705,3,30,0.064561,TNX_diff_20d,1,1,0.416622,0.416622,251
6,NVDA_ret_5d_lag120,0.056072,0.001459,2.128896e-06,0.052971,0.058355,3,30,0.054613,NVDA_ret_5d,120,120,-0.233880,0.233880,132
7,DXY_ret_5d_lag120,0.053295,0.001976,3.904778e-06,0.049647,0.058129,3,30,0.051319,DXY_ret_5d,120,120,-0.267096,0.267096,132
8,VIX_level_lag20,0.051839,0.001035,1.070311e-06,0.049900,0.053607,3,30,0.050805,VIX_level,20,20,0.239784,0.239784,232
9,USDKRW_ret_20d_lag40,0.051299,0.001162,1.350872e-06,0.049044,0.053384,3,30,0.050136,USDKRW_ret_20d,40,40,0.281470,0.281470,212
10,TSM_ret_20d_lag1,0.050516,0.002066,4.268228e-06,0.047785,0.054069,3,30,0.048450,TSM_ret_20d,1,1,0.339692,0.339692,251
11,SMH_ma60_ratio_lag1,0.047034,0.001847,3.412431e-06,0.043919,0.049834,3,30,0.045187,SMH_ma60_ratio,1,1,0.226498,0.226498,251
12,OIL_ret_20d_lag120,0.044614,0.001553,2.410659e-06,0.041020,0.048293,3,30,0.043061,OIL_ret_20d,120,120,0.291387,0.291387,132
13,VIX_chg_5d_lag120,0.042947,0.001208,1.459362e-06,0.040616,0.045759,3,30,0.041739,VIX_chg_5d,120,120,0.143824,0.143824,132
14,SPY_ret_20d_lag1,0.043100,0.001912,3.657161e-06,0.039473,0.046173,3,30,0.041188,SPY_ret_20d,1,1,0.273031,0.273031,251
15,TNX_diff_5d_lag5,0.041964,0.001642,2.694547e-06,0.039434,0.045450,3,30,0.040323,TNX_diff_5d,5,5,0.182059,0.182059,247
16,GOLD_ret_20d_lag120,0.037065,0.001167,1.361693e-06,0.034635,0.040013,3,30,0.035898,GOLD_ret_20d,120,120,-0.306548,0.306548,132
17,SMH_ma20_ratio_lag120,0.034339,0.000618,3.813267e-07,0.033254,0.035764,3,30,0.033721,SMH_ma20_ratio,120,120,-0.303183,0.303183,132
18,TSM_ret_5d_lag120,0.034178,0.001041,1.084444e-06,0.032365,0.036477,3,30,0.033136,TSM_ret_5d,120,120,-0.251775,0.251775,132
19,GOLD_ret_5d_lag40,0.031021,0.001323,1.750672e-06,0.028289,0.032956,3,30,0.029698,GOLD_ret_5d,40,40,-0.185968,0.185968,212

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_1pct
1    815
0    568
Name: count, dtype: int64
target_20d_up_1pct
1    0.589299
0    0.410701
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_1pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.750339     1
1  2026-02-24     419.160004                 0.0    0.799959     1
2  2026-02-25     426.160004                 0.0    0.753538     1
3  2026-02-26     412.010010                 0.0    0.671782     1
4  2026-02-27     406.369995                 0.0    0.754339     1
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.620544     1
60 2026-05-19     543.960022                 NaN    0.693011     1
61 2026-05-20     564.659973                 NaN    0.643136     1
62 2026-05-21     567.880005                 NaN    0.856053     1
63 2026-05-22     576.320007                 NaN    0.734244     1

[64 rows x 5 columns]

예측값 분포:
pred
1    51
0    13
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 34
예측 1 중 실제 1 개수: 26
예측 1 기준 정확도 precision: 0.7647058823529411

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.01,1,20,20,gradient_boosting,"{'n_estimators': 500, 'learning_rate': 0.05, '...",44,34,...,0.613636,0.764706,0.742857,0.753623,0.346032,0.623031,1,8,9,26

[I 2026-05-23 21:07:02,530] Trial 98 finished with value: 0.7647058823529411 and parameters: {'n_days': 20, 'threshold': 0.01, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'gradient_boosting', 'gb_n_estimators': 500, 'gb_learning_rate': 0.05, 'gb_max_depth': 2}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 100/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 3, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'logistic', 'model_params': {'C': 0.1, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 99}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_3d_up_2pct
target_df shape: (1540, 31)
target 분포:
target_3d_up_2pct
0    1034
1     506
Name: count, dtype: int64
lagged_df shape: (1400, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1599

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.159

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1591
TOP feature count: 20
['NVDA_ret_20d_lag1', 'DXY_ret_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma5_ratio_lag10', 'SMH_ma60_ratio_lag1', 'SOXX_ret_5d_lag1', 'VIX_level_lag1', 'VIX_chg_20d_lag40', 'TSM_ret_5d_lag10', 'GOLD_ret_5d_lag120', 'GOLD_ret_20d_lag120', 'TSM_ret_20d_lag40', 'USDKRW_ret_20d_lag40', 'SMH_ret_1d_lag10', 'TNX_level_lag1', 'VIX_chg_5d_lag40', 'SMH_vol_20d_lag60', 'NVDA_ret_5d_lag1', 'SPY_ret_20d_lag120', 'SPY_ret_5d_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,NVDA_ret_20d_lag1,0.097206,0.004106,1.686072e-05,0.090497,0.104698,3,30,0.093100,NVDA_ret_20d,1,1,-0.111781,0.111781,250
1,DXY_ret_20d_lag120,0.070614,0.001475,2.175890e-06,0.067993,0.074612,3,30,0.069139,DXY_ret_20d,120,120,-0.105215,0.105215,131
2,SMH_ma20_ratio_lag1,0.061117,0.001850,3.423071e-06,0.057828,0.065284,3,30,0.059267,SMH_ma20_ratio,1,1,-0.175532,0.175532,250
3,SMH_ma5_ratio_lag10,0.056295,0.001797,3.229324e-06,0.052956,0.059930,3,30,0.054498,SMH_ma5_ratio,10,10,-0.235165,0.235165,241
4,SMH_ma60_ratio_lag1,0.054641,0.001352,1.827155e-06,0.051610,0.056799,3,30,0.053289,SMH_ma60_ratio,1,1,-0.137592,0.137592,250
5,SOXX_ret_5d_lag1,0.052406,0.002972,8.835182e-06,0.046161,0.056209,3,30,0.049434,SOXX_ret_5d,1,1,-0.199028,0.199028,250
6,VIX_level_lag1,0.052427,0.003118,9.723011e-06,0.048047,0.057951,3,30,0.049308,VIX_level,1,1,0.126094,0.126094,250
7,VIX_chg_20d_lag40,0.048218,0.001064,1.132742e-06,0.045217,0.050314,3,30,0.047154,VIX_chg_20d,40,40,0.182643,0.182643,211
8,TSM_ret_5d_lag10,0.044915,0.001040,1.082322e-06,0.043098,0.047615,3,30,0.043874,TSM_ret_5d,10,10,-0.179270,0.179270,241
9,GOLD_ret_5d_lag120,0.044546,0.001121,1.255637e-06,0.042196,0.047571,3,30,0.043425,GOLD_ret_5d,120,120,-0.114377,0.114377,131
10,GOLD_ret_20d_lag120,0.043482,0.001129,1.274155e-06,0.040819,0.045993,3,30,0.042353,GOLD_ret_20d,120,120,-0.107223,0.107223,131
11,TSM_ret_20d_lag40,0.043783,0.002185,4.773945e-06,0.039529,0.046979,3,30,0.041598,TSM_ret_20d,40,40,-0.096849,0.096849,211
12,USDKRW_ret_20d_lag40,0.041263,0.001944,3.778063e-06,0.037834,0.044233,3,30,0.039320,USDKRW_ret_20d,40,40,0.152425,0.152425,211
13,SMH_ret_1d_lag10,0.040061,0.001287,1.656742e-06,0.037420,0.042480,3,30,0.038774,SMH_ret_1d,10,10,-0.169190,0.169190,241
14,TNX_level_lag1,0.039300,0.000939,8.809489e-07,0.036885,0.040442,3,30,0.038361,TNX_level,1,1,-0.130603,0.130603,250
15,VIX_chg_5d_lag40,0.039871,0.001533,2.351359e-06,0.037075,0.042152,3,30,0.038338,VIX_chg_5d,40,40,0.159722,0.159722,211
16,SMH_vol_20d_lag60,0.039652,0.001963,3.852132e-06,0.036112,0.042364,3,30,0.037689,SMH_vol_20d,60,60,-0.150076,0.150076,191
17,NVDA_ret_5d_lag1,0.038617,0.001202,1.445857e-06,0.036307,0.040936,3,30,0.037415,NVDA_ret_5d,1,1,-0.181966,0.181966,250
18,SPY_ret_20d_lag120,0.038898,0.001529,2.338266e-06,0.036068,0.041820,3,30,0.037369,SPY_ret_20d,120,120,-0.124476,0.124476,131
19,SPY_ret_5d_lag40,0.038334,0.001174,1.378602e-06,0.035871,0.040135,3,30,0.037160,SPY_ret_5d,40,40,-0.203227,0.203227,211

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1400, 23)
X_train shape: (1400, 20)
train target 분포:
target_3d_up_2pct
0    942
1    458
Name: count, dtype: int64
target_3d_up_2pct
0    0.672857
1    0.327143
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_3d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                0.0    0.449941     0
1  2026-02-24     419.160004                0.0    0.355653     0
2  2026-02-25     426.160004                0.0    0.347871     0
3  2026-02-26     412.010010                0.0    0.359268     0
4  2026-02-27     406.369995                0.0    0.436546     0
..        ...            ...                ...         ...   ...
59 2026-05-18     546.159973                1.0    0.490250     0
60 2026-05-19     543.960022                1.0    0.495313     0
61 2026-05-20     564.659973                NaN    0.422521     0
62 2026-05-21     567.880005                NaN    0.368377     0
63 2026-05-22     576.320007                NaN    0.337149     0

[64 rows x 5 columns]

예측값 분포:
pred
0    61
1     3
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 61
예측 1 개수: 3
예측 1 중 실제 1 개수: 1
예측 1 기준 정확도 precision: 0.3333333333333333

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,3,0.02,1,20,20,logistic,"{'C': 0.1, 'class_weight': 'balanced', 'max_it...",61,3,...,0.491803,0.333333,0.033333,0.060606,0.437634,0.753776,29,2,29,1

[I 2026-05-23 21:07:19,878] Trial 99 finished with value: 0.3333333333333333 and parameters: {'n_days': 3, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'logistic', 'logistic_C': 0.1}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 101/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.01, 'max_depth': 5}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 100}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 20
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.463030     0
1  2026-02-24     419.160004                 0.0    0.562749     0
2  2026-02-25     426.160004                 0.0    0.565855     0
3  2026-02-26     412.010010                 0.0    0.570370     0
4  2026-02-27     406.369995                 0.0    0.630296     1
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.556302     0
60 2026-05-19     543.960022                 NaN    0.537999     0
61 2026-05-20     564.659973                 NaN    0.314920     0
62 2026-05-21     567.880005                 NaN    0.474601     0
63 2026-05-22     576.320007                 NaN    0.487182     0

[64 rows x 5 columns]

예측값 분포:
pred
0    44
1    20
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 8
예측 1 중 실제 1 개수: 6
예측 1 기준 정확도 precision: 0.75

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.01, '...",44,8,...,0.318182,0.75,0.176471,0.285714,0.385294,0.719736,8,2,28,6

[I 2026-05-23 21:07:38,611] Trial 100 finished with value: 0.75 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.01, 'gb_max_depth': 5}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:07:38,634] Trial 101 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:07:38,657] Trial 102 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:07:38,680] Trial 103 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:07:38,702] Trial 104 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 102/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 101}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204741_optuna_holdout_trial_0011
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 103/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 102}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204741_optuna_holdout_trial_0011
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 104/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 103}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_205932_optuna_holdout_trial_0060
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 105/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 104}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204741_optuna_holdout_trial_0011
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 106/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 5, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 105}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_5d_up_2pct
target_df shape: (1538, 31)
target 분포:
target_5d_up_2pct
0    919
1    619
Name: count, dtype: int64
lagged_df shape: (1398, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1646

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1648

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1651
TOP feature count: 20
['DXY_ret_20d_lag120', 'SMH_vol_20d_lag60', 'TNX_diff_5d_lag1', 'TNX_level_lag1', 'GOLD_ret_5d_lag120', 'VIX_level_lag40', 'VIX_chg_20d_lag120', 'DXY_ret_5d_lag120', 'TNX_diff_20d_lag5', 'SPY_ret_20d_lag120', 'OIL_ret_20d_lag60', 'GOLD_ret_20d_lag1', 'USDKRW_ret_5d_lag40', 'TSM_ret_20d_lag40', 'VIX_chg_5d_lag40', 'USDKRW_ret_20d_lag40', 'TSM_ret_5d_lag40', 'SPY_ret_5d_lag40', 'SMH_ma20_ratio_lag40', 'SMH_ma60_ratio_lag20']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,DXY_ret_20d_lag120,0.097643,0.003116,9.710753e-06,0.091485,0.102341,3,30,0.094526,DXY_ret_20d,120,120,-0.177627,0.177627,132
1,SMH_vol_20d_lag60,0.073933,0.001638,2.684309e-06,0.071582,0.077448,3,30,0.072294,SMH_vol_20d,60,60,-0.200945,0.200945,192
2,TNX_diff_5d_lag1,0.072014,0.003887,1.510828e-05,0.064915,0.076751,3,30,0.068127,TNX_diff_5d,1,1,-0.194687,0.194687,251
3,TNX_level_lag1,0.070761,0.003199,1.023364e-05,0.063743,0.075185,3,30,0.067562,TNX_level,1,1,-0.214996,0.214996,251
4,GOLD_ret_5d_lag120,0.061778,0.001114,1.241156e-06,0.059052,0.064708,3,30,0.060664,GOLD_ret_5d,120,120,-0.197469,0.197469,132
5,VIX_level_lag40,0.057051,0.001657,2.746894e-06,0.053453,0.059921,3,30,0.055394,VIX_level,40,40,0.129031,0.129031,212
6,VIX_chg_20d_lag120,0.051215,0.001738,3.018957e-06,0.048241,0.053650,3,30,0.049477,VIX_chg_20d,120,120,0.178242,0.178242,132
7,DXY_ret_5d_lag120,0.050292,0.001078,1.163088e-06,0.048544,0.052323,3,30,0.049214,DXY_ret_5d,120,120,0.144858,0.144858,132
8,TNX_diff_20d_lag5,0.049925,0.001771,3.135040e-06,0.046680,0.052575,3,30,0.048155,TNX_diff_20d,5,5,0.233782,0.233782,247
9,SPY_ret_20d_lag120,0.049587,0.001888,3.563241e-06,0.047120,0.053090,3,30,0.047699,SPY_ret_20d,120,120,-0.184210,0.184210,132
10,OIL_ret_20d_lag60,0.049609,0.002562,6.566202e-06,0.046023,0.054144,3,30,0.047046,OIL_ret_20d,60,60,0.183668,0.183668,192
11,GOLD_ret_20d_lag1,0.049299,0.002614,6.835072e-06,0.045773,0.053670,3,30,0.046685,GOLD_ret_20d,1,1,0.156010,0.156010,251
12,USDKRW_ret_5d_lag40,0.047465,0.000926,8.578479e-07,0.045333,0.048986,3,30,0.046538,USDKRW_ret_5d,40,40,0.194949,0.194949,212
13,TSM_ret_20d_lag40,0.046758,0.001039,1.080266e-06,0.044701,0.048959,3,30,0.045719,TSM_ret_20d,40,40,-0.156042,0.156042,212
14,VIX_chg_5d_lag40,0.046637,0.001318,1.737261e-06,0.043782,0.049049,3,30,0.045319,VIX_chg_5d,40,40,0.213755,0.213755,212
15,USDKRW_ret_20d_lag40,0.044589,0.000760,5.781988e-07,0.043431,0.046596,3,30,0.043829,USDKRW_ret_20d,40,40,0.230330,0.230330,212
16,TSM_ret_5d_lag40,0.044796,0.001053,1.108525e-06,0.042784,0.046687,3,30,0.043743,TSM_ret_5d,40,40,-0.250401,0.250401,212
17,SPY_ret_5d_lag40,0.045185,0.001809,3.272031e-06,0.041485,0.048565,3,30,0.043376,SPY_ret_5d,40,40,-0.271129,0.271129,212
18,SMH_ma20_ratio_lag40,0.042832,0.000860,7.400631e-07,0.041198,0.044580,3,30,0.041972,SMH_ma20_ratio,40,40,-0.200945,0.200945,212
19,SMH_ma60_ratio_lag20,0.039862,0.000882,7.786455e-07,0.037686,0.041883,3,30,0.038980,SMH_ma60_ratio,20,20,-0.095011,0.095011,232

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1398, 23)
X_train shape: (1398, 20)
train target 분포:
target_5d_up_2pct
0    841
1    557
Name: count, dtype: int64
target_5d_up_2pct
0    0.601574
1    0.398426
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_5d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                0.0    0.262087     0
1  2026-02-24     419.160004                0.0    0.022288     0
2  2026-02-25     426.160004                0.0    0.076639     0
3  2026-02-26     412.010010                0.0    0.035075     0
4  2026-02-27     406.369995                0.0    0.057521     0
..        ...            ...                ...         ...   ...
59 2026-05-18     546.159973                NaN    0.609049     1
60 2026-05-19     543.960022                NaN    0.595514     0
61 2026-05-20     564.659973                NaN    0.412353     0
62 2026-05-21     567.880005                NaN    0.308183     0
63 2026-05-22     576.320007                NaN    0.295928     0

[64 rows x 5 columns]

예측값 분포:
pred
0    60
1     4
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 59
예측 1 개수: 3
예측 1 중 실제 1 개수: 1
예측 1 기준 정확도 precision: 0.3333333333333333

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,5,0.02,1,20,20,hist_gradient_boosting,"{'max_iter': 300, 'learning_rate': 0.03, 'max_...",59,3,...,0.491525,0.333333,0.034483,0.0625,0.387356,1.110748,28,2,28,1

[I 2026-05-23 21:07:57,542] Trial 105 finished with value: 0.3333333333333333 and parameters: {'n_days': 5, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 107/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 30, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 106}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 27
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1', 'TNX_diff_5d_lag5', 'SPY_ret_5d_lag120', 'NVDA_ret_5d_lag60', 'SOXX_ret_5d_lag120', 'SMH_volume_ratio_20d_lag40', 'SMH_ma5_ratio_lag60', 'SMH_ret_1d_lag60']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251
20,TNX_diff_5d_lag5,0.028148,0.001107,1.226237e-06,0.026030,0.029843,3,30,0.027041,TNX_diff_5d,5,5,0.205918,0.205918,247
21,SPY_ret_5d_lag120,0.027266,0.000982,9.634165e-07,0.025657,0.029503,3,30,0.026284,SPY_ret_5d,120,120,-0.226060,0.226060,132
22,NVDA_ret_5d_lag60,0.026746,0.001502,2.255625e-06,0.024752,0.029620,3,30,0.025244,NVDA_ret_5d,60,60,-0.230714,0.230714,192
23,SOXX_ret_5d_lag120,0.025377,0.000772,5.958999e-07,0.023624,0.026787,3,30,0.024605,SOXX_ret_5d,120,120,-0.180724,0.180724,132
24,SMH_volume_ratio_20d_lag40,0.023451,0.000495,2.454801e-07,0.022375,0.024293,3,30,0.022956,SMH_volume_ratio_20d,40,40,-0.175235,0.175235,212
25,SMH_ma5_ratio_lag60,0.020131,0.000685,4.688208e-07,0.018742,0.021058,3,30,0.019447,SMH_ma5_ratio,60,60,-0.179975,0.179975,192
26,SMH_ret_1d_lag60,0.015072,0.000675,4.562163e-07,0.013999,0.016328,3,30,0.014397,SMH_ret_1d,60,60,-0.127110,0.127110,192

============================================================
6. valid_df 생성
============================================================
top feature 수: 27
lag 생성 후 valid_df shape: (1607, 56)
원본 base_feature 제거 후 valid_df shape: (1607, 29)
최종 컬럼 수: 29
target 생성 후 valid_df shape: (1607, 31)
최종 valid_df shape: (64, 31)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 27
train_df shape: (1383, 30)
X_train shape: (1383, 27)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 31)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.491375     0
1  2026-02-24     419.160004                 0.0    0.538695     0
2  2026-02-25     426.160004                 0.0    0.482424     0
3  2026-02-26     412.010010                 0.0    0.570947     0
4  2026-02-27     406.369995                 0.0    0.573479     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.585350     0
60 2026-05-19     543.960022                 NaN    0.578917     0
61 2026-05-20     564.659973                 NaN    0.333243     0
62 2026-05-21     567.880005                 NaN    0.526470     0
63 2026-05-22     576.320007                 NaN    0.710277     1

[64 rows x 5 columns]

예측값 분포:
pred
0    53
1    11
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 2
예측 1 중 실제 1 개수: 2
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,30,27,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.03, '...",44,2,...,0.272727,1.0,0.058824,0.111111,0.358824,0.808679,10,0,32,2

[I 2026-05-23 21:08:17,425] Trial 106 finished with value: 0.6666666666666666 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 30, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 108/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 10, 'threshold': 0.005, 'top_n': 20, 'pred_threshold': 0.75, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.05, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 107}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_10d_up_0pct
target_df shape: (1533, 31)
target 분포:
target_10d_up_0pct
1    882
0    651
Name: count, dtype: int64
lagged_df shape: (1354, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1396

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1396

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1394
TOP feature count: 20
['TNX_level_lag120', 'USDKRW_ret_20d_lag3', 'DXY_ret_20d_lag120', 'SMH_vol_20d_lag40', 'OIL_ret_20d_lag120', 'TNX_diff_20d_lag5', 'GOLD_ret_20d_lag40', 'NVDA_ret_20d_lag120', 'TSM_ret_5d_lag40', 'SPY_ret_20d_lag120', 'VIX_level_lag40', 'VIX_chg_5d_lag60', 'VIX_chg_20d_lag120', 'SMH_ma60_ratio_lag120', 'SMH_volume_ratio_20d_lag5', 'SMH_ma20_ratio_lag120', 'TSM_ret_20d_lag120', 'USDKRW_ret_5d_lag120', 'TNX_diff_5d_lag60', 'DXY_ret_5d_lag120']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.114099,0.005156,2.658068e-05,0.102361,0.121295,3,30,0.108944,TNX_level,120,120,-0.247079,0.247079,132
1,USDKRW_ret_20d_lag3,0.105354,0.006455,4.166613e-05,0.094970,0.115848,3,30,0.098899,USDKRW_ret_20d,3,3,-0.314678,0.314678,249
2,DXY_ret_20d_lag120,0.097480,0.002902,8.420871e-06,0.091990,0.102329,3,30,0.094578,DXY_ret_20d,120,120,-0.300370,0.300370,132
3,SMH_vol_20d_lag40,0.079376,0.002295,5.266172e-06,0.075700,0.083706,3,30,0.077081,SMH_vol_20d,40,40,0.216317,0.216317,212
4,OIL_ret_20d_lag120,0.066135,0.001842,3.394378e-06,0.063081,0.069975,3,30,0.064293,OIL_ret_20d,120,120,-0.229237,0.229237,132
5,TNX_diff_20d_lag5,0.061168,0.001872,3.503907e-06,0.057590,0.065294,3,30,0.059296,TNX_diff_20d,5,5,0.361960,0.361960,247
6,GOLD_ret_20d_lag40,0.057597,0.001910,3.647110e-06,0.053794,0.061701,3,30,0.055687,GOLD_ret_20d,40,40,-0.148102,0.148102,212
7,NVDA_ret_20d_lag120,0.054337,0.001519,2.307904e-06,0.050717,0.058087,3,30,0.052818,NVDA_ret_20d,120,120,-0.253585,0.253585,132
8,TSM_ret_5d_lag40,0.053448,0.001459,2.129743e-06,0.051298,0.056400,3,30,0.051989,TSM_ret_5d,40,40,-0.242780,0.242780,212
9,SPY_ret_20d_lag120,0.051863,0.001866,3.480598e-06,0.047460,0.055409,3,30,0.049998,SPY_ret_20d,120,120,-0.318511,0.318511,132
10,VIX_level_lag40,0.050667,0.001172,1.372871e-06,0.047863,0.052770,3,30,0.049496,VIX_level,40,40,0.151591,0.151591,212
11,VIX_chg_5d_lag60,0.047297,0.003269,1.068507e-05,0.042487,0.052602,3,30,0.044028,VIX_chg_5d,60,60,0.127624,0.127624,192
12,VIX_chg_20d_lag120,0.044215,0.001232,1.516596e-06,0.041359,0.046152,3,30,0.042983,VIX_chg_20d,120,120,0.313103,0.313103,132
13,SMH_ma60_ratio_lag120,0.043850,0.001086,1.179128e-06,0.041431,0.046171,3,30,0.042764,SMH_ma60_ratio,120,120,-0.197638,0.197638,132
14,SMH_volume_ratio_20d_lag5,0.042285,0.001657,2.746598e-06,0.039245,0.045566,3,30,0.040627,SMH_volume_ratio_20d,5,5,0.195126,0.195126,247
15,SMH_ma20_ratio_lag120,0.040721,0.001256,1.578181e-06,0.039018,0.043972,3,30,0.039465,SMH_ma20_ratio,120,120,-0.312656,0.312656,132
16,TSM_ret_20d_lag120,0.039925,0.001511,2.282005e-06,0.037629,0.043307,3,30,0.038415,TSM_ret_20d,120,120,-0.264108,0.264108,132
17,USDKRW_ret_5d_lag120,0.037754,0.001205,1.451256e-06,0.034878,0.039443,3,30,0.036549,USDKRW_ret_5d,120,120,0.236574,0.236574,132
18,TNX_diff_5d_lag60,0.034374,0.000919,8.439244e-07,0.032628,0.036210,3,30,0.033455,TNX_diff_5d,60,60,-0.203933,0.203933,192
19,DXY_ret_5d_lag120,0.032644,0.001161,1.349066e-06,0.030826,0.035434,3,30,0.031482,DXY_ret_5d,120,120,-0.110706,0.110706,132

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1354, 23)
X_train shape: (1354, 20)
train target 분포:
target_10d_up_0pct
1    766
0    588
Name: count, dtype: int64
target_10d_up_0pct
1    0.565731
0    0.434269
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_10d_up_0pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.997235     1
1  2026-02-24     419.160004                 0.0    0.992100     1
2  2026-02-25     426.160004                 0.0    0.981337     1
3  2026-02-26     412.010010                 0.0    0.082503     0
4  2026-02-27     406.369995                 0.0    0.440510     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.003458     0
60 2026-05-19     543.960022                 NaN    0.030182     0
61 2026-05-20     564.659973                 NaN    0.232637     0
62 2026-05-21     567.880005                 NaN    0.179200     0
63 2026-05-22     576.320007                 NaN    0.888924     1

[64 rows x 5 columns]

예측값 분포:
pred
0    48
1    16
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 54
예측 1 개수: 14
예측 1 중 실제 1 개수: 8
예측 1 기준 정확도 precision: 0.5714285714285714

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,10,0.005,1,20,20,hist_gradient_boosting,"{'max_iter': 300, 'learning_rate': 0.05, 'max_...",54,14,...,0.351852,0.571429,0.216216,0.313725,0.375199,1.361598,11,6,29,8

[I 2026-05-23 21:08:36,086] Trial 107 finished with value: 0.5714285714285714 and parameters: {'n_days': 10, 'threshold': 0.005, 'top_n': 20, 'pred_threshold': 0.75, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.05, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 109/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'logistic', 'model_params': {'C': 0.01, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 108}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.478013     0
1  2026-02-24     419.160004                 0.0    0.472442     0
2  2026-02-25     426.160004                 0.0    0.501560     0
3  2026-02-26     412.010010                 0.0    0.546459     0
4  2026-02-27     406.369995                 0.0    0.552615     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.455237     0
60 2026-05-19     543.960022                 NaN    0.505466     0
61 2026-05-20     564.659973                 NaN    0.563178     0
62 2026-05-21     567.880005                 NaN    0.576022     0
63 2026-05-22     576.320007                 NaN    0.556520     0

[64 rows x 5 columns]

예측값 분포:
pred
0    59
1     5
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 3
예측 1 중 실제 1 개수: 3
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,logistic,"{'C': 0.01, 'class_weight': 'balanced', 'max_i...",44,3,...,0.295455,1.0,0.088235,0.162162,0.320588,0.744518,10,0,31,3

[I 2026-05-23 21:08:53,087] Trial 108 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'logistic', 'logistic_C': 0.01}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 110/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 10, 'pred_threshold': 0.55, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 109}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 10
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,0.000029,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,0.000011,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,0.000019,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,0.000002,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,0.000008,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,0.000010,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,0.000010,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,0.000007,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,0.000003,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,0.000002,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212

============================================================
6. valid_df 생성
============================================================
top feature 수: 10
lag 생성 후 valid_df shape: (1607, 22)
원본 base_feature 제거 후 valid_df shape: (1607, 12)
최종 컬럼 수: 12
target 생성 후 valid_df shape: (1607, 14)
최종 valid_df shape: (64, 14)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 10
train_df shape: (1383, 13)
X_train shape: (1383, 10)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 14)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.499373     0
1  2026-02-24     419.160004                 0.0    0.512391     0
2  2026-02-25     426.160004                 0.0    0.552511     1
3  2026-02-26     412.010010                 0.0    0.612322     1
4  2026-02-27     406.369995                 0.0    0.537445     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.866509     1
60 2026-05-19     543.960022                 NaN    0.640262     1
61 2026-05-20     564.659973                 NaN    0.379498     0
62 2026-05-21     567.880005                 NaN    0.723250     1
63 2026-05-22     576.320007                 NaN    0.783241     1

[64 rows x 5 columns]

예측값 분포:
pred
1    46
0    18
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 28
예측 1 중 실제 1 개수: 23
예측 1 기준 정확도 precision: 0.8214285714285714

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,10,10,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.03, '...",44,28,...,0.636364,0.821429,0.676471,0.741935,0.641176,0.598648,5,5,11,23

[I 2026-05-23 21:09:10,827] Trial 109 finished with value: 0.8214285714285714 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 10, 'pred_threshold': 0.55, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 111/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.1, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 110}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.231809     0
1  2026-02-24     419.160004                 0.0    0.944922     1
2  2026-02-25     426.160004                 0.0    0.428717     0
3  2026-02-26     412.010010                 0.0    0.003932     0
4  2026-02-27     406.369995                 0.0    0.037355     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.990750     1
60 2026-05-19     543.960022                 NaN    0.998436     1
61 2026-05-20     564.659973                 NaN    0.969777     1
62 2026-05-21     567.880005                 NaN    0.833720     1
63 2026-05-22     576.320007                 NaN    0.499551     0

[64 rows x 5 columns]

예측값 분포:
pred
1    35
0    29
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 16
예측 1 중 실제 1 개수: 10
예측 1 기준 정확도 precision: 0.625

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,hist_gradient_boosting,"{'max_iter': 300, 'learning_rate': 0.1, 'max_l...",44,16,...,0.318182,0.625,0.294118,0.4,0.361765,1.843154,4,6,24,10

[I 2026-05-23 21:09:29,104] Trial 110 finished with value: 0.625 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.1, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:09:29,143] Trial 111 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'logistic', 'logistic_C': 1.0}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:09:29,184] Trial 112 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'logistic', 'logistic_C': 1.0}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 112/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'logistic', 'model_params': {'C': 1.0, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 111}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204639_optuna_holdout_trial_0007
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 113/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'logistic', 'model_params': {'C': 1.0, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 112}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204639_optuna_holdout_trial_0007
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 114/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'logistic', 'model_params': {'C': 1.0, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 113}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.476654     0
1  2026-02-24     419.160004                 0.0    0.471490     0
2  2026-02-25     426.160004                 0.0    0.503152     0
3  2026-02-26     412.010010                 0.0    0.561370     0
4  2026-02-27     406.369995                 0.0    0.573927     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.452401     0
60 2026-05-19     543.960022                 NaN    0.504150     0
61 2026-05-20     564.659973                 NaN    0.565276     0
62 2026-05-21     567.880005                 NaN    0.585366     0
63 2026-05-22     576.320007                 NaN    0.566451     0

[64 rows x 5 columns]

예측값 분포:
pred
0    53
1    11
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 4
예측 1 중 실제 1 개수: 4
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,logistic,"{'C': 1.0, 'class_weight': 'balanced', 'max_it...",44,4,...,0.318182,1.0,0.117647,0.210526,0.3,0.770975,10,0,30,4

[I 2026-05-23 21:09:46,413] Trial 113 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'logistic', 'logistic_C': 1.0}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:09:46,441] Trial 114 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'logistic', 'logistic_C': 1.0}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 115/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'logistic', 'model_params': {'C': 1.0, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 114}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_210421_optuna_holdout_trial_0085
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 116/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'logistic', 'model_params': {'C': 1.0, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 115}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 20
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.374846     0
1  2026-02-24     419.160004                 0.0    0.411498     0
2  2026-02-25     426.160004                 0.0    0.463852     0
3  2026-02-26     412.010010                 0.0    0.500278     0
4  2026-02-27     406.369995                 0.0    0.574794     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.543106     0
60 2026-05-19     543.960022                 NaN    0.613901     0
61 2026-05-20     564.659973                 NaN    0.633458     0
62 2026-05-21     567.880005                 NaN    0.681169     1
63 2026-05-22     576.320007                 NaN    0.632552     0

[64 rows x 5 columns]

예측값 분포:
pred
0    46
1    18
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 12
예측 1 중 실제 1 개수: 12
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,20,20,logistic,"{'C': 1.0, 'class_weight': 'balanced', 'max_it...",44,12,...,0.5,1.0,0.352941,0.521739,0.755882,0.57965,10,0,22,12

[I 2026-05-23 21:10:03,050] Trial 115 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'logistic', 'logistic_C': 1.0}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 117/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.01, 'max_depth': 5}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 116}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.580681     0
1  2026-02-24     419.160004                 0.0    0.646262     1
2  2026-02-25     426.160004                 0.0    0.629085     1
3  2026-02-26     412.010010                 0.0    0.437223     0
4  2026-02-27     406.369995                 0.0    0.468838     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.509053     0
60 2026-05-19     543.960022                 NaN    0.678743     1
61 2026-05-20     564.659973                 NaN    0.364124     0
62 2026-05-21     567.880005                 NaN    0.253155     0
63 2026-05-22     576.320007                 NaN    0.305266     0

[64 rows x 5 columns]

예측값 분포:
pred
0    39
1    25
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 12
예측 1 중 실제 1 개수: 9
예측 1 기준 정확도 precision: 0.75

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.01, '...",44,12,...,0.363636,0.75,0.264706,0.391304,0.488235,0.685286,7,3,25,9

[I 2026-05-23 21:10:22,285] Trial 116 finished with value: 0.75 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.01, 'gb_max_depth': 5}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 118/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 10, 'threshold': 0.015, 'top_n': 50, 'pred_threshold': 0.65, 'model_name': 'random_forest', 'model_params': {'n_estimators': 800, 'max_depth': 10, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 117}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_10d_up_1pct
target_df shape: (1533, 31)
target 분포:
target_10d_up_1pct
1    789
0    744
Name: count, dtype: int64
lagged_df shape: (1393, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1435

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.143

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1436
TOP feature count: 27
['USDKRW_ret_20d_lag3', 'TNX_level_lag120', 'DXY_ret_20d_lag120', 'OIL_ret_20d_lag40', 'SMH_vol_20d_lag40', 'SMH_ma60_ratio_lag40', 'SMH_ma20_ratio_lag40', 'TNX_diff_20d_lag5', 'TSM_ret_20d_lag40', 'NVDA_ret_20d_lag120', 'VIX_chg_20d_lag120', 'VIX_level_lag40', 'SPY_ret_20d_lag120', 'GOLD_ret_20d_lag120', 'VIX_chg_5d_lag60', 'USDKRW_ret_5d_lag120', 'TSM_ret_5d_lag40', 'SMH_volume_ratio_20d_lag5', 'NVDA_ret_5d_lag60', 'SOXX_ret_5d_lag40', 'GOLD_ret_5d_lag40', 'TNX_diff_5d_lag60', 'SPY_ret_5d_lag60', 'OIL_ret_5d_lag120', 'DXY_ret_5d_lag10', 'SMH_ma5_ratio_lag60', 'SMH_ret_1d_lag120']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,USDKRW_ret_20d_lag3,0.120179,0.003203,1.025687e-05,0.114064,0.127153,3,30,0.116976,USDKRW_ret_20d,3,3,-0.357632,0.357632,249
1,TNX_level_lag120,0.098635,0.002875,8.264090e-06,0.089594,0.103376,3,30,0.095760,TNX_level,120,120,-0.209417,0.209417,132
2,DXY_ret_20d_lag120,0.089309,0.002229,4.967756e-06,0.083745,0.092958,3,30,0.087080,DXY_ret_20d,120,120,-0.244463,0.244463,132
3,OIL_ret_20d_lag40,0.069472,0.001444,2.086402e-06,0.066390,0.072341,3,30,0.068028,OIL_ret_20d,40,40,-0.261638,0.261638,212
4,SMH_vol_20d_lag40,0.068675,0.001826,3.334384e-06,0.065220,0.072490,3,30,0.066849,SMH_vol_20d,40,40,0.258244,0.258244,212
5,SMH_ma60_ratio_lag40,0.066721,0.001533,2.351514e-06,0.063232,0.069945,3,30,0.065187,SMH_ma60_ratio,40,40,-0.236194,0.236194,212
6,SMH_ma20_ratio_lag40,0.057550,0.001558,2.426530e-06,0.053863,0.060871,3,30,0.055992,SMH_ma20_ratio,40,40,-0.241800,0.241800,212
7,TNX_diff_20d_lag5,0.055415,0.001547,2.392637e-06,0.052586,0.058614,3,30,0.053869,TNX_diff_20d,5,5,0.323838,0.323838,247
8,TSM_ret_20d_lag40,0.054409,0.001754,3.076881e-06,0.050440,0.058271,3,30,0.052655,TSM_ret_20d,40,40,-0.276363,0.276363,212
9,NVDA_ret_20d_lag120,0.054923,0.002644,6.989798e-06,0.049354,0.059768,3,30,0.052279,NVDA_ret_20d,120,120,-0.174684,0.174684,132
10,VIX_chg_20d_lag120,0.052718,0.001795,3.222371e-06,0.050121,0.057159,3,30,0.050923,VIX_chg_20d,120,120,0.179828,0.179828,132
11,VIX_level_lag40,0.050085,0.001329,1.765036e-06,0.047345,0.052508,3,30,0.048756,VIX_level,40,40,0.190705,0.190705,212
12,SPY_ret_20d_lag120,0.048621,0.000906,8.215688e-07,0.046890,0.050990,3,30,0.047715,SPY_ret_20d,120,120,-0.230254,0.230254,132
13,GOLD_ret_20d_lag120,0.045884,0.002215,4.904031e-06,0.041327,0.048565,3,30,0.043669,GOLD_ret_20d,120,120,-0.137286,0.137286,132
14,VIX_chg_5d_lag60,0.044085,0.001796,3.227083e-06,0.041035,0.047028,3,30,0.042289,VIX_chg_5d,60,60,0.141418,0.141418,192
15,USDKRW_ret_5d_lag120,0.044194,0.002562,6.566231e-06,0.040713,0.049551,3,30,0.041632,USDKRW_ret_5d,120,120,0.211443,0.211443,132
16,TSM_ret_5d_lag40,0.039475,0.001123,1.262164e-06,0.037073,0.042047,3,30,0.038352,TSM_ret_5d,40,40,-0.314300,0.314300,212
17,SMH_volume_ratio_20d_lag5,0.036161,0.001115,1.243013e-06,0.033575,0.038225,3,30,0.035046,SMH_volume_ratio_20d,5,5,0.179281,0.179281,247
18,NVDA_ret_5d_lag60,0.036037,0.001161,1.349002e-06,0.034426,0.039001,3,30,0.034876,NVDA_ret_5d,60,60,-0.223746,0.223746,192
19,SOXX_ret_5d_lag40,0.034374,0.001140,1.299101e-06,0.032316,0.037244,3,30,0.033234,SOXX_ret_5d,40,40,-0.229707,0.229707,212
20,GOLD_ret_5d_lag40,0.033847,0.001390,1.931199e-06,0.031405,0.035998,3,30,0.032457,GOLD_ret_5d,40,40,-0.175929,0.175929,212
21,TNX_diff_5d_lag60,0.031193,0.000840,7.057839e-07,0.029443,0.032800,3,30,0.030353,TNX_diff_5d,60,60,-0.165860,0.165860,192
22,SPY_ret_5d_lag60,0.029524,0.001186,1.406714e-06,0.027299,0.032238,3,30,0.028338,SPY_ret_5d,60,60,-0.208519,0.208519,192
23,OIL_ret_5d_lag120,0.027740,0.000713,5.077654e-07,0.026383,0.029387,3,30,0.027028,OIL_ret_5d,120,120,-0.199841,0.199841,132
24,DXY_ret_5d_lag10,0.027050,0.000497,2.473056e-07,0.026131,0.028214,3,30,0.026552,DXY_ret_5d,10,10,-0.092208,0.092208,242
25,SMH_ma5_ratio_lag60,0.024530,0.001439,2.070036e-06,0.022161,0.027047,3,30,0.023091,SMH_ma5_ratio,60,60,-0.222118,0.222118,192
26,SMH_ret_1d_lag120,0.019806,0.000326,1.062366e-07,0.019077,0.020450,3,30,0.019480,SMH_ret_1d,120,120,0.164121,0.164121,132

============================================================
6. valid_df 생성
============================================================
top feature 수: 27
lag 생성 후 valid_df shape: (1607, 56)
원본 base_feature 제거 후 valid_df shape: (1607, 29)
최종 컬럼 수: 29
target 생성 후 valid_df shape: (1607, 31)
최종 valid_df shape: (64, 31)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 27
train_df shape: (1393, 30)
X_train shape: (1393, 27)
train target 분포:
target_10d_up_1pct
1    706
0    687
Name: count, dtype: int64
target_10d_up_1pct
1    0.50682
0    0.49318
Name: proportion, dtype: float64
valid_df shape: (64, 31)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: random_forest
valid_df 예측 완료

         Date  SMH_adj_close  target_10d_up_1pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.793872     1
1  2026-02-24     419.160004                 0.0    0.789341     1
2  2026-02-25     426.160004                 0.0    0.629200     0
3  2026-02-26     412.010010                 0.0    0.399517     0
4  2026-02-27     406.369995                 0.0    0.460599     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.366745     0
60 2026-05-19     543.960022                 NaN    0.527835     0
61 2026-05-20     564.659973                 NaN    0.508633     0
62 2026-05-21     567.880005                 NaN    0.513954     0
63 2026-05-22     576.320007                 NaN    0.357603     0

[64 rows x 5 columns]

예측값 분포:
pred
0    62
1     2
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 54
예측 1 개수: 2
예측 1 중 실제 1 개수: 0
예측 1 기준 정확도 precision: 0.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,10,0.015,1,50,27,random_forest,"{'n_estimators': 800, 'max_depth': 10, 'min_sa...",54,2,...,0.314815,0.0,0.0,0.0,0.338346,0.797918,17,2,35,0

[I 2026-05-23 21:10:39,652] Trial 117 finished with value: 0.0 and parameters: {'n_days': 10, 'threshold': 0.015, 'top_n': 50, 'pred_threshold': 0.65, 'model_name': 'random_forest', 'rf_n_estimators': 800, 'rf_max_depth': 10, 'rf_min_samples_leaf': 1, 'rf_max_features': 0.5}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 119/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 100, 'learning_rate': 0.01, 'max_leaf_nodes': 15}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 118}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 20
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.536809     0
1  2026-02-24     419.160004                 0.0    0.552331     0
2  2026-02-25     426.160004                 0.0    0.585929     0
3  2026-02-26     412.010010                 0.0    0.575571     0
4  2026-02-27     406.369995                 0.0    0.582251     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.579604     0
60 2026-05-19     543.960022                 NaN    0.552221     0
61 2026-05-20     564.659973                 NaN    0.376441     0
62 2026-05-21     567.880005                 NaN    0.343455     0
63 2026-05-22     576.320007                 NaN    0.348765     0

[64 rows x 5 columns]

예측값 분포:
pred
0    52
1    12
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 2
예측 1 중 실제 1 개수: 2
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,20,20,hist_gradient_boosting,"{'max_iter': 100, 'learning_rate': 0.01, 'max_...",44,2,...,0.272727,1.0,0.058824,0.111111,0.317647,0.711398,10,0,32,2

[I 2026-05-23 21:10:57,316] Trial 118 finished with value: 0.6666666666666666 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 100, 'hgb_learning_rate': 0.01, 'hgb_max_leaf_nodes': 15}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 120/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 3, 'threshold': 0.01, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 100, 'learning_rate': 0.1, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 119}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_3d_up_1pct
target_df shape: (1540, 31)
target 분포:
target_3d_up_1pct
0    858
1    682
Name: count, dtype: int64
lagged_df shape: (1361, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1775

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.178

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1777
TOP feature count: 20
['DXY_ret_20d_lag120', 'SOXX_ret_5d_lag10', 'TNX_diff_5d_lag20', 'NVDA_ret_5d_lag1', 'USDKRW_ret_20d_lag1', 'SMH_vol_20d_lag60', 'SMH_ma5_ratio_lag10', 'NVDA_ret_20d_lag120', 'VIX_chg_20d_lag120', 'SPY_ret_20d_lag120', 'TSM_ret_5d_lag5', 'OIL_ret_20d_lag60', 'GOLD_ret_20d_lag1', 'OIL_ret_5d_lag20', 'SMH_ma60_ratio_lag120', 'TNX_level_lag1', 'TNX_diff_20d_lag5', 'TSM_ret_20d_lag120', 'VIX_chg_5d_lag40', 'VIX_level_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,DXY_ret_20d_lag120,0.099679,0.002438,5.943633e-06,0.094715,0.104590,3,30,0.097242,DXY_ret_20d,120,120,-0.202539,0.202539,131
1,SOXX_ret_5d_lag10,0.077610,0.005324,2.834364e-05,0.069281,0.086203,3,30,0.072286,SOXX_ret_5d,10,10,-0.138531,0.138531,241
2,TNX_diff_5d_lag20,0.057548,0.002587,6.691529e-06,0.052693,0.061019,3,30,0.054961,TNX_diff_5d,20,20,0.185910,0.185910,231
3,NVDA_ret_5d_lag1,0.056908,0.002596,6.739910e-06,0.052460,0.061254,3,30,0.054312,NVDA_ret_5d,1,1,-0.153357,0.153357,250
4,USDKRW_ret_20d_lag1,0.057024,0.002773,7.687779e-06,0.052551,0.060200,3,30,0.054251,USDKRW_ret_20d,1,1,-0.156555,0.156555,250
5,SMH_vol_20d_lag60,0.055205,0.001767,3.122677e-06,0.051758,0.057493,3,30,0.053438,SMH_vol_20d,60,60,-0.119649,0.119649,191
6,SMH_ma5_ratio_lag10,0.054981,0.001559,2.429523e-06,0.052625,0.059181,3,30,0.053423,SMH_ma5_ratio,10,10,-0.198808,0.198808,241
7,NVDA_ret_20d_lag120,0.054383,0.001651,2.726769e-06,0.051834,0.057944,3,30,0.052732,NVDA_ret_20d,120,120,-0.151425,0.151425,131
8,VIX_chg_20d_lag120,0.049870,0.000823,6.780593e-07,0.047655,0.051175,3,30,0.049046,VIX_chg_20d,120,120,0.129767,0.129767,131
9,SPY_ret_20d_lag120,0.050411,0.001498,2.245267e-06,0.047224,0.053040,3,30,0.048913,SPY_ret_20d,120,120,-0.188158,0.188158,131
10,TSM_ret_5d_lag5,0.049761,0.001009,1.017911e-06,0.047816,0.051717,3,30,0.048752,TSM_ret_5d,5,5,0.232924,0.232924,246
11,OIL_ret_20d_lag60,0.051218,0.003152,9.934761e-06,0.046043,0.057292,3,30,0.048066,OIL_ret_20d,60,60,0.207999,0.207999,191
12,GOLD_ret_20d_lag1,0.049863,0.002615,6.840338e-06,0.046775,0.054317,3,30,0.047248,GOLD_ret_20d,1,1,0.109612,0.109612,250
13,OIL_ret_5d_lag20,0.048873,0.002054,4.220476e-06,0.045117,0.052153,3,30,0.046819,OIL_ret_5d,20,20,-0.145432,0.145432,231
14,SMH_ma60_ratio_lag120,0.047406,0.001284,1.648376e-06,0.044350,0.049324,3,30,0.046122,SMH_ma60_ratio,120,120,-0.088680,0.088680,131
15,TNX_level_lag1,0.046193,0.001356,1.837639e-06,0.043787,0.048247,3,30,0.044837,TNX_level,1,1,-0.173322,0.173322,250
16,TNX_diff_20d_lag5,0.046170,0.001424,2.026992e-06,0.043856,0.048976,3,30,0.044746,TNX_diff_20d,5,5,0.153462,0.153462,246
17,TSM_ret_20d_lag120,0.045639,0.000973,9.472751e-07,0.043245,0.047114,3,30,0.044666,TSM_ret_20d,120,120,-0.149607,0.149607,131
18,VIX_chg_5d_lag40,0.045701,0.001570,2.464805e-06,0.043163,0.048905,3,30,0.044131,VIX_chg_5d,40,40,0.164356,0.164356,211
19,VIX_level_lag40,0.044222,0.001178,1.387722e-06,0.041839,0.046441,3,30,0.043044,VIX_level,40,40,0.108848,0.108848,211

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1361, 23)
X_train shape: (1361, 20)
train target 분포:
target_3d_up_1pct
0    758
1    603
Name: count, dtype: int64
target_3d_up_1pct
0    0.556943
1    0.443057
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_3d_up_1pct  pred_proba  pred
0  2026-02-23     412.880005                0.0    0.477217     0
1  2026-02-24     419.160004                0.0    0.504877     0
2  2026-02-25     426.160004                0.0    0.356887     0
3  2026-02-26     412.010010                0.0    0.460882     0
4  2026-02-27     406.369995                0.0    0.416578     0
..        ...            ...                ...         ...   ...
59 2026-05-18     546.159973                1.0    0.498048     0
60 2026-05-19     543.960022                1.0    0.483865     0
61 2026-05-20     564.659973                NaN    0.374111     0
62 2026-05-21     567.880005                NaN    0.417087     0
63 2026-05-22     576.320007                NaN    0.390866     0

[64 rows x 5 columns]

예측값 분포:
pred
0    64
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 61
예측 1 개수: 0
예측 1 중 실제 1 개수: 0
예측 1 기준 정확도 precision: nan

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,3,0.01,1,20,20,gradient_boosting,"{'n_estimators': 100, 'learning_rate': 0.1, 'm...",61,0,...,0.42623,0.0,0.0,0.0,0.328571,0.821431,26,0,35,0

[I 2026-05-23 21:11:15,257] Trial 119 finished with value: 0.0 and parameters: {'n_days': 3, 'threshold': 0.01, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'gb_n_estimators': 100, 'gb_learning_rate': 0.1, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 121/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.75, 'model_name': 'logistic', 'model_params': {'C': 0.1, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 120}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.475823     0
1  2026-02-24     419.160004                 0.0    0.470516     0
2  2026-02-25     426.160004                 0.0    0.502625     0
3  2026-02-26     412.010010                 0.0    0.559081     0
4  2026-02-27     406.369995                 0.0    0.570878     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.451135     0
60 2026-05-19     543.960022                 NaN    0.504116     0
61 2026-05-20     564.659973                 NaN    0.566198     0
62 2026-05-21     567.880005                 NaN    0.585040     0
63 2026-05-22     576.320007                 NaN    0.565403     0

[64 rows x 5 columns]

예측값 분포:
pred
0    60
1     4
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 2
예측 1 중 실제 1 개수: 2
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,logistic,"{'C': 0.1, 'class_weight': 'balanced', 'max_it...",44,2,...,0.272727,1.0,0.058824,0.111111,0.3,0.767374,10,0,32,2

[I 2026-05-23 21:11:32,347] Trial 120 finished with value: 0.6666666666666666 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.75, 'model_name': 'logistic', 'logistic_C': 0.1}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:11:32,380] Trial 121 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:11:32,413] Trial 122 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:11:32,443] Trial 123 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 122/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 121}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204741_optuna_holdout_trial_0011
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 123/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 122}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204741_optuna_holdout_trial_0011
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 124/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 123}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204741_optuna_holdout_trial_0011
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 125/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 124}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 20
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.441412     0
1  2026-02-24     419.160004                 0.0    0.515109     0
2  2026-02-25     426.160004                 0.0    0.446093     0
3  2026-02-26     412.010010                 0.0    0.520890     0
4  2026-02-27     406.369995                 0.0    0.605391     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.499986     0
60 2026-05-19     543.960022                 NaN    0.601600     0
61 2026-05-20     564.659973                 NaN    0.427989     0
62 2026-05-21     567.880005                 NaN    0.600528     0
63 2026-05-22     576.320007                 NaN    0.621633     0

[64 rows x 5 columns]

예측값 분포:
pred
0    53
1    11
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 3
예측 1 중 실제 1 개수: 3
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.03, '...",44,3,...,0.295455,1.0,0.088235,0.162162,0.397059,0.761671,10,0,31,3

[I 2026-05-23 21:11:50,959] Trial 124 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 126/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 4}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 125}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.504989     0
1  2026-02-24     419.160004                 0.0    0.739353     1
2  2026-02-25     426.160004                 0.0    0.618586     0
3  2026-02-26     412.010010                 0.0    0.431028     0
4  2026-02-27     406.369995                 0.0    0.443173     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.610421     0
60 2026-05-19     543.960022                 NaN    0.790912     1
61 2026-05-20     564.659973                 NaN    0.505732     0
62 2026-05-21     567.880005                 NaN    0.520876     0
63 2026-05-22     576.320007                 NaN    0.619263     0

[64 rows x 5 columns]

예측값 분포:
pred
0    42
1    22
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 10
예측 1 중 실제 1 개수: 8
예측 1 기준 정확도 precision: 0.8

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.03, '...",44,10,...,0.363636,0.8,0.235294,0.363636,0.444118,0.760315,8,2,26,8

[I 2026-05-23 21:12:09,141] Trial 125 finished with value: 0.8 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 4}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 127/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 500, 'learning_rate': 0.01, 'max_leaf_nodes': 31}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 126}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.498724     0
1  2026-02-24     419.160004                 0.0    0.690052     1
2  2026-02-25     426.160004                 0.0    0.663651     1
3  2026-02-26     412.010010                 0.0    0.460138     0
4  2026-02-27     406.369995                 0.0    0.389949     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.763975     1
60 2026-05-19     543.960022                 NaN    0.721783     1
61 2026-05-20     564.659973                 NaN    0.546346     0
62 2026-05-21     567.880005                 NaN    0.413878     0
63 2026-05-22     576.320007                 NaN    0.339661     0

[64 rows x 5 columns]

예측값 분포:
pred
0    41
1    23
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 8
예측 1 중 실제 1 개수: 5
예측 1 기준 정확도 precision: 0.625

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,hist_gradient_boosting,"{'max_iter': 500, 'learning_rate': 0.01, 'max_...",44,8,...,0.272727,0.625,0.147059,0.238095,0.270588,0.909668,7,3,29,5

[I 2026-05-23 21:12:27,884] Trial 126 finished with value: 0.625 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 500, 'hgb_learning_rate': 0.01, 'hgb_max_leaf_nodes': 31}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 128/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 5, 'threshold': 0.03, 'top_n': 30, 'pred_threshold': 0.6000000000000001, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 500, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 127}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_5d_up_3pct
target_df shape: (1538, 31)
target 분포:
target_5d_up_3pct
0    1051
1     487
Name: count, dtype: int64
lagged_df shape: (1398, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1462

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1467

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1461
TOP feature count: 27
['SMH_ma60_ratio_lag1', 'SMH_vol_20d_lag60', 'TNX_level_lag1', 'GOLD_ret_5d_lag120', 'VIX_level_lag1', 'VIX_chg_20d_lag40', 'OIL_ret_20d_lag60', 'TNX_diff_5d_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag40', 'DXY_ret_20d_lag5', 'USDKRW_ret_20d_lag40', 'USDKRW_ret_5d_lag1', 'GOLD_ret_20d_lag1', 'DXY_ret_5d_lag120', 'TNX_diff_20d_lag5', 'SMH_volume_ratio_20d_lag20', 'SMH_ma20_ratio_lag40', 'OIL_ret_5d_lag60', 'NVDA_ret_20d_lag120', 'TSM_ret_5d_lag40', 'SMH_ret_1d_lag10', 'NVDA_ret_5d_lag40', 'VIX_chg_5d_lag40', 'SMH_ma5_ratio_lag40', 'SPY_ret_5d_lag40', 'SOXX_ret_5d_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_ma60_ratio_lag1,0.078441,0.001863,3.470473e-06,0.074815,0.082776,3,30,0.076578,SMH_ma60_ratio,1,1,-0.172629,0.172629,251
1,SMH_vol_20d_lag60,0.069105,0.001919,3.684021e-06,0.065530,0.073300,3,30,0.067185,SMH_vol_20d,60,60,-0.189027,0.189027,192
2,TNX_level_lag1,0.069129,0.002486,6.181890e-06,0.063543,0.073483,3,30,0.066643,TNX_level,1,1,-0.191147,0.191147,251
3,GOLD_ret_5d_lag120,0.060355,0.002163,4.676538e-06,0.055174,0.064143,3,30,0.058193,GOLD_ret_5d,120,120,-0.218877,0.218877,132
4,VIX_level_lag1,0.059673,0.002784,7.752705e-06,0.055123,0.064462,3,30,0.056889,VIX_level,1,1,0.153605,0.153605,251
5,VIX_chg_20d_lag40,0.056407,0.001996,3.983510e-06,0.052414,0.060620,3,30,0.054411,VIX_chg_20d,40,40,0.225283,0.225283,212
6,OIL_ret_20d_lag60,0.053212,0.002001,4.002755e-06,0.049749,0.057240,3,30,0.051212,OIL_ret_20d,60,60,0.237427,0.237427,192
7,TNX_diff_5d_lag20,0.053372,0.002314,5.355884e-06,0.048577,0.056207,3,30,0.051058,TNX_diff_5d,20,20,0.185217,0.185217,232
8,SPY_ret_20d_lag120,0.048811,0.001230,1.513431e-06,0.045170,0.051545,3,30,0.047581,SPY_ret_20d,120,120,-0.195151,0.195151,132
9,TSM_ret_20d_lag40,0.049182,0.002547,6.484842e-06,0.045876,0.055137,3,30,0.046635,TSM_ret_20d,40,40,-0.186887,0.186887,212
10,DXY_ret_20d_lag5,0.044759,0.001859,3.455597e-06,0.040812,0.048252,3,30,0.042900,DXY_ret_20d,5,5,-0.123856,0.123856,247
11,USDKRW_ret_20d_lag40,0.044490,0.001832,3.357242e-06,0.041625,0.048470,3,30,0.042657,USDKRW_ret_20d,40,40,0.204293,0.204293,212
12,USDKRW_ret_5d_lag1,0.042260,0.001278,1.633171e-06,0.039336,0.045023,3,30,0.040982,USDKRW_ret_5d,1,1,-0.135928,0.135928,251
13,GOLD_ret_20d_lag1,0.039152,0.002092,4.374883e-06,0.035630,0.042243,3,30,0.037061,GOLD_ret_20d,1,1,0.185988,0.185988,251
14,DXY_ret_5d_lag120,0.037692,0.000937,8.787204e-07,0.035442,0.040194,3,30,0.036755,DXY_ret_5d,120,120,0.201244,0.201244,132
15,TNX_diff_20d_lag5,0.038099,0.001366,1.866021e-06,0.035694,0.040829,3,30,0.036733,TNX_diff_20d,5,5,0.197432,0.197432,247
16,SMH_volume_ratio_20d_lag20,0.037433,0.000858,7.356760e-07,0.035823,0.038871,3,30,0.036576,SMH_volume_ratio_20d,20,20,-0.106779,0.106779,232
17,SMH_ma20_ratio_lag40,0.036965,0.000649,4.216770e-07,0.035800,0.038710,3,30,0.036315,SMH_ma20_ratio,40,40,-0.224204,0.224204,212
18,OIL_ret_5d_lag60,0.035339,0.000720,5.182253e-07,0.033657,0.036754,3,30,0.034619,OIL_ret_5d,60,60,0.222858,0.222858,192
19,NVDA_ret_20d_lag120,0.035294,0.000913,8.331741e-07,0.033754,0.037211,3,30,0.034381,NVDA_ret_20d,120,120,-0.135504,0.135504,132
20,TSM_ret_5d_lag40,0.034814,0.001188,1.410571e-06,0.032626,0.037546,3,30,0.033626,TSM_ret_5d,40,40,-0.269283,0.269283,212
21,SMH_ret_1d_lag10,0.034392,0.000863,7.439626e-07,0.033020,0.036370,3,30,0.033530,SMH_ret_1d,10,10,-0.143609,0.143609,242
22,NVDA_ret_5d_lag40,0.031941,0.001019,1.038905e-06,0.029972,0.033729,3,30,0.030922,NVDA_ret_5d,40,40,-0.152996,0.152996,212
23,VIX_chg_5d_lag40,0.032318,0.001417,2.006900e-06,0.029677,0.034358,3,30,0.030901,VIX_chg_5d,40,40,0.243917,0.243917,212
24,SMH_ma5_ratio_lag40,0.030392,0.000914,8.346690e-07,0.028814,0.031679,3,30,0.029479,SMH_ma5_ratio,40,40,-0.185997,0.185997,212
25,SPY_ret_5d_lag40,0.030118,0.000958,9.179304e-07,0.028305,0.032695,3,30,0.029160,SPY_ret_5d,40,40,-0.334969,0.334969,212
26,SOXX_ret_5d_lag40,0.026600,0.001038,1.078219e-06,0.024692,0.028338,3,30,0.025562,SOXX_ret_5d,40,40,-0.234680,0.234680,212

============================================================
6. valid_df 생성
============================================================
top feature 수: 27
lag 생성 후 valid_df shape: (1607, 56)
원본 base_feature 제거 후 valid_df shape: (1607, 29)
최종 컬럼 수: 29
target 생성 후 valid_df shape: (1607, 31)
최종 valid_df shape: (64, 31)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 27
train_df shape: (1398, 30)
X_train shape: (1398, 27)
train target 분포:
target_5d_up_3pct
0    958
1    440
Name: count, dtype: int64
target_5d_up_3pct
0    0.685265
1    0.314735
Name: proportion, dtype: float64
valid_df shape: (64, 31)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_5d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                0.0    0.316006     0
1  2026-02-24     419.160004                0.0    0.269015     0
2  2026-02-25     426.160004                0.0    0.271415     0
3  2026-02-26     412.010010                0.0    0.245155     0
4  2026-02-27     406.369995                0.0    0.204696     0
..        ...            ...                ...         ...   ...
59 2026-05-18     546.159973                NaN    0.198144     0
60 2026-05-19     543.960022                NaN    0.170031     0
61 2026-05-20     564.659973                NaN    0.166307     0
62 2026-05-21     567.880005                NaN    0.141677     0
63 2026-05-22     576.320007                NaN    0.416110     0

[64 rows x 5 columns]

예측값 분포:
pred
0    63
1     1
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 59
예측 1 개수: 1
예측 1 중 실제 1 개수: 1
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,5,0.03,1,30,27,gradient_boosting,"{'n_estimators': 500, 'learning_rate': 0.03, '...",59,1,...,0.542373,1.0,0.035714,0.068966,0.493088,0.876694,31,0,27,1

[I 2026-05-23 21:12:47,852] Trial 127 finished with value: 0.3333333333333333 and parameters: {'n_days': 5, 'threshold': 0.03, 'top_n': 30, 'pred_threshold': 0.6000000000000001, 'model_name': 'gradient_boosting', 'gb_n_estimators': 500, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 129/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'logistic', 'model_params': {'C': 10.0, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 128}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.476770     0
1  2026-02-24     419.160004                 0.0    0.471605     0
2  2026-02-25     426.160004                 0.0    0.503201     0
3  2026-02-26     412.010010                 0.0    0.561606     0
4  2026-02-27     406.369995                 0.0    0.574237     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.452571     0
60 2026-05-19     543.960022                 NaN    0.504163     0
61 2026-05-20     564.659973                 NaN    0.565166     0
62 2026-05-21     567.880005                 NaN    0.585396     0
63 2026-05-22     576.320007                 NaN    0.566557     0

[64 rows x 5 columns]

예측값 분포:
pred
0    53
1    11
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 4
예측 1 중 실제 1 개수: 4
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,logistic,"{'C': 10.0, 'class_weight': 'balanced', 'max_i...",44,4,...,0.318182,1.0,0.117647,0.210526,0.3,0.771386,10,0,30,4

[I 2026-05-23 21:13:04,311] Trial 128 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'logistic', 'logistic_C': 10.0}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 130/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 2}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 129}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 20
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.493389     0
1  2026-02-24     419.160004                 0.0    0.488171     0
2  2026-02-25     426.160004                 0.0    0.446612     0
3  2026-02-26     412.010010                 0.0    0.604194     0
4  2026-02-27     406.369995                 0.0    0.569337     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.616759     0
60 2026-05-19     543.960022                 NaN    0.604432     0
61 2026-05-20     564.659973                 NaN    0.223678     0
62 2026-05-21     567.880005                 NaN    0.324533     0
63 2026-05-22     576.320007                 NaN    0.357020     0

[64 rows x 5 columns]

예측값 분포:
pred
0    53
1    11
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 3
예측 1 중 실제 1 개수: 3
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.05, '...",44,3,...,0.295455,1.0,0.088235,0.162162,0.517647,0.701157,10,0,31,3

[I 2026-05-23 21:13:22,040] Trial 129 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.05, 'gb_max_depth': 2}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 131/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 10, 'threshold': 0.005, 'top_n': 20, 'pred_threshold': 0.4, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 500, 'learning_rate': 0.03, 'max_leaf_nodes': 31}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 130}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_10d_up_0pct
target_df shape: (1533, 31)
target 분포:
target_10d_up_0pct
1    882
0    651
Name: count, dtype: int64
lagged_df shape: (1354, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1396

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1396

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1394
TOP feature count: 20
['TNX_level_lag120', 'USDKRW_ret_20d_lag3', 'DXY_ret_20d_lag120', 'SMH_vol_20d_lag40', 'OIL_ret_20d_lag120', 'TNX_diff_20d_lag5', 'GOLD_ret_20d_lag40', 'NVDA_ret_20d_lag120', 'TSM_ret_5d_lag40', 'SPY_ret_20d_lag120', 'VIX_level_lag40', 'VIX_chg_5d_lag60', 'VIX_chg_20d_lag120', 'SMH_ma60_ratio_lag120', 'SMH_volume_ratio_20d_lag5', 'SMH_ma20_ratio_lag120', 'TSM_ret_20d_lag120', 'USDKRW_ret_5d_lag120', 'TNX_diff_5d_lag60', 'DXY_ret_5d_lag120']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.114099,0.005156,2.658068e-05,0.102361,0.121295,3,30,0.108944,TNX_level,120,120,-0.247079,0.247079,132
1,USDKRW_ret_20d_lag3,0.105354,0.006455,4.166613e-05,0.094970,0.115848,3,30,0.098899,USDKRW_ret_20d,3,3,-0.314678,0.314678,249
2,DXY_ret_20d_lag120,0.097480,0.002902,8.420871e-06,0.091990,0.102329,3,30,0.094578,DXY_ret_20d,120,120,-0.300370,0.300370,132
3,SMH_vol_20d_lag40,0.079376,0.002295,5.266172e-06,0.075700,0.083706,3,30,0.077081,SMH_vol_20d,40,40,0.216317,0.216317,212
4,OIL_ret_20d_lag120,0.066135,0.001842,3.394378e-06,0.063081,0.069975,3,30,0.064293,OIL_ret_20d,120,120,-0.229237,0.229237,132
5,TNX_diff_20d_lag5,0.061168,0.001872,3.503907e-06,0.057590,0.065294,3,30,0.059296,TNX_diff_20d,5,5,0.361960,0.361960,247
6,GOLD_ret_20d_lag40,0.057597,0.001910,3.647110e-06,0.053794,0.061701,3,30,0.055687,GOLD_ret_20d,40,40,-0.148102,0.148102,212
7,NVDA_ret_20d_lag120,0.054337,0.001519,2.307904e-06,0.050717,0.058087,3,30,0.052818,NVDA_ret_20d,120,120,-0.253585,0.253585,132
8,TSM_ret_5d_lag40,0.053448,0.001459,2.129743e-06,0.051298,0.056400,3,30,0.051989,TSM_ret_5d,40,40,-0.242780,0.242780,212
9,SPY_ret_20d_lag120,0.051863,0.001866,3.480598e-06,0.047460,0.055409,3,30,0.049998,SPY_ret_20d,120,120,-0.318511,0.318511,132
10,VIX_level_lag40,0.050667,0.001172,1.372871e-06,0.047863,0.052770,3,30,0.049496,VIX_level,40,40,0.151591,0.151591,212
11,VIX_chg_5d_lag60,0.047297,0.003269,1.068507e-05,0.042487,0.052602,3,30,0.044028,VIX_chg_5d,60,60,0.127624,0.127624,192
12,VIX_chg_20d_lag120,0.044215,0.001232,1.516596e-06,0.041359,0.046152,3,30,0.042983,VIX_chg_20d,120,120,0.313103,0.313103,132
13,SMH_ma60_ratio_lag120,0.043850,0.001086,1.179128e-06,0.041431,0.046171,3,30,0.042764,SMH_ma60_ratio,120,120,-0.197638,0.197638,132
14,SMH_volume_ratio_20d_lag5,0.042285,0.001657,2.746598e-06,0.039245,0.045566,3,30,0.040627,SMH_volume_ratio_20d,5,5,0.195126,0.195126,247
15,SMH_ma20_ratio_lag120,0.040721,0.001256,1.578181e-06,0.039018,0.043972,3,30,0.039465,SMH_ma20_ratio,120,120,-0.312656,0.312656,132
16,TSM_ret_20d_lag120,0.039925,0.001511,2.282005e-06,0.037629,0.043307,3,30,0.038415,TSM_ret_20d,120,120,-0.264108,0.264108,132
17,USDKRW_ret_5d_lag120,0.037754,0.001205,1.451256e-06,0.034878,0.039443,3,30,0.036549,USDKRW_ret_5d,120,120,0.236574,0.236574,132
18,TNX_diff_5d_lag60,0.034374,0.000919,8.439244e-07,0.032628,0.036210,3,30,0.033455,TNX_diff_5d,60,60,-0.203933,0.203933,192
19,DXY_ret_5d_lag120,0.032644,0.001161,1.349066e-06,0.030826,0.035434,3,30,0.031482,DXY_ret_5d,120,120,-0.110706,0.110706,132

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1354, 23)
X_train shape: (1354, 20)
train target 분포:
target_10d_up_0pct
1    766
0    588
Name: count, dtype: int64
target_10d_up_0pct
1    0.565731
0    0.434269
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_10d_up_0pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.987919     1
1  2026-02-24     419.160004                 0.0    0.982539     1
2  2026-02-25     426.160004                 0.0    0.941757     1
3  2026-02-26     412.010010                 0.0    0.100740     0
4  2026-02-27     406.369995                 0.0    0.213972     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.028297     0
60 2026-05-19     543.960022                 NaN    0.135677     0
61 2026-05-20     564.659973                 NaN    0.309327     0
62 2026-05-21     567.880005                 NaN    0.407383     1
63 2026-05-22     576.320007                 NaN    0.781918     1

[64 rows x 5 columns]

예측값 분포:
pred
1    36
0    28
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 54
예측 1 개수: 30
예측 1 중 실제 1 개수: 18
예측 1 기준 정확도 precision: 0.6

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,10,0.005,1,20,20,hist_gradient_boosting,"{'max_iter': 500, 'learning_rate': 0.03, 'max_...",54,30,...,0.425926,0.6,0.486486,0.537313,0.422893,1.190387,5,12,19,18

[I 2026-05-23 21:13:40,592] Trial 130 finished with value: 0.6 and parameters: {'n_days': 10, 'threshold': 0.005, 'top_n': 20, 'pred_threshold': 0.4, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 500, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 31}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 132/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 131}
====================================================================================================

[I 2026-05-23 21:13:40,695] Trial 131 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:13:40,736] Trial 132 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:13:40,775] Trial 133 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_205932_optuna_holdout_trial_0060
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 133/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 132}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204741_optuna_holdout_trial_0011
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 134/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 133}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_205932_optuna_holdout_trial_0060
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 135/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.75, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 134}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.555357     0
1  2026-02-24     419.160004                 0.0    0.646397     0
2  2026-02-25     426.160004                 0.0    0.597912     0
3  2026-02-26     412.010010                 0.0    0.457527     0
4  2026-02-27     406.369995                 0.0    0.545480     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.619136     0
60 2026-05-19     543.960022                 NaN    0.842201     1
61 2026-05-20     564.659973                 NaN    0.492613     0
62 2026-05-21     567.880005                 NaN    0.405804     0
63 2026-05-22     576.320007                 NaN    0.501921     0

[64 rows x 5 columns]

예측값 분포:
pred
0    55
1     9
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 1
예측 1 중 실제 1 개수: 1
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.03, '...",44,1,...,0.25,1.0,0.029412,0.057143,0.370588,0.77784,10,0,33,1

[I 2026-05-23 21:13:59,332] Trial 134 finished with value: 0.3333333333333333 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.75, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 136/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.01, 'max_depth': 5}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 135}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.580681     0
1  2026-02-24     419.160004                 0.0    0.646262     0
2  2026-02-25     426.160004                 0.0    0.629085     0
3  2026-02-26     412.010010                 0.0    0.437223     0
4  2026-02-27     406.369995                 0.0    0.468838     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.509053     0
60 2026-05-19     543.960022                 NaN    0.678743     1
61 2026-05-20     564.659973                 NaN    0.364124     0
62 2026-05-21     567.880005                 NaN    0.253155     0
63 2026-05-22     576.320007                 NaN    0.305266     0

[64 rows x 5 columns]

예측값 분포:
pred
0    47
1    17
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 6
예측 1 중 실제 1 개수: 6
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.01, '...",44,6,...,0.363636,1.0,0.176471,0.3,0.488235,0.685286,10,0,28,6

[I 2026-05-23 21:14:18,081] Trial 135 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.01, 'gb_max_depth': 5}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 137/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 10, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 136}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 10
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,0.000029,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,0.000011,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,0.000019,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,0.000002,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,0.000008,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,0.000010,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,0.000010,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,0.000007,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,0.000003,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,0.000002,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212

============================================================
6. valid_df 생성
============================================================
top feature 수: 10
lag 생성 후 valid_df shape: (1607, 22)
원본 base_feature 제거 후 valid_df shape: (1607, 12)
최종 컬럼 수: 12
target 생성 후 valid_df shape: (1607, 14)
최종 valid_df shape: (64, 14)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 10
train_df shape: (1383, 13)
X_train shape: (1383, 10)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 14)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.499373     0
1  2026-02-24     419.160004                 0.0    0.512391     0
2  2026-02-25     426.160004                 0.0    0.552511     0
3  2026-02-26     412.010010                 0.0    0.612322     0
4  2026-02-27     406.369995                 0.0    0.537445     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.866509     1
60 2026-05-19     543.960022                 NaN    0.640262     0
61 2026-05-20     564.659973                 NaN    0.379498     0
62 2026-05-21     567.880005                 NaN    0.723250     1
63 2026-05-22     576.320007                 NaN    0.783241     1

[64 rows x 5 columns]

예측값 분포:
pred
0    46
1    18
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 5
예측 1 중 실제 1 개수: 5
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,10,10,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.03, '...",44,5,...,0.340909,1.0,0.147059,0.25641,0.641176,0.598648,10,0,29,5

[I 2026-05-23 21:14:35,640] Trial 136 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 10, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 138/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.8, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.05, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 137}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.398819     0
1  2026-02-24     419.160004                 0.0    0.862304     1
2  2026-02-25     426.160004                 0.0    0.784833     0
3  2026-02-26     412.010010                 0.0    0.130773     0
4  2026-02-27     406.369995                 0.0    0.230890     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.942578     1
60 2026-05-19     543.960022                 NaN    0.989190     1
61 2026-05-20     564.659973                 NaN    0.464285     0
62 2026-05-21     567.880005                 NaN    0.627552     0
63 2026-05-22     576.320007                 NaN    0.388747     0

[64 rows x 5 columns]

예측값 분포:
pred
0    38
1    26
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 11
예측 1 중 실제 1 개수: 6
예측 1 기준 정확도 precision: 0.5454545454545454

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,hist_gradient_boosting,"{'max_iter': 300, 'learning_rate': 0.05, 'max_...",44,11,...,0.25,0.545455,0.176471,0.266667,0.297059,1.2751,5,5,28,6

[I 2026-05-23 21:14:54,001] Trial 137 finished with value: 0.5454545454545454 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.8, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.05, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:14:54,063] Trial 138 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'logistic', 'logistic_C': 1.0}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 139/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'logistic', 'model_params': {'C': 1.0, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 138}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204639_optuna_holdout_trial_0007
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 140/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 139}
====================================================================================================

[I 2026-05-23 21:14:54,108] Trial 139 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_211150_optuna_holdout_trial_0124
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 141/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 50, 'pred_threshold': 0.65, 'model_name': 'random_forest', 'model_params': {'n_estimators': 300, 'max_depth': 5, 'min_samples_leaf': 5, 'max_features': 'log2', 'class_weight': 'balanced'}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 140}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 27
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1', 'NVDA_ret_5d_lag60', 'SPY_ret_5d_lag120', 'SOXX_ret_5d_lag120', 'USDKRW_ret_5d_lag40', 'SMH_ma5_ratio_lag60', 'SMH_volume_ratio_20d_lag120', 'SMH_ret_1d_lag60']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251
20,NVDA_ret_5d_lag60,0.026639,0.001112,1.237156e-06,0.024575,0.028571,3,30,0.025526,NVDA_ret_5d,60,60,-0.251682,0.251682,192
21,SPY_ret_5d_lag120,0.025915,0.000723,5.228773e-07,0.024417,0.027251,3,30,0.025192,SPY_ret_5d,120,120,-0.252525,0.252525,132
22,SOXX_ret_5d_lag120,0.025491,0.000480,2.300800e-07,0.024445,0.026427,3,30,0.025011,SOXX_ret_5d,120,120,-0.254602,0.254602,132
23,USDKRW_ret_5d_lag40,0.025065,0.000769,5.909936e-07,0.023745,0.026481,3,30,0.024296,USDKRW_ret_5d,40,40,0.146047,0.146047,212
24,SMH_ma5_ratio_lag60,0.021075,0.000702,4.932835e-07,0.019899,0.022518,3,30,0.020372,SMH_ma5_ratio,60,60,-0.238638,0.238638,192
25,SMH_volume_ratio_20d_lag120,0.020579,0.001005,1.009657e-06,0.018787,0.022134,3,30,0.019574,SMH_volume_ratio_20d,120,120,0.263883,0.263883,132
26,SMH_ret_1d_lag60,0.014771,0.000621,3.856972e-07,0.013554,0.015965,3,30,0.014150,SMH_ret_1d,60,60,-0.167087,0.167087,192

============================================================
6. valid_df 생성
============================================================
top feature 수: 27
lag 생성 후 valid_df shape: (1607, 56)
원본 base_feature 제거 후 valid_df shape: (1607, 29)
최종 컬럼 수: 29
target 생성 후 valid_df shape: (1607, 31)
최종 valid_df shape: (64, 31)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 27
train_df shape: (1383, 30)
X_train shape: (1383, 27)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 31)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: random_forest
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.540712     0
1  2026-02-24     419.160004                 0.0    0.528046     0
2  2026-02-25     426.160004                 0.0    0.523649     0
3  2026-02-26     412.010010                 0.0    0.537428     0
4  2026-02-27     406.369995                 0.0    0.525746     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.530760     0
60 2026-05-19     543.960022                 NaN    0.512751     0
61 2026-05-20     564.659973                 NaN    0.456819     0
62 2026-05-21     567.880005                 NaN    0.497912     0
63 2026-05-22     576.320007                 NaN    0.512763     0

[64 rows x 5 columns]

예측값 분포:
pred
0    64
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 0
예측 1 중 실제 1 개수: 0
예측 1 기준 정확도 precision: nan

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,50,27,random_forest,"{'n_estimators': 300, 'max_depth': 5, 'min_sam...",44,0,...,0.227273,0.0,0.0,0.0,0.347059,0.703188,10,0,34,0

[I 2026-05-23 21:15:11,468] Trial 140 finished with value: 0.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 50, 'pred_threshold': 0.65, 'model_name': 'random_forest', 'rf_n_estimators': 300, 'rf_max_depth': 5, 'rf_min_samples_leaf': 5, 'rf_max_features': 'log2'}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:15:11,500] Trial 141 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:15:11,537] Trial 142 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 142/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 141}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_205244_optuna_holdout_trial_0031
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 143/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 142}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_205244_optuna_holdout_trial_0031
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 144/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.75, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 143}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 20
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.298517     0
1  2026-02-24     419.160004                 0.0    0.339273     0
2  2026-02-25     426.160004                 0.0    0.612624     0
3  2026-02-26     412.010010                 0.0    0.400821     0
4  2026-02-27     406.369995                 0.0    0.632620     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.808243     1
60 2026-05-19     543.960022                 NaN    0.869996     1
61 2026-05-20     564.659973                 NaN    0.490125     0
62 2026-05-21     567.880005                 NaN    0.353365     0
63 2026-05-22     576.320007                 NaN    0.432212     0

[64 rows x 5 columns]

예측값 분포:
pred
0    42
1    22
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 8
예측 1 중 실제 1 개수: 8
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,20,20,hist_gradient_boosting,"{'max_iter': 300, 'learning_rate': 0.03, 'max_...",44,8,...,0.409091,1.0,0.235294,0.380952,0.55,0.894799,10,0,26,8

[I 2026-05-23 21:15:30,588] Trial 143 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.75, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:15:30,635] Trial 144 finished with value: 0.8333333333333334 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 145/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 144}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_205302_optuna_holdout_trial_0033
기존 test_precision: 0.8333333333333334

====================================================================================================
OPTUNA HOLDOUT TRIAL 146/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 10, 'threshold': 0.015, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 100, 'learning_rate': 0.1, 'max_leaf_nodes': 15}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 145}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_10d_up_1pct
target_df shape: (1533, 31)
target 분포:
target_10d_up_1pct
1    789
0    744
Name: count, dtype: int64
lagged_df shape: (1393, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1435

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.143

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1436
TOP feature count: 20
['USDKRW_ret_20d_lag3', 'TNX_level_lag120', 'DXY_ret_20d_lag120', 'OIL_ret_20d_lag40', 'SMH_vol_20d_lag40', 'SMH_ma60_ratio_lag40', 'SMH_ma20_ratio_lag40', 'TNX_diff_20d_lag5', 'TSM_ret_20d_lag40', 'NVDA_ret_20d_lag120', 'VIX_chg_20d_lag120', 'VIX_level_lag40', 'SPY_ret_20d_lag120', 'GOLD_ret_20d_lag120', 'VIX_chg_5d_lag60', 'USDKRW_ret_5d_lag120', 'TSM_ret_5d_lag40', 'SMH_volume_ratio_20d_lag5', 'NVDA_ret_5d_lag60', 'SOXX_ret_5d_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,USDKRW_ret_20d_lag3,0.120179,0.003203,1.025687e-05,0.114064,0.127153,3,30,0.116976,USDKRW_ret_20d,3,3,-0.357632,0.357632,249
1,TNX_level_lag120,0.098635,0.002875,8.264090e-06,0.089594,0.103376,3,30,0.095760,TNX_level,120,120,-0.209417,0.209417,132
2,DXY_ret_20d_lag120,0.089309,0.002229,4.967756e-06,0.083745,0.092958,3,30,0.087080,DXY_ret_20d,120,120,-0.244463,0.244463,132
3,OIL_ret_20d_lag40,0.069472,0.001444,2.086402e-06,0.066390,0.072341,3,30,0.068028,OIL_ret_20d,40,40,-0.261638,0.261638,212
4,SMH_vol_20d_lag40,0.068675,0.001826,3.334384e-06,0.065220,0.072490,3,30,0.066849,SMH_vol_20d,40,40,0.258244,0.258244,212
5,SMH_ma60_ratio_lag40,0.066721,0.001533,2.351514e-06,0.063232,0.069945,3,30,0.065187,SMH_ma60_ratio,40,40,-0.236194,0.236194,212
6,SMH_ma20_ratio_lag40,0.057550,0.001558,2.426530e-06,0.053863,0.060871,3,30,0.055992,SMH_ma20_ratio,40,40,-0.241800,0.241800,212
7,TNX_diff_20d_lag5,0.055415,0.001547,2.392637e-06,0.052586,0.058614,3,30,0.053869,TNX_diff_20d,5,5,0.323838,0.323838,247
8,TSM_ret_20d_lag40,0.054409,0.001754,3.076881e-06,0.050440,0.058271,3,30,0.052655,TSM_ret_20d,40,40,-0.276363,0.276363,212
9,NVDA_ret_20d_lag120,0.054923,0.002644,6.989798e-06,0.049354,0.059768,3,30,0.052279,NVDA_ret_20d,120,120,-0.174684,0.174684,132
10,VIX_chg_20d_lag120,0.052718,0.001795,3.222371e-06,0.050121,0.057159,3,30,0.050923,VIX_chg_20d,120,120,0.179828,0.179828,132
11,VIX_level_lag40,0.050085,0.001329,1.765036e-06,0.047345,0.052508,3,30,0.048756,VIX_level,40,40,0.190705,0.190705,212
12,SPY_ret_20d_lag120,0.048621,0.000906,8.215688e-07,0.046890,0.050990,3,30,0.047715,SPY_ret_20d,120,120,-0.230254,0.230254,132
13,GOLD_ret_20d_lag120,0.045884,0.002215,4.904031e-06,0.041327,0.048565,3,30,0.043669,GOLD_ret_20d,120,120,-0.137286,0.137286,132
14,VIX_chg_5d_lag60,0.044085,0.001796,3.227083e-06,0.041035,0.047028,3,30,0.042289,VIX_chg_5d,60,60,0.141418,0.141418,192
15,USDKRW_ret_5d_lag120,0.044194,0.002562,6.566231e-06,0.040713,0.049551,3,30,0.041632,USDKRW_ret_5d,120,120,0.211443,0.211443,132
16,TSM_ret_5d_lag40,0.039475,0.001123,1.262164e-06,0.037073,0.042047,3,30,0.038352,TSM_ret_5d,40,40,-0.314300,0.314300,212
17,SMH_volume_ratio_20d_lag5,0.036161,0.001115,1.243013e-06,0.033575,0.038225,3,30,0.035046,SMH_volume_ratio_20d,5,5,0.179281,0.179281,247
18,NVDA_ret_5d_lag60,0.036037,0.001161,1.349002e-06,0.034426,0.039001,3,30,0.034876,NVDA_ret_5d,60,60,-0.223746,0.223746,192
19,SOXX_ret_5d_lag40,0.034374,0.001140,1.299101e-06,0.032316,0.037244,3,30,0.033234,SOXX_ret_5d,40,40,-0.229707,0.229707,212

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1393, 23)
X_train shape: (1393, 20)
train target 분포:
target_10d_up_1pct
1    706
0    687
Name: count, dtype: int64
target_10d_up_1pct
1    0.50682
0    0.49318
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_10d_up_1pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.910152     1
1  2026-02-24     419.160004                 0.0    0.903233     1
2  2026-02-25     426.160004                 0.0    0.729162     1
3  2026-02-26     412.010010                 0.0    0.376476     0
4  2026-02-27     406.369995                 0.0    0.385590     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.245036     0
60 2026-05-19     543.960022                 NaN    0.445211     0
61 2026-05-20     564.659973                 NaN    0.581599     0
62 2026-05-21     567.880005                 NaN    0.553468     0
63 2026-05-22     576.320007                 NaN    0.360905     0

[64 rows x 5 columns]

예측값 분포:
pred
0    44
1    20
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 54
예측 1 개수: 16
예측 1 중 실제 1 개수: 11
예측 1 기준 정확도 precision: 0.6875

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,10,0.015,1,20,20,hist_gradient_boosting,"{'max_iter': 100, 'learning_rate': 0.1, 'max_l...",54,16,...,0.462963,0.6875,0.314286,0.431373,0.442105,0.94047,14,5,24,11

[I 2026-05-23 21:15:47,803] Trial 145 finished with value: 0.6875 and parameters: {'n_days': 10, 'threshold': 0.015, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 100, 'hgb_learning_rate': 0.1, 'hgb_max_leaf_nodes': 15}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 147/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.45, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 100, 'learning_rate': 0.1, 'max_depth': 5}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 146}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 20
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.288926     0
1  2026-02-24     419.160004                 0.0    0.709022     1
2  2026-02-25     426.160004                 0.0    0.442846     0
3  2026-02-26     412.010010                 0.0    0.507793     1
4  2026-02-27     406.369995                 0.0    0.578783     1
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.266168     0
60 2026-05-19     543.960022                 NaN    0.476100     1
61 2026-05-20     564.659973                 NaN    0.301219     0
62 2026-05-21     567.880005                 NaN    0.275993     0
63 2026-05-22     576.320007                 NaN    0.133690     0

[64 rows x 5 columns]

예측값 분포:
pred
1    34
0    30
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 20
예측 1 중 실제 1 개수: 15
예측 1 기준 정확도 precision: 0.75

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,20,20,gradient_boosting,"{'n_estimators': 100, 'learning_rate': 0.1, 'm...",44,20,...,0.454545,0.75,0.441176,0.555556,0.535294,0.79349,5,5,19,15

[I 2026-05-23 21:16:05,947] Trial 146 finished with value: 0.75 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.45, 'model_name': 'gradient_boosting', 'gb_n_estimators': 100, 'gb_learning_rate': 0.1, 'gb_max_depth': 5}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 148/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 3, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'logistic', 'model_params': {'C': 1.0, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 147}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_3d_up_2pct
target_df shape: (1540, 31)
target 분포:
target_3d_up_2pct
0    1034
1     506
Name: count, dtype: int64
lagged_df shape: (1400, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1599

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.159

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1591
TOP feature count: 20
['NVDA_ret_20d_lag1', 'DXY_ret_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma5_ratio_lag10', 'SMH_ma60_ratio_lag1', 'SOXX_ret_5d_lag1', 'VIX_level_lag1', 'VIX_chg_20d_lag40', 'TSM_ret_5d_lag10', 'GOLD_ret_5d_lag120', 'GOLD_ret_20d_lag120', 'TSM_ret_20d_lag40', 'USDKRW_ret_20d_lag40', 'SMH_ret_1d_lag10', 'TNX_level_lag1', 'VIX_chg_5d_lag40', 'SMH_vol_20d_lag60', 'NVDA_ret_5d_lag1', 'SPY_ret_20d_lag120', 'SPY_ret_5d_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,NVDA_ret_20d_lag1,0.097206,0.004106,1.686072e-05,0.090497,0.104698,3,30,0.093100,NVDA_ret_20d,1,1,-0.111781,0.111781,250
1,DXY_ret_20d_lag120,0.070614,0.001475,2.175890e-06,0.067993,0.074612,3,30,0.069139,DXY_ret_20d,120,120,-0.105215,0.105215,131
2,SMH_ma20_ratio_lag1,0.061117,0.001850,3.423071e-06,0.057828,0.065284,3,30,0.059267,SMH_ma20_ratio,1,1,-0.175532,0.175532,250
3,SMH_ma5_ratio_lag10,0.056295,0.001797,3.229324e-06,0.052956,0.059930,3,30,0.054498,SMH_ma5_ratio,10,10,-0.235165,0.235165,241
4,SMH_ma60_ratio_lag1,0.054641,0.001352,1.827155e-06,0.051610,0.056799,3,30,0.053289,SMH_ma60_ratio,1,1,-0.137592,0.137592,250
5,SOXX_ret_5d_lag1,0.052406,0.002972,8.835182e-06,0.046161,0.056209,3,30,0.049434,SOXX_ret_5d,1,1,-0.199028,0.199028,250
6,VIX_level_lag1,0.052427,0.003118,9.723011e-06,0.048047,0.057951,3,30,0.049308,VIX_level,1,1,0.126094,0.126094,250
7,VIX_chg_20d_lag40,0.048218,0.001064,1.132742e-06,0.045217,0.050314,3,30,0.047154,VIX_chg_20d,40,40,0.182643,0.182643,211
8,TSM_ret_5d_lag10,0.044915,0.001040,1.082322e-06,0.043098,0.047615,3,30,0.043874,TSM_ret_5d,10,10,-0.179270,0.179270,241
9,GOLD_ret_5d_lag120,0.044546,0.001121,1.255637e-06,0.042196,0.047571,3,30,0.043425,GOLD_ret_5d,120,120,-0.114377,0.114377,131
10,GOLD_ret_20d_lag120,0.043482,0.001129,1.274155e-06,0.040819,0.045993,3,30,0.042353,GOLD_ret_20d,120,120,-0.107223,0.107223,131
11,TSM_ret_20d_lag40,0.043783,0.002185,4.773945e-06,0.039529,0.046979,3,30,0.041598,TSM_ret_20d,40,40,-0.096849,0.096849,211
12,USDKRW_ret_20d_lag40,0.041263,0.001944,3.778063e-06,0.037834,0.044233,3,30,0.039320,USDKRW_ret_20d,40,40,0.152425,0.152425,211
13,SMH_ret_1d_lag10,0.040061,0.001287,1.656742e-06,0.037420,0.042480,3,30,0.038774,SMH_ret_1d,10,10,-0.169190,0.169190,241
14,TNX_level_lag1,0.039300,0.000939,8.809489e-07,0.036885,0.040442,3,30,0.038361,TNX_level,1,1,-0.130603,0.130603,250
15,VIX_chg_5d_lag40,0.039871,0.001533,2.351359e-06,0.037075,0.042152,3,30,0.038338,VIX_chg_5d,40,40,0.159722,0.159722,211
16,SMH_vol_20d_lag60,0.039652,0.001963,3.852132e-06,0.036112,0.042364,3,30,0.037689,SMH_vol_20d,60,60,-0.150076,0.150076,191
17,NVDA_ret_5d_lag1,0.038617,0.001202,1.445857e-06,0.036307,0.040936,3,30,0.037415,NVDA_ret_5d,1,1,-0.181966,0.181966,250
18,SPY_ret_20d_lag120,0.038898,0.001529,2.338266e-06,0.036068,0.041820,3,30,0.037369,SPY_ret_20d,120,120,-0.124476,0.124476,131
19,SPY_ret_5d_lag40,0.038334,0.001174,1.378602e-06,0.035871,0.040135,3,30,0.037160,SPY_ret_5d,40,40,-0.203227,0.203227,211

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1400, 23)
X_train shape: (1400, 20)
train target 분포:
target_3d_up_2pct
0    942
1    458
Name: count, dtype: int64
target_3d_up_2pct
0    0.672857
1    0.327143
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_3d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                0.0    0.456844     0
1  2026-02-24     419.160004                0.0    0.351053     0
2  2026-02-25     426.160004                0.0    0.341951     0
3  2026-02-26     412.010010                0.0    0.360355     0
4  2026-02-27     406.369995                0.0    0.437228     0
..        ...            ...                ...         ...   ...
59 2026-05-18     546.159973                1.0    0.502170     0
60 2026-05-19     543.960022                1.0    0.507624     0
61 2026-05-20     564.659973                NaN    0.422657     0
62 2026-05-21     567.880005                NaN    0.362585     0
63 2026-05-22     576.320007                NaN    0.328649     0

[64 rows x 5 columns]

예측값 분포:
pred
0    64
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 61
예측 1 개수: 0
예측 1 중 실제 1 개수: 0
예측 1 기준 정확도 precision: nan

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,3,0.02,1,20,20,logistic,"{'C': 1.0, 'class_weight': 'balanced', 'max_it...",61,0,...,0.508197,0.0,0.0,0.0,0.433333,0.759923,31,0,30,0

[I 2026-05-23 21:16:23,277] Trial 147 finished with value: 0.0 and parameters: {'n_days': 3, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'logistic', 'logistic_C': 1.0}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 149/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 148}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 20
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.441412     0
1  2026-02-24     419.160004                 0.0    0.515109     0
2  2026-02-25     426.160004                 0.0    0.446093     0
3  2026-02-26     412.010010                 0.0    0.520890     0
4  2026-02-27     406.369995                 0.0    0.605391     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.499986     0
60 2026-05-19     543.960022                 NaN    0.601600     0
61 2026-05-20     564.659973                 NaN    0.427989     0
62 2026-05-21     567.880005                 NaN    0.600528     0
63 2026-05-22     576.320007                 NaN    0.621633     0

[64 rows x 5 columns]

예측값 분포:
pred
0    51
1    13
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 4
예측 1 중 실제 1 개수: 4
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.03, '...",44,4,...,0.318182,1.0,0.117647,0.210526,0.397059,0.761671,10,0,30,4

[I 2026-05-23 21:16:41,292] Trial 148 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 150/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.01, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 149}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_1pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_1pct
1    917
0    606
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1301

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1302

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1305
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'NVDA_ret_5d_lag120', 'DXY_ret_5d_lag120', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SMH_ma60_ratio_lag1', 'OIL_ret_20d_lag120', 'VIX_chg_5d_lag120', 'SPY_ret_20d_lag1', 'TNX_diff_5d_lag5', 'GOLD_ret_20d_lag120', 'SMH_ma20_ratio_lag120', 'TSM_ret_5d_lag120', 'GOLD_ret_5d_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.113199,0.003130,9.798652e-06,0.105366,0.117758,3,30,0.110069,SMH_vol_20d,120,120,-0.305565,0.305565,132
1,TNX_level_lag20,0.111395,0.001966,3.863856e-06,0.107542,0.114334,3,30,0.109430,TNX_level,20,20,-0.282349,0.282349,232
2,NVDA_ret_20d_lag1,0.080573,0.003084,9.508619e-06,0.075624,0.086273,3,30,0.077490,NVDA_ret_20d,1,1,0.282168,0.282168,251
3,VIX_chg_20d_lag120,0.077843,0.001462,2.138529e-06,0.074670,0.080400,3,30,0.076381,VIX_chg_20d,120,120,0.371232,0.371232,132
4,DXY_ret_20d_lag60,0.073491,0.002177,4.737914e-06,0.068070,0.077471,3,30,0.071314,DXY_ret_20d,60,60,-0.256904,0.256904,192
5,TNX_diff_20d_lag1,0.066654,0.002093,4.380060e-06,0.062034,0.070705,3,30,0.064561,TNX_diff_20d,1,1,0.416622,0.416622,251
6,NVDA_ret_5d_lag120,0.056072,0.001459,2.128896e-06,0.052971,0.058355,3,30,0.054613,NVDA_ret_5d,120,120,-0.233880,0.233880,132
7,DXY_ret_5d_lag120,0.053295,0.001976,3.904778e-06,0.049647,0.058129,3,30,0.051319,DXY_ret_5d,120,120,-0.267096,0.267096,132
8,VIX_level_lag20,0.051839,0.001035,1.070311e-06,0.049900,0.053607,3,30,0.050805,VIX_level,20,20,0.239784,0.239784,232
9,USDKRW_ret_20d_lag40,0.051299,0.001162,1.350872e-06,0.049044,0.053384,3,30,0.050136,USDKRW_ret_20d,40,40,0.281470,0.281470,212
10,TSM_ret_20d_lag1,0.050516,0.002066,4.268228e-06,0.047785,0.054069,3,30,0.048450,TSM_ret_20d,1,1,0.339692,0.339692,251
11,SMH_ma60_ratio_lag1,0.047034,0.001847,3.412431e-06,0.043919,0.049834,3,30,0.045187,SMH_ma60_ratio,1,1,0.226498,0.226498,251
12,OIL_ret_20d_lag120,0.044614,0.001553,2.410659e-06,0.041020,0.048293,3,30,0.043061,OIL_ret_20d,120,120,0.291387,0.291387,132
13,VIX_chg_5d_lag120,0.042947,0.001208,1.459362e-06,0.040616,0.045759,3,30,0.041739,VIX_chg_5d,120,120,0.143824,0.143824,132
14,SPY_ret_20d_lag1,0.043100,0.001912,3.657161e-06,0.039473,0.046173,3,30,0.041188,SPY_ret_20d,1,1,0.273031,0.273031,251
15,TNX_diff_5d_lag5,0.041964,0.001642,2.694547e-06,0.039434,0.045450,3,30,0.040323,TNX_diff_5d,5,5,0.182059,0.182059,247
16,GOLD_ret_20d_lag120,0.037065,0.001167,1.361693e-06,0.034635,0.040013,3,30,0.035898,GOLD_ret_20d,120,120,-0.306548,0.306548,132
17,SMH_ma20_ratio_lag120,0.034339,0.000618,3.813267e-07,0.033254,0.035764,3,30,0.033721,SMH_ma20_ratio,120,120,-0.303183,0.303183,132
18,TSM_ret_5d_lag120,0.034178,0.001041,1.084444e-06,0.032365,0.036477,3,30,0.033136,TSM_ret_5d,120,120,-0.251775,0.251775,132
19,GOLD_ret_5d_lag40,0.031021,0.001323,1.750672e-06,0.028289,0.032956,3,30,0.029698,GOLD_ret_5d,40,40,-0.185968,0.185968,212

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_1pct
1    815
0    568
Name: count, dtype: int64
target_20d_up_1pct
1    0.589299
0    0.410701
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_1pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.932494     1
1  2026-02-24     419.160004                 0.0    0.941298     1
2  2026-02-25     426.160004                 0.0    0.934112     1
3  2026-02-26     412.010010                 0.0    0.911374     1
4  2026-02-27     406.369995                 0.0    0.890462     1
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.797970     1
60 2026-05-19     543.960022                 NaN    0.904581     1
61 2026-05-20     564.659973                 NaN    0.956243     1
62 2026-05-21     567.880005                 NaN    0.945733     1
63 2026-05-22     576.320007                 NaN    0.946984     1

[64 rows x 5 columns]

예측값 분포:
pred
1    55
0     9
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 35
예측 1 중 실제 1 개수: 26
예측 1 기준 정확도 precision: 0.7428571428571429

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.01,1,20,20,hist_gradient_boosting,"{'max_iter': 300, 'learning_rate': 0.03, 'max_...",44,35,...,0.590909,0.742857,0.742857,0.742857,0.168254,0.789703,0,9,9,26

[I 2026-05-23 21:16:59,245] Trial 149 finished with value: 0.7428571428571429 and parameters: {'n_days': 20, 'threshold': 0.01, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 151/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 5, 'threshold': 0.02, 'top_n': 30, 'pred_threshold': 0.6000000000000001, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 500, 'learning_rate': 0.01, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 150}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_5d_up_2pct
target_df shape: (1538, 31)
target 분포:
target_5d_up_2pct
0    919
1    619
Name: count, dtype: int64
lagged_df shape: (1398, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1646

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1648

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1651
TOP feature count: 27
['DXY_ret_20d_lag120', 'SMH_vol_20d_lag60', 'TNX_diff_5d_lag1', 'TNX_level_lag1', 'GOLD_ret_5d_lag120', 'VIX_level_lag40', 'VIX_chg_20d_lag120', 'DXY_ret_5d_lag120', 'TNX_diff_20d_lag5', 'SPY_ret_20d_lag120', 'OIL_ret_20d_lag60', 'GOLD_ret_20d_lag1', 'USDKRW_ret_5d_lag40', 'TSM_ret_20d_lag40', 'VIX_chg_5d_lag40', 'USDKRW_ret_20d_lag40', 'TSM_ret_5d_lag40', 'SPY_ret_5d_lag40', 'SMH_ma20_ratio_lag40', 'SMH_ma60_ratio_lag20', 'NVDA_ret_20d_lag120', 'OIL_ret_5d_lag60', 'SMH_volume_ratio_20d_lag60', 'NVDA_ret_5d_lag40', 'SMH_ma5_ratio_lag40', 'SOXX_ret_5d_lag40', 'SMH_ret_1d_lag10']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,DXY_ret_20d_lag120,0.097643,0.003116,9.710753e-06,0.091485,0.102341,3,30,0.094526,DXY_ret_20d,120,120,-0.177627,0.177627,132
1,SMH_vol_20d_lag60,0.073933,0.001638,2.684309e-06,0.071582,0.077448,3,30,0.072294,SMH_vol_20d,60,60,-0.200945,0.200945,192
2,TNX_diff_5d_lag1,0.072014,0.003887,1.510828e-05,0.064915,0.076751,3,30,0.068127,TNX_diff_5d,1,1,-0.194687,0.194687,251
3,TNX_level_lag1,0.070761,0.003199,1.023364e-05,0.063743,0.075185,3,30,0.067562,TNX_level,1,1,-0.214996,0.214996,251
4,GOLD_ret_5d_lag120,0.061778,0.001114,1.241156e-06,0.059052,0.064708,3,30,0.060664,GOLD_ret_5d,120,120,-0.197469,0.197469,132
5,VIX_level_lag40,0.057051,0.001657,2.746894e-06,0.053453,0.059921,3,30,0.055394,VIX_level,40,40,0.129031,0.129031,212
6,VIX_chg_20d_lag120,0.051215,0.001738,3.018957e-06,0.048241,0.053650,3,30,0.049477,VIX_chg_20d,120,120,0.178242,0.178242,132
7,DXY_ret_5d_lag120,0.050292,0.001078,1.163088e-06,0.048544,0.052323,3,30,0.049214,DXY_ret_5d,120,120,0.144858,0.144858,132
8,TNX_diff_20d_lag5,0.049925,0.001771,3.135040e-06,0.046680,0.052575,3,30,0.048155,TNX_diff_20d,5,5,0.233782,0.233782,247
9,SPY_ret_20d_lag120,0.049587,0.001888,3.563241e-06,0.047120,0.053090,3,30,0.047699,SPY_ret_20d,120,120,-0.184210,0.184210,132
10,OIL_ret_20d_lag60,0.049609,0.002562,6.566202e-06,0.046023,0.054144,3,30,0.047046,OIL_ret_20d,60,60,0.183668,0.183668,192
11,GOLD_ret_20d_lag1,0.049299,0.002614,6.835072e-06,0.045773,0.053670,3,30,0.046685,GOLD_ret_20d,1,1,0.156010,0.156010,251
12,USDKRW_ret_5d_lag40,0.047465,0.000926,8.578479e-07,0.045333,0.048986,3,30,0.046538,USDKRW_ret_5d,40,40,0.194949,0.194949,212
13,TSM_ret_20d_lag40,0.046758,0.001039,1.080266e-06,0.044701,0.048959,3,30,0.045719,TSM_ret_20d,40,40,-0.156042,0.156042,212
14,VIX_chg_5d_lag40,0.046637,0.001318,1.737261e-06,0.043782,0.049049,3,30,0.045319,VIX_chg_5d,40,40,0.213755,0.213755,212
15,USDKRW_ret_20d_lag40,0.044589,0.000760,5.781988e-07,0.043431,0.046596,3,30,0.043829,USDKRW_ret_20d,40,40,0.230330,0.230330,212
16,TSM_ret_5d_lag40,0.044796,0.001053,1.108525e-06,0.042784,0.046687,3,30,0.043743,TSM_ret_5d,40,40,-0.250401,0.250401,212
17,SPY_ret_5d_lag40,0.045185,0.001809,3.272031e-06,0.041485,0.048565,3,30,0.043376,SPY_ret_5d,40,40,-0.271129,0.271129,212
18,SMH_ma20_ratio_lag40,0.042832,0.000860,7.400631e-07,0.041198,0.044580,3,30,0.041972,SMH_ma20_ratio,40,40,-0.200945,0.200945,212
19,SMH_ma60_ratio_lag20,0.039862,0.000882,7.786455e-07,0.037686,0.041883,3,30,0.038980,SMH_ma60_ratio,20,20,-0.095011,0.095011,232
20,NVDA_ret_20d_lag120,0.037676,0.001378,1.899688e-06,0.035413,0.039635,3,30,0.036297,NVDA_ret_20d,120,120,-0.109313,0.109313,132
21,OIL_ret_5d_lag60,0.037094,0.001530,2.340370e-06,0.034731,0.040008,3,30,0.035564,OIL_ret_5d,60,60,0.162607,0.162607,192
22,SMH_volume_ratio_20d_lag60,0.036327,0.001550,2.403041e-06,0.033251,0.039058,3,30,0.034777,SMH_volume_ratio_20d,60,60,0.119552,0.119552,192
23,NVDA_ret_5d_lag40,0.035022,0.001888,3.563596e-06,0.032714,0.038933,3,30,0.033134,NVDA_ret_5d,40,40,-0.159992,0.159992,212
24,SMH_ma5_ratio_lag40,0.034321,0.001210,1.464483e-06,0.032805,0.036595,3,30,0.033110,SMH_ma5_ratio,40,40,-0.197677,0.197677,212
25,SOXX_ret_5d_lag40,0.032909,0.001147,1.314949e-06,0.030857,0.034877,3,30,0.031762,SOXX_ret_5d,40,40,-0.211367,0.211367,212
26,SMH_ret_1d_lag10,0.032574,0.001488,2.214505e-06,0.030357,0.035630,3,30,0.031086,SMH_ret_1d,10,10,-0.139697,0.139697,242

============================================================
6. valid_df 생성
============================================================
top feature 수: 27
lag 생성 후 valid_df shape: (1607, 56)
원본 base_feature 제거 후 valid_df shape: (1607, 29)
최종 컬럼 수: 29
target 생성 후 valid_df shape: (1607, 31)
최종 valid_df shape: (64, 31)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 27
train_df shape: (1398, 30)
X_train shape: (1398, 27)
train target 분포:
target_5d_up_2pct
0    841
1    557
Name: count, dtype: int64
target_5d_up_2pct
0    0.601574
1    0.398426
Name: proportion, dtype: float64
valid_df shape: (64, 31)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_5d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                0.0    0.334031     0
1  2026-02-24     419.160004                0.0    0.226966     0
2  2026-02-25     426.160004                0.0    0.318064     0
3  2026-02-26     412.010010                0.0    0.256169     0
4  2026-02-27     406.369995                0.0    0.312078     0
..        ...            ...                ...         ...   ...
59 2026-05-18     546.159973                NaN    0.299229     0
60 2026-05-19     543.960022                NaN    0.430925     0
61 2026-05-20     564.659973                NaN    0.430288     0
62 2026-05-21     567.880005                NaN    0.452775     0
63 2026-05-22     576.320007                NaN    0.435527     0

[64 rows x 5 columns]

예측값 분포:
pred
0    64
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 59
예측 1 개수: 0
예측 1 중 실제 1 개수: 0
예측 1 기준 정확도 precision: nan

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,5,0.02,1,30,27,gradient_boosting,"{'n_estimators': 500, 'learning_rate': 0.01, '...",59,0,...,0.508475,0.0,0.0,0.0,0.439655,0.764443,30,0,29,0

[I 2026-05-23 21:17:19,336] Trial 150 finished with value: 0.0 and parameters: {'n_days': 5, 'threshold': 0.02, 'top_n': 30, 'pred_threshold': 0.6000000000000001, 'model_name': 'gradient_boosting', 'gb_n_estimators': 500, 'gb_learning_rate': 0.01, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:17:19,412] Trial 151 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:17:19,439] Trial 152 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:17:19,465] Trial 153 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 152/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 151}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_205244_optuna_holdout_trial_0031
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 153/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 152}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_205244_optuna_holdout_trial_0031
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 154/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 153}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_205244_optuna_holdout_trial_0031
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 155/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 154}
====================================================================================================

[I 2026-05-23 21:17:19,492] Trial 154 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204756_optuna_holdout_trial_0012
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 156/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'logistic', 'model_params': {'C': 0.01, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 155}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 20
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.401427     0
1  2026-02-24     419.160004                 0.0    0.431935     0
2  2026-02-25     426.160004                 0.0    0.470326     0
3  2026-02-26     412.010010                 0.0    0.498619     0
4  2026-02-27     406.369995                 0.0    0.551744     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.487770     0
60 2026-05-19     543.960022                 NaN    0.559662     0
61 2026-05-20     564.659973                 NaN    0.576878     0
62 2026-05-21     567.880005                 NaN    0.626036     0
63 2026-05-22     576.320007                 NaN    0.584614     0

[64 rows x 5 columns]

예측값 분포:
pred
0    56
1     8
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 6
예측 1 중 실제 1 개수: 6
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,20,20,logistic,"{'C': 0.01, 'class_weight': 'balanced', 'max_i...",44,6,...,0.363636,1.0,0.176471,0.3,0.747059,0.621483,10,0,28,6

[I 2026-05-23 21:17:36,021] Trial 155 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'logistic', 'logistic_C': 0.01}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 157/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 156}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.269206     0
1  2026-02-24     419.160004                 0.0    0.771321     1
2  2026-02-25     426.160004                 0.0    0.740775     1
3  2026-02-26     412.010010                 0.0    0.342419     0
4  2026-02-27     406.369995                 0.0    0.392937     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.915356     1
60 2026-05-19     543.960022                 NaN    0.919825     1
61 2026-05-20     564.659973                 NaN    0.677128     0
62 2026-05-21     567.880005                 NaN    0.616242     0
63 2026-05-22     576.320007                 NaN    0.425491     0

[64 rows x 5 columns]

예측값 분포:
pred
0    38
1    26
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 9
예측 1 중 실제 1 개수: 5
예측 1 기준 정확도 precision: 0.5555555555555556

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,hist_gradient_boosting,"{'max_iter': 300, 'learning_rate': 0.03, 'max_...",44,9,...,0.25,0.555556,0.147059,0.232558,0.244118,1.169609,6,4,29,5

[I 2026-05-23 21:17:54,146] Trial 156 finished with value: 0.5555555555555556 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 158/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 4}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 157}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 20
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.535520     0
1  2026-02-24     419.160004                 0.0    0.628092     1
2  2026-02-25     426.160004                 0.0    0.454908     0
3  2026-02-26     412.010010                 0.0    0.453988     0
4  2026-02-27     406.369995                 0.0    0.619837     1
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.430849     0
60 2026-05-19     543.960022                 NaN    0.649059     1
61 2026-05-20     564.659973                 NaN    0.412795     0
62 2026-05-21     567.880005                 NaN    0.563479     0
63 2026-05-22     576.320007                 NaN    0.617826     1

[64 rows x 5 columns]

예측값 분포:
pred
0    42
1    22
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 10
예측 1 중 실제 1 개수: 7
예측 1 기준 정확도 precision: 0.7

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.03, '...",44,10,...,0.318182,0.7,0.205882,0.318182,0.394118,0.814403,7,3,27,7

[I 2026-05-23 21:18:13,112] Trial 157 finished with value: 0.7 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 4}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 159/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 158}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.269206     0
1  2026-02-24     419.160004                 0.0    0.771321     1
2  2026-02-25     426.160004                 0.0    0.740775     1
3  2026-02-26     412.010010                 0.0    0.342419     0
4  2026-02-27     406.369995                 0.0    0.392937     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.915356     1
60 2026-05-19     543.960022                 NaN    0.919825     1
61 2026-05-20     564.659973                 NaN    0.677128     1
62 2026-05-21     567.880005                 NaN    0.616242     0
63 2026-05-22     576.320007                 NaN    0.425491     0

[64 rows x 5 columns]

예측값 분포:
pred
0    35
1    29
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 11
예측 1 중 실제 1 개수: 6
예측 1 기준 정확도 precision: 0.5454545454545454

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,hist_gradient_boosting,"{'max_iter': 300, 'learning_rate': 0.03, 'max_...",44,11,...,0.25,0.545455,0.176471,0.266667,0.244118,1.169609,5,5,28,6

[I 2026-05-23 21:18:31,269] Trial 158 finished with value: 0.5454545454545454 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 160/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 10, 'threshold': 0.005, 'top_n': 10, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 2}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 159}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_10d_up_0pct
target_df shape: (1533, 31)
target 분포:
target_10d_up_0pct
1    882
0    651
Name: count, dtype: int64
lagged_df shape: (1354, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1396

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1396

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1394
TOP feature count: 10
['TNX_level_lag120', 'USDKRW_ret_20d_lag3', 'DXY_ret_20d_lag120', 'SMH_vol_20d_lag40', 'OIL_ret_20d_lag120', 'TNX_diff_20d_lag5', 'GOLD_ret_20d_lag40', 'NVDA_ret_20d_lag120', 'TSM_ret_5d_lag40', 'SPY_ret_20d_lag120']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.114099,0.005156,0.000027,0.102361,0.121295,3,30,0.108944,TNX_level,120,120,-0.247079,0.247079,132
1,USDKRW_ret_20d_lag3,0.105354,0.006455,0.000042,0.094970,0.115848,3,30,0.098899,USDKRW_ret_20d,3,3,-0.314678,0.314678,249
2,DXY_ret_20d_lag120,0.097480,0.002902,0.000008,0.091990,0.102329,3,30,0.094578,DXY_ret_20d,120,120,-0.300370,0.300370,132
3,SMH_vol_20d_lag40,0.079376,0.002295,0.000005,0.075700,0.083706,3,30,0.077081,SMH_vol_20d,40,40,0.216317,0.216317,212
4,OIL_ret_20d_lag120,0.066135,0.001842,0.000003,0.063081,0.069975,3,30,0.064293,OIL_ret_20d,120,120,-0.229237,0.229237,132
5,TNX_diff_20d_lag5,0.061168,0.001872,0.000004,0.057590,0.065294,3,30,0.059296,TNX_diff_20d,5,5,0.361960,0.361960,247
6,GOLD_ret_20d_lag40,0.057597,0.001910,0.000004,0.053794,0.061701,3,30,0.055687,GOLD_ret_20d,40,40,-0.148102,0.148102,212
7,NVDA_ret_20d_lag120,0.054337,0.001519,0.000002,0.050717,0.058087,3,30,0.052818,NVDA_ret_20d,120,120,-0.253585,0.253585,132
8,TSM_ret_5d_lag40,0.053448,0.001459,0.000002,0.051298,0.056400,3,30,0.051989,TSM_ret_5d,40,40,-0.242780,0.242780,212
9,SPY_ret_20d_lag120,0.051863,0.001866,0.000003,0.047460,0.055409,3,30,0.049998,SPY_ret_20d,120,120,-0.318511,0.318511,132

============================================================
6. valid_df 생성
============================================================
top feature 수: 10
lag 생성 후 valid_df shape: (1607, 22)
원본 base_feature 제거 후 valid_df shape: (1607, 12)
최종 컬럼 수: 12
target 생성 후 valid_df shape: (1607, 14)
최종 valid_df shape: (64, 14)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 10
train_df shape: (1354, 13)
X_train shape: (1354, 10)
train target 분포:
target_10d_up_0pct
1    766
0    588
Name: count, dtype: int64
target_10d_up_0pct
1    0.565731
0    0.434269
Name: proportion, dtype: float64
valid_df shape: (64, 14)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_10d_up_0pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.865235     1
1  2026-02-24     419.160004                 0.0    0.835175     1
2  2026-02-25     426.160004                 0.0    0.784846     1
3  2026-02-26     412.010010                 0.0    0.480207     0
4  2026-02-27     406.369995                 0.0    0.413737     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.364349     0
60 2026-05-19     543.960022                 NaN    0.366927     0
61 2026-05-20     564.659973                 NaN    0.366927     0
62 2026-05-21     567.880005                 NaN    0.429827     0
63 2026-05-22     576.320007                 NaN    0.424895     0

[64 rows x 5 columns]

예측값 분포:
pred
0    50
1    14
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 54
예측 1 개수: 11
예측 1 중 실제 1 개수: 8
예측 1 기준 정확도 precision: 0.7272727272727273

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,10,0.005,1,10,10,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.05, '...",54,11,...,0.407407,0.727273,0.216216,0.333333,0.426073,0.750364,14,3,29,8

[I 2026-05-23 21:18:49,064] Trial 159 finished with value: 0.7272727272727273 and parameters: {'n_days': 10, 'threshold': 0.005, 'top_n': 10, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.05, 'gb_max_depth': 2}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 161/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'logistic', 'model_params': {'C': 10.0, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 160}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.476770     0
1  2026-02-24     419.160004                 0.0    0.471605     0
2  2026-02-25     426.160004                 0.0    0.503201     0
3  2026-02-26     412.010010                 0.0    0.561606     0
4  2026-02-27     406.369995                 0.0    0.574237     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.452571     0
60 2026-05-19     543.960022                 NaN    0.504163     0
61 2026-05-20     564.659973                 NaN    0.565166     0
62 2026-05-21     567.880005                 NaN    0.585396     0
63 2026-05-22     576.320007                 NaN    0.566557     0

[64 rows x 5 columns]

예측값 분포:
pred
0    59
1     5
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 3
예측 1 중 실제 1 개수: 3
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,logistic,"{'C': 10.0, 'class_weight': 'balanced', 'max_i...",44,3,...,0.295455,1.0,0.088235,0.162162,0.3,0.771386,10,0,31,3

[I 2026-05-23 21:19:05,839] Trial 160 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'logistic', 'logistic_C': 10.0}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:19:05,927] Trial 161 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 162/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 161}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204756_optuna_holdout_trial_0012
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 163/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 162}
====================================================================================================

[I 2026-05-23 21:19:05,960] Trial 162 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:19:05,991] Trial 163 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.75, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204756_optuna_holdout_trial_0012
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 164/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.75, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 163}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_211530_optuna_holdout_trial_0143
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 165/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.1, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 164}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 20
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.030324     0
1  2026-02-24     419.160004                 0.0    0.810977     1
2  2026-02-25     426.160004                 0.0    0.024295     0
3  2026-02-26     412.010010                 0.0    0.278987     0
4  2026-02-27     406.369995                 0.0    0.252246     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.966504     1
60 2026-05-19     543.960022                 NaN    0.871126     1
61 2026-05-20     564.659973                 NaN    0.032781     0
62 2026-05-21     567.880005                 NaN    0.070181     0
63 2026-05-22     576.320007                 NaN    0.035766     0

[64 rows x 5 columns]

예측값 분포:
pred
0    38
1    26
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 11
예측 1 중 실제 1 개수: 10
예측 1 기준 정확도 precision: 0.9090909090909091

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,20,20,hist_gradient_boosting,"{'max_iter': 300, 'learning_rate': 0.1, 'max_l...",44,11,...,0.431818,0.909091,0.294118,0.444444,0.711765,1.48115,9,1,24,10

[I 2026-05-23 21:19:25,142] Trial 164 finished with value: 0.9090909090909091 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.1, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:19:25,191] Trial 165 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 166/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 165}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_211641_optuna_holdout_trial_0148
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 167/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 500, 'learning_rate': 0.03, 'max_leaf_nodes': 31}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 166}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.428933     0
1  2026-02-24     419.160004                 0.0    0.843627     1
2  2026-02-25     426.160004                 0.0    0.759298     1
3  2026-02-26     412.010010                 0.0    0.169997     0
4  2026-02-27     406.369995                 0.0    0.189714     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.966475     1
60 2026-05-19     543.960022                 NaN    0.970868     1
61 2026-05-20     564.659973                 NaN    0.790406     1
62 2026-05-21     567.880005                 NaN    0.733327     1
63 2026-05-22     576.320007                 NaN    0.571802     0

[64 rows x 5 columns]

예측값 분포:
pred
0    37
1    27
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 9
예측 1 중 실제 1 개수: 5
예측 1 기준 정확도 precision: 0.5555555555555556

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,hist_gradient_boosting,"{'max_iter': 500, 'learning_rate': 0.03, 'max_...",44,9,...,0.25,0.555556,0.147059,0.232558,0.297059,1.193679,6,4,29,5

[I 2026-05-23 21:19:44,067] Trial 166 finished with value: 0.5555555555555556 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 500, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 31}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 168/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.75, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.01, 'max_depth': 5}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 167}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 20
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.463030     0
1  2026-02-24     419.160004                 0.0    0.562749     0
2  2026-02-25     426.160004                 0.0    0.565855     0
3  2026-02-26     412.010010                 0.0    0.570370     0
4  2026-02-27     406.369995                 0.0    0.630296     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.556302     0
60 2026-05-19     543.960022                 NaN    0.537999     0
61 2026-05-20     564.659973                 NaN    0.314920     0
62 2026-05-21     567.880005                 NaN    0.474601     0
63 2026-05-22     576.320007                 NaN    0.487182     0

[64 rows x 5 columns]

예측값 분포:
pred
0    62
1     2
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 0
예측 1 중 실제 1 개수: 0
예측 1 기준 정확도 precision: nan

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.01, '...",44,0,...,0.227273,0.0,0.0,0.0,0.385294,0.719736,10,0,34,0

[I 2026-05-23 21:20:03,270] Trial 167 finished with value: 0.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.75, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.01, 'gb_max_depth': 5}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 169/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.55, 'model_name': 'random_forest', 'model_params': {'n_estimators': 800, 'max_depth': None, 'min_samples_leaf': 10, 'max_features': 0.5, 'class_weight': 'balanced'}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 168}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: random_forest
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.589646     1
1  2026-02-24     419.160004                 0.0    0.582905     1
2  2026-02-25     426.160004                 0.0    0.557022     1
3  2026-02-26     412.010010                 0.0    0.555314     1
4  2026-02-27     406.369995                 0.0    0.546938     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.552010     1
60 2026-05-19     543.960022                 NaN    0.564429     1
61 2026-05-20     564.659973                 NaN    0.493749     0
62 2026-05-21     567.880005                 NaN    0.551909     1
63 2026-05-22     576.320007                 NaN    0.547227     0

[64 rows x 5 columns]

예측값 분포:
pred
1    32
0    32
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 17
예측 1 중 실제 1 개수: 10
예측 1 기준 정확도 precision: 0.5882352941176471

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,random_forest,"{'n_estimators': 800, 'max_depth': None, 'min_...",44,17,...,0.295455,0.588235,0.294118,0.392157,0.252941,0.755591,3,7,24,10

[I 2026-05-23 21:20:20,559] Trial 168 finished with value: 0.5882352941176471 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.55, 'model_name': 'random_forest', 'rf_n_estimators': 800, 'rf_max_depth': None, 'rf_min_samples_leaf': 10, 'rf_max_features': 0.5}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:20:20,595] Trial 169 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'logistic', 'logistic_C': 1.0}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 170/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'logistic', 'model_params': {'C': 1.0, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 169}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_210946_optuna_holdout_trial_0113
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 171/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 3, 'threshold': 0.03, 'top_n': 50, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 170}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_3d_up_3pct
target_df shape: (1540, 31)
target 분포:
target_3d_up_3pct
0    1195
1     345
Name: count, dtype: int64
lagged_df shape: (1400, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1259

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.127

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1269
TOP feature count: 27
['SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag1', 'TNX_level_lag120', 'VIX_level_lag1', 'SPY_ret_5d_lag1', 'SMH_ma5_ratio_lag1', 'SOXX_ret_5d_lag1', 'SMH_vol_20d_lag3', 'GOLD_ret_5d_lag120', 'SMH_ret_1d_lag1', 'SPY_ret_20d_lag40', 'TNX_diff_20d_lag5', 'DXY_ret_5d_lag60', 'OIL_ret_20d_lag20', 'NVDA_ret_20d_lag40', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag20', 'VIX_chg_5d_lag120', 'NVDA_ret_5d_lag1', 'DXY_ret_20d_lag5', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag40', 'TSM_ret_5d_lag1', 'OIL_ret_5d_lag120', 'SMH_volume_ratio_20d_lag120', 'USDKRW_ret_5d_lag60', 'VIX_chg_20d_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_ma20_ratio_lag1,0.056589,0.001591,2.531595e-06,0.053024,0.059396,3,30,0.054998,SMH_ma20_ratio,1,1,-0.221458,0.221458,250
1,SMH_ma60_ratio_lag1,0.052707,0.002447,5.987327e-06,0.049894,0.057618,3,30,0.050260,SMH_ma60_ratio,1,1,-0.210906,0.210906,250
2,TNX_level_lag120,0.050870,0.001302,1.695808e-06,0.048159,0.053889,3,30,0.049568,TNX_level,120,120,-0.095157,0.095157,131
3,VIX_level_lag1,0.045134,0.001281,1.639994e-06,0.042055,0.047115,3,30,0.043854,VIX_level,1,1,0.247865,0.247865,250
4,SPY_ret_5d_lag1,0.044011,0.001323,1.750608e-06,0.041346,0.046226,3,30,0.042688,SPY_ret_5d,1,1,-0.218958,0.218958,250
5,SMH_ma5_ratio_lag1,0.042944,0.001415,2.002289e-06,0.041179,0.046525,3,30,0.041529,SMH_ma5_ratio,1,1,-0.216861,0.216861,250
6,SOXX_ret_5d_lag1,0.041604,0.001194,1.425218e-06,0.039081,0.044079,3,30,0.040410,SOXX_ret_5d,1,1,-0.250730,0.250730,250
7,SMH_vol_20d_lag3,0.039820,0.001543,2.381931e-06,0.036781,0.043012,3,30,0.038277,SMH_vol_20d,3,3,0.174897,0.174897,248
8,GOLD_ret_5d_lag120,0.037840,0.000945,8.938618e-07,0.035847,0.040030,3,30,0.036894,GOLD_ret_5d,120,120,-0.241289,0.241289,131
9,SMH_ret_1d_lag1,0.036673,0.001014,1.028800e-06,0.034861,0.039198,3,30,0.035659,SMH_ret_1d,1,1,-0.122369,0.122369,250
10,SPY_ret_20d_lag40,0.036011,0.001082,1.169956e-06,0.033436,0.038535,3,30,0.034930,SPY_ret_20d,40,40,-0.196954,0.196954,211
11,TNX_diff_20d_lag5,0.036665,0.002214,4.899699e-06,0.032652,0.040637,3,30,0.034451,TNX_diff_20d,5,5,0.221646,0.221646,246
12,DXY_ret_5d_lag60,0.035643,0.001253,1.570409e-06,0.032152,0.037665,3,30,0.034390,DXY_ret_5d,60,60,0.192636,0.192636,191
13,OIL_ret_20d_lag20,0.036393,0.002864,8.205027e-06,0.033187,0.041896,3,30,0.033529,OIL_ret_20d,20,20,-0.144221,0.144221,231
14,NVDA_ret_20d_lag40,0.034605,0.001088,1.183386e-06,0.032135,0.037136,3,30,0.033517,NVDA_ret_20d,40,40,-0.144158,0.144158,211
15,GOLD_ret_20d_lag120,0.033901,0.000752,5.650846e-07,0.032428,0.035390,3,30,0.033149,GOLD_ret_20d,120,120,-0.163086,0.163086,131
16,TNX_diff_5d_lag20,0.033100,0.001087,1.182453e-06,0.031154,0.035631,3,30,0.032013,TNX_diff_5d,20,20,0.229786,0.229786,231
17,VIX_chg_5d_lag120,0.033648,0.002350,5.522816e-06,0.029115,0.038062,3,30,0.031298,VIX_chg_5d,120,120,0.188099,0.188099,131
18,NVDA_ret_5d_lag1,0.031730,0.000798,6.363294e-07,0.030435,0.033592,3,30,0.030932,NVDA_ret_5d,1,1,-0.199486,0.199486,250
19,DXY_ret_20d_lag5,0.031600,0.000716,5.126522e-07,0.030105,0.032995,3,30,0.030884,DXY_ret_20d,5,5,-0.135316,0.135316,246
20,USDKRW_ret_20d_lag40,0.031082,0.000722,5.215775e-07,0.029340,0.032210,3,30,0.030360,USDKRW_ret_20d,40,40,0.160744,0.160744,211
21,TSM_ret_20d_lag40,0.031050,0.000916,8.396264e-07,0.029719,0.032574,3,30,0.030133,TSM_ret_20d,40,40,-0.186369,0.186369,211
22,TSM_ret_5d_lag1,0.031246,0.001439,2.069516e-06,0.028803,0.033298,3,30,0.029808,TSM_ret_5d,1,1,-0.209219,0.209219,250
23,OIL_ret_5d_lag120,0.030555,0.001035,1.070729e-06,0.028739,0.032885,3,30,0.029521,OIL_ret_5d,120,120,-0.146418,0.146418,131
24,SMH_volume_ratio_20d_lag120,0.028392,0.001148,1.318036e-06,0.026233,0.030658,3,30,0.027244,SMH_volume_ratio_20d,120,120,0.125977,0.125977,131
25,USDKRW_ret_5d_lag60,0.027303,0.000780,6.077149e-07,0.025851,0.028928,3,30,0.026523,USDKRW_ret_5d,60,60,0.200168,0.200168,191
26,VIX_chg_20d_lag40,0.026917,0.000599,3.591069e-07,0.025750,0.027971,3,30,0.026318,VIX_chg_20d,40,40,0.198251,0.198251,211

============================================================
6. valid_df 생성
============================================================
top feature 수: 27
lag 생성 후 valid_df shape: (1607, 56)
원본 base_feature 제거 후 valid_df shape: (1607, 29)
최종 컬럼 수: 29
target 생성 후 valid_df shape: (1607, 31)
최종 valid_df shape: (64, 31)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 27
train_df shape: (1400, 30)
X_train shape: (1400, 27)
train target 분포:
target_3d_up_3pct
0    1087
1     313
Name: count, dtype: int64
target_3d_up_3pct
0    0.776429
1    0.223571
Name: proportion, dtype: float64
valid_df shape: (64, 31)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_3d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                0.0    0.084982     0
1  2026-02-24     419.160004                0.0    0.102617     0
2  2026-02-25     426.160004                0.0    0.094581     0
3  2026-02-26     412.010010                0.0    0.112558     0
4  2026-02-27     406.369995                0.0    0.113507     0
..        ...            ...                ...         ...   ...
59 2026-05-18     546.159973                1.0    0.114682     0
60 2026-05-19     543.960022                1.0    0.109441     0
61 2026-05-20     564.659973                NaN    0.089718     0
62 2026-05-21     567.880005                NaN    0.088498     0
63 2026-05-22     576.320007                NaN    0.180795     0

[64 rows x 5 columns]

예측값 분포:
pred
0    64
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 61
예측 1 개수: 0
예측 1 중 실제 1 개수: 0
예측 1 기준 정확도 precision: nan

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,3,0.03,1,50,27,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.03, '...",61,0,...,0.622951,0.0,0.0,0.0,0.471396,0.916371,38,0,23,0

[I 2026-05-23 21:20:39,842] Trial 170 finished with value: 0.0 and parameters: {'n_days': 3, 'threshold': 0.03, 'top_n': 50, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:20:39,871] Trial 171 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 500, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 31}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:20:39,900] Trial 172 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 500, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 31}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 172/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 500, 'learning_rate': 0.03, 'max_leaf_nodes': 31}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 171}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_205950_optuna_holdout_trial_0065
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 173/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 500, 'learning_rate': 0.03, 'max_leaf_nodes': 31}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 172}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_205950_optuna_holdout_trial_0065
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 174/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 100, 'learning_rate': 0.03, 'max_leaf_nodes': 31}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 173}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 20
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.353303     0
1  2026-02-24     419.160004                 0.0    0.530240     0
2  2026-02-25     426.160004                 0.0    0.505858     0
3  2026-02-26     412.010010                 0.0    0.497778     0
4  2026-02-27     406.369995                 0.0    0.654425     1
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.722982     1
60 2026-05-19     543.960022                 NaN    0.627989     0
61 2026-05-20     564.659973                 NaN    0.342577     0
62 2026-05-21     567.880005                 NaN    0.338378     0
63 2026-05-22     576.320007                 NaN    0.292596     0

[64 rows x 5 columns]

예측값 분포:
pred
0    43
1    21
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 7
예측 1 중 실제 1 개수: 6
예측 1 기준 정확도 precision: 0.8571428571428571

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,20,20,hist_gradient_boosting,"{'max_iter': 100, 'learning_rate': 0.03, 'max_...",44,7,...,0.340909,0.857143,0.176471,0.292683,0.402941,0.816447,9,1,28,6

[I 2026-05-23 21:20:57,167] Trial 173 finished with value: 0.8571428571428571 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 100, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 31}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:20:57,217] Trial 174 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 500, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 31}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 175/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 500, 'learning_rate': 0.03, 'max_leaf_nodes': 31}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 174}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_205950_optuna_holdout_trial_0065
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 176/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.015, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 500, 'learning_rate': 0.05, 'max_leaf_nodes': 15}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 175}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_1pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_1pct
1    875
0    648
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1282

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1291

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1292
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'VIX_chg_20d_lag120', 'NVDA_ret_20d_lag1', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'SMH_ma20_ratio_lag1', 'USDKRW_ret_20d_lag40', 'DXY_ret_5d_lag120', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'VIX_level_lag20', 'VIX_chg_5d_lag120', 'OIL_ret_20d_lag120', 'SMH_ma60_ratio_lag1', 'TNX_diff_5d_lag5', 'GOLD_ret_20d_lag120', 'OIL_ret_5d_lag10', 'GOLD_ret_5d_lag60', 'SPY_ret_5d_lag120']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118484,0.002821,7.957216e-06,0.109722,0.124056,3,30,0.115663,SMH_vol_20d,120,120,-0.303085,0.303085,132
1,TNX_level_lag20,0.098508,0.003546,1.257577e-05,0.091406,0.103231,3,30,0.094962,TNX_level,20,20,-0.312171,0.312171,232
2,VIX_chg_20d_lag120,0.084307,0.004767,2.272657e-05,0.074815,0.090386,3,30,0.079540,VIX_chg_20d,120,120,0.361218,0.361218,132
3,NVDA_ret_20d_lag1,0.077011,0.002656,7.056867e-06,0.073438,0.082286,3,30,0.074355,NVDA_ret_20d,1,1,0.255267,0.255267,251
4,DXY_ret_20d_lag60,0.073972,0.003501,1.226018e-05,0.065067,0.079207,3,30,0.070471,DXY_ret_20d,60,60,-0.224007,0.224007,192
5,TNX_diff_20d_lag1,0.067782,0.002068,4.275689e-06,0.063536,0.070710,3,30,0.065714,TNX_diff_20d,1,1,0.409580,0.409580,251
6,SMH_ma20_ratio_lag1,0.064028,0.003588,1.287606e-05,0.057455,0.069127,3,30,0.060440,SMH_ma20_ratio,1,1,0.278312,0.278312,251
7,USDKRW_ret_20d_lag40,0.054209,0.001347,1.813178e-06,0.051963,0.056946,3,30,0.052862,USDKRW_ret_20d,40,40,0.344971,0.344971,212
8,DXY_ret_5d_lag120,0.053646,0.002349,5.516362e-06,0.049564,0.057537,3,30,0.051297,DXY_ret_5d,120,120,-0.258618,0.258618,132
9,SPY_ret_20d_lag120,0.053166,0.002152,4.629870e-06,0.049174,0.057806,3,30,0.051015,SPY_ret_20d,120,120,-0.257846,0.257846,132
10,TSM_ret_20d_lag1,0.051027,0.002671,7.136912e-06,0.045914,0.054292,3,30,0.048356,TSM_ret_20d,1,1,0.323766,0.323766,251
11,VIX_level_lag20,0.051332,0.003401,1.156368e-05,0.046068,0.056499,3,30,0.047931,VIX_level,20,20,0.256886,0.256886,232
12,VIX_chg_5d_lag120,0.050033,0.002465,6.074460e-06,0.045693,0.053445,3,30,0.047568,VIX_chg_5d,120,120,0.140989,0.140989,132
13,OIL_ret_20d_lag120,0.046951,0.001639,2.685367e-06,0.043890,0.051856,3,30,0.045313,OIL_ret_20d,120,120,0.317093,0.317093,132
14,SMH_ma60_ratio_lag1,0.045240,0.000929,8.634352e-07,0.043842,0.047279,3,30,0.044311,SMH_ma60_ratio,1,1,0.195063,0.195063,251
15,TNX_diff_5d_lag5,0.044214,0.002358,5.561184e-06,0.039888,0.047489,3,30,0.041856,TNX_diff_5d,5,5,0.211260,0.211260,247
16,GOLD_ret_20d_lag120,0.038123,0.001246,1.553398e-06,0.035914,0.041085,3,30,0.036877,GOLD_ret_20d,120,120,-0.347004,0.347004,132
17,OIL_ret_5d_lag10,0.030618,0.000852,7.251870e-07,0.029380,0.032145,3,30,0.029766,OIL_ret_5d,10,10,0.189850,0.189850,242
18,GOLD_ret_5d_lag60,0.029241,0.000940,8.827980e-07,0.027493,0.030948,3,30,0.028301,GOLD_ret_5d,60,60,0.194501,0.194501,192
19,SPY_ret_5d_lag120,0.028214,0.000910,8.287835e-07,0.026523,0.029787,3,30,0.027304,SPY_ret_5d,120,120,-0.236798,0.236798,132

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_1pct
1    773
0    610
Name: count, dtype: int64
target_20d_up_1pct
1    0.55893
0    0.44107
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_1pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.610516     1
1  2026-02-24     419.160004                 0.0    0.772384     1
2  2026-02-25     426.160004                 0.0    0.388901     0
3  2026-02-26     412.010010                 0.0    0.558669     0
4  2026-02-27     406.369995                 0.0    0.398497     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.879555     1
60 2026-05-19     543.960022                 NaN    0.894411     1
61 2026-05-20     564.659973                 NaN    0.697443     1
62 2026-05-21     567.880005                 NaN    0.898202     1
63 2026-05-22     576.320007                 NaN    0.940306     1

[64 rows x 5 columns]

예측값 분포:
pred
1    39
0    25
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 19
예측 1 중 실제 1 개수: 15
예측 1 기준 정확도 precision: 0.7894736842105263

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.015,1,20,20,hist_gradient_boosting,"{'max_iter': 500, 'learning_rate': 0.05, 'max_...",44,19,...,0.477273,0.789474,0.441176,0.566038,0.529412,0.777189,6,4,19,15

[I 2026-05-23 21:21:15,769] Trial 175 finished with value: 0.7894736842105263 and parameters: {'n_days': 20, 'threshold': 0.015, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 500, 'hgb_learning_rate': 0.05, 'hgb_max_leaf_nodes': 15}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:21:15,819] Trial 176 finished with value: 0.3333333333333333 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'gb_n_estimators': 100, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 177/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 100, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 176}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_205540_optuna_holdout_trial_0044
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 178/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 10, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.01, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 177}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_10d_up_3pct
target_df shape: (1533, 31)
target 분포:
target_10d_up_3pct
0    907
1    626
Name: count, dtype: int64
lagged_df shape: (1393, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1431

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1425

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1433
TOP feature count: 20
['USDKRW_ret_20d_lag1', 'OIL_ret_20d_lag40', 'TNX_level_lag120', 'DXY_ret_20d_lag120', 'SMH_vol_20d_lag40', 'VIX_level_lag1', 'TNX_diff_20d_lag5', 'TSM_ret_20d_lag40', 'SMH_ma20_ratio_lag40', 'SMH_ma60_ratio_lag40', 'SMH_volume_ratio_20d_lag1', 'NVDA_ret_20d_lag40', 'SPY_ret_20d_lag40', 'VIX_chg_5d_lag60', 'VIX_chg_20d_lag40', 'GOLD_ret_20d_lag1', 'USDKRW_ret_5d_lag3', 'DXY_ret_5d_lag5', 'SOXX_ret_5d_lag40', 'TSM_ret_5d_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,USDKRW_ret_20d_lag1,0.126034,0.002997,8.980695e-06,0.119453,0.133261,3,30,0.123037,USDKRW_ret_20d,1,1,-0.408214,0.408214,251
1,OIL_ret_20d_lag40,0.096463,0.002678,7.170844e-06,0.091112,0.102565,3,30,0.093785,OIL_ret_20d,40,40,-0.318626,0.318626,212
2,TNX_level_lag120,0.080627,0.002211,4.888913e-06,0.074639,0.086368,3,30,0.078416,TNX_level,120,120,-0.195924,0.195924,132
3,DXY_ret_20d_lag120,0.073622,0.001373,1.884736e-06,0.070474,0.075453,3,30,0.072249,DXY_ret_20d,120,120,-0.293154,0.293154,132
4,SMH_vol_20d_lag40,0.063920,0.001438,2.066961e-06,0.061510,0.067246,3,30,0.062482,SMH_vol_20d,40,40,0.281937,0.281937,212
5,VIX_level_lag1,0.059403,0.001746,3.047977e-06,0.056041,0.063472,3,30,0.057657,VIX_level,1,1,0.240225,0.240225,251
6,TNX_diff_20d_lag5,0.059302,0.002218,4.918486e-06,0.054268,0.064710,3,30,0.057085,TNX_diff_20d,5,5,0.307873,0.307873,247
7,TSM_ret_20d_lag40,0.055242,0.001483,2.198098e-06,0.052429,0.058885,3,30,0.053759,TSM_ret_20d,40,40,-0.349006,0.349006,212
8,SMH_ma20_ratio_lag40,0.054793,0.001213,1.471149e-06,0.052111,0.057220,3,30,0.053580,SMH_ma20_ratio,40,40,-0.288530,0.288530,212
9,SMH_ma60_ratio_lag40,0.053386,0.001023,1.046921e-06,0.051840,0.055668,3,30,0.052363,SMH_ma60_ratio,40,40,-0.297396,0.297396,212
10,SMH_volume_ratio_20d_lag1,0.051650,0.002090,4.367474e-06,0.048032,0.055660,3,30,0.049560,SMH_volume_ratio_20d,1,1,0.186136,0.186136,251
11,NVDA_ret_20d_lag40,0.047124,0.001591,2.531745e-06,0.043689,0.049773,3,30,0.045533,NVDA_ret_20d,40,40,-0.192054,0.192054,212
12,SPY_ret_20d_lag40,0.049969,0.004929,2.429532e-05,0.042242,0.057221,3,30,0.045040,SPY_ret_20d,40,40,-0.270977,0.270977,212
13,VIX_chg_5d_lag60,0.043663,0.001981,3.925745e-06,0.039731,0.047597,3,30,0.041682,VIX_chg_5d,60,60,0.176557,0.176557,192
14,VIX_chg_20d_lag40,0.042420,0.001552,2.410066e-06,0.039666,0.045644,3,30,0.040867,VIX_chg_20d,40,40,0.240142,0.240142,212
15,GOLD_ret_20d_lag1,0.039796,0.000720,5.186415e-07,0.038508,0.041410,3,30,0.039076,GOLD_ret_20d,1,1,0.150955,0.150955,251
16,USDKRW_ret_5d_lag3,0.037802,0.001225,1.500943e-06,0.035512,0.039620,3,30,0.036577,USDKRW_ret_5d,3,3,-0.270483,0.270483,249
17,DXY_ret_5d_lag5,0.036078,0.000914,8.350636e-07,0.034211,0.037683,3,30,0.035164,DXY_ret_5d,5,5,-0.186237,0.186237,247
18,SOXX_ret_5d_lag40,0.034375,0.001310,1.716438e-06,0.032454,0.036978,3,30,0.033064,SOXX_ret_5d,40,40,-0.243564,0.243564,212
19,TSM_ret_5d_lag40,0.034537,0.001604,2.573093e-06,0.031413,0.037121,3,30,0.032933,TSM_ret_5d,40,40,-0.332453,0.332453,212

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1393, 23)
X_train shape: (1393, 20)
train target 분포:
target_10d_up_3pct
0    834
1    559
Name: count, dtype: int64
target_10d_up_3pct
0    0.598708
1    0.401292
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_10d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.188697     0
1  2026-02-24     419.160004                 0.0    0.379601     0
2  2026-02-25     426.160004                 0.0    0.454192     0
3  2026-02-26     412.010010                 0.0    0.152255     0
4  2026-02-27     406.369995                 0.0    0.414735     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.171296     0
60 2026-05-19     543.960022                 NaN    0.324854     0
61 2026-05-20     564.659973                 NaN    0.546061     0
62 2026-05-21     567.880005                 NaN    0.452638     0
63 2026-05-22     576.320007                 NaN    0.159943     0

[64 rows x 5 columns]

예측값 분포:
pred
0    55
1     9
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 54
예측 1 개수: 9
예측 1 중 실제 1 개수: 5
예측 1 기준 정확도 precision: 0.5555555555555556

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,10,0.03,1,20,20,hist_gradient_boosting,"{'max_iter': 300, 'learning_rate': 0.01, 'max_...",54,9,...,0.444444,0.555556,0.16129,0.25,0.423562,0.916627,19,4,26,5

[I 2026-05-23 21:21:34,678] Trial 177 finished with value: 0.5555555555555556 and parameters: {'n_days': 10, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.01, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 179/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.01, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'logistic', 'model_params': {'C': 0.1, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 178}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_1pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_1pct
1    917
0    606
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1301

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1302

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1305
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'NVDA_ret_5d_lag120', 'DXY_ret_5d_lag120', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SMH_ma60_ratio_lag1', 'OIL_ret_20d_lag120', 'VIX_chg_5d_lag120', 'SPY_ret_20d_lag1', 'TNX_diff_5d_lag5', 'GOLD_ret_20d_lag120', 'SMH_ma20_ratio_lag120', 'TSM_ret_5d_lag120', 'GOLD_ret_5d_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.113199,0.003130,9.798652e-06,0.105366,0.117758,3,30,0.110069,SMH_vol_20d,120,120,-0.305565,0.305565,132
1,TNX_level_lag20,0.111395,0.001966,3.863856e-06,0.107542,0.114334,3,30,0.109430,TNX_level,20,20,-0.282349,0.282349,232
2,NVDA_ret_20d_lag1,0.080573,0.003084,9.508619e-06,0.075624,0.086273,3,30,0.077490,NVDA_ret_20d,1,1,0.282168,0.282168,251
3,VIX_chg_20d_lag120,0.077843,0.001462,2.138529e-06,0.074670,0.080400,3,30,0.076381,VIX_chg_20d,120,120,0.371232,0.371232,132
4,DXY_ret_20d_lag60,0.073491,0.002177,4.737914e-06,0.068070,0.077471,3,30,0.071314,DXY_ret_20d,60,60,-0.256904,0.256904,192
5,TNX_diff_20d_lag1,0.066654,0.002093,4.380060e-06,0.062034,0.070705,3,30,0.064561,TNX_diff_20d,1,1,0.416622,0.416622,251
6,NVDA_ret_5d_lag120,0.056072,0.001459,2.128896e-06,0.052971,0.058355,3,30,0.054613,NVDA_ret_5d,120,120,-0.233880,0.233880,132
7,DXY_ret_5d_lag120,0.053295,0.001976,3.904778e-06,0.049647,0.058129,3,30,0.051319,DXY_ret_5d,120,120,-0.267096,0.267096,132
8,VIX_level_lag20,0.051839,0.001035,1.070311e-06,0.049900,0.053607,3,30,0.050805,VIX_level,20,20,0.239784,0.239784,232
9,USDKRW_ret_20d_lag40,0.051299,0.001162,1.350872e-06,0.049044,0.053384,3,30,0.050136,USDKRW_ret_20d,40,40,0.281470,0.281470,212
10,TSM_ret_20d_lag1,0.050516,0.002066,4.268228e-06,0.047785,0.054069,3,30,0.048450,TSM_ret_20d,1,1,0.339692,0.339692,251
11,SMH_ma60_ratio_lag1,0.047034,0.001847,3.412431e-06,0.043919,0.049834,3,30,0.045187,SMH_ma60_ratio,1,1,0.226498,0.226498,251
12,OIL_ret_20d_lag120,0.044614,0.001553,2.410659e-06,0.041020,0.048293,3,30,0.043061,OIL_ret_20d,120,120,0.291387,0.291387,132
13,VIX_chg_5d_lag120,0.042947,0.001208,1.459362e-06,0.040616,0.045759,3,30,0.041739,VIX_chg_5d,120,120,0.143824,0.143824,132
14,SPY_ret_20d_lag1,0.043100,0.001912,3.657161e-06,0.039473,0.046173,3,30,0.041188,SPY_ret_20d,1,1,0.273031,0.273031,251
15,TNX_diff_5d_lag5,0.041964,0.001642,2.694547e-06,0.039434,0.045450,3,30,0.040323,TNX_diff_5d,5,5,0.182059,0.182059,247
16,GOLD_ret_20d_lag120,0.037065,0.001167,1.361693e-06,0.034635,0.040013,3,30,0.035898,GOLD_ret_20d,120,120,-0.306548,0.306548,132
17,SMH_ma20_ratio_lag120,0.034339,0.000618,3.813267e-07,0.033254,0.035764,3,30,0.033721,SMH_ma20_ratio,120,120,-0.303183,0.303183,132
18,TSM_ret_5d_lag120,0.034178,0.001041,1.084444e-06,0.032365,0.036477,3,30,0.033136,TSM_ret_5d,120,120,-0.251775,0.251775,132
19,GOLD_ret_5d_lag40,0.031021,0.001323,1.750672e-06,0.028289,0.032956,3,30,0.029698,GOLD_ret_5d,40,40,-0.185968,0.185968,212

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_1pct
1    815
0    568
Name: count, dtype: int64
target_20d_up_1pct
1    0.589299
0    0.410701
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_1pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.515298     0
1  2026-02-24     419.160004                 0.0    0.509042     0
2  2026-02-25     426.160004                 0.0    0.566667     0
3  2026-02-26     412.010010                 0.0    0.573995     0
4  2026-02-27     406.369995                 0.0    0.681503     1
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.475428     0
60 2026-05-19     543.960022                 NaN    0.525211     0
61 2026-05-20     564.659973                 NaN    0.566899     0
62 2026-05-21     567.880005                 NaN    0.658215     1
63 2026-05-22     576.320007                 NaN    0.687232     1

[64 rows x 5 columns]

예측값 분포:
pred
0    49
1    15
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 6
예측 1 중 실제 1 개수: 1
예측 1 기준 정확도 precision: 0.16666666666666666

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.01,1,20,20,logistic,"{'C': 0.1, 'class_weight': 'balanced', 'max_it...",44,6,...,0.113636,0.166667,0.028571,0.04878,0.250794,0.702161,4,5,34,1

[I 2026-05-23 21:21:51,946] Trial 178 finished with value: 0.16666666666666666 and parameters: {'n_days': 20, 'threshold': 0.01, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'logistic', 'logistic_C': 0.1}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:21:51,985] Trial 179 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 180/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 179}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_205932_optuna_holdout_trial_0060
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 181/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 5, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 180}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_5d_up_3pct
target_df shape: (1538, 31)
target 분포:
target_5d_up_3pct
0    1051
1     487
Name: count, dtype: int64
lagged_df shape: (1398, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1462

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1467

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1461
TOP feature count: 20
['SMH_ma60_ratio_lag1', 'SMH_vol_20d_lag60', 'TNX_level_lag1', 'GOLD_ret_5d_lag120', 'VIX_level_lag1', 'VIX_chg_20d_lag40', 'OIL_ret_20d_lag60', 'TNX_diff_5d_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag40', 'DXY_ret_20d_lag5', 'USDKRW_ret_20d_lag40', 'USDKRW_ret_5d_lag1', 'GOLD_ret_20d_lag1', 'DXY_ret_5d_lag120', 'TNX_diff_20d_lag5', 'SMH_volume_ratio_20d_lag20', 'SMH_ma20_ratio_lag40', 'OIL_ret_5d_lag60', 'NVDA_ret_20d_lag120']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_ma60_ratio_lag1,0.078441,0.001863,3.470473e-06,0.074815,0.082776,3,30,0.076578,SMH_ma60_ratio,1,1,-0.172629,0.172629,251
1,SMH_vol_20d_lag60,0.069105,0.001919,3.684021e-06,0.065530,0.073300,3,30,0.067185,SMH_vol_20d,60,60,-0.189027,0.189027,192
2,TNX_level_lag1,0.069129,0.002486,6.181890e-06,0.063543,0.073483,3,30,0.066643,TNX_level,1,1,-0.191147,0.191147,251
3,GOLD_ret_5d_lag120,0.060355,0.002163,4.676538e-06,0.055174,0.064143,3,30,0.058193,GOLD_ret_5d,120,120,-0.218877,0.218877,132
4,VIX_level_lag1,0.059673,0.002784,7.752705e-06,0.055123,0.064462,3,30,0.056889,VIX_level,1,1,0.153605,0.153605,251
5,VIX_chg_20d_lag40,0.056407,0.001996,3.983510e-06,0.052414,0.060620,3,30,0.054411,VIX_chg_20d,40,40,0.225283,0.225283,212
6,OIL_ret_20d_lag60,0.053212,0.002001,4.002755e-06,0.049749,0.057240,3,30,0.051212,OIL_ret_20d,60,60,0.237427,0.237427,192
7,TNX_diff_5d_lag20,0.053372,0.002314,5.355884e-06,0.048577,0.056207,3,30,0.051058,TNX_diff_5d,20,20,0.185217,0.185217,232
8,SPY_ret_20d_lag120,0.048811,0.001230,1.513431e-06,0.045170,0.051545,3,30,0.047581,SPY_ret_20d,120,120,-0.195151,0.195151,132
9,TSM_ret_20d_lag40,0.049182,0.002547,6.484842e-06,0.045876,0.055137,3,30,0.046635,TSM_ret_20d,40,40,-0.186887,0.186887,212
10,DXY_ret_20d_lag5,0.044759,0.001859,3.455597e-06,0.040812,0.048252,3,30,0.042900,DXY_ret_20d,5,5,-0.123856,0.123856,247
11,USDKRW_ret_20d_lag40,0.044490,0.001832,3.357242e-06,0.041625,0.048470,3,30,0.042657,USDKRW_ret_20d,40,40,0.204293,0.204293,212
12,USDKRW_ret_5d_lag1,0.042260,0.001278,1.633171e-06,0.039336,0.045023,3,30,0.040982,USDKRW_ret_5d,1,1,-0.135928,0.135928,251
13,GOLD_ret_20d_lag1,0.039152,0.002092,4.374883e-06,0.035630,0.042243,3,30,0.037061,GOLD_ret_20d,1,1,0.185988,0.185988,251
14,DXY_ret_5d_lag120,0.037692,0.000937,8.787204e-07,0.035442,0.040194,3,30,0.036755,DXY_ret_5d,120,120,0.201244,0.201244,132
15,TNX_diff_20d_lag5,0.038099,0.001366,1.866021e-06,0.035694,0.040829,3,30,0.036733,TNX_diff_20d,5,5,0.197432,0.197432,247
16,SMH_volume_ratio_20d_lag20,0.037433,0.000858,7.356760e-07,0.035823,0.038871,3,30,0.036576,SMH_volume_ratio_20d,20,20,-0.106779,0.106779,232
17,SMH_ma20_ratio_lag40,0.036965,0.000649,4.216770e-07,0.035800,0.038710,3,30,0.036315,SMH_ma20_ratio,40,40,-0.224204,0.224204,212
18,OIL_ret_5d_lag60,0.035339,0.000720,5.182253e-07,0.033657,0.036754,3,30,0.034619,OIL_ret_5d,60,60,0.222858,0.222858,192
19,NVDA_ret_20d_lag120,0.035294,0.000913,8.331741e-07,0.033754,0.037211,3,30,0.034381,NVDA_ret_20d,120,120,-0.135504,0.135504,132

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1398, 23)
X_train shape: (1398, 20)
train target 분포:
target_5d_up_3pct
0    958
1    440
Name: count, dtype: int64
target_5d_up_3pct
0    0.685265
1    0.314735
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_5d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                0.0    0.041705     0
1  2026-02-24     419.160004                0.0    0.054555     0
2  2026-02-25     426.160004                0.0    0.134087     0
3  2026-02-26     412.010010                0.0    0.017115     0
4  2026-02-27     406.369995                0.0    0.047238     0
..        ...            ...                ...         ...   ...
59 2026-05-18     546.159973                NaN    0.158313     0
60 2026-05-19     543.960022                NaN    0.101048     0
61 2026-05-20     564.659973                NaN    0.027293     0
62 2026-05-21     567.880005                NaN    0.047203     0
63 2026-05-22     576.320007                NaN    0.042272     0

[64 rows x 5 columns]

예측값 분포:
pred
0    61
1     3
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 59
예측 1 개수: 3
예측 1 중 실제 1 개수: 1
예측 1 기준 정확도 precision: 0.3333333333333333

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,5,0.03,1,20,20,hist_gradient_boosting,"{'max_iter': 300, 'learning_rate': 0.03, 'max_...",59,3,...,0.508475,0.333333,0.035714,0.064516,0.434332,1.409431,29,2,27,1

[I 2026-05-23 21:22:10,592] Trial 180 finished with value: 0.3333333333333333 and parameters: {'n_days': 5, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:22:10,643] Trial 181 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 182/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 181}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204756_optuna_holdout_trial_0012
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 183/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 182}
====================================================================================================

[I 2026-05-23 21:22:10,694] Trial 182 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:22:10,758] Trial 183 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.75, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204756_optuna_holdout_trial_0012
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 184/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.75, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 183}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_211530_optuna_holdout_trial_0143
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 185/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 30, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 184}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 27
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1', 'TNX_diff_5d_lag5', 'SPY_ret_5d_lag120', 'NVDA_ret_5d_lag60', 'SOXX_ret_5d_lag120', 'SMH_volume_ratio_20d_lag40', 'SMH_ma5_ratio_lag60', 'SMH_ret_1d_lag60']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251
20,TNX_diff_5d_lag5,0.028148,0.001107,1.226237e-06,0.026030,0.029843,3,30,0.027041,TNX_diff_5d,5,5,0.205918,0.205918,247
21,SPY_ret_5d_lag120,0.027266,0.000982,9.634165e-07,0.025657,0.029503,3,30,0.026284,SPY_ret_5d,120,120,-0.226060,0.226060,132
22,NVDA_ret_5d_lag60,0.026746,0.001502,2.255625e-06,0.024752,0.029620,3,30,0.025244,NVDA_ret_5d,60,60,-0.230714,0.230714,192
23,SOXX_ret_5d_lag120,0.025377,0.000772,5.958999e-07,0.023624,0.026787,3,30,0.024605,SOXX_ret_5d,120,120,-0.180724,0.180724,132
24,SMH_volume_ratio_20d_lag40,0.023451,0.000495,2.454801e-07,0.022375,0.024293,3,30,0.022956,SMH_volume_ratio_20d,40,40,-0.175235,0.175235,212
25,SMH_ma5_ratio_lag60,0.020131,0.000685,4.688208e-07,0.018742,0.021058,3,30,0.019447,SMH_ma5_ratio,60,60,-0.179975,0.179975,192
26,SMH_ret_1d_lag60,0.015072,0.000675,4.562163e-07,0.013999,0.016328,3,30,0.014397,SMH_ret_1d,60,60,-0.127110,0.127110,192

============================================================
6. valid_df 생성
============================================================
top feature 수: 27
lag 생성 후 valid_df shape: (1607, 56)
원본 base_feature 제거 후 valid_df shape: (1607, 29)
최종 컬럼 수: 29
target 생성 후 valid_df shape: (1607, 31)
최종 valid_df shape: (64, 31)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 27
train_df shape: (1383, 30)
X_train shape: (1383, 27)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 31)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.302219     0
1  2026-02-24     419.160004                 0.0    0.468794     0
2  2026-02-25     426.160004                 0.0    0.464843     0
3  2026-02-26     412.010010                 0.0    0.312408     0
4  2026-02-27     406.369995                 0.0    0.755833     1
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.671110     1
60 2026-05-19     543.960022                 NaN    0.936996     1
61 2026-05-20     564.659973                 NaN    0.393600     0
62 2026-05-21     567.880005                 NaN    0.279917     0
63 2026-05-22     576.320007                 NaN    0.425673     0

[64 rows x 5 columns]

예측값 분포:
pred
0    37
1    27
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 12
예측 1 중 실제 1 개수: 10
예측 1 기준 정확도 precision: 0.8333333333333334

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,30,27,hist_gradient_boosting,"{'max_iter': 300, 'learning_rate': 0.03, 'max_...",44,12,...,0.409091,0.833333,0.294118,0.434783,0.567647,0.907753,8,2,24,10

[I 2026-05-23 21:22:29,119] Trial 184 finished with value: 0.8333333333333334 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 30, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 186/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 500, 'learning_rate': 0.03, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 185}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.530376     0
1  2026-02-24     419.160004                 0.0    0.703141     1
2  2026-02-25     426.160004                 0.0    0.563778     0
3  2026-02-26     412.010010                 0.0    0.428116     0
4  2026-02-27     406.369995                 0.0    0.531936     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.647297     0
60 2026-05-19     543.960022                 NaN    0.855619     1
61 2026-05-20     564.659973                 NaN    0.503012     0
62 2026-05-21     567.880005                 NaN    0.380792     0
63 2026-05-22     576.320007                 NaN    0.475769     0

[64 rows x 5 columns]

예측값 분포:
pred
0    43
1    21
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 7
예측 1 중 실제 1 개수: 6
예측 1 기준 정확도 precision: 0.8571428571428571

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,gradient_boosting,"{'n_estimators': 500, 'learning_rate': 0.03, '...",44,7,...,0.340909,0.857143,0.176471,0.292683,0.373529,0.797501,9,1,28,6

[I 2026-05-23 21:22:48,148] Trial 185 finished with value: 0.8571428571428571 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'gb_n_estimators': 500, 'gb_learning_rate': 0.03, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:22:48,179] Trial 186 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:22:48,208] Trial 187 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'logistic', 'logistic_C': 1.0}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 187/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 186}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204756_optuna_holdout_trial_0012
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 188/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'logistic', 'model_params': {'C': 1.0, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 187}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_204639_optuna_holdout_trial_0007
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 189/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 5}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 188}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 20
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.321964     0
1  2026-02-24     419.160004                 0.0    0.781868     1
2  2026-02-25     426.160004                 0.0    0.489146     0
3  2026-02-26     412.010010                 0.0    0.409121     0
4  2026-02-27     406.369995                 0.0    0.298769     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.092745     0
60 2026-05-19     543.960022                 NaN    0.277575     0
61 2026-05-20     564.659973                 NaN    0.045452     0
62 2026-05-21     567.880005                 NaN    0.084452     0
63 2026-05-22     576.320007                 NaN    0.038562     0

[64 rows x 5 columns]

예측값 분포:
pred
0    44
1    20
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 8
예측 1 중 실제 1 개수: 7
예측 1 기준 정확도 precision: 0.875

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.1, 'm...",44,8,...,0.363636,0.875,0.205882,0.333333,0.597059,0.938844,9,1,27,7

[I 2026-05-23 21:23:07,220] Trial 188 finished with value: 0.875 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.1, 'gb_max_depth': 5}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:23:07,250] Trial 189 finished with value: 0.5454545454545454 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 190/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 189}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_211831_optuna_holdout_trial_0158
기존 test_precision: 0.5454545454545454

====================================================================================================
OPTUNA HOLDOUT TRIAL 191/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.005, 'top_n': 10, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.01, 'max_depth': 3}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 190}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_0pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_0pct
1    954
0    569
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1268

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1266

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1268
TOP feature count: 10
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'NVDA_ret_20d_lag3', 'TNX_diff_20d_lag1', 'USDKRW_ret_20d_lag40', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'TSM_ret_20d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.121135,0.003648,0.000013,0.109618,0.129014,3,30,0.117487,SMH_vol_20d,120,120,-0.311759,0.311759,132
1,TNX_level_lag20,0.114853,0.004163,0.000017,0.107622,0.122139,3,30,0.110690,TNX_level,20,20,-0.293715,0.293715,232
2,VIX_chg_20d_lag120,0.075229,0.001942,0.000004,0.071615,0.078600,3,30,0.073287,VIX_chg_20d,120,120,0.412213,0.412213,132
3,DXY_ret_20d_lag60,0.074905,0.003362,0.000011,0.069638,0.081821,3,30,0.071543,DXY_ret_20d,60,60,-0.259348,0.259348,192
4,NVDA_ret_20d_lag3,0.073374,0.002196,0.000005,0.070062,0.078038,3,30,0.071178,NVDA_ret_20d,3,3,0.322984,0.322984,249
5,TNX_diff_20d_lag1,0.063939,0.001889,0.000004,0.060603,0.067850,3,30,0.062050,TNX_diff_20d,1,1,0.412756,0.412756,251
6,USDKRW_ret_20d_lag40,0.055286,0.001816,0.000003,0.051478,0.058858,3,30,0.053470,USDKRW_ret_20d,40,40,0.237516,0.237516,212
7,VIX_level_lag20,0.053933,0.001508,0.000002,0.050630,0.056676,3,30,0.052424,VIX_level,20,20,0.211435,0.211435,232
8,DXY_ret_5d_lag120,0.053468,0.001693,0.000003,0.051128,0.056476,3,30,0.051775,DXY_ret_5d,120,120,-0.259682,0.259682,132
9,TSM_ret_20d_lag1,0.049539,0.001233,0.000002,0.046883,0.051635,3,30,0.048307,TSM_ret_20d,1,1,0.350834,0.350834,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 10
lag 생성 후 valid_df shape: (1607, 22)
원본 base_feature 제거 후 valid_df shape: (1607, 12)
최종 컬럼 수: 12
target 생성 후 valid_df shape: (1607, 14)
최종 valid_df shape: (64, 14)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 10
train_df shape: (1383, 13)
X_train shape: (1383, 10)
train target 분포:
target_20d_up_0pct
1    851
0    532
Name: count, dtype: int64
target_20d_up_0pct
1    0.615329
0    0.384671
Name: proportion, dtype: float64
valid_df shape: (64, 14)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_0pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.641300     0
1  2026-02-24     419.160004                 0.0    0.655839     1
2  2026-02-25     426.160004                 0.0    0.654083     1
3  2026-02-26     412.010010                 0.0    0.659208     1
4  2026-02-27     406.369995                 0.0    0.668289     1
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.516649     0
60 2026-05-19     543.960022                 NaN    0.558917     0
61 2026-05-20     564.659973                 NaN    0.569220     0
62 2026-05-21     567.880005                 NaN    0.738209     1
63 2026-05-22     576.320007                 NaN    0.738209     1

[64 rows x 5 columns]

예측값 분포:
pred
1    42
0    22
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 28
예측 1 중 실제 1 개수: 22
예측 1 기준 정확도 precision: 0.7857142857142857

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.005,1,10,10,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.01, '...",44,28,...,0.568182,0.785714,0.628571,0.698413,0.612698,0.537942,3,6,13,22

[I 2026-05-23 21:23:25,202] Trial 190 finished with value: 0.7857142857142857 and parameters: {'n_days': 20, 'threshold': 0.005, 'top_n': 10, 'pred_threshold': 0.65, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.01, 'gb_max_depth': 3}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:23:25,232] Trial 191 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:23:25,263] Trial 192 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:23:25,293] Trial 193 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:23:25,323] Trial 194 finished with value: 0.9285714285714286 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 300, 'hgb_learning_rate': 0.05, 'hgb_max_leaf_nodes': 63}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 192/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 191}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_205244_optuna_holdout_trial_0031
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 193/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 192}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_205244_optuna_holdout_trial_0031
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 194/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.03, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 193}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_205244_optuna_holdout_trial_0031
기존 test_precision: 1.0

====================================================================================================
OPTUNA HOLDOUT TRIAL 195/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 300, 'learning_rate': 0.05, 'max_leaf_nodes': 63}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 194}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_210140_optuna_holdout_trial_0074
기존 test_precision: 0.9285714285714286

====================================================================================================
OPTUNA HOLDOUT TRIAL 196/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 10, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.25, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 100, 'learning_rate': 0.03, 'max_leaf_nodes': 15}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 195}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_10d_up_3pct
target_df shape: (1533, 31)
target 분포:
target_10d_up_3pct
0    907
1    626
Name: count, dtype: int64
lagged_df shape: (1393, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1431

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1425

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1433
TOP feature count: 20
['USDKRW_ret_20d_lag1', 'OIL_ret_20d_lag40', 'TNX_level_lag120', 'DXY_ret_20d_lag120', 'SMH_vol_20d_lag40', 'VIX_level_lag1', 'TNX_diff_20d_lag5', 'TSM_ret_20d_lag40', 'SMH_ma20_ratio_lag40', 'SMH_ma60_ratio_lag40', 'SMH_volume_ratio_20d_lag1', 'NVDA_ret_20d_lag40', 'SPY_ret_20d_lag40', 'VIX_chg_5d_lag60', 'VIX_chg_20d_lag40', 'GOLD_ret_20d_lag1', 'USDKRW_ret_5d_lag3', 'DXY_ret_5d_lag5', 'SOXX_ret_5d_lag40', 'TSM_ret_5d_lag40']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,USDKRW_ret_20d_lag1,0.126034,0.002997,8.980695e-06,0.119453,0.133261,3,30,0.123037,USDKRW_ret_20d,1,1,-0.408214,0.408214,251
1,OIL_ret_20d_lag40,0.096463,0.002678,7.170844e-06,0.091112,0.102565,3,30,0.093785,OIL_ret_20d,40,40,-0.318626,0.318626,212
2,TNX_level_lag120,0.080627,0.002211,4.888913e-06,0.074639,0.086368,3,30,0.078416,TNX_level,120,120,-0.195924,0.195924,132
3,DXY_ret_20d_lag120,0.073622,0.001373,1.884736e-06,0.070474,0.075453,3,30,0.072249,DXY_ret_20d,120,120,-0.293154,0.293154,132
4,SMH_vol_20d_lag40,0.063920,0.001438,2.066961e-06,0.061510,0.067246,3,30,0.062482,SMH_vol_20d,40,40,0.281937,0.281937,212
5,VIX_level_lag1,0.059403,0.001746,3.047977e-06,0.056041,0.063472,3,30,0.057657,VIX_level,1,1,0.240225,0.240225,251
6,TNX_diff_20d_lag5,0.059302,0.002218,4.918486e-06,0.054268,0.064710,3,30,0.057085,TNX_diff_20d,5,5,0.307873,0.307873,247
7,TSM_ret_20d_lag40,0.055242,0.001483,2.198098e-06,0.052429,0.058885,3,30,0.053759,TSM_ret_20d,40,40,-0.349006,0.349006,212
8,SMH_ma20_ratio_lag40,0.054793,0.001213,1.471149e-06,0.052111,0.057220,3,30,0.053580,SMH_ma20_ratio,40,40,-0.288530,0.288530,212
9,SMH_ma60_ratio_lag40,0.053386,0.001023,1.046921e-06,0.051840,0.055668,3,30,0.052363,SMH_ma60_ratio,40,40,-0.297396,0.297396,212
10,SMH_volume_ratio_20d_lag1,0.051650,0.002090,4.367474e-06,0.048032,0.055660,3,30,0.049560,SMH_volume_ratio_20d,1,1,0.186136,0.186136,251
11,NVDA_ret_20d_lag40,0.047124,0.001591,2.531745e-06,0.043689,0.049773,3,30,0.045533,NVDA_ret_20d,40,40,-0.192054,0.192054,212
12,SPY_ret_20d_lag40,0.049969,0.004929,2.429532e-05,0.042242,0.057221,3,30,0.045040,SPY_ret_20d,40,40,-0.270977,0.270977,212
13,VIX_chg_5d_lag60,0.043663,0.001981,3.925745e-06,0.039731,0.047597,3,30,0.041682,VIX_chg_5d,60,60,0.176557,0.176557,192
14,VIX_chg_20d_lag40,0.042420,0.001552,2.410066e-06,0.039666,0.045644,3,30,0.040867,VIX_chg_20d,40,40,0.240142,0.240142,212
15,GOLD_ret_20d_lag1,0.039796,0.000720,5.186415e-07,0.038508,0.041410,3,30,0.039076,GOLD_ret_20d,1,1,0.150955,0.150955,251
16,USDKRW_ret_5d_lag3,0.037802,0.001225,1.500943e-06,0.035512,0.039620,3,30,0.036577,USDKRW_ret_5d,3,3,-0.270483,0.270483,249
17,DXY_ret_5d_lag5,0.036078,0.000914,8.350636e-07,0.034211,0.037683,3,30,0.035164,DXY_ret_5d,5,5,-0.186237,0.186237,247
18,SOXX_ret_5d_lag40,0.034375,0.001310,1.716438e-06,0.032454,0.036978,3,30,0.033064,SOXX_ret_5d,40,40,-0.243564,0.243564,212
19,TSM_ret_5d_lag40,0.034537,0.001604,2.573093e-06,0.031413,0.037121,3,30,0.032933,TSM_ret_5d,40,40,-0.332453,0.332453,212

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1393, 23)
X_train shape: (1393, 20)
train target 분포:
target_10d_up_3pct
0    834
1    559
Name: count, dtype: int64
target_10d_up_3pct
0    0.598708
1    0.401292
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: hist_gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_10d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.259406     1
1  2026-02-24     419.160004                 0.0    0.259681     1
2  2026-02-25     426.160004                 0.0    0.337816     1
3  2026-02-26     412.010010                 0.0    0.218782     0
4  2026-02-27     406.369995                 0.0    0.414033     1
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.232333     0
60 2026-05-19     543.960022                 NaN    0.331190     1
61 2026-05-20     564.659973                 NaN    0.394145     1
62 2026-05-21     567.880005                 NaN    0.342907     1
63 2026-05-22     576.320007                 NaN    0.187490     0

[64 rows x 5 columns]

예측값 분포:
pred
1    53
0    11
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 54
예측 1 개수: 45
예측 1 중 실제 1 개수: 23
예측 1 기준 정확도 precision: 0.5111111111111111

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,10,0.03,1,20,20,hist_gradient_boosting,"{'max_iter': 100, 'learning_rate': 0.03, 'max_...",54,45,...,0.444444,0.511111,0.741935,0.605263,0.402525,0.847276,1,22,8,23

[I 2026-05-23 21:23:42,495] Trial 195 finished with value: 0.5111111111111111 and parameters: {'n_days': 10, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.25, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 100, 'hgb_learning_rate': 0.03, 'hgb_max_leaf_nodes': 15}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 197/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.8, 'model_name': 'logistic', 'model_params': {'C': 0.01, 'class_weight': 'balanced', 'max_iter': 3000}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 196}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_2pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_2pct
1    841
0    682
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1295

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.13

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1303
TOP feature count: 20
['SMH_vol_20d_lag120', 'TNX_level_lag20', 'NVDA_ret_20d_lag1', 'OIL_ret_20d_lag40', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag1', 'VIX_chg_20d_lag120', 'SMH_ma20_ratio_lag1', 'SMH_ma60_ratio_lag20', 'USDKRW_ret_20d_lag40', 'TSM_ret_20d_lag1', 'SPY_ret_20d_lag120', 'VIX_level_lag20', 'DXY_ret_5d_lag120', 'VIX_chg_5d_lag120', 'GOLD_ret_20d_lag120', 'TNX_diff_5d_lag5', 'GOLD_ret_5d_lag60', 'OIL_ret_5d_lag10', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,SMH_vol_20d_lag120,0.118471,0.002453,6.016397e-06,0.112494,0.123767,3,30,0.116018,SMH_vol_20d,120,120,-0.287916,0.287916,132
1,TNX_level_lag20,0.104124,0.004767,2.272442e-05,0.099081,0.112950,3,30,0.099357,TNX_level,20,20,-0.283565,0.283565,232
2,NVDA_ret_20d_lag1,0.080684,0.003048,9.290876e-06,0.076206,0.086065,3,30,0.077636,NVDA_ret_20d,1,1,0.216185,0.216185,251
3,OIL_ret_20d_lag40,0.079343,0.002449,5.999457e-06,0.073720,0.083487,3,30,0.076894,OIL_ret_20d,40,40,-0.279275,0.279275,212
4,DXY_ret_20d_lag60,0.071537,0.001774,3.145741e-06,0.067539,0.074524,3,30,0.069763,DXY_ret_20d,60,60,-0.192227,0.192227,192
5,TNX_diff_20d_lag1,0.068682,0.002271,5.157877e-06,0.064544,0.074282,3,30,0.066411,TNX_diff_20d,1,1,0.373698,0.373698,251
6,VIX_chg_20d_lag120,0.065839,0.001508,2.274859e-06,0.062437,0.068328,3,30,0.064331,VIX_chg_20d,120,120,0.336435,0.336435,132
7,SMH_ma20_ratio_lag1,0.059547,0.002252,5.072058e-06,0.055200,0.063416,3,30,0.057295,SMH_ma20_ratio,1,1,0.259371,0.259371,251
8,SMH_ma60_ratio_lag20,0.057925,0.001752,3.071082e-06,0.054516,0.062821,3,30,0.056173,SMH_ma60_ratio,20,20,-0.175599,0.175599,232
9,USDKRW_ret_20d_lag40,0.055714,0.001807,3.266253e-06,0.052780,0.058985,3,30,0.053906,USDKRW_ret_20d,40,40,0.355567,0.355567,212
10,TSM_ret_20d_lag1,0.053389,0.002641,6.974246e-06,0.049342,0.057465,3,30,0.050748,TSM_ret_20d,1,1,0.287874,0.287874,251
11,SPY_ret_20d_lag120,0.049451,0.001110,1.232191e-06,0.047218,0.051227,3,30,0.048341,SPY_ret_20d,120,120,-0.246817,0.246817,132
12,VIX_level_lag20,0.049167,0.001503,2.258756e-06,0.046679,0.052080,3,30,0.047665,VIX_level,20,20,0.263437,0.263437,232
13,DXY_ret_5d_lag120,0.045148,0.001450,2.101181e-06,0.042452,0.048732,3,30,0.043699,DXY_ret_5d,120,120,-0.213393,0.213393,132
14,VIX_chg_5d_lag120,0.039906,0.000888,7.876928e-07,0.037891,0.041806,3,30,0.039018,VIX_chg_5d,120,120,0.174271,0.174271,132
15,GOLD_ret_20d_lag120,0.039501,0.000929,8.624037e-07,0.037580,0.041251,3,30,0.038572,GOLD_ret_20d,120,120,-0.370141,0.370141,132
16,TNX_diff_5d_lag5,0.037168,0.000873,7.617640e-07,0.035401,0.038563,3,30,0.036295,TNX_diff_5d,5,5,0.221477,0.221477,247
17,GOLD_ret_5d_lag60,0.032755,0.001231,1.514995e-06,0.030420,0.035158,3,30,0.031524,GOLD_ret_5d,60,60,0.206481,0.206481,192
18,OIL_ret_5d_lag10,0.030082,0.002366,5.599958e-06,0.027044,0.033812,3,30,0.027715,OIL_ret_5d,10,10,0.164072,0.164072,242
19,TSM_ret_5d_lag1,0.027576,0.000672,4.513848e-07,0.026543,0.029016,3,30,0.026904,TSM_ret_5d,1,1,0.229206,0.229206,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_2pct
1    744
0    639
Name: count, dtype: int64
target_20d_up_2pct
1    0.537961
0    0.462039
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: logistic
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_2pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.478013     0
1  2026-02-24     419.160004                 0.0    0.472442     0
2  2026-02-25     426.160004                 0.0    0.501560     0
3  2026-02-26     412.010010                 0.0    0.546459     0
4  2026-02-27     406.369995                 0.0    0.552615     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.455237     0
60 2026-05-19     543.960022                 NaN    0.505466     0
61 2026-05-20     564.659973                 NaN    0.563178     0
62 2026-05-21     567.880005                 NaN    0.576022     0
63 2026-05-22     576.320007                 NaN    0.556520     0

[64 rows x 5 columns]

예측값 분포:
pred
0    64
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 0
예측 1 중 실제 1 개수: 0
예측 1 기준 정확도 precision: nan

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.02,1,20,20,logistic,"{'C': 0.01, 'class_weight': 'balanced', 'max_i...",44,0,...,0.227273,0.0,0.0,0.0,0.320588,0.744518,10,0,34,0

[I 2026-05-23 21:24:00,009] Trial 196 finished with value: 0.0 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.8, 'model_name': 'logistic', 'logistic_C': 0.01}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 198/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'model_params': {'n_estimators': 300, 'learning_rate': 0.03, 'max_depth': 4}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 197}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 20
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: gradient_boosting
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.535520     0
1  2026-02-24     419.160004                 0.0    0.628092     0
2  2026-02-25     426.160004                 0.0    0.454908     0
3  2026-02-26     412.010010                 0.0    0.453988     0
4  2026-02-27     406.369995                 0.0    0.619837     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.430849     0
60 2026-05-19     543.960022                 NaN    0.649059     0
61 2026-05-20     564.659973                 NaN    0.412795     0
62 2026-05-21     567.880005                 NaN    0.563479     0
63 2026-05-22     576.320007                 NaN    0.617826     0

[64 rows x 5 columns]

예측값 분포:
pred
0    53
1    11
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 3
예측 1 중 실제 1 개수: 3
예측 1 기준 정확도 precision: 1.0

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,20,20,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.03, '...",44,3,...,0.295455,1.0,0.088235,0.162162,0.394118,0.814403,10,0,31,3

[I 2026-05-23 21:24:18,943] Trial 197 finished with value: 1.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.03, 'gb_max_depth': 4}. Best is trial 6 with value: 1.0.
[I 2026-05-23 21:24:18,985] Trial 198 finished with value: 0.625 and parameters: {'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'hgb_max_iter': 500, 'hgb_learning_rate': 0.01, 'hgb_max_leaf_nodes': 31}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

====================================================================================================
OPTUNA HOLDOUT TRIAL 199/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.02, 'top_n': 20, 'pred_threshold': 0.65, 'model_name': 'hist_gradient_boosting', 'model_params': {'max_iter': 500, 'learning_rate': 0.01, 'max_leaf_nodes': 31}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 198}
====================================================================================================

기존에 같은 조건의 holdout 실험 결과가 있어 재실행을 건너뜁니다.
기존 run_id: 20260523_211227_optuna_holdout_trial_0126
기존 test_precision: 0.625

====================================================================================================
OPTUNA HOLDOUT TRIAL 200/200
{'etf_code': 'SMH', 'test_months': 3, 'vif_threshold': 10, 'lag_search_years': 1, 'lag_days': [1, 3, 5, 10, 20, 40, 60, 120], 'random_state': 42, 'n_rf_runs': 3, 'n_repeats': 10, 'start_date': '2020-01-01', 'end_date': None, 'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'random_forest', 'model_params': {'n_estimators': 300, 'max_depth': 7, 'min_samples_leaf': 1, 'max_features': 'log2', 'class_weight': 'balanced'}, 'search_method': 'optuna_holdout', 'optuna_trial_number': 199}
====================================================================================================
============================================================
Holdout feature selection
train 기간: 2019-12-31 00:00:00 ~ 2026-02-20 00:00:00
test  기간: 2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
train_base_df shape: (1543, 34)
test_base_df shape: (64, 34)
close_col: SMH_adj_close
VIF 계산 대상 row 수: 1484
VIF 계산 대상 feature 수: 32
현재 max VIF: 158.58 / feature: SMH_ret_20d
현재 max VIF: 121.48 / feature: SMH_ret_5d
현재 max VIF: 15.37 / feature: QQQ_ret_20d
현재 max VIF: 12.04 / feature: QQQ_ret_5d
현재 max VIF: 10.24 / feature: SOXX_ret_20d
현재 max VIF: 9.43 / feature: SOXX_ret_5d

========== VIF 제거 결과 ==========
초기 feature 수: 32
상수 제거 feature 수: 0
VIF 제거 feature 수: 5
최종 feature 수: 27
===================================
target_col: target_20d_up_3pct
target_df shape: (1523, 31)
target 분포:
target_20d_up_3pct
0    769
1    754
Name: count, dtype: int64
lagged_df shape: (1383, 31)
lagged feature count: 27

========== RF RUN 1 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1352

========== RF RUN 2 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1356

========== RF RUN 3 / 3 ==========
accuracy : 1.0
precision: 1.0
recall   : 1.0
f1       : 1.0
log_loss : 0.1346
TOP feature count: 20
['TNX_level_lag120', 'OIL_ret_20d_lag40', 'NVDA_ret_20d_lag1', 'SMH_vol_20d_lag60', 'VIX_chg_20d_lag120', 'DXY_ret_20d_lag60', 'TNX_diff_20d_lag5', 'SMH_ma20_ratio_lag1', 'VIX_level_lag20', 'USDKRW_ret_20d_lag40', 'SMH_ma60_ratio_lag20', 'SPY_ret_20d_lag120', 'TSM_ret_20d_lag1', 'DXY_ret_5d_lag120', 'USDKRW_ret_5d_lag1', 'OIL_ret_5d_lag40', 'GOLD_ret_20d_lag120', 'GOLD_ret_5d_lag60', 'VIX_chg_5d_lag120', 'TSM_ret_5d_lag1']

,feature,importance_mean,importance_std,importance_var,importance_min,importance_max,run_count,repeat_count,importance_score,base_feature,selected_lag,best_lag,lag_corr,lag_abs_corr,lag_n_rows
0,TNX_level_lag120,0.134135,0.005407,2.923208e-05,0.122849,0.144661,3,30,0.128728,TNX_level,120,120,-0.344800,0.344800,132
1,OIL_ret_20d_lag40,0.094345,0.003261,1.063446e-05,0.087540,0.100455,3,30,0.091084,OIL_ret_20d,40,40,-0.318216,0.318216,212
2,NVDA_ret_20d_lag1,0.078360,0.004381,1.919357e-05,0.071600,0.087486,3,30,0.073979,NVDA_ret_20d,1,1,0.171167,0.171167,251
3,SMH_vol_20d_lag60,0.069290,0.001450,2.101188e-06,0.067233,0.072787,3,30,0.067840,SMH_vol_20d,60,60,-0.273476,0.273476,192
4,VIX_chg_20d_lag120,0.065674,0.002879,8.290976e-06,0.060164,0.069858,3,30,0.062794,VIX_chg_20d,120,120,0.369931,0.369931,132
5,DXY_ret_20d_lag60,0.064301,0.003089,9.543067e-06,0.060481,0.071249,3,30,0.061212,DXY_ret_20d,60,60,-0.138093,0.138093,192
6,TNX_diff_20d_lag5,0.062814,0.003138,9.847171e-06,0.057228,0.069092,3,30,0.059676,TNX_diff_20d,5,5,0.316812,0.316812,247
7,SMH_ma20_ratio_lag1,0.060456,0.002617,6.849843e-06,0.055600,0.063899,3,30,0.057839,SMH_ma20_ratio,1,1,0.250143,0.250143,251
8,VIX_level_lag20,0.058055,0.001801,3.245159e-06,0.054578,0.061128,3,30,0.056254,VIX_level,20,20,0.266546,0.266546,232
9,USDKRW_ret_20d_lag40,0.055299,0.001560,2.433555e-06,0.051932,0.057940,3,30,0.053739,USDKRW_ret_20d,40,40,0.412829,0.412829,212
10,SMH_ma60_ratio_lag20,0.054864,0.001544,2.383420e-06,0.052014,0.058592,3,30,0.053320,SMH_ma60_ratio,20,20,-0.261293,0.261293,232
11,SPY_ret_20d_lag120,0.052395,0.001161,1.347079e-06,0.049973,0.054706,3,30,0.051235,SPY_ret_20d,120,120,-0.323737,0.323737,132
12,TSM_ret_20d_lag1,0.051688,0.001196,1.430086e-06,0.049593,0.053947,3,30,0.050492,TSM_ret_20d,1,1,0.270907,0.270907,251
13,DXY_ret_5d_lag120,0.049333,0.002424,5.874553e-06,0.044771,0.053631,3,30,0.046910,DXY_ret_5d,120,120,-0.201025,0.201025,132
14,USDKRW_ret_5d_lag1,0.045180,0.000934,8.723238e-07,0.042302,0.047306,3,30,0.044246,USDKRW_ret_5d,1,1,-0.161535,0.161535,251
15,OIL_ret_5d_lag40,0.040614,0.002492,6.210620e-06,0.036219,0.044981,3,30,0.038121,OIL_ret_5d,40,40,-0.179836,0.179836,212
16,GOLD_ret_20d_lag120,0.038389,0.001548,2.395396e-06,0.035878,0.040975,3,30,0.036841,GOLD_ret_20d,120,120,-0.290644,0.290644,132
17,GOLD_ret_5d_lag60,0.035527,0.001952,3.812019e-06,0.032493,0.038901,3,30,0.033575,GOLD_ret_5d,60,60,0.160394,0.160394,192
18,VIX_chg_5d_lag120,0.033865,0.002083,4.340112e-06,0.030700,0.037136,3,30,0.031782,VIX_chg_5d,120,120,0.160374,0.160374,132
19,TSM_ret_5d_lag1,0.028766,0.000549,3.016207e-07,0.027679,0.029893,3,30,0.028216,TSM_ret_5d,1,1,0.258214,0.258214,251

============================================================
6. valid_df 생성
============================================================
top feature 수: 20
lag 생성 후 valid_df shape: (1607, 42)
원본 base_feature 제거 후 valid_df shape: (1607, 22)
최종 컬럼 수: 22
target 생성 후 valid_df shape: (1607, 24)
최종 valid_df shape: (64, 24)
valid_base_df shape: (64, 34)
valid_df 기간:
2026-02-23 00:00:00 ~ 2026-05-22 00:00:00
============================================================
7. Train 학습 후 valid_df 예측
============================================================
사용 feature 수: 20
train_df shape: (1383, 23)
X_train shape: (1383, 20)
train target 분포:
target_20d_up_3pct
0    717
1    666
Name: count, dtype: int64
target_20d_up_3pct
0    0.518438
1    0.481562
Name: proportion, dtype: float64
valid_df shape: (64, 24)
예측 가능한 valid row 수: 64
예측 불가능 row 수: 0
모델 학습 완료: random_forest
valid_df 예측 완료

         Date  SMH_adj_close  target_20d_up_3pct  pred_proba  pred
0  2026-02-23     412.880005                 0.0    0.531191     0
1  2026-02-24     419.160004                 0.0    0.521230     0
2  2026-02-25     426.160004                 0.0    0.532309     0
3  2026-02-26     412.010010                 0.0    0.540683     0
4  2026-02-27     406.369995                 0.0    0.531416     0
..        ...            ...                 ...         ...   ...
59 2026-05-18     546.159973                 NaN    0.458919     0
60 2026-05-19     543.960022                 NaN    0.460680     0
61 2026-05-20     564.659973                 NaN    0.419117     0
62 2026-05-21     567.880005                 NaN    0.442068     0
63 2026-05-22     576.320007                 NaN    0.453363     0

[64 rows x 5 columns]

예측값 분포:
pred
0    64
Name: count, dtype: Int64
============================================================
8. 예측 1 기준 정확도 확인
============================================================
평가 가능 row 수: 44
예측 1 개수: 0
예측 1 중 실제 1 개수: 0
예측 1 기준 정확도 precision: nan

,etf_code,n_days,threshold,lag_search_years,top_n,feature_count,model_name,model_params,eval_count,pred_1_count,...,accuracy,precision,recall,f1,auc,logloss,tn,fp,fn,tp
0,SMH,20,0.03,1,20,20,random_forest,"{'n_estimators': 300, 'max_depth': 7, 'min_sam...",44,0,...,0.227273,0.0,0.0,0.0,0.497059,0.686412,10,0,34,0

[I 2026-05-23 21:24:37,097] Trial 199 finished with value: 0.0 and parameters: {'n_days': 20, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.7, 'model_name': 'random_forest', 'rf_n_estimators': 300, 'rf_max_depth': 7, 'rf_min_samples_leaf': 1, 'rf_max_features': 'log2'}. Best is trial 6 with value: 1.0.

Excel 저장 완료
holdout summary 파일: experiments_excel/experiment_summary_holdout.xlsx

================================================================================
OPTUNA HOLDOUT BEST TRIAL
================================================================================
best_value: 1.0
best_params: {'n_days': 10, 'threshold': 0.03, 'top_n': 20, 'pred_threshold': 0.6000000000000001, 'model_name': 'gradient_boosting', 'gb_n_estimators': 300, 'gb_learning_rate': 0.01, 'gb_max_depth': 5}

,trial_number,score,etf_code,test_months,vif_threshold,lag_search_years,lag_days,random_state,n_rf_runs,n_repeats,...,top_n,pred_threshold,model_name,model_params,search_method,optuna_trial_number,test_precision,test_eval_count,test_pred_1_count,skipped_existing
0,174,1.0,SMH,3,10,1,"[1, 3, 5, 10, 20, 40, 60, 120]",42,3,10,...,20,0.65,hist_gradient_boosting,"{'max_iter': 500, 'learning_rate': 0.03, 'max_...",optuna_holdout,174,1.0,44,9,True
1,138,1.0,SMH,3,10,1,"[1, 3, 5, 10, 20, 40, 60, 120]",42,3,10,...,20,0.65,logistic,"{'C': 1.0, 'class_weight': 'balanced', 'max_it...",optuna_holdout,138,1.0,44,4,True
2,115,1.0,SMH,3,10,1,"[1, 3, 5, 10, 20, 40, 60, 120]",42,3,10,...,20,0.65,logistic,"{'C': 1.0, 'class_weight': 'balanced', 'max_it...",optuna_holdout,115,1.0,44,12,False
3,182,1.0,SMH,3,10,1,"[1, 3, 5, 10, 20, 40, 60, 120]",42,3,10,...,20,0.70,hist_gradient_boosting,"{'max_iter': 300, 'learning_rate': 0.03, 'max_...",optuna_holdout,182,1.0,44,8,True
4,181,1.0,SMH,3,10,1,"[1, 3, 5, 10, 20, 40, 60, 120]",42,3,10,...,20,0.70,hist_gradient_boosting,"{'max_iter': 300, 'learning_rate': 0.03, 'max_...",optuna_holdout,181,1.0,44,8,True
5,121,1.0,SMH,3,10,1,"[1, 3, 5, 10, 20, 40, 60, 120]",42,3,10,...,20,0.65,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.03, '...",optuna_holdout,121,1.0,44,6,True
6,65,1.0,SMH,3,10,1,"[1, 3, 5, 10, 20, 40, 60, 120]",42,3,10,...,20,0.65,hist_gradient_boosting,"{'max_iter': 500, 'learning_rate': 0.03, 'max_...",optuna_holdout,65,1.0,44,9,False
7,64,1.0,SMH,3,10,1,"[1, 3, 5, 10, 20, 40, 60, 120]",42,3,10,...,20,0.70,hist_gradient_boosting,"{'max_iter': 300, 'learning_rate': 0.03, 'max_...",optuna_holdout,64,1.0,44,8,True
8,62,1.0,SMH,3,10,1,"[1, 3, 5, 10, 20, 40, 60, 120]",42,3,10,...,20,0.65,hist_gradient_boosting,"{'max_iter': 300, 'learning_rate': 0.03, 'max_...",optuna_holdout,62,1.0,44,9,True
9,61,1.0,SMH,3,10,1,"[1, 3, 5, 10, 20, 40, 60, 120]",42,3,10,...,20,0.65,hist_gradient_boosting,"{'max_iter': 300, 'learning_rate': 0.03, 'max_...",optuna_holdout,61,1.0,44,9,True
10,60,1.0,SMH,3,10,1,"[1, 3, 5, 10, 20, 40, 60, 120]",42,3,10,...,20,0.70,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.03, '...",optuna_holdout,60,1.0,44,4,False
11,122,1.0,SMH,3,10,1,"[1, 3, 5, 10, 20, 40, 60, 120]",42,3,10,...,20,0.65,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.03, '...",optuna_holdout,122,1.0,44,6,True
12,123,1.0,SMH,3,10,1,"[1, 3, 5, 10, 20, 40, 60, 120]",42,3,10,...,20,0.65,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.03, '...",optuna_holdout,123,1.0,44,6,True
13,124,1.0,SMH,3,10,1,"[1, 3, 5, 10, 20, 40, 60, 120]",42,3,10,...,20,0.70,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.03, '...",optuna_holdout,124,1.0,44,3,False
14,128,1.0,SMH,3,10,1,"[1, 3, 5, 10, 20, 40, 60, 120]",42,3,10,...,20,0.60,logistic,"{'C': 10.0, 'class_weight': 'balanced', 'max_i...",optuna_holdout,128,1.0,44,4,False
15,129,1.0,SMH,3,10,1,"[1, 3, 5, 10, 20, 40, 60, 120]",42,3,10,...,20,0.70,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.05, '...",optuna_holdout,129,1.0,44,3,False
16,51,1.0,SMH,3,10,1,"[1, 3, 5, 10, 20, 40, 60, 120]",42,3,10,...,20,0.65,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.03, '...",optuna_holdout,51,1.0,44,6,True
17,132,1.0,SMH,3,10,1,"[1, 3, 5, 10, 20, 40, 60, 120]",42,3,10,...,20,0.65,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.03, '...",optuna_holdout,132,1.0,44,6,True
18,133,1.0,SMH,3,10,1,"[1, 3, 5, 10, 20, 40, 60, 120]",42,3,10,...,20,0.70,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.03, '...",optuna_holdout,133,1.0,44,4,True
19,135,1.0,SMH,3,10,1,"[1, 3, 5, 10, 20, 40, 60, 120]",42,3,10,...,20,0.65,gradient_boosting,"{'n_estimators': 300, 'learning_rate': 0.01, '...",optuna_holdout,135,1.0,44,6,False